### ISSUE TITLE
Migrate Documentation & Support Materials To Tangram Vector Tiles (and other Raster Tiles)

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#103]
All Pelias documentation & supporting materials should, where possible, should showcase @tangram (as suggested by @burritojustice). It'll help get the word out about Tangram, but also help differentiate Mapzen's product aesthetic.

Where we can't/aren't yet ready to switch over to Tangram, consider an alternate tile service.

Currently these materials include:
- [x] [Mapzen Demo Page](https://mapzen.com/pelias)
- [x] [Pelias/Pelias README](https://github.com/pelias/pelias/blob/master/README.md)
- [x] [UX for Leaflet Plugin](https://github.com/pelias/leaflet-geocoder)

**Comment by riordan** [comment]
Re - leaflet plugin:

See: Stamen Toner Test [Branch](https://github.com/pelias/leaflet-geocoder/tree/stamen-toner) | [rawgit](http://rawgit.com/pelias/leaflet-geocoder/stamen-toner/index.html)

**Comment by dianashk** [comment]
wrong repo
