### ISSUE TITLE
Write blog post about ngrams release

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#105]
Write blog post about ngrams release explaining the differences in architecture between FST and grams, why it produces better matches and why it's slower

Also cover API changes, new features, analysis techniques, memory requirements, FST v2 etc

**Comment by missinglink** [comment]
An API changelog document needs to be written to outline the changes due to this release

**Comment by riordan** [comment]
@missinglink are we ever doing this or should we just close the ticket?

Also is there a better place for us to track our blogging tickets than here?

**Comment by riordan** [comment]
Moot point.
