### ISSUE TITLE
Split Pelias Index into admin and address indeces

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#109]
what if we have different indeces lets say one for all admins (countries, cities, down to neighborhoods, localities), one for all places (pois, place names) and another one just for addresses.. 

we could have a middleware at the API level that parses the query to figure out if its looking for an address or not.. and based on that we hit one or the other index..
that could speed up ES query response time in theory

Thoughts?

**Comment by dianashk** [comment]
we now have separate indices for admin layers.
