### ISSUE TITLE
Search Type Parser Module

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#110]
A module that takes a input query string and classify it as 

* admin/poi search type
* address point search type

This module could be used in the API at the time of query parsing/ sanitizing stage and based on the parsed results - we could customize our ES queries to target the specific index as necessary. 

Related to https://github.com/pelias/pelias/issues/109

**Comment by dianashk** [comment]
this will be partially handled by the `libpostal` integration and further decisions on how to decide if it's a POI or admin type of search will be made during that integration process.
