### ISSUE TITLE
Support for numeric streets with and without ordinals

### ISSUE THREAD

**Issue by colinreilly** [pelias/pelias#112]
Currently Pelias only returns a result (checked in NYC but I would imagine this is the case elsewhere) when a numeric street name includes an ordinal (eg, West 59th Street, New York). It would be extremely beneficial if Pelias could support numeric streets with and without (eg, 59 Street, New York) ordinals. 

Example:
https://mapzen.com/pelias/#loc=12,40.7078,-73.9993&q=w 59 st new york&t=fine&gb=bbox
Suggestions returned are not where near the input address. 

https://mapzen.com/pelias#loc=12,40.7078,-73.9993&q=west 59 st street&t=fine&gb=bbox
Better but still not perfect. Why is  "West 59th Street Generating Station," shown as opposed to " West 59th Street, New York"? Is there also an issue with directionals (East, West...) and their abbreviations (E, W...)?  

From experience in NYC, many users input numeric streets without an ordinal.

**Comment by dianashk** [comment]
@colinreilly that's a really good catch. I don't believe we've discussed this at all internally. We'll kick it around and keep this thread posted on findings. Thanks.

**Comment by dianashk** [comment]
This looks to be resolved.
