### ISSUE TITLE
Running Pelias with multiple data sources

### ISSUE THREAD

**Issue by adam21** [pelias/pelias#114]
Hello everyone,

Is it possible to run Pelias with OSM data, GeoNames, OpenAddress and quattroshapes at the same time ? if it is possible, how can I do This ?
and how will be the reverse query format  ?

Thank you in advance

**Comment by hkrishna** [comment]
Yes! This is possible. There are importers for openstreetmap, openaddresses, geonames and quattroshapes (look at github.com/pelias/geonames github.com/pelias/openaddresses and similarly for osm and quattro)

Once you create your pelias schema (look at github.com/pelias/schema) just run all the above mentioned importers for the regions you want to geocode (you can specify this in the pelias.json config file) 

Alternatively, if you don't want to do all the work manually.. There is a vagrant setup (github.com/vagrant) where you just run ```vagrant up``` and it sets up everything for you including the api :) 

Let me know if this helps

**Comment by hkrishna** [comment]
And for API query formats, you can look at ```/reverse``` part of documentation at pelias.mapzen.com

**Comment by adam21** [comment]
Thank you very much Hkrishna  for your reply, I will try your solution and will be back for you

**Comment by adam21** [comment]
Hello again,

I encountered this error message while creating index for schema:
![error](https://cloud.githubusercontent.com/assets/11215545/9059728/fbad37a6-3aac-11e5-8fd2-41ff6f40a3d9.png)

Your help please

**Comment by hkrishna** [comment]
What that means is that the index already exists and es is unable to create a duplicate one. The solution here is either not creating one and continuing with the import process

Or, run ```node scripts/drop_index.JS``` before running ```node scripts/create_index.js```

**Comment by adam21** [comment]
Thank you for your quick reply Hkrishna,

Now I want to run node index.js and I get the message:
![error2](https://cloud.githubusercontent.com/assets/11215545/9060437/25e8cde4-3ab4-11e5-81a3-8a1fa21c9c09.png)

This is my pelias.json file: 

{
  "imports": {
    "geonames": {
      "datapath": "/geonames/data/",
      "adminLookup": true
    },
    "quattroshapes": {
      "datapath": "/var/pelias-shp/simplified"
    },
    "openstreetmap": {
      "adminLookup": true,
      "datapath": "/var/pelias-shp/pelias-osm-files/",
      "import": [{
        "type": { "node": "osmnode", "way": "osmway" },
        "filename": "tunisia-latest.osm.pbf"
      }]
    }
  }
}

**Comment by adam21** [comment]
Thank you for your quick reply Hkrishna,

Now I want to run node index.js and I get the message:

![error2](https://cloud.githubusercontent.com/assets/11215545/9060770/2ffe0b02-3ab7-11e5-9c27-1bc41f7aa765.png)

This is my pelias.json file:

{
"imports": {
"geonames": {
"datapath": "/geonames/data/",
"adminLookup": true
},
"quattroshapes": {
"datapath": "/var/pelias-shp/simplified"
},
"openstreetmap": {
"adminLookup": true,
"datapath": "/var/pelias-shp/pelias-osm-files/",
"import": [{
"type": { "node": "osmnode", "way": "osmway" },
"filename": "tunisia-latest.osm.pbf"
}]
}
}
}

I placed it in "/openstreetmap/node_modules/pelias-config/config"

**Comment by adam21** [comment]
I still not have a solution for this error message :(

**Comment by hkrishna** [comment]
Try placing creating a ```~/pelias.json``` file in your home directory. You are seeing that error because the importer is reading a wrong config file and/or falling back to defaults and trying to import ```/mnt/pelias/openstreetmap/planet.osm.pbf``` and failing.

**Comment by adam21** [comment]
I was able to solve this problem by editing the ```default.json``` file, and now by running ```node index.js``` , the terminal show me this output : 

![message3](https://cloud.githubusercontent.com/assets/11215545/9107926/2b862bfc-3c2b-11e5-96e5-aba82310f772.png)

Is this all the process ?? 
Note that the area is Tunisia (pbf file size = 18 mega)

**Comment by missinglink** [comment]
hi @adam21 you might find that the Tunisia file doesn't contain any data which is appropriate for geocoding, try a larger pbf extract from https://mapzen.com/data/metro-extracts

there are more detailed instructions here: https://github.com/pelias/openstreetmap

**Comment by ltbam** [comment]
@adam21 you might want to lookt to:

http://localhost:9200/pelias/_search/_stats

it displays the amout of created addresses while the importer is running.

**Comment by missinglink** [comment]
@ltbam I think that url might be wrong, maybe you meant `http://localhost:9200/pelias/_stats`?

I use a couple different methods for checking the doc counts, either you can do a count such as:
- http://localhost:9200/pelias/_count
- http://localhost:9200/pelias/geoname/_count

or you can get aggregate counts in a single query such as:

```
{
    "facets": {
      "count_by_type": {
        "terms": {
          "field": "_type"
        }
      }
    }
  }
```

**Comment by missinglink** [comment]
closing this issue as it's from 7 Aug
