### ISSUE TITLE
Introduce internally consistent ID scheme

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#115]
We need a consistent ID system for places in Pelias.

Each location that can be returned from a search in Pelias is a [place](https://github.com/pelias/pelias/wiki/Terminology#place-n). When we're not computing these places at run-time, these places are documents in the ElasticSearch database, each of which have an ID. Today that might be OSMNODE:<osm-node-id>, but we should remove the document ID's dependence from where we initially sourced from.

We would like to have a way to ensure that ID's from [Who's on First](https://github.com/mapzen/theory-whosonfirst) can be used in Pelias, making WOFIDs de-facto standards for places within Mapzen products.

Ideally these should be:
- not tied to the specific source they originate from (except for WOF)
- Kept consistent between builds & instances

Thoughts on how to make this happen are encouraged.

**Comment by dianashk** [comment]
Discussed keeping source ids as part of our id and concatenate with source:type:id to ensure uniqueness.

**Comment by riordan** [comment]
We're including this as a stretch goal for the Who's on First milestone.

**Comment by dianashk** [comment]
This has already been addressed as part of the initial WOF integration.
