### ISSUE TITLE
Each place / response has a license

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#116]
The different datasets going into Pelias have different licenses and may have licensing implications when they are interoperating.

At a minimum, each place we import we will need to have a license from the source dataset as a tracked field. If there are licensing implications against reverse geocoding against Quatroshapes, we'll need to include that data in the field as well.

Enables pelias/api#189

**Comment by riordan** [comment]
I'd love some help thinking this feature through.

**Comment by missinglink** [comment]
there will be a 1:1 mapping between the `"source"` property from our most recent design proposal and the corresponding data licence, so when a user asks for only data from the `openstreetmap` `"source"` then they can assume `ODbL`.

returning a second property named `licence` (per record) would be an unnecessary duplication which would increase the response body file size.

the question remains "who is in charge of maintaining a list of these 1:1 mappings?" and I'd suggest that we have an API which can provide more information about *sources* and *layers*.

something like this:

```javascript
GET /source

{
  "sources": [
    {
      "source": "openstreetmap",
      "licence": "ODbL",
      "layers": [ "node", "way", "address" ]
    }
    ... etc
  ]
}
```

```javascript
GET /source/openstreetmap

{
  "source": "openstreetmap",
  "licence": "ODbL",
  "layers": [ "node", "way", "address" ]
}
```

**Comment by dianashk** [comment]
I like the source and layer endpoints. Should be helpful. I could see them also supporting a categories endpoint that lists all supported categories. 

As for the licence info, part of the geocodejson spec calls out having licence info in the geocoding block, which i think is where it belongs. That can be an array if needed. Returning duplicated info per result is excessive.
