### ISSUE TITLE
Add confidence score to results

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#120]
Basic confidence score should be computed and returned for each item in the results. The score should range between 0-1, and take into consideration as many factors as possible. 

Some factors to consider:
* number of results from ES
* score of item within the range of highest-lowest scores from ES (within the returned set)
* linguistic match of query

**Comment by riordan** [comment]
This scoring should also take into account detection (or specification) of query type.

**Comment by hkrishna** [comment]
:+1:
