### ISSUE TITLE
Regions not completely imported from Quattroshapes leads to gaps in coverage

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#123]
In Quattroshapes, some areas do not map precisely to the Who's on First model of the world. This data is contained in Quattroshapes, but in the admin1_regions & admin2_regions datasets, which we did not import, so we can't remap our existing data to incorporate the missing information.

Example: When searching for Hackney, a neighborhood (borough) of London, the result skips the city of London entirely as an element.

ex. `/v1/search?text=Hackney&size=1`
```
{
  "geocoding": {
    "version": "0.1",
    "license": "http://pelias.mapzen.com//license",
    "attribution": "http://pelias.mapzen.com//attribution",
    "query": {
      "input": "hackney",
      "parsed_input": {
        "target_layer": [
          "geoname",
          "osmnode",
          "osmway",
          "admin0",
          "admin1",
          "admin2",
          "neighborhood",
          "locality",
          "local_admin"
        ]
      },
      "size": 1,
      "default_layers_set": true,
      "layers": [
        "geoname",
        "osmnode",
        "osmway",
        "admin0",
        "admin1",
        "admin2",
        "neighborhood",
        "locality",
        "local_admin",
        "osmaddress",
        "openaddresses"
      ],
      "details": true
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1441312418516
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "geocoding": {
          "id": "3582:adm1:gb:gbr:hackney",
          "layer": "region",
          "source": "qs",
          "name": "Hackney",
          "country_a": "GBR",
          "country": "United Kingdom",
          "region": "Hackney",
          "label": "Hackney, United Kingdom"
        }
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.0633702197991269,
          51.5522538450273
        ]
      }
    }
  ],
  "bbox": [
    -0.0633702197991269,
    51.5522538450273,
    -0.0633702197991269,
    51.5522538450273
  ]
}
```

Two paths to resolution:
1. refactoring [pelias/openstreetmap](https://github.com/pelias/openstreetmap) to bring the Quattroshapes Admin1 Region & Admin2 Region into the import
2. Incorporate [Who's on First](https://github.com/whosonfirst) as Pelias' replacement for Quattroshapes, which already holds the correct model and data (something which we'll have to do anyway in the very near future).

**Comment by riordan** [comment]
To be resolved by Quattroshapes migration (pelias/pelias#144)

**Comment by nvkelso** [comment]
Tell memory about gaps.

**Comment by thisisaaronland** [comment]
adm1_region (now called `macroregion`) and adm2_region (now called `macrocounty`) data has been imported and in master on whosonfirst-data.

The localadmin (now called `localadmin`) import is proceeding a pace. It's had to be restarted a couple of times to account for weirdness in the data and error-handling that could basically be described as "WOO!!! WOO!!!!!"

I also need to make sure that there really are as many localadmins as what's being imported and not a brain-freeze on my part (it's the same code that imported the others so I think there are just a lot of local admins...)

Meta files (and concordances) have not been updated yet but will be once the localadmin import is complete.

**Comment by nvkelso** [comment]
There are a surprising number of `localadmin` features, that's normal.

**Comment by riordan** [comment]
@thisisaaronland @nvkelso: Wanted to double-check that WoF is at parity with Quattroshapes. Is this correct?

**Comment by nvkelso** [comment]
@riordan Should be, are you seeing specific problems?

**Comment by riordan** [comment]
Nope; just doing some Github gardening.

Thanks, @nvkelso!

**Comment by thisisaaronland** [comment]
The one piece of QS that remains to be imported is the weird
cities-as-points file which I am pretty sure is:

http://static.quattroshapes.com/quattroshapes_gazetteer_gn_then_gp_with_content.zip
