### ISSUE TITLE
API Key Required

### ISSUE THREAD

**Issue by josephmisiti** [pelias/pelias#134]
Your documented example below say an API key is not required, but it looks like it is

```
JOSEPH-MISITI:~ josephmisiti$ curl -s "pelias.mapzen.com/v1/reverse?size=1&point.lat=40.74358294846026&point.lon=-73.99047374725342" | jq '.'
{
  "meta": {
    "version": 1,
    "status_code": 403
  },
  "results": {
    "error": {
      "type": "KeyError",
      "message": "No api_key specified."
    }
  }
}
```

**Comment by riordan** [comment]
Eeek, looks like you caught an inconsistency in our documentation.

Moving from our beta to v1 api we started requiring API keys (but
they're free). We realized we wanted to be able to contact folks if we
were ever changing anything and this was the easiest way to do it.

We'll get that updated.

On 10/2/15 10:41, Joseph Misiti wrote:
>
> Your documented example below say an API key is not required, but it
> looks like it is
>
> |JOSEPH-MISITI:~ josephmisiti$ curl -s
> "pelias.mapzen.com/v1/reverse?size=1&point.lat=40.74358294846026&point.lon=-73.99047374725342"
> | jq '.' { "meta": { "version": 1, "status_code": 403 }, "results": {
> "error": { "type": "KeyError", "message": "No api_key specified." } } } |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/pelias/issues/134>.
>

-- 
-- 
David Riordan | Product Manager - Search | Mapzen
dave.riordan@mapzen.com | @riordan | gpg 235D 9DC9 5EF6 277C
https://mapzen.com | @mapzen

**Comment by orangejulius** [comment]
Hey @josephmisiti, thanks for pointing this out. I've added a parameter to that query in the docs with a place for a user to put their API key. Let us know what you think of Pelias and we'd love to hear other places where our docs can be improved.

**Comment by Alster** [comment]
It wants api_key

`https://api.geocode.earth/v1/search?text=%D0%BE`

```json
{
  "meta": {
    "version": 1,
    "status_code": 401
  },
  "results": {
    "error": {
      "type": "KeyError",
      "message": "No api_key specified."
    }
  }
}
```

Builded&runned from [this repo](https://github.com/pelias/docker/)

**Comment by missinglink** [comment]
@Alster, if you are running the docker setup then you can access Pelias on your local machine at `http://localhost:4000`.

Self-hosted Pelias setups such as this do not require authentication.

The `geocode.earth` domain offers a hosted service to paid customers which requires an API key.

You can sign up for a `geocode.earth` API key from that website

**Comment by Alster** [comment]
@missinglink clear)))

The application located at the address `http://localhost:4300/demo` makes requests to `https://api.geocode.earth`.
Here is my pelias.json:

```json
{
  "logger": {
    "level": "debug",
    "timestamp": false
  },
  "esclient": {
    "apiVersion": "5.6",
    "hosts": [
      { "host": "elasticsearch" }
    ]
  },
  "elasticsearch": {
    "settings": {
      "index": {
        "refresh_interval": "10s",
        "number_of_replicas": "0",
        "number_of_shards": "1"
      }
    }
  },
  "api": {
    "textAnalyzer": "libpostal",
    "services": {
      "pip": { "url": "http://pip:4200" },
      "libpostal": { "url": "http://libpostal:4400" },
      "placeholder": { "url": "http://placeholder:4100" },
      "interpolation": { "url": "http://interpolation:4300" }
    },
    "defaultParameters": {
      "focus.point.lat": 46.61,
      "focus.point.lon": 2.45
    }
  },
  "imports": {
    "adminLookup": {
      "enabled": true
    },
    "geonames": {
      "datapath": "/data/geonames",
      "countryCode": "UA"
    },
    "openstreetmap": {
      "download": [
        { "sourceURL": "http://download.geofabrik.de/europe/ukraine-latest.osm.pbf" }
      ],
      "leveldbpath": "/tmp",
      "datapath": "/data/openstreetmap",
      "import": [{
        "filename": "ukraine-latest.osm.pbf"
      }]
    }
  }
}

```

Is it bug or i forgot some option?

**Comment by missinglink** [comment]
Oh I see the issue now, the demos usually just points to `geocode.earth` for convenience.

Since the keys are publicly visible they tend to get abused, so we disabled the key last week and I haven't got around to adding a new one yet.

It'll fix itself once I've updated the key, or another option is to point those search widgets on the demo pages to local addresses.
