### ISSUE TITLE
Indianapolis reverse geocoding gives odd city results

### ISSUE THREAD

**Issue by erjiang** [pelias/pelias#137]
I am using mapzen search for reverse geocoding, and I think the results for Indianapolis could be better.

Pretty much everything within the I-465 ring should come back with "Indianapolis" as the city, but that's not the case with Mapzen search.

consider the coordinates lat=39.768452903976495, lon=-86.15347623825073. Mapzen returns the label: "156 East Market Street, Center, IN" but I would expect "156 East Market Street, Indianapolis, IN"

I assume the `localadmin=Center` result comes from the township, which is not typically used except bureaucratically or to specify a specific area inside Indianapolis. The locality is "Indianapolis city (balance)", which is a statistical entity and only used bureaucratically.

If these unexpected results are a problem caused by poor data in OSM, I'd be happy to fix it. But Nominatim seems to give the expected results: http://nominatim.openstreetmap.org/reverse?lon=-86.15347623825073&lat=39.768452903976495

**Comment by riordan** [comment]
@erjiang: I think your interpretation of what's going on is probably the case: it's treating the township as the element in the address that should generate the label. It's not exactly [Unigov](https://en.wikipedia.org/wiki/Unigov) compliant. 

Right now we're using [Quattroshapes](https://github.com/foursquare/quattroshapes) to power the administrative lookup, and if you look at [the results](https://gist.github.com/riordan/4bf3d7aa2993c677c83b?short_path=d8c077e), you'll see that the result knows it's in Indianapolis as the `locality`, but overrides that with the `localadmin`, which is used to represent governmental things beneath the level of the city. The rules about which places prioritize which things for complete addresses and display labels are weird and inconsistent (like addresses themselves).

Pretty soon, we're switching out Quattroshapes for [Who's on First](https://whosonfirst.mapzen.com), Mapzen's open gazetteer. From there we'll start tackling this particular thorny issue. Most of the time, these addressing systems are determined on a national level, but there are plenty of places where there are overrides to these general rules.

Thanks for flagging this.

cc: @thisisaaronland

**Comment by thisisaaronland** [comment]
Somehow I managed to import a bunch of duplicate localadmins which have now been purged, so this should be all ready to go (or at least ready to be the source of New Bugs...)

**Comment by riordan** [comment]
@erjiang: quick update on this. We're getting close to switching over to Who's on First in the next few weeks.

As a result, we'll be able to take any upstream changes from their project.

They're tracking the issue of this (and all others like it) in whosonfirst/whosonfirst-data#193

Should be fixed relatively soon!

**Comment by orangejulius** [comment]
Hello everyone, it's been a while. It looks like since the last update Pelias has adopted Who's on First, and Who's on First has dramatically improved their handling of Indianapolis, so everything looks good now! I'm going to close this issue but if there are any further issues don't hesitate to reopen this one, or create a new issue. :tada: 

http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=39.768452903976495&point.lon=-86.15347623825073
![screenshot_2016-07-01_16-41-08](https://cloud.githubusercontent.com/assets/111716/16534014/b4811b8c-3faa-11e6-8ff8-fab0a8c8825f.png)

**Comment by erjiang** [comment]
Awesome to see this fixed!
