### ISSUE TITLE
Unify Gitter Chat Rooms

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#138]
We're moving to Gitter as the public team chat du-jor. But by default it creates new rooms for new repositories. It makes more sense for Pelias to have a single chat across the project.

**Comment by orangejulius** [comment]
Historically, the pelias/api gitter room has been the most active, but it might make sense for pelias/pelias to be designated the official main room, to parallel the meta-ness of the pelias/pelias repo

**Comment by orangejulius** [comment]
I think we've done this now (we've had a couple questions pop up in pelias/pelias chat)!
