### ISSUE TITLE
Launch a point in polygon service

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#139]
We currently use the [pelias/admin-lookup](https://github.com/pelias/admin-lookup) NPM module to set fields for city, country, state, etc in every record we import. While the current interface isn't especially amicable to general use, this module is in fact, as noted in its own readme, a coarse reverse-geocoder in its own right. We should build and fully support this as its own service.

Some notes:
- the datasource for this is currently [Quattroshapes](http://quattroshapes.com/), but we will eventually want it to use [Who's on First](http://whosonfirst.mapzen.com/)
- This could be a completely separate service than pelias, simply another pelias API endpoint, or both (by using a proxy in pelias), but it shouldn't use Elasticsearch at all

**Comment by orangejulius** [comment]
Long awaited update: support in the Pelias API for using an external [point in polygon service](https://github.com/pelias/pip-service) to massively improve the performance and accuracy of coarse (city, country, etc) reverse geocoding is nearly done. https://github.com/pelias/api/pull/810 brings that support into the API and will be live for Mapzen Search soon.

**Comment by orangejulius** [comment]
More information is also available at the coarse reverse milestone page: http://pelias.io/milestones/coarse_reverse/

**Comment by dianashk** [comment]
This is officially DONE! 🎉  🎈 💃  🕺
