### ISSUE TITLE
Quattroshapes -> Who's on First

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#144]
Migration from Quattroshapes as a data source and the driver for [admin-lookup](https://github.com/pelias/admin-lookup).

Implications in many areas. Further definition to come.

See: [pelias/whosonfirst](https://github.com/pelias/whosonfirst)

**Comment by dianashk** [comment]
This story can be closed given that we've switched to using milestones. See [Who's on First milestone here](https://github.com/pelias/pelias/milestones/Who's%20on%20First).
