### ISSUE TITLE
Unify Private and Vagrant Chef Cookbooks

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#146]
Right now there are two sets of cookbooks for building Pelias: the full Chef cookbooks (which are in a private repository), and the Chef cookbooks in the Pelias [Vagrant](https://github.com/pelias/vagrant) image.

While this makes it easy to ensure our private credentials for AWS, etc don't accidentally leak out, it has the following disadvantages:
- any functionality in the vagrant image is duplicated in the full cookbooks
- the functionality that exists in the vagrant image is usually a bit more limited than in the full cookbooks
- Most of us (I think) use the Vagrant image fairly infrequently, so it's possible we could break it inadvertently and not know until someone else reports it
- the vagrant image often falls behind the full cookbooks, for example it was missing Openaddresses support until [recently](https://github.com/pelias/vagrant/pull/13)
- Pull requests and contributions to the Vagrant cookbooks can't easily be incorporated into the full cookbooks

Even if it's not a full unification, it would be great if more of the cookbook code was shared.

_This comment written by @orangejulius_

**Comment by riordan** [comment]
@orangejulius can you define?

**Comment by dianashk** [comment]
Vagrant setup has been deprecated.
