### ISSUE TITLE
Move onto Libpostal for address parsing and deduplication

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#152]
We have to figure out the state of [Libpostal](https://github.com/openvenues/libpostal). Would be remarkable as an address parsing engine.

**Comment by riordan** [comment]
In the meantime, we need to figure out if it breaks an address down to components.

**Comment by mattiasb** [comment]
Just passing by, but do you mean [this repo](https://github.com/openvenues/libpostal)?

**Comment by riordan** [comment]
@mattiasb: I did; whoops! Thank you catching it!

**Comment by YannBrrd** [comment]
Hi,

Plans to move forward ? Very exciting lib

**Comment by riordan** [comment]
Yes, we hope to begin this work in the next several weeks.

On Thu, Feb 25, 2016 at 9:17 AM, Yann Barraud <notifications@github.com>
wrote:

> Hi,
>
> Plans to move forward ? Very exciting lib
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/pelias/issues/152#issuecomment-188801466>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by YannBrrd** [comment]
👍 thanks

**Comment by vesameskanen** [comment]
Any proceedings? This would be a great improvement. Currently it seems impossible to generate local street address searches, because parsing is strictly specific to US conventions. Postfixing a magic word 'rd' or 'st' helps, but that is not Finnish :)

**Comment by dianashk** [comment]
@trescube is hard at work on this as we speak! We got held up by the infamous WOF integration and are just now picking back up on other tasks. Thanks for your patience. To see progress, keep an eye on the [Address Parsing milestone](https://waffle.io/pelias/pelias?milestone=Address%20Parsing).

**Comment by trescube** [comment]
Modify GeodisambiguationQuery to incorporate `query` so that "Union Square, San Francisco" can find venues in a single coarse field context.

**Comment by trescube** [comment]
Add support for `sources` and `layers` parameters in new Query modules.

**Comment by trescube** [comment]
Geonames module

[ ] get pelias model version bumped up
[ ] make sure geonames tests pass with model version change
[ ] release new version of geonames
[ ] kick off data build for geonames changes
[ ] merge data build to staging/production

Text Analyzer module

[ ] version bump

Query module

[ ] update to ES 2 (naming parts of query, bake into GeodisambiguationQuery for easier trimming)
[ ] get query and address support into GeodisambiguationQuery
[ ] support for population/popularity scoring
[ ] support for focus point
[ ] support for `sources` and `layers` parameters
[ ] support for boundaries

API module

primary
[ ] single instance of libpostal (microservice OR parent/child messaging like in WoF PiP lookup)
[ ] revisit deduper for correct operation (throws away Socorro, NM for “socorro” input)… may be an issue, not sure yet
[ ] fallback to existing behavior when new queries don’t return anything

secondary
[ ] modify trimByGranularity to account for Geodisambiguation case
[ ] work out strategy for input granularity vs output granularity (possible confidence score update)

Ops work
[ ] modify chef setup to include libpostal on API

Validation work
[ ] run/evaluate acceptance tests

**Comment by dianashk** [comment]
This is all done!
