### ISSUE TITLE
Generic GeoJSON importer

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#153]
Should be a basic way and tutorial to import GeoJSON POI's.

Perhaps can be done as part of pelias/pelias#117.

**Comment by dianashk** [comment]
Connected to pelias/pelias#525

**Comment by dianashk** [comment]
Done! 🌮 🌮 🌮

**Comment by Alex237** [comment]
Hello, i cannot find the link i the doc, please ca you give me the link to  the doc ?

Best regards

**Comment by trescube** [comment]
Hi, we recently started up a project that formats documents into JSON ready to be inserted into Elasticsearch, available here: https://github.com/pelias/document-service/

There are example importers here:  https://github.com/pelias/document-service/tree/master/examples

**Comment by Alex237** [comment]
Thank you @trescube ! i will take a look to this.
