### ISSUE TITLE
SF City / SF County - Permanent Fix

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#156]
Last week the team made a temporary change to the index to conflate SF County with SF City (and to change the display centroid so it's not in the middle of the Pacific).

While that worked pretty well, it fell apart after we rebuilt the world. 

Lets make SF SF so @burritojustice stops bugging us.

- [x] Test for issue (done in pelias/acceptance-tests#187)
- [ ] Perform temp hotfix after each new build until...
- [x] Fix for good using WOF and possibly fixes to quattroshapes importer

**Comment by dianashk** [comment]
Write test and close issue.

**Comment by orangejulius** [comment]
@dianashk, do you have the document update `curl` we used saved in a gist somewhere that can be linked to in this ticket?

**Comment by dianashk** [comment]
The full report was in an email. Here's the command we ran.

```bash
curl -XPOST 'localhost:9200/pelias/locality/2099:locality:us:usa:san_francisco/_update?pretty' -d '
{
  "doc": {
    "center_point": {
      "lon": -122.431272,
      "lat": 37.778008
    },
    "popularity":1588330,
    "population": 805235,
    "name":{
      "default":"San Francisco",
      "alt1":"San Francisco City"
    },
    "admin1_abbr": "CA",
    "admin1": "California",
    "locality": "San Francisco",
    "alpha3": "USA",
    "admin2": "San Francisco County",
    "admin0": "United States",
    "category": [
      "admin:city",
      "admin"
    ]
  }
}
'
```
