### ISSUE TITLE
Reverse geocode label incomplete [in UK]

### ISSUE THREAD

**Issue by amnesia7** [pelias/pelias#157]
The example reverse geocode for `Arlington, Manhattan, NY` looks to be using `name`, `localadmin` and `region_a` for the label.

If I run the following position:

http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=53.483602348746956&point.lon=-2.2415220737457275

it returns:
```
properties: {
id: "4960939",
gid: "osm:venue:4960939",
layer: "venue",
source: "osm",
name: "Arndale Centre",
country_a: "GBR",
country: "United Kingdom",
region: "Manchester",
county: "Greater Manchester",
locality: "Manchester",
neighbourhood: "Chinatown",
confidence: 0.8,
distance: 0.043,
label: "Arndale Centre, Chinatown, Greater Manchester"
}
```
which uses the `name`, `neighbourhood` and `county` for the label.

I can understand that some countries would shorten the label in different ways depending on how those that live there would refer to places in the country. 

I've checked a range in the UK and they look like they would be clearer if they included the `region` in the label as well (or maybe instead of `neighbourhood`), eg `Arndale Centre, Chinatown, Manchester, Greater Manchester` or  `Arndale Centre, Manchester, Greater Manchester` in this case.

Here's another example, this time in London `The Hack and Hop, Lincolns Inn, Greater London` although it would probably be better if it was `The Hack and Hop, Lincolns Inn, London, Greater London` by including the `region`.

**Comment by dianashk** [comment]
@amnesia7, thanks for the issue. Currently the label format is based on this [config file](https://github.com/pelias/api/blob/master/helper/labelSchema.json). If you think there's a better label format for GBR, feel free to submit a PR for that config file.

In the future, we plan to grab the label format info from our new data source, [WOF](https://github.com/whosonfirst/whosonfirst-data). Until we're integrated with that source and they start to actually support that information, we're going to continue to rely on the simple config file with one entry per country code.

**Comment by amnesia7** [comment]
@dianashk can you give me more information of how these arrays are used?

Does the `label` first uses the `name`, then uses the first data it finds for the record as it steps through the `local` array options and then uses the first data it finds as it steps through the `regional` array?

If so, how would adding an extra data field value into the `label` response be attained for my suggestion? Would it need each of the arrays to have a `local`, `regional` and a `national` array?

**Comment by missinglink** [comment]
hi @amnesia7, we are aiming for 3x 'sections' in the label, something like this: `{name}, {local}, {regional}`

for Great Britain it's currently set up like this:
```
  "GBR": {
    "local": ["neighbourhood", "county", "localadmin", "locality", "region"],
    "regional": ["county","country","region"]
  },
```

not all records have all of those fields set, so the code cycles through those arrays and checks if the document has that field set, when it finds one that is available, it uses that value.

eg. `doc.neighbourhood` is not set, but `doc.county` is set, so we use the value of that.

it also checks for duplicates, so if it matches a field for `local` that ends up having the same value in `regional` it'll go ahead and skip that one, looking for the next match.

it might make more sense to have a look at the unit tests https://github.com/pelias/api/blob/master/test/unit/helper/labelGenerator.js

eg: https://github.com/pelias/api/blob/master/test/unit/helper/labelGenerator.js#L299

choosing the best fields to use seems to be subjective and dependant on geography and how the data is arranged, so we added a top-level section in the config which allows us to vary the config depending on the country.

for the UK ones, I was a Londoner and so I set it up to work for the places I know in London, which probably doesn't work so well in the rest of the UK, so I'd be happy to see how it might look for elsewhere in the UK.

the general idea is that there should be enough information in the label to disambiguate the labels in a list.

**Comment by nvkelso** [comment]
Lurking

**Comment by amnesia7** [comment]
Your test looks to be a bit of a jump between `Haggerston` and `Greater London`. I would've thought it would be better to produce `Hackney City Farm, Haggerston, London`. @missinglink as a previous Londoner which makes more sense to you if you were searching and this result came up?

To jump from a small place like `Haggerston` (not been, just assuming) to `Greater London` and miss out `London` itself seems a bit disjoint.

It may just be a case of changing the order that the code decides which field to use rather than adding another one to the label but I'm not sure because if it uses fields that are not big enough places on their own then it may not give the user a good enough picture of where in the country the location actually is.

Some of the ones for towns may be just as difficult because the labels may jump from a small area of the town that even the residents didn't realise it was called; to the county that the place resides in.

An example of one that may just be the order that the fields are selected is https://search.mapzen.com/v1/reverse?size=1&point.lat=53.7&point.lon=-2.6&api_key=search-xxxxxxx which returns `Brown House Wood, Wheelton CP, United Kingdom` but would probably be better returning `Brown House Wood, Wheelton CP, Lancashire`. That may just benefit from changing `"regional": ["county","country","region"]` to `"regional": ["county","region","country"]` or `"regional": ["region","county","country"]`. I'm sure you'll have a better understanding of the kind of things that are in the county and region fields.

**Comment by missinglink** [comment]
hey @amnesia7, how about this config?

```javascript
"GBR": {
  "local": ["neighbourhood", "region", "county", "localadmin"],
  "regional": ["locality","county","country","region"]
}
```

```
before:

Hackney City Farm, Haggerston, Greater London
Brown House Wood, Wheelton CP, United Kingdom

after:

Hackney City Farm, Haggerston, London
Brown House Wood, Lancashire, United Kingdom
```

**Comment by amnesia7** [comment]
@missinglink I see what you're saying about it not being as obvious to foreigners where the place is...without showing it on a map. 

It should be fine to use the `properties.text` with a map but it could also be shown in an autocomplete dropdown.

As a comparison, here's how nominatim outputs wheelton: https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&limit=2&q=wheelton

How would the updated config fair if the location had a `locality` and a `county`? 
Isn't the locality supposed to be more local than county? 
Would this not result in the address appearing backwards?

I think I'd keep locality with `"local"` rather than put it in `"regional"`. It might be worth checking nominatim/openstreetmap to find out the order that the fields all apply to check they're in the right order in `"local"` and in `"regional"`. A good example I can find to check on the database would be https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&limit=2&q=chorley+little+theatre because it looks to have all the fields filled in but I'm not sure which text is coming from which field.

**Comment by missinglink** [comment]
I think it's best to put this on hold for now, when we have upgraded from `quattroshapes` to `who's on first` for our admin hierarchy we can revisit, as it currently stands the `key->value` mapping of admin properties is not consistent enough to do this feature justice.

DO NOT CLOSE

**Comment by orangejulius** [comment]
Hey @amnesia7,
Checking in after a looong delay. We have Who's on First all imported as mentioned by @missinglink, and @trescube has done a ton of work on labels. The labels are looking much better now!

Some comparisons of labels mentioned in this thread:

Before | Today
----- | ----
Arndale Centre, Chinatown, Greater Manchester | 	Arndale Centre, Manchester, England, United Kingdom
The Hack and Hop, Lincolns Inn, Greater London | 	The Hack and Hop, London, England, United Kingdom 
Hackney City Farm, Haggerston, Greater London | Hackney City Farm, London, England, United Kingdom
Brown House Wood, Wheelton CP, United Kingdom | Brown House Wood, Wheelton, England, United Kingdom

Do you whink we cover all the cases sufficiently? If not, what are we missing?

**Comment by amnesia7** [comment]
@orangejulius from what I can see and what I've checked it looks great now, very happy with the output. I'll re-open or create a new issue if I spot anything that's off but from my point of view this issue can be closed now if that's the case.
Thanks to all involved.

**Comment by orangejulius** [comment]
Awesome, glad to confirm we've been improving :)

:100: :palm_tree: :tada: :+1:
