### ISSUE TITLE
Encoding issue with some search results

### ISSUE THREAD

**Issue by elyoh** [pelias/pelias#163]
https://search.mapzen.com/v1/search?text=Athens, Greece&api_key=search-putownkey

Gives:

{"type":"Feature","properties":{"id":"264371","gid":"gn:locality:264371","layer":"locality","source":"gn","name":"Athens","country_a":"GRC","country":"Greece","region":"Attica","county":"Nomarchía Athínas","locality":"ÎÎÎÎÎÎ","confidence":0.952,"label":"Athens, ÎÎÎÎÎÎ, Greece"},"geometry":{"type":"Point","coordinates":[23.71622,37.97945]}},
{"type":"Feature","properties":{"id":"8133876","gid":"gn:neighbourhood:8133876","layer":"neighbourhood","source":"gn","name":"Dimos Athens","country_a":"GRC","country":"Greece","region":"Attica","county":"Nomarchía Athínas","locality":"ÎÎÎÎÎÎ","confidence":0.884,"label":"Dimos Athens, ÎÎÎÎÎÎ, Greece"},"geometry":{"type":"Point","coordinates":[23.73604,37.98888]}},
{"type":"Feature","properties":{"id":"8131587","gid":"gn:locality:8131587","layer":"locality","source":"gn","name":"Ymittos Athens","country_a":"GRC","country":"Greece","region":"Attica","county":"Nomarchía Athínas","locality":"ÎÎÎÎÎÎ","confidence":0.672,"label":"Ymittos Athens, ÎÎÎÎÎÎ, Greece"},"geometry":{"type":"Point","coordinates":[23.74897,37.95342]}},

Results contains "locality" field which contains bytes which do not map to characters in UTF8.

The corresponding geonames entries do not appear to have any encoding issues.
http://www.geonames.org/264371/
http://www.geonames.org/8133876/
http://www.geonames.org/8131587/
although it is unclear which field in geonames maps to "locality".

**Comment by riordan** [comment]
We believe these should all be fixed by moving our data sources to rely on [Who's on First](https://whosonfirst.mapzen.com), a gazetteer that replaces Quattroshapes. We should have this resolved within the next few weeks.

**Comment by orangejulius** [comment]
Hey @elyoh,
At long last we are using Who's on First in production as @riordan mentioned. And [as you can see](http://pelias.github.io/compare/#/v1/search%3Ftext=athens,%20greece), this is now fixed!

If you do see any other encoding errors, let us know. There are still a few, but we can fix them much faster now.
