### ISSUE TITLE
BUG: Focus Point Autocomplete - Jumpy Address Search

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#165]
__this is very much in progress__

- [x] Needs acceptance tests added

:rotating_light: **THIS IS A BLOCKER FOR ERASERMAP**:rotating_light:

Focus point should be able to boost address searches within a sufficiently large distance from the user's current point.

Introducing more consistency into autocomplete results (preferring exact matches, particularly exact start of phrase matches for addresses) should assist with this.

### Example: Looking for 190 Dean Street, in Brooklyn, NY, starting from [Orient Point](https://en.wikipedia.org/wiki/Orient,_New_York) on Long Island.

Let's say I'm out at the [furthest tip of Long Island's north fork](https://en.wikipedia.org/wiki/Orient,_New_York) and have a reservation at [Rucola](http://nymag.com/listings/restaurant/rucola/) a favorite neighbourhood restaurant in Brooklyn.

> **_[1](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=1)_** 
>   1)	Vuwani 1, NORTHERN PROVINCE, South Africa :x:
 2)	Mdutjana 1, MPUMALANGA, South Africa
 3)	Moretele 1, NORTH WEST, South Africa
 4)	Mdantsane 1, EASTERN CAPE, South Africa

> **_[19](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=19)_**
>   1)	Paris 19, PARIS-19E-ARRONDISSEMENT, France :x:
 2)	19 de Febrero de 1812, Cuautla, Mexico
 3)	Kilómetro 19, El Fuerte, Mexico
 4)	Colonia 19 de Marzo (Colonia San José), Heroica Ciudad de Juchitán de Zaragoza, Mexico

> **_[190](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190)_**
>   1)	190 D Street, Groton, CT :x:
 2)	190, South West, Singapore
 3)	190, Headington, Oxfordshire
 4)	190, Blangpidie, Indonesia

> **_[190 *space*](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20 )_**
>   1)	190 D Street, Groton, CT :x:
 2)	190, South West, Singapore
 3)	190, Headington, Oxfordshire
 4)	190, Blangpidie, Indonesia

> **_[190 d](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20d)_**
> 1)	190 D Street, Groton, CT :x:
 2)	190 D Street, Lowell, MA
 3)	190 D Street, Johnstown, PA
 4)	190 D Street, Chula Vista, CA

> **_[190 de](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20de)_**
>   1)	190 De Dennen, Bussum, Netherlands :x:
 2)	190 De Dennen, Bussum, Netherlands
 3)	190 De Haernestraat, Brussel, Belgium
 4)	190 De Lange Akker, Vaals, Netherlands

> **_[190 dea](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dea)_**
>  1)	19 Dean Road, East Lyme, CT :x:
 2)	1902 Deerfield Road, Southampton, NY
 3)	1903 Deerfield Road, Southampton, NY
 4)	190 Deerfield Road, Southampton, NY

> **_[190 dean](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dean)_**
>  1)	190 Dean Street, Brooklyn, NY :white_check_mark: 
 2)	190 Dean Street, Norwood, MA
 3)	190 Dean Street, Brooklyn, NY
 4)	190 Dean Road, Alamo, CA

> **_[190 dean s](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dean%20s)_**
 1)	Sekgosese 1, NORTHERN PROVINCE, South Africa :x:
 2)	19 Dean Road, East Lyme, CT
 3)	0 Dean Road, East Lyme, CT
 4)	9 Dean Road, East Lyme, CT

> **_[190 dean st](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dean%20st)_**
 1)	190 Dean Street, Brooklyn, NY :white_check_mark: 
 2)	190 Dean Street, Norwood, MA
 3)	190 Dean Street, Brooklyn, NY
 4)	190 Dean Street, Berserker, Australia

> **_[190 dean str]
(http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dean%20str)_**
 1)	Sekgosese 1, NORTHERN PROVINCE, South Africa ¯\_(ツ)_/¯
 2)	19 Dean Road, East Lyme, CT
 3)	0 Dean Road, East Lyme, CT
 4)	9 Dean Road, East Lyme, CT

> **_[190 dean stre](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dean%20stre)_**
>   1)	19 Dean Road, East Lyme, CT ¯\_(ツ)_/¯
 2)	Sekgosese 1, NORTHERN PROVINCE, South Africa
 3)	Dunajska Streda, Trnavský kraj, Slovakia
 4)	0 Dean Road, East Lyme, CT

> **_[190 dean stree](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dean%20stree)_**
 1)	19 Dean Road, East Lyme, CT ¯\_(ツ)_/¯
 2)	Sekgosese 1, NORTHERN PROVINCE, South Africa
 3)	0 Dean/Hill Streets, Raynham, MA
 4)	0 Dean Road, East Lyme, CT
 5)	9 Dean Road, East Lyme, CT

> **_[190 dean street](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=41.145278&focus.point.lon=-72.288611&text=190%20dean%20s)_**
 1)	190 Dean Street, Brooklyn, NY :white_check_mark: 
 2)	190 Dean Street, Norwood, MA
 3)	190 Dean Street, Brooklyn, NY
 4)	190 Dean Street, Berserker, Australia

cc: @randymeech

**Comment by riordan** [comment]
Perhaps we should have a _very_ fast address/locality detector running in Autocomplete.

**Comment by missinglink** [comment]
is this fixed now?

![image](http://missinglink.embed.s3.amazonaws.com/pelias-issue-165.gif)

**Comment by riordan** [comment]
@missinglink That looks like it's behaving awesomely. But try it from [Orient Point](http://pelias.github.io/leaflet-geocoder/#14/41.1604/-72.2336)

Gets weird when you start putting "190 dean street brooklyn".

**Comment by riordan** [comment]
Examples:
**From NYC**
![fromnyc](https://cloud.githubusercontent.com/assets/227472/11130777/db19a76c-8954-11e5-8829-c54fa23f950b.gif)

**From Orient Point**
![fromorientpoint](http://g.recordit.co/hp01Q1nqEF.gif)

**From Orient Point, but with Search at the end**
![withsearch](http://g.recordit.co/IwJf7qlPgu.gif)

**Comment by missinglink** [comment]
it may be best to delete this issue in favour of a new issue called `"write an input parser for autocomplete"`

... just because there is mixed messaging in the title and description of this ticket from what you described in the last comment.

**Comment by randymeech** [comment]
let's change the title if we need to, but this is a huge issue that needs attention as soon as possible

**Comment by riordan** [comment]
I've been thinking about this some more, and I'd like to run some tests to see what happens if we increase the distance for focus again. Right now the [default distance](https://github.com/pelias/api/blob/master/query/autocomplete_defaults.js#L34) for Autocomplete focus boosting is 50km, which can be rather small for a large metro area.

50km might be fine if you're in the middle of that city, but the moment you're on one side of the city (e.g. the airport) and trying to find some place on the other side of town, it's not going to be as rewarding an experience.

Frankly 50km isn't that far.

I'd be interested to see what happens were we to expand that radius so it's much larger, on the order of 290km (the distance from Newark, NJ to Montauk, NY, and about the distance from the outskirts of LA to San Diego). And there are a growing number of [Megacommuters (PDF to census study)](http://www.census.gov/newsroom/releases/pdf/paper_mega_%20commuters_us.pdf) who travel > 80km and more than 90 minutes each way to work. Perhaps we might know a few of these folks ;)

I was talking with @indyhurt about this and we might try to figure out what the size across large metro areas would be.

Hopefully that'd be a distance that even in the densest areas would return good results, fast.

It doesn't fix the jumpyness of the query (though we have some ideas on how to resolve that as well).

**Comment by dianashk** [comment]
@orangejulius is actively investigating the issues plaguing autocomplete at this time. 
 The radius for the focus and decay function is purely config driven now so everyone can experiment with different values and see how the tests fair on dev. 

I'll add the link to the line of code to change in a following comment.

**Comment by riordan** [comment]
Props to the team on the significant progress in analyzing, diagnosing, and improving autocomplete issues over the past few weeks.

Between @orangejulius' [Autocomplete Tester](https://github.com/pelias/fuzzy-tester/tree/autocomplete-tester) helping us diagnose the situation and @missinglink's sleuthing, we've got two omnibus pull requests merged that radically improve the situation.

1. Autocomplete API Overhaul (pelias/api#378)
2. Autocomplete Elasticsearch Schema Overhaul (pelias/schema#84) 

There's a lot of changes in both of these, so I recommend reading through the linked tickets (particularly pelias/api#378) to see detailed summaries (and code) of what's changed.

We should see how this fares in the real world once the latest [reindexing completes](http://pelias-dashboard.mapzen.com/pelias) tomorrow. Once that's done, I'm looking forward to @randymeech's next erasermap test drive.

**Comment by riordan** [comment]
Needs acceptance tests for jumpy autocomplete

**Comment by orangejulius** [comment]
The branch in #196 is where I've been putting acceptance tests for these sorts of issues. Help creating tests or adding to the list of checkboxes is welcome.

**Comment by missinglink** [comment]
this issue is resolved in production and covered by https://github.com/pelias/acceptance-tests/commit/84d5e515f7f7a12ca90dac0de4d8c1b1775dd032
