### ISSUE TITLE
Stop stripping out leading 0's in postalcodes

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#166]
We currently fail the search for [339 W Main St, Cheshire, CT, 06410](http://pelias.github.io/compare/#/v1/search%3Ftext=339%20W%20Main%20St,%20Cheshire,%20CT%2006410) as well as [301 Commons Park S, Stamford, CT 06902](http://pelias.github.io/compare/#/v1/search%3Ftext=301%20Commons%20Park%20S,%20Stamford,%20CT%2006902) because we strip out leading `0`'s from the postal code numbers. 

That's unfortunate because looks like postal codes often will start with `0` and stripping them out results in matches to the wrong ones. Shouldn't hold up this PR. I'll create a separate issue.

`06902` ends up matching `6902`, which is a legitimate postal code in _Tirol, Australia_.

This became evident when postalcode boost was significantly increased to improve result accuracy where postalcode was specified. But highlighted this problem as a result.

**Comment by riordan** [comment]
Great catch. CT postal codes (and much of the east coast) start with 0's

**Comment by missinglink** [comment]
:+1: good catch
