### ISSUE TITLE
Handling unicode symbols

### ISSUE THREAD

**Issue by KathleenLD** [pelias/pelias#173]
The following question was sent in by Mapzen Search user @Freundschaft

> I was just wondering, how are you handling unicode symbols such as umlauts etc?
> I have a problem with the following reverse lookup:

```
{"geocoding":{"version":"0.1","attribution":"https://search.mapzen.com/v1/attribution","query":{"types":{"from_layers":["locality"]},"size":1,"private":false,"point.lat":51.85110884353617,"point.lon":12.434658666990284,"boundary.circle.radius":50,"boundary.circle.lat":51.85110884353617,"boundary.circle.lon":12.434658666990284,"type":["locality"]},"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1444855337735},"type":"FeatureCollection","features":[{"type":"Feature","properties":{"id":"70158:locality:de:deu:w__rlitz","gid":"qs:locality:70158:locality:de:deu:w__rlitz","layer":"locality","source":"qs","name":"Wã¶rlitz","country_a":"DEU","country":"Germany","region":"Sachsen-Anhalt","county":"Wittenberg","confidence":0.5,"distance":1.63,"label":"Wã¶rlitz, Wittenberg, Germany"},"geometry":{"type":"Point","coordinates":[12.4203959486103,51.8394245502361]}}],"bbox":[12.4203959486103,51.8394245502361,12.4203959486103,51.8394245502361]}
```

**Comment by Freundschaft** [comment]
thanks! :+1:

**Comment by dianashk** [comment]
Hey, @Freundschaft. Thanks for reaching out. There is a known issue in our current administrative data source (and its import process) that is responsible for the encoding errors you're seeing. The team is working on switching to a different administrative data set, which will resolve all these issues. We're expecting that to be released within the next few months.

Track this issue for resolution status: https://github.com/pelias/pelias/issues/144

Other related issues: 
* https://github.com/pelias/pelias/issues/163
* https://github.com/pelias/quattroshapes-patch/issues/10
