### ISSUE TITLE
Can't find 521 E Kennedy Blvd in Florida

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#174]
This is from the incredibly large Florida restaurant inspections dataset found by @riordan 

I was unable to come up with a query that find this address in the top 10 (best was 16th place), even though the data is there, and quite complete, including zipcode. Other less relevant results keep coming up on top. Anyone have any idea why?

http://pelias.github.io/compare/#/v1/search%3Fsize=40&text=521%20East%20KENNEDY%20Boulevard,%20eatonville,%20FL,%2032751

**Comment by orangejulius** [comment]
We fixed this at some point! :tada:

**Comment by dianashk** [comment]
Looks like a good acceptance test. Let's add it if it hasn't already been
added.

**Comment by orangejulius** [comment]
This is in the fuzzy tests, along with the other post office tests, so I think we can leave it out of acceptance tests for now. Going through the post office tests almost always valuable though, and there are certainly good acceptance test cases in there
