### ISSUE TITLE
Create generic Varnish Geohash VMOD

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#175]
Storing location-bound requests (e.g. focus.viewport, focus.point) is significantly easier to cache if the key is a geohash, however most clients don't expect to geohash these queries.

Luckily point -> geohash & bbox->geohash are transactions that could hypothetically be performed very quickly in the cache layer with a [Varnish VMOD](https://www.varnish-cache.org/docs/trunk/reference/vmod.html) plugin written in C, if it were to be installed by Fastly.

Useful features would look like a combination of [node-geohash](https://github.com/sunng87/node-geohash), for most transactions. Would be even better if it also had support for [geohash polygons](https://github.com/derrickpelletier/geohash-poly).

Once it exists, it's a matter of convincing Fastly to install it.

cc: @missinglink

**Comment by riordan** [comment]
Could possibly just extend SimpleGeo :cry: [libgeohash](https://github.com/simplegeo/libgeohash) and add bbox / polygon encoding in the process.

**Comment by missinglink** [comment]
a simpler solution could also be considered so long as it exhibits `SpatialPrefixTree` functionality. Eg. it could be `quadtree` or even `trip floating point precision`.

agree an *ideal* solution would be `s2` or `geohash`.

**Comment by missinglink** [comment]
as a first step I would reach out to `fastly` (our VAAS provider) and speak with them about it. their docs say that they will not install 3rd party VMOD extensions as they run their infrastructure in a shared environment, plus they might be happy to do it for us as it would benefit their other customer too.

**Comment by riordan** [comment]
Quick update: Aaron's talked to Fastly about doing some work with Who's on First and they seemed very amenable to adding additional VMOD code to support it in their GeoIP tool. Likely to extend the same hospitality for a geohash service.

One thing I'd like to see from this: In addition to converting a lat/lon into a geohash, this would be incredibly useful if it were to have a function that could convert a BBOX or polygon) into a single geohash OR a collection of (simplified) geohashes.

**Comment by orangejulius** [comment]
This is a Mapzen Search specific issue. Pelias itself doesn't do any stuff with [Varnish](https://varnish-cache.org/)
