### ISSUE TITLE
Place lookup for geonames ids are all listed as `gn:venue`, even if they're of different place types

### ISSUE THREAD

**Issue by UnicycleJonathan** [pelias/pelias#176]
Do a simple search like https://search.mapzen.com/v1/search?api_key<key>&text=London that returns results from geonames.  Pull the gid out of one of the results and try to do a place lookup, e.g. 

https://search.mapzen.com/v1/place?api_key=<key>&ids=gn:locality:2643743

No results are found.  Place lookups seem to work fine for other source namespaces.

Connected to pelias/pelias#226

**Comment by riordan** [comment]
@UnicycleJonathan Good catch!

From some preliminary tests, it looks like all of geonames is treated as `venue` for id lookup purposes, meaning our ID system needs some work.

To retrieve those documents today though, replace `gn:locality` with `gn:venue`.

e.g.
`/v1/place?ids=gn:venue:2643743`

We'll now be adding that to our documentation addendum for Geonames pretty soon [pelias/pelias-doc#77].

Thank you!

**Comment by UnicycleJonathan** [comment]
Great, really appreciate the fast response and the suggested workaround.
