### ISSUE TITLE
A list of locations that returned 0 features

### ISSUE THREAD

**Issue by Caged** [pelias/pelias#177]
First of all, thanks for the great work on this project!  I ran a large set of location names through the Mapzen search API (v1) using `boundary.country=USA`.  The vast majority of them were identified, however the items in the list below didn't return any feature results.  

* Green Bay, Wisconsin
* Bend, Oregon
* Spring, Texas
* River Ridge, Louisiana
* Mountain Brook, Alabama
* Valley Forge, Pennsylvania
* Vista, California
* Mill Creek, Washington
* Forest, Virginia
* Spring Grove, Pennsylvania
* Spring Branch, Texas
* Green Cove Springs, Florida
* Grove Hill, Alabama
* Valley Glen, California
* Spring Valley, California
* Pine Bluff, Arkansas
* Valley Center, California
* Green River, Wyoming
* Valley, Alabama
* Bay Springs, Mississippi
* Garden Grove, California
* Manor, Texas

**Comment by orangejulius** [comment]
Hey @Caged, this is super helpful! A lot of these are probably data issues that can be quickly resolved in the near future after we begin importing data from [Who's on First](http://whosonfirst.mapzen.com).

Can you share the dataset you used for this? I'd love to add it to our [test suite](https://github.com/pelias/fuzzy-tests) so we can continuously monitor progress going forward.

**Comment by Caged** [comment]
> Can you share the dataset you used for this? I'd love to add it to our test suite so we can continuously monitor progress going forward.

@orangejulius sure!  Here's a gist containing a list of distinct names I was searching on https://gist.github.com/Caged/6ce6b2a6ecda4579b64f

**Comment by orangejulius** [comment]
A while back, we added this dataset to our [fuzzy-tests](https://github.com/pelias/fuzzy-tests), and I just now took a quick look at how they're doing. After some simple [fixes](https://github.com/pelias/fuzzy-tests/pull/29) we get all but 81 correct (most of which we find, but too far down in the results to be satisfactory), and we don't return an empty result list for _any_ of them!
