### ISSUE TITLE
Searching from Brooklyn with viewport on finds no pizza in Brooklyn

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#181]
Query in question: [Pizza](http://pelias.github.io/compare/#/v1/search%3Ffocus.viewport.max_lat=40.69013283158811&focus.viewport.min_lon=-74.01224764277981&focus.viewport.min_lat=40.648468077860784&focus.viewport.max_lon=-73.98134859722018&text=pizza)

Works ok on autocomplete, but on search is a bit batty.

[missinglink] note: the `focus.viewport` API is not available via `/v1/autocomplete`, it IS available via `/v1/search`, care must be taken not to confuse the two.

This is one good reason for introduction of more readable bbox/point syntax.

**Comment by riordan** [comment]
cc @mjcunningham

**Comment by dianashk** [comment]
Add acceptance test and close. Fixed on dev at the time of this update.

**Comment by missinglink** [comment]
the bbox in question is:

![embed](http://missinglink.embed.s3.amazonaws.com/riordan_bbox.png)

**Comment by missinglink** [comment]
I've looked at this a few times now and I don't really understand the issue, there bbox API seems to return unusual results, however it's a small bbox and so I'm not sure what results were expected?

When changing the request to use the `focus.point` API instead such as [this](http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=40.69013283158811&focus.point.lon=-74.01224764277981&text=pizza) returns decent results.

**Comment by dianashk** [comment]
`/autocomplete` never supported, nor should it have supported, focus.viewport. It is a parameter we implemented on `/search` but failed to document it and it has gone unused. It's a contentious parameter and we'd like to run some user research studies around it to determine if it should stay or get yanked out.

**Comment by dianashk** [comment]
After checking the logs for usage of focus.viewport in the last few months it seems that there are no real users sending queries with it. Let's remove it and add a note to release notes when the change is released.

**Comment by missinglink** [comment]
resolved by https://github.com/pelias/api/pull/620
