### ISSUE TITLE
Pelias without Vagrant Instance

### ISSUE THREAD

**Issue by curiousc0w** [pelias/pelias#182]
I was wondering if there was any detailed documentation to install Pelias without a Vagrant instance. If not where would be a good starting point?

Thank you!

**Comment by hannesj** [comment]
You can look at our [Dockerfile](https://github.com/HSLdevcom/digitransit-deploy/blob/master/roles/pelias-docker-image/templates/Dockerfile.j2) for some inspiration how to load some data and run the Pelias API.

**Comment by riordan** [comment]
That's awesome, @hannesj

**Comment by KentJacobs** [comment]
@hannesj I was able to ```docker build``` successfully and ```curl localhost:9200```. Are there any other steps to execute queries using Pelias?

**Comment by dianashk** [comment]
@hannesj, the dockerfile is fantastic and super helpful to many. Would you mind if we linked to it directly from our documentation as an example of how others can do the same?

**Comment by hannesj** [comment]
@dianashk, sure I could strip out some parts that are specific to our data and make a PR over at pelias/pelias-doc. Also note that it's a bit unorthodox to run multiple services in one container, so maybe I could split out also a file which separates the Elasticsearch container.

**Comment by hannesj** [comment]
@KentJacobs, the pelias API should be exposed in port 3000, did you try that?

**Comment by KentJacobs** [comment]
@hannesj I can't curl to 3000 either. When I look in ```/mnt/``` there aren't any extracts either. Maybe something was missed?

**Comment by hannesj** [comment]
@KentJacobs 😕 Could you upload the docker build log to e.g. pastebin?

**Comment by dianashk** [comment]
@hannesj, any updates you feel should be made would be extremely appreciated!!! I think just having a place to direct folks is already helpful in itself. If you have the bandwidth to make changes to the dockerfile that makes it more generic and push it to `pelias-doc` we would be incredibly grateful!

**Comment by KentJacobs** [comment]
@hannesj 

http://pastebin.com/CuCxPqGg

Hopefully this helps!

**Comment by KrishnaPG** [comment]
Getting below errors from address-deduplicator while doing `pelias openaddresses import --admin-values --deduplicate`:
````
127.0.0.1 - - [2015-12-04 18:50:49] "POST /addresses/dedupe?batch=1 HTTP/1.1" 500 161 0.329054
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 508, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 494, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/address_deduper/address_deduper/views/base.py", line 47, in wrapper
    return func(cls, *args, **kw)
  File "/home/ubuntu/address_deduper/address_deduper/views/address.py", line 82, in dedupe
    created = AddressNearDupe.check(addresses, add=True)
  File "/usr/local/lib/python2.7/dist-packages/address_normalizer/deduping/near_duplicates.py", line 107, in check
    clusters, local_dupes, global_dupes = cls.find_dupes(objects)
  File "/usr/local/lib/python2.7/dist-packages/address_normalizer/deduping/near_duplicates.py", line 56, in find_dupes
    _ = [clusters[safe_encode(c)].add(ent.guid) for ent in ents for c in cls.gen_keys(ent)]
  File "/usr/local/lib/python2.7/dist-packages/address_normalizer/deduping/near_duplicates.py", line 203, in gen_keys
    all_geo = cls.geohash(address)
  File "/usr/local/lib/python2.7/dist-packages/address_normalizer/deduping/near_duplicates.py", line 193, in geohash
    geo = geohash.encode(address.latitude, address.longitude, cls.geohash_precision)
  File "/usr/local/lib/python2.7/dist-packages/geohash.py", line 79, in encode
    raise Exception("invalid latitude.")
Exception: invalid latitude.
{'CONTENT_LENGTH': '117735',
 'CONTENT_TYPE': 'application/json',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'application/json',
 'HTTP_CONNECTION': 'close',
 'HTTP_HOST': 'localhost:5000',
 'PATH_INFO': '/addresses/dedupe',
 'QUERY_STRING': 'batch=1',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_PORT': '39782',
 'REQUEST_METHOD': 'POST',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'crossbar-test',
 'SERVER_PORT': '5000',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'gevent/1.0 Python/2.7',
 'werkzeug.request': <Request 'http://localhost:5000/addresses/dedupe?batch=1' [POST]>,
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fe5251dc1e0>,
 'wsgi.input': <gevent.pywsgi.Input object at 0x7fe52069ee50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)} failed with Exception

````

**Comment by hannesj** [comment]
Ok, I separated the data container creation and api into two separate docker containers.

An example data container can be found [here](https://github.com/HSLdevcom/pelias-data-container)
The Pelias API docerfile can be found in [this](https://github.com/pelias/api/pull/400) pull request.

**Comment by orangejulius** [comment]
Hello everyone,
This ticket is pretty old. Since we last checked in, we've written [installation docs](https://github.com/pelias/pelias-doc/blob/master/installing.md) that explain how to manually set up Pelias more or less from scratch. I'm going to close this ticket but feel free to open new ones for any installation issues: we want to keep the docs complete and up to date!

Also, there's growing excitement around Docker. We currently use Chef but that may change in the near future. We would definitely want to make anything we do with Docker public so stay tuned.

**Comment by ktjaco** [comment]
@orangejulius Here is something I've been working on a bit. I created a series of bash scripts to install Pelias dependencies and populate Elasticsearch. The scripts are created for CentOS 6.7. There is also a service file to start, stop, restart, etc. the Pelias server.

https://github.com/ktjaco/pelias-scripts

PS. I changed my username haha. :)
