### ISSUE TITLE
Searching for Zoo in SF does not return the San Fransisco Zoo

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#183]
Pelias Reference for: mapzen/eraser-map#141
Logged by @nvkelso
-    Device name: Samsung Galaxy S6 edge
-    Android Version: 5.1.1
-    App build number: master-481
-    What did you expected to happen? I searched for zoo and expected to find the San Francisco Zoo to nav to as the top result.
-    What happened instead? I didn't see the SF Zoo in the first 10 results, so had to fully qualify it as san francisco zoo to get that as the top result. We should be seeding search with the current map view so results are more specific.
-    Steps to reproduce: Search for zoo with current location lat/lng somewhere in SF.
-    Attach a screenshot See below.
-    Attach device logs eh.

If something happened while you were searching, share with us:
-    Where were you? 273 29th St (San Francisco, California, USA)

Searching for `zoo` near the SF Zoo should return that result first:
![img1](https://cloud.githubusercontent.com/assets/853051/11412549/00363608-9393-11e5-92b0-37c34756ee3b.png)

Instead I had to search for `san francisco zoo`:
![img2](https://cloud.githubusercontent.com/assets/853051/11412548/0008d442-9393-11e5-8502-deff4e5c27ea.png)

**Comment by riordan** [comment]
- [ ] Confirm with a Compare query
- [ ] Create a new Acceptance Test for this case

**Comment by riordan** [comment]
Test queries:
[Search](http://pelias.github.io/compare/#/v1/search%3Ffocus.point.lon=-122.426117&focus.point.lat=37.743618&text=zoo) | [Autocomplete](http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lon=-122.426117&focus.point.lat=37.743618&text=zoo)

**Comment by missinglink** [comment]
Expected:

```
    {
      "type": "Feature",
      "properties": {
        "id": "9199863",
        "gid": "gn:venue:9199863",
        "layer": "venue",
        "source": "gn",
        "name": "San Francisco Zoo",
        "country_a": "USA",
        "country": "United States",
        "region": "California",
        "region_a": "CA",
        "county": "San Francisco County",
        "locality": "San Francisco",
        "neighbourhood": "Outer Parkside",
        "confidence": 0.962,
        "label": "San Francisco Zoo, San Francisco, CA"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.50318,
          37.73259
        ]
      }
    },
```

**Comment by riordan** [comment]
This is where getting to a better sense of ranking for places would be useful. More useful for when we get to categories.

**Comment by orangejulius** [comment]
We now do a much better job with this query, thanks largely to our new popularity scoring for OSM venues (https://github.com/pelias/openstreetmap/pull/531)

[/v1/autocomplete?focus.point.lat=37.743618&focus.point.lon=-122.426117&text=zoo&debug=0](https://pelias.github.io/compare/#/v1/autocomplete?focus.point.lat=37.743618&focus.point.lon=-122.426117&text=zoo&debug=0)
![Screenshot_2020-06-25_08-57-20](https://user-images.githubusercontent.com/111716/85754449-ea0ec000-b6c1-11ea-8d2f-ee2d119c7d07.png)
