### ISSUE TITLE
Autocomplete results for Walt Disney Family Museum

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#190]
I was using EraserMap around San Francisco (~build 530) with a destination of the Walt Disney Family Museum. (These images show the Leaflet plug-in because it's easier for me to take a screenshot, but the results are the same.)

I start typing and get relevant results (at least the first result is relevant) up through Walt Disn + the e.

![image](https://cloud.githubusercontent.com/assets/4380498/11671203/5e98c2b0-9dbb-11e5-964c-dffdf07670e6.png)

When typing the y + a space, the suggestions change totally and the Family Museum drops out of the top 10 results when I would have expected it to only get more correct and highlight it. 

![image](https://cloud.githubusercontent.com/assets/4380498/11671284/053e9bda-9dbc-11e5-92b4-d5ff405c60a3.png)

It comes back when I type f.

**Comment by orangejulius** [comment]
This is super helpful! I made some test cases for this and they seem to be able to mostly reproduce it, but not completely. The difference is that with all the focus points I tried(the Transamerica Pyramid, Seacliff, the exact location of the museum, and the NYC office), the result never disappears completely, but just moves down to the 6th spot in the results.

![screenshot_2015-12-08_22-08-14](https://cloud.githubusercontent.com/assets/111716/11675523/6da87d30-9df8-11e5-8bdd-ddb84ee21388.png)

**Comment by orangejulius** [comment]
Just an update on these tests:
![waltdisneyupdate](https://cloud.githubusercontent.com/assets/111716/14509588/07973462-019b-11e6-8608-98483513db74.png)

We now return the correct result on the `i` in Disney, when searching from SF. After that we return the correct result for the rest of the query!

I'd always like to see us get the right result even sooner in the text, but as we look to have fixed all the jitter issues, I think it's safe to close this issue. If anything else crops us let us know :) :tada:
