### ISSUE TITLE
Autocomplete results for Daly City, CA (near San Francisco)

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#191]
Daly City is immediately south of San Francisco City/County and the most populous city (105k) of San Mateo County. Here's an interesting autocomplete result when searching for it from within SF, first found in EraserMap.

http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=37.769316&focus.point.lon=-122.484223&text=daly%20c

I start typing Daly and it comes up, along with other locations that do not have "daly" in them, like Hills and Dales in OH and KY...I grew up in Jefferson Co, KY and hadn't heard of "Hills and Dales" before...Turns out it has a population of 150, total.

![image](https://cloud.githubusercontent.com/assets/4380498/11731257/e237a7fa-9f4e-11e5-9a50-40356a9a1453.png)

Type a space and a C and the results all change to Dallas County, and anything related to Daly City drops out. Side note, TX, which should be the most important distant result, is down at fourth.

![image](https://cloud.githubusercontent.com/assets/4380498/11731283/1359140e-9f4f-11e5-9542-8ed6457b9742.png)

Same for + i.

Daly City in CA doesn't appear again until I've typed Daly Cit.

![image](https://cloud.githubusercontent.com/assets/4380498/11731306/357336dc-9f4f-11e5-9250-6903fecc4547.png)

**Comment by riordan** [comment]
@orangejulius + @missinglink dug into this and found that there are issues involving Elasticsearch's "kstemming". They're reviewing it in issue pelias/schema#89.

"Daly City" winds up becoming something like "Dal".

**Comment by missinglink** [comment]
Moving to 'in review', this should be resolved by https://github.com/pelias/schema/pull/109

**Comment by missinglink** [comment]
this is significantly improved on the dev server and will be rolled out to production shortly.

for SF residents "Daly City" is retrievable via autocomplete from "dal...". From "daly ci..." there is a tight clustering around the correct geography with a bunch of points of interest listed:

note: the light blue marker represents the `focus.point`.

![embed](http://missinglink.embed.s3.amazonaws.com/issue_191.png)

**Comment by missinglink** [comment]
acceptance tests: https://github.com/pelias/acceptance-tests/commit/61a66bdba9a4e5a58ea70a673d323899e5d3706c

**Comment by missinglink** [comment]
DONE. waiting on confirmation from the production cluster then this can be closed.

**Comment by dianashk** [comment]
Confirmed! 🎉
