### ISSUE TITLE
Alternative Names

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#194]
_previous title: Search & Store multiple names for places_

At present, we only store and search one name for a place, even if there are different names in different languages.

This leads to us (partially) missing the [Eifel Tower](http://pelias.github.io/compare/#/v1/search%3Ftext=Eiffel%20Tower,%20Paris,%20France), not to mention cities + towns in other languages.

Who's on First should provide a strong start on this, given that it has 7 languages for most of the administrative areas, and concordances with Geonames + Wikidata should allow for more language additions.

Obviously, there'll be issues. Index bloat. Unintended matches between languages. But this would make for a huge area of improvement and open us up to use by more developers worldwide.

**Comment by migurski** [comment]
+1 yes very important.

**Comment by Swizz** [comment]
Working on a service to locate aerodrome and heliport ; we decided to give you our use case, to bring you attention on the need of this feature.

We choosed to use Pelias, from the indexation to the api, for it simplicity. The openstreetmap importer is fine, and allow us to easiliy import only `aeroway:aerodrome` and `aeroway:heliport` keys.

We found, the configuration file to allow us to bind, important feature for our needs.
To bind `iata` field to `alternate_name` and `icao` field to official_name ; to allow our user to find Aeroway using those fields too.

For example, you are looking for the `London Heathrow Airport`, we want to give a way to our user to search it on :
```yaml
Name: London Heathrow
IATA: LHR
ICAO: EGLL
```

We are not really aware about name translation, but most on the capability to type `EGLL` in the searh field and find the right airport.

At the moment, we choose to concat on import both field in the field name too.
Like this : `London Heathrow Airport (LHR) [EGLL]`

We know this is not the greatest way. So, we enjoyed to give you this use case, to help you on you awesome job.

Thank you guys !

Cheers,

**Comment by jfuehner** [comment]
Any update on this?  is it stalled? 

https://github.com/pelias/pelias/issues/194 

Last updates were from 2019

This proposal was last updated in 2017
https://github.com/pelias/pelias/blob/master/milestones/alt-names_and_internationalization/design_proposal.md

**Comment by missinglink** [comment]
This was resolved many years ago
