### ISSUE TITLE
Create autocomplete specific test cases

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#196]
Note: this issue description itself is still a work in progress

We now have the [autocomplete tester](https://github.com/pelias/fuzzy-tester/pull/28), but still very few tests specifically designed to capture all the interesting cases for autocomplete. Roughly, this breaks down to 4 categories: addresses, points of interest, regions, and categories. We need some tests for each interesting case of each category

## Addresses
- [ ] Housenumbers that look like postcodes (are 5 digits long)

## Regions
-  [ ] Region with a common prefix (ex: New York vs New Zealand)
-  [ ] Region that shares a name with another region of different popularity, no explicit focus
-  [ ] Region that shares a name with another region of different popularity, focus on the smaller region
-  [ ] Region that shares a name with another region of different popularity, focus on the larger region
-  [ ] Region with and without commas in the query ( we should support queries with no commas )
-  [ ] Region query with a zipcode
-  [ ] Region query with a zipcode in place of a larger region in the query
-  [ ] Postal code only query
-  [ ] Query with an abbreviated region that does _not_ start with the abbreviation (ex: New Mexico, Georgia)

## POIs
-  [ ] point of interest name followed by full address
-  [ ] point of interest with partial address
-  [x] [ambiguous POI with relevant focus](https://github.com/pelias/acceptance-tests/blob/f21f6c4b19ef57d19c3f83cee0c6735ff60c98d2/test_cases/autocomplete_poi.json#L49-L71) (pelias/acceptance-tests#182)

## Categories

**Comment by orangejulius** [comment]
Noe Valley will make a great POI test

**Comment by orangejulius** [comment]
There's a small start to these tests in https://github.com/pelias/fuzzy-tests/tree/candidate_acceptance_tests

**Comment by avulfson17** [comment]
What does "Query with an abbreviated region that does not start with the abbreviation" mean? Is it like the Florida, NM example where a place shares a name with a region but is contained within another region (which has an abbreviation)?  What about  "Region query with a zipcode in place of a larger region in the query"?

**Comment by orangejulius** [comment]
It means searching for a place like New York (the state), where the abbreviation (NY), is not the first two letters of the place (but don't use New York because we have a ton of tests for it already). Michigan (MI), and California(CA) are examples of places that _wouldn't_ work.

Region query with a zipcode in place of a larger region means using the zipcode as an admin area, for example "San Diego Convention Center, 92101". (This might not be a good test since the admin area name is also in the venue name, but you get the idea).

**Comment by missinglink** [comment]
sufficient work has been done to close this ticket
