### ISSUE TITLE
ES2 Support?

### ISSUE THREAD

**Issue by hampsterx** [pelias/pelias#198]
Getting this error on upgrading ES from 1.7 to 2.1

Exception in thread "main" java.lang.IllegalStateException: unable to upgrade the mappings for the index [pelias], reason: [Mapper for [name] conflicts with existing mapping in other types[mapper [name.default] has different [analyzer], mapper [name.alt1] has different [analyzer]]]
Likely root cause: java.lang.IllegalArgumentException: Mapper for [name] conflicts with existing mapping in other types[mapper [name.default] has different [analyzer], mapper [name.alt1] has different [analyzer]]

Any ideas/Thoughts?

**Comment by riordan** [comment]
It's been on our list of things to check up on, but we haven't had a chance to check it out yet. 

Hope to have more answers for you in a month or so.

**Comment by orangejulius** [comment]
Hey @hampsterx,
We just merged support for ES2 (we are using 2.3) to our master and staging branches yesterday. We'd love for you to give it a try if and when you have the time. You can track primary progress on the ticket in #325, so I'm going to close this ticket to remove clutter. But if you have any issues at all feel free to reopen or open a new ticket. Cheers!
