### ISSUE TITLE
"Beijing China" should return the city in China and not a restaurant in Arkansas

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#199]
Rachel Binx flagged this to me in an email a few weeks back and I didn't log it at the time.

> FYI new bug report, "Beijing, China" is being sent to the US, while "Beijing" is going correctly to China.

Since that time the behavior has changed (and improved) but still won't find "Beijing China", but will with a comma.
http://pelias.github.io/compare/#/v1/search%3Ftext=Beijing%20China

**Comment by orangejulius** [comment]
This is still an issue :( Anything we do to avoid requiring commas will help

**Comment by trescube** [comment]
It's better now with the libpostal changes, but geonames localities are screwing up the results.

**Comment by trescube** [comment]
Fixed in pelias/api#730
