### ISSUE TITLE
US/CA postal codes

### ISSUE THREAD

**Issue by trescube** [pelias/pelias#201]
Add support for US/CA postal codes, preferably thru WOF

**Comment by riordan** [comment]
Related: #111

**Comment by riordan** [comment]
To go a bit further with this (and building on other previous tickets, principally #111 and pelias/admin-lookup#21):

- We want the data. Preferably as polygons, semi-acceptably as points.
- Polygonal postal codes will be added to the admin-lookup process for standardizing addresses (there will be edge cases here)
- Postal codes are all first-class administrative objects that can be searched for independently (like a country or city). Where polygonal, that polygon should be returned. Where point, we return the point.
- We pretend the whole "Zip Codes are postal routes, not polygons" issue is a non-issue, but we keep it in the back of our minds.

**Comment by dianashk** [comment]
Done! 🎉
