### ISSUE TITLE
Daily Production Import

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#206]
In 2015, there was an incredible amount of work done by @missinglink, @sevko, @hkrishna, @heffergm and @dianashk (and maybe even @randymeech :grin:) to take the time to import the entire planet's worth of Openstreetmap, Openaddresses, Geonames, and Quattroshapes data into Pelias from a month to a day.

Right now, we only import once a week, but as Pelias matures and becomes more stable we'll want to offer even more frequent updates. There have already been a few cases of people asking us when, for example, their OSM change will make it into Mapzen Search. It's nice to be able to tell them "next week" but it will be REALLY great to tell them "tomorrow".

We already have most of the work done to turn this on, and hopefully the extra server costs are minimal (by my estimation, it simply means spinning up one worker 7 days a week instead of 1). In return we will get not only more up to date search results, but quicker iteration on new features, faster catching of bugs and issues, and even more incentive to keep our planet build time low.

**Comment by riordan** [comment]
@stephenkhess sez:
> Can we do this with OpenAddresses given that they do weekly rebuilds? How might they do deltas?

**Comment by orangejulius** [comment]
It turns out with a few improvements we've made to the import architecture over the year, [OSM importer speed improvements](https://github.com/pelias/pbf2json/pull/70), [parallelizing the OpenAddresses importer](https://github.com/pelias/openaddresses/#parallel-importing), [proper Elasticsearch settings](https://github.com/pelias/docker/pull/71), and a single machine with lots of CPUs (36 is a good number) and RAM (40GB or so), it's entirely possible to see full planet build times well below 24 hours.

So its now up to any providers running Pelias to build the infrastructure to run frequent builds, validate the results, and push them live daily!
