### ISSUE TITLE
More non-Mapzen contributors

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#209]
We built Pelias in the open for a lot of reasons, but one of them was so that the geo community could have an open geocoder that it can influence. Technically, that influence is already just a pull-request away. While we do have a few awesome outside contributors, its still really hard to get started with Pelias. Part of this is unavoidable: geocoders are inherently complex and difficult. But we can also do a lot to help.

Some ideas, all of which are optional/open for improvment:
- Continue adding more documentation of the internals of Pelias (being especially careful to update out of date documentation)
- Move more communication/planning out of our private slack channel (maybe Gitter, maybe public slack, maybe IRC? who knows)
- host events/meetups/workshops for digging into pelias internals
- speak at conferences
- Make Pelias even better in general, so that more people are interested
- Publish individual components as stand-alone tools (see #208)
- Write the blogs
- Clean up unreadable code ;)

**Comment by riordan** [comment]
:100:

**Comment by orangejulius** [comment]
We are all non-Mapzen contributors now :upside_down_face:
