### ISSUE TITLE
Autocomplete returns no results when last word is a stopword

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#211]
Hey gang, while looking at how some of our older bug reports were faring with the new Autocomplete release, I noticed a particularly strange new behavior.

For some queries (and I haven't isolated the precise criteria yet), a fully specified query will return zero matches.

Since this was discovered on "Noe Valley" (neighborhood in SF), I've been calling this the "Noe Valley Problem", but it happens for other types of queries as well, most notably addresses.

![noe valley](https://cloud.githubusercontent.com/assets/227472/12126483/75070768-b3bf-11e5-9a56-f94b54ce1a4c.gif)

Here are a few other examples:
451 Fog Hill Road

![fog hill road](https://cloud.githubusercontent.com/assets/227472/12126577/f8606992-b3bf-11e5-9f96-569eba4157a7.gif)

1030 Flintlock Road
![flintlock](https://cloud.githubusercontent.com/assets/227472/12126600/297f8ddc-b3c0-11e5-8a4e-d9eaf7f5bfcf.gif)

I've created [acceptance tests for these in a separate branch](https://github.com/pelias/acceptance-tests/blob/noe-valley-problem/test_cases/noe_valley_problem.json) for the time being.

Here's the results of the fuzzy autocomplete test:
![1__driordan_powermacg4____code_pelias_acceptance-tests__zsh__and_new_issue_ _pelias_pelias](https://cloud.githubusercontent.com/assets/227472/12126547/d28330c4-b3bf-11e5-8bed-3dc6da37fdf5.png)

Lets talk these through tomorrow.

**Comment by riordan** [comment]
@migurski has identified that `heights` is a trigger-word for this behavior (#212)

> Seeing a strange auto-complete results [on this November blog post](https://mapzen.com/blog/find-your-community). This works:

> <img width="420" alt="singular" src="https://cloud.githubusercontent.com/assets/58730/12129435/7d2bc02a-b3b8-11e5-9dae-cddc9680fafb.png">

> …but this is weird:

> <img width="418" alt="plural" src="https://cloud.githubusercontent.com/assets/58730/12129445/9070cb80-b3b8-11e5-8364-907c03e869a8.png">


![heights](https://cloud.githubusercontent.com/assets/227472/12129936/c6288dbe-b3d4-11e5-90d1-86ed67eed62e.gif)

**Comment by dianashk** [comment]
It seems to be when the last word is a stop word

**Comment by missinglink** [comment]
:+1: for @dianashk comment, it seems to be isolated to when the last incomplete token is a stop word.

**Comment by riordan** [comment]
I ran the post office tests with the autocomplete fuzzy tester to see if there were some more examples we could mine and decided to be a human grep/awk pattern and pull out only the ones that break mid-query. There were some pretty revealing examples.

* [full results](http://www.googledrive.com/host/0B0w4om8KqXUARmlvVjlDTm9EX1E)
* [Only errors that recover](http://www.googledrive.com/host/0B0w4om8KqXUAUkVxWlVuYTlUU2s)

```
1050 North Hills Boulevard, Reno, NV, 89506
FFFFFFFFFFFF60FFFF0000000F00000000000000000
```


```
30777 Rancho California Road, Temecula, CA, 92591
FFFFFFF211F1111111000000000F000000000000000000000
```

Fun fact: you can attach word docs + PDFs to Github, but not HTML pages!

**Comment by jczaplew** [comment]
I have noticed a similar behavior with some parks / natural areas. 'Rocky Mountain', 'Grand Canyon', and 'Red Rock Canyon' return zero results, but 'Rocky Mountain Na', 'Grand Canyon Na', and 'Red Rock Canyon Na' will return the expected results.

**Comment by riordan** [comment]
Good catches! We're on it!

**Comment by jczaplew** [comment]
Another interesting edge case is if you search for 'Green'. Nearly all the the results returned have either a Cyrillic letter or an abbreviation, and don't obviously include the string 'green' in any way.

**Comment by riordan** [comment]
Another characteristic of this bug is that commas affect its output substantially:
![](http://g.recordit.co/V3CDjdmude.gif)

**Comment by missinglink** [comment]
FYI @jczaplew this issue should be resolved in https://github.com/pelias/schema/pull/109, will let you know when it goes to production.

**Comment by dianashk** [comment]
@jczaplew, we're all doing the happy dance 💃 👯  since this is now fixed in production!
