### ISSUE TITLE
What's a good process for handling contributed import plugins?

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#215]
## The Question:
What's a scalable approach to inviting and including contributed import plugins for the Pelias project?

## Background:
We've started to see our first user-contributed import plugins for Pelias, which is a huge milestone for an open project like ours. 

A few weeks ago, @rmaceissoft let us know that they [built a transit stop importer](https://github.com/rmaceissoft/pelias-gtfs) using [GTFS data](https://en.wikipedia.org/wiki/General_Transit_Feed_Specification) from an [Open Trip Planner](http://www.opentripplanner.org/) API.

To facilitate the install, they also submitted a PR (pelias/vagrant#31) to our Vagrant project, enabling others to add it to the install pipeline if they wished to use the new plugin.

Really, really impressive!

Sadly, I'm worried that this approach won't scale. As more folks start writing plugins, we'll be faced with (at least) 2 problems:
1. Providing necessary hooks and code to install these plugins
2. Discovering (and us surfacing) user contributed plugins

Simply adding their specific install instructions into the Vagrant installer doesn't seem like an efficient way to accomplish either.

So how do we showcase user contributed plugins and give folks the right code (in the right places) to use these contributed plugins, without having to amend the build code every time?

**Comment by riordan** [comment]
cc @KathleenLD @rmglennon @migurski

**Comment by riordan** [comment]
__writing this in a separate post from the problem description__

I really like the notion of contributed plugins being generally overseen by outside maintainers, even if the core team's helping out. So having [OTP-GTFS](https://github.com/rmaceissoft/pelias-gtfs) live with @rmaceissoft seems :+1: by my count.

That leaves the Vagrant PR, which we could merge, leave as a separate branch, or find some other process for. Merging it means it's now upon the core team to maintain and ensure it doesn't cause issues over time. Leaving it as a separate branch makes it harder to discover, makes it tough to choose among multiple plugins to work with (especially if the plugin branch doesn't update frequently and the core codebase evolves). So I'm behind finding some other solution.

That said, it's clearly patterned on our existing importers, which don't have the code self-contained within their own repositories to add them to an import process without additions to the build process, as is done in the corresponding Vagrant pull request (pelias/vagrant#31). So perhaps there'd be an easier way to encapsulate those instructions, both as code and as written requirements in the import plugin repository.

If the [changes in the Vagrant PR](https://github.com/pelias/vagrant/pull/31/files) were written as instructions (e.g. _In `cookbooks/pelias/recipes/default.rb` add `gtfs_otp` to a new line right before `).each do |r|`) with corresponding sample files, that aren't actually called by the importer code, but are to be run manually before creating a new system (similar to setting up the Vagrant machine today with different kinds of data feeds to import from), we'd have a process that other could follow to create additional plugins.

Then we prominently collect and display these plugins, with their install instructions, in the [Pelias Wiki](https://github.com/pelias/pelias/wiki), and link to it prominently from the readme, serving as a directory for folks looking to use Pelias with other datasets to see what's available to them and serving as a guide to creating their own, if desired.

Of course, this doesn't consider what happens if a plugin needs to modify [pelias/schema](https://github.com/pelias/schema)....

Thoughts?

**Comment by dianashk** [comment]
The idea of creating a Pelias plugin ecosystem is very appealing, and having it be community maintained is doubly awesome. We need to sure to document this thing up and down and side to side, so it's very clear how to add the plugins to the build, be it Vagrant or otherwise.

We've also had some discussions with @missinglink and @trescube about creating an intermediate Pelias data file format. All data regardless of source would be ported to this standard and the build process would only need to know how to handle one type of input. This will eliminate the need to repeat code in several importers. It will also allow people to write their data porters in any language they'd like without having to interface directly with javascript in any way. It will further allow us to prepare the data files in advance as separate steps and thereby speed up import times. This is still a very raw idea so all feedback is welcome. Maybe it belongs in a separate ticket, but I wanted to raise it up here so it's visible.

**Comment by hannesj** [comment]
If you are collecting a list of community-written import plugins, you could add [HSLdevcom/pelias-nlsfi-places-importer](https://github.com/HSLdevcom/pelias-nlsfi-places-importer), even tough it's very specific to the data source (the place database of the Finnish National Land Survey).

An additional question in addition to the vagrant repo is how the default configs should be handled. Should the individual packages be responsible for that, or should everything be pushed to pelias/config?

**Comment by KathleenLD** [comment]
@riordan and I had a long talk about this yesterday-- not the nitty gritty, but the big picture view.

The primary thing that I came out of the conversation with was that this is a really big deal, and we want to handle it thoughtfully. The idea of pelias as a community larger than Mapzen was one of the first things I heard about the project, and it's incredibly cool to see that developing. 

IMO, and it sounds like there's agreement here, the first priority is to make it easier for potential contributors to plug their work in to ours. I'd say that we need to think about that before we put too many brain cycles into what the eventual plugin ecosytem looks like (even though that's probably more fun). Making it easy and appealing for community members to contribute will encourage others to participate, and then we can worry about the ecosystem itself once we have a few more community plugins.
