### ISSUE TITLE
Labels for US States (regions) should be Region, CountryAlpha3

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#216]
As noted in pelias/pelias#164 (New York, NY is the center of NY State), Regions are getting labels that are confusing our users.

Today: q-> `New York, NY` gives back NY State, but with the label `New York, NY`.

Instead, the state should be `New York, USA`

This is also true for all other states (e.g. `California` -> Label: `California, CA`), but is pronounced in New York because of the prominence of New York City.

**Comment by riordan** [comment]
@trescube: while you're working with the labels on ordering, do you think you could take a stab at this as well?

**Comment by trescube** [comment]
Yep, I'll take care of it

**Comment by riordan** [comment]
Awesome!

**Comment by trescube** [comment]
Until US postal codes are in place, 'USA' should be appended to all labels.
