### ISSUE TITLE
Searching for a label output by Mapzen Search should guarantee finding that same place as top result

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#219]
We flagged yesterday that we'd like to make some improvements to the label generation from Pelias/Mapzen Search. I'd like to propose a standard way to test for that:

For any document in the index, we should be capable of doing a batch search for that place with its label and returning that exact place. It can feed on itself.

__DISCLAIMERS: ok, you've got me, there are certainly some instances where this won't work, principally venues where there are multiple places with the same name in the same vicinity, but for addresses, admin areas, and AOI's, they should generally be uniquely named__

![starbucks across from a starbucks](http://www.ianbe.com/wp-content/themes/photos/manila/manilastarbucks.jpg)

**Comment by riordan** [comment]
This isn't truly "Address Parsing" per se, but it is deeply related to it. Moving it into the milestone for now.

**Comment by trescube** [comment]
Add acceptance tests for "whatever I search for, the label should be parsed correctly and find the same result.

**Comment by missinglink** [comment]
This should be considered a design goal, although confirming it might be difficult.

Add tests where possible to confirm behavior.

- test addresses in different locales (different label formats)
- labels for admin areas such as: locality, region, country

**Comment by trescube** [comment]
See @missinglink comments, team agrees.
