### ISSUE TITLE
Street fallback

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#22]
In cases where no street numbers exist for a certain street, or there are few numbers on that street it would be ideal to simply return the name of the street with a centroid of the polyline.

An example would be if for 'Main Street' we only had numbers 1,2 and 42. A user should still be able to type 'Main Street' and get the central point for that street, while also being able to search for "1 Main Street" etc.

Street segments may need to be re-assembled to accurately compute the centroid, or alternatively we could try to import the roads as a geoJSON polyline type.

reported by: @randymeech

**Comment by sevko** [comment]
Related: pelias/pelias#52

**Comment by hkrishna** [comment]
after the ngram schema change, this issue is resolved (acceptance tests needed)

**Comment by missinglink** [comment]
the ngrams release solved the case of "there are few numbers on that street" but doesn't solve the issue of "no street numbers exist for a certain street" which would require importing the OSM street geometry.

**Comment by dianashk** [comment]
Add acceptance tests where street-fallback is already working. Open separate issue for more complex street fallback, computing centroid of street. That will also involve a schema change.

**Comment by aguiraf** [comment]
:+1:  on this feature!
In Italy we generally have a poor numbers coverage, and it's quite common to rely on street centroid

**Comment by tiagofassoni** [comment]
Seconded. In Brazil, we do not have many street numbers on the OSM map.

So queries like "rua das rosas" (rose street) in São Paulo fail.

**Comment by riordan** [comment]
@aguiraf @tiagofassoni: thank you! We're on it!

I'm trying to think what the best behaviour for something like this would be.

Perhaps some property in the context of the GeoJSON Feature to indicate that its a street centroid rather than the specific destination/search?

Would be good to talk to the @valhalla team about what kind of context they'd expect and use for a routing engine.

**Comment by tiagofassoni** [comment]
I guess to make the API easier for clients, the property saying it is a centroid would be the best way. 

Is the centroid feature in any way easy to implement?

Thanks a lot, love how fast Pelias is and the work you guys are doing!

**Comment by dianashk** [comment]
This has been completed. There is a new property in results, `accuracy`, which can be set to `point` or `centroid` to let users know when it's a computed centroid of a street or admin area.
