### ISSUE TITLE
Ensure de-duplicated records prefers WoF

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#220]
Once we have *Mapzen Canonical Data* coming from Who's on First, we'll want to ensure that when there's a conflict between sources, that Who's on First is the preferred record.

This should build on top of @dianashk's deduper (pelias/api#376)

Connected to pelias/api#650

**Comment by hyperknot** [comment]
Example with bad behaviour (from https://github.com/pelias/pelias/issues/333#issuecomment-216082925):

When searching for `naszály`, by default I get a geonames record. Only if I specify 'sources': 'osm,oa,wof', I get a wof record for the same feature.

https://search.mapzen.com/v1/search?text=nasz%C3%A1ly&api_key=search-uOD59t8&sources=osm%2Coa%2Cwof (whosonfirst:locality:101785801)
vs.
https://search.mapzen.com/v1/search?text=nasz%C3%A1ly&api_key=search-uOD59t8 (geonames:locality:3047443)
