### ISSUE TITLE
Investigate implications of disabling Quattroshapes + Geonames

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#222]
Between WoF + OSM we _should_ have the ability to turn off both of these import sources. Lets make sure we can turn these off before we do.

Linked to ensure parity of 4shapes (pelias/whosonfirst#20)

**Comment by riordan** [comment]
# Data Changes
Addition of Who’s on First to default set of datasets searched
Removal of Quattroshapes from default set of datasets searched
Deprecation of Geonames from default set of datasets searched

Still a large number of users using Geonames, and making up a significant volume of use, particularly for our reverse geocoding users. Anecdotal evidence (from WSJ) of using Geonames when a search gets “crowded out” by OSM or OA data.

And many of our top results get populated by Geonames (see: https://github.com/pelias/acceptance-tests/tree/de-onames). We’re going to need a plan in place for these users.





# Options:
## 1. Fresh Start
* Add WoF
* Remove Quattroshapes
* Remove Geonames


Users using Geonames & Quattroshapes explicitly get forwarded to using WoF (assuming same weights & results). These assumptions may not be completely correct. Option to return an error message, but working systems will keep returning api calls.

## 2. Business as Usual
* Add Wof
* Keep Quattroshapes
* Keep Geonames

What Happens: System?
* Continue to be collisions
* Continue to be strange encoding issues
* De-duplicator set to prefer WoF

What Happens: Users?
* Users of places endpoint continue
* Can’t rely on consistency of update of just WoF, which means in the short-term that we won’t have to bite the bullet and just improve its weighting data / our weighting decisions.


If we decomission Quattroshapes, we can likely forward that to Sources=WoF without impact, but those assumptions simply don’t hold for Geonames and we’ll have to return an error.


## 3. Business Upgraded
* Add WoF
* Keep Quattroshapes, but make its inclusion exclusively opt-in
* Keep GeoNames, but make its inclusion exclusively opt-in

What Happens: Systems
* Need to upgrade importers for Quattroshapes and Geonames
* All default API queries are constructed so they are for `sources=openstreetmap,whosonfirst,openaddresses`
* Introduce new syntax for “Defaults plus a datasource”, e.g. sources=+geonames


## 3.a Business-esque
Same as 3, but without Quattroshapes (since we have 100% duplicate coverage from Who's on First)

Of all the options, I’m most in favor of this one (even if it’s just keeping Geonames intact). This does a few things: It rips off the Geonames band-aid for search results, which have been driving a large proportion of top results for coarse search and autocomplete. It’s going to mean we’ll have exposure to the issues that moving to JUST WoF will have.

But as the past week’s conversations and log analysis has shown, Geonames is a recognized and trusted brand with folks, and frankly for coarse geocoding is pretty well tuned. People have come to rely on it. And they’re relying on us for it.

This also gives us an “escape hatch” if we discover that relying on Who’s on First returns the same results as our blended Quattroshapes + Geonames offers now.




## ALSO:
What happens when the assumptions of users using the Place ID change? e.g. Varun is using the Places endpoint to pull data for Tangram/Erasermap, what if our ID construction rules change?

Our initial assumption was that users would only call Places after retrieving the ID from one of our other APIs. Varun’s proven this isn’t completely the case. Will our ID changes change this assumption for other users as well?

**Comment by riordan** [comment]
If we are to go with 3 or 3a, is there a way we can mitigate the impact of the issue identified in ticket pelias/api#191 (Order of `target_layers` significantly impacts results)?

**Comment by dianashk** [comment]
Awesome analysis. Covers all the bases. I'm leaning towards 3.a as well. It seems to be the best of both worlds, removing old sources from the default experiences, while still allowing for it in the legacy integrations. 

It's hard to tell what impact this will have on that layers ordering ticket, but I'm inclined to believe this will be more of the same. We have yet to dig into it and really understand what's at the core of that problem. 

Let's have the id stability and /place endpoint interface discussion in a separate ticket since it's not really impacting this decision.

**Comment by riordan** [comment]
We've decided that we should keep Geonames in as a core dataset for now. We'll save deprecating Geonames for the future (if ever).
