### ISSUE TITLE
place API should be able to return records obtained via search API

### ISSUE THREAD

**Issue by samuelmanzanera** [pelias/pelias#226]
If you do
https://search.mapzen.com/v1/search?api_key=search-Xjo092k&text=Lille

=> you retrieve multiple gids and among them you have :
- gn:locality:2998324
- gn:neighbourhood:2792361
- gn:neighbourhood:2998323

and when you do 
https://search.mapzen.com/v1/place?api_key=search-Xjo092k&ids={id}

with {id} replaced by one of the three previous ids it gives you

```
{"geocoding":{"version":"0.1","attribution":"https://search.mapzen.com/v1/attribution","query":{"ids":[{"id":"2998323","types":[]}],"private":false},"errors":[{"message":"ActionRequestValidationException[Validation Failed: 1: no documents to get;]"}],"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1452870069761},"type":"FeatureCollection","features":[]}
```

To us, it seems that there is currently a problem with gn source but maybe this is more tricky :)

Current workaround for us : remove records coming from gn :(

**Comment by orangejulius** [comment]
Hey @samuelmanzanera,
This is a known bug. At the moment there's a rather awkward fix: you can ignore the layer field of the gid (the one in the middle) for Geonames records, and replace it with venue. For example: https://search.mapzen.com/v1/place?api_key=search-Xjo092k&ids=gn:venue:2998324 will work just fine.

We've had to make some schema changes to fix this rather embarrassing issue, but fortunately we are [almost there](https://github.com/pelias/model/pull/21).
