### ISSUE TITLE
Missing locality for address features

### ISSUE THREAD

**Issue by geocodingtakeaway** [pelias/pelias#231]
When I search for a street in Hindeloopen, The Netherlands (text=hanzestraat, hindeloopen&boundary.country=nl&size=40) the properties of results that are actually in Hindeloopen do not have a locality key. This happens for both the osm and the oa results. I have tried several streets in the city.

When I look up the osm node for an address, the addr:city tag is present. For example, for Hanzestraat 4, the result has gid osm:address:address-osmnode-2966710620. https://www.openstreetmap.org/node/2966710620 shows that the node has a city tag.

**Comment by riordan** [comment]
We think this is going to be resolved by our addition of Who's on First as a data source superceding Quattroshapes.

We'll have to check to be certain.

**Comment by orangejulius** [comment]
This does appear to have been by our Who's on First release!
