### ISSUE TITLE
OpenAddresses data source performs incorrect address expansions for non US/ENG addresses

### ISSUE THREAD

**Issue by geocodingtakeaway** [pelias/pelias#232]
*EDITED*
From a ticket initially filed by @geocodingtakeaway 

An address coming from OpenAddresses will expand an entry from its `street`field using rules primarily for US/English addresses. This is most pronounced with Spanish, French (and other romance languages) that use `la` as definite article. So `Rue de la Prairie` becomes `Rue de Lane Prairie`.

In the US, this is a particular issue in the American Southwest (think New Mexico). But also there's literally all of Latin America, Spain, France, Belgium.

Core issue is being tracked at openaddresses/machine#32 with an ancillary issue being tracked at openaddresses/openaddresses#1465

*Original Title*: Addresses in streets titled `Rue de la ***` show up as `Rue De Lane ***`

ORIGINAL POST:
> For example: text=rue de la justice, paris&size=40&boundary.country=fr

> yields all kinds of results from the non-existing street 'Rue De Lane Justice'. Note also the odd capitalization.

> This issue seems limited to results with oa as source. However, the name seems to be correctly stored in the oa database.

> For exampe: '1 Rue de la Prairie, Lieusaint, France' shows up as '1 Rue De Lane Prairie, LIEUSAINT, France' (gid=oa:address:07baa2bc1e6d40789f0760e9b40800b6). Looking at the sample data for fr/seien_et_marne at http://results.openaddresses.io/, number 1 of that street is stored correctly in the oa database as 'rue de la prairie'.

> I took French streets as an example, but it also happens in Belgium.

**Comment by riordan** [comment]
Thanks for flagging; we're on it! This is a known issue with OpenAddresses, where their system is automatically expanding terms [openaddresses/machine#32].

We're hoping to revive their project's interest in this issue.

**Comment by riordan** [comment]
I'm going to make a few edits to your original issue so we can track the broader issue at hand.

**Comment by riordan** [comment]
Looks like they're now going to make those corrections inside OpenAddresses. Should be a pretty quick turnaround.

**Comment by orangejulius** [comment]
And it looks like these corrections have made it into Pelias: http://pelias.github.io/compare/#/v1/search%3Ftext=1%20Rue%20de%20la%20Prairie,%20Lieusaint,%20France

There is still this case though: http://pelias.github.io/compare/#/v1/search%3Fsize=2&sources=oa&text=1065%20La%20Avenida,%20Mountain%20View,%20Santa%20Clara%20County,%20California,%2094043

**Comment by orangejulius** [comment]
Lane Avenida is still a problem in the global OA download, I've bumped the linked issue in OA and hopefully this will be totally fixed soon.

**Comment by orangejulius** [comment]
So the issue brought up in this ticket is fixed, and as it turns out the expansions done for the global file is going to stay. So this ticket is all done, and we will fix "Lane Avenida" with #247
