### ISSUE TITLE
Documentation updates for Who's on First

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#233]
- [x] Updates to Sources & Layers for `search` and `reverse` endpoints
- [x] Updates to Sources page
- [x] Deprecation of 4Shapes; steps for users already using it
- [x] Updates to all responses w/ WoF bboxes for each result
- [x] Updates to ID Schema
- [x] Blog Post announcing it

**Comment by orangejulius** [comment]
I think we've covered all of this once we merge https://github.com/pelias/pelias-doc/pull/119
