### ISSUE TITLE
Special characters are not encoded correctly in API responses

### ISSUE THREAD

**Issue by martinburch** [pelias/pelias#235]
Pelias/Mapzen Search returns JSON, which is expected to be UTF-8, but there are some mangled characters in strings.

OpenStreetMap
https://search.mapzen.com/v1/reverse?api_key=search-DU9odMU&point.lat=38.46&point.lon=-105.22556&sources=osm
`"locality": "CaÃ±on City"`

Quattroshapes
https://search.mapzen.com/v1/reverse?api_key=search-DU9odMU&point.lat=38.46&point.lon=-105.22556&sources=qs.
`"name": "Caã±on City",`

The correct string is `Cañon City`

We're really excited about using this geocoder at The Wall Street Journal. Thanks for your open-source work!

**Comment by dianashk** [comment]
Hey @martinburch, thanks for filing this and sorry for the delayed response. We're actively working on an integration with the [Who's On First](whosonfirst.mapzen.com) dataset, as a replacement for QuattroShapes. This integration will resolve a lot of the encoding issues users are experiences. We'll close this issue once the fix has been promoted to production.

Cheers. :wave:

**Comment by orangejulius** [comment]
We've now released an integration with Who's on First and this is now [fixed](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=38.46&point.lon=-105.22556&sources=osm)!

**Comment by martinburch** [comment]
Thanks, folks!
