### ISSUE TITLE
Some localities have overly verbose names

### ISSUE THREAD

**Issue by martinburch** [pelias/pelias#237]
In both OSM and Quattroshapes, some localities end in "balance" as in
`Athens-Clarke County Unified Government (balance)`
https://search.mapzen.com/v1/reverse?api_key=search-DU9odMU&point.lat=33.94806&point.lon=-83.3275&sources=osm

This looks like an artifact of Census-derived data. There are only a handful of these in the U.S. Can this be cleaned up somehow?

**Comment by riordan** [comment]
:shakes_fist_at_census_bureau:

I came across this (very perplexing) artifact a few months ago as well.

We're a week or two away from transitioning to a new backing gazetteer, [Who's on First](https://whosonfirst.mapzen.com), that supplants Quattroshapes. But it, too, [still has these artifacts](https://whosonfirst.mapzen.com/spelunker/search/?q=balance&placetype=locality).

I'll flag these to our data team so we can clean it up over there.

cc: @thisisaaronland @dphiffer

**Comment by riordan** [comment]
Also way to track it down to the Census Bureau!

**Comment by orangejulius** [comment]
It looks like this has been fixed in whosonfirst! :tada: :trumpet: 

http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=33.94806&point.lon=-83.3275&sources=osm
