### ISSUE TITLE
Some Kansas locations suggest numbers as feature name labels

### ISSUE THREAD

**Issue by martinburch** [pelias/pelias#238]
http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=39.40306&point.lon=-99.41917&sources=wof

```
{
      "type": "Feature",
      "properties": {
        "id": "100160:localadmin:us:usa:6",
        "gid": "qs:localadmin:100160:localadmin:us:usa:6",
        "layer": "localadmin",
        "source": "qs",
        "name": "6",
        "country_a": "USA",
        "country": "United States",
        "region": "Kansas",
        "region_a": "KS",
        "county": "Rooks County",
        "confidence": 0.5,
        "distance": 1.767,
        "label": "6, Rooks County, KS"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -99.4361316543031,
          39.3941087037824
        ]
      }
    }
```

Google is also affected by this. Try clicking on the map near this point:
https://www.google.com/maps/place/39%C2%B023'48.3%22N+99%C2%B024'22.6%22W/@39.3950933,-99.4051283,15.18z/data=!4m2!3m1!1s0x0:0x0
39.396748, -99.406291
![image](https://cloud.githubusercontent.com/assets/2335284/12523695/735b911c-c126-11e5-9306-117071869c41.png)

**Comment by martinburch** [comment]
Ok, I think I've figured this out. It's a township. (Or maybe a district.) It's what happens to parts of Kansas counties that don't contain many features -- or people. I think the `name` or `label` property should suggest "Township 6"
http://statisticalatlas.com/county-subdivision/Kansas/Rooks-County/Rooks-Township-6/Overview

**Comment by riordan** [comment]
@martinburch + I have been doing some sleuthing via Twitter and came to the conclusion they're localadmins.

See [5](https://whosonfirst.mapzen.com/spelunker/search/?q=5&iso=us&placetype=localadmin), [6](https://whosonfirst.mapzen.com/spelunker/search/?q=6&iso=us&placetype=localadmin) (last results).

Mapzenners: any thoughts on how best to handle this particular class of localadmins?

**Comment by IndyHurt** [comment]
@martinburch is correct.  These townships should include "Township" in the name.   Rooks County has 12 of them.  
Here are some GNIS links for 9 more in Morris County, Kansas:
[Township 1](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:477025)
[Township 2](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:476902)
[Township 3](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:485451)
[Township 4](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:476891)
[Township 5](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:476876)
[Township 6](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:476877)
[Township 7](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:477002)
[Township 8](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:477153)
[Township 9](http://geonames.usgs.gov/apex/f?p=gnispq:3:::NO::P3_FID:477007)

Kansas has both civil and survey townships.  They might not be expected for reverse geocoding.

**Comment by orangejulius** [comment]
Somehow we missed reporting this to the whosonfirst team. I put an issue in: https://github.com/whosonfirst/whosonfirst-data/issues/313

**Comment by orangejulius** [comment]
Hey @martinburch,
Just a quick update here. The underlying data issue has been fixed and queries on our [development servers](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=39.40306&point.lon=-99.41917&sources=wof) are now showing the right results. We are in the midst of a big upgrade to Elasticsearch 2 but our next release should fix this! We'll update here when it does.
![screenshot_2016-07-01_18-11-35](https://cloud.githubusercontent.com/assets/111716/16535682/59a501c6-3fb7-11e6-9a10-0a2dadb36df6.png)

**Comment by orangejulius** [comment]
Okay and now it looks like we've fixed these names on production. Note that we made some changes to the search radius for reverse, it defaults to 1km now, but with this query you can see we've updated all the names.
http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lat=39.40306&point.lon=-99.41917&sources=wof&boundary.circle.radius=500
![screenshot from 2016-07-06 12-23-07](https://cloud.githubusercontent.com/assets/111716/16625842/69e8f720-4374-11e6-857c-f73129ba2902.png)

I'm going to close this issue since I think we've taken care of anything, but if we haven't feel free to reopen, and of course feel free to open a new issue for anything else. Cheers! :tada:
