### ISSUE TITLE
Install without Vagrant

### ISSUE THREAD

**Issue by lance0821** [pelias/pelias#239]
I'm trying to install Mapzen and Pelias more permanently but allowing easy development. Is there a install guide, or resources I can look to configure these projects in AWS Opworks or Chef Server?

**Comment by orangejulius** [comment]
hey @lance0821, at the moment we don't have a single piece of documentation for this, although it's a task I plan to work on [in the near future](https://github.com/pelias/pelias-doc/issues/88). In the meantime you can look at an old [blog post](https://mapzen.com/blog/pelias-setup-tutorial), and the READMEs for [pelias-schema](https://github.com/pelias/schema/), and our importers for [openstreetmap](https://github.com/pelias/openstreetmap), [openaddresses](https://github.com/openaddresses/openaddresses), [geonames](https://github.com/pelias/geonames/), and [quattroshapes](https://github.com/pelias/quattroshapes)

**Comment by lance0821** [comment]
I started messing around with the Opzworks offering hosted over in the Mapzen repo, not being very familiar with AWS OPSWorks, Or Chef I was able to shoot the tgz archive with the Pelias cookbook to my instance, it fails though complaining about the npm version. I'll read around and try to figure out what's goin on, but other than that it seems like a smooth way to deploy
