### ISSUE TITLE
investigate postal_code polygons

### ISSUE THREAD

**Issue by sevko** [pelias/pelias#24]
We should explore whether zip codes are valuable to index. They currently aren't accounted for in our Elasticsearch pipeline, and are mostly discarded by import scripts.

**Comment by sevko** [comment]
+1 from the routing team.

**Comment by quiqua** [comment]
Hey there!
Just an idea: Preprocess osm data and filter nodes/ways which contain the key-value-pairs `boundary=postal_code`, `postal_code=<text>` and `addr:postal_code=<text>`, merge all data with the same postal code to one polygon and populate the data pelias?

**Comment by dianashk** [comment]
@quiqua great suggestion. Just checked out the values in taginfo and it looks like there is a good amount of data there. I'll play around with extracting it with pelias/fences-builder.

**Comment by dianashk** [comment]
WOF might make this data available to us in the foreseeable future.
