### ISSUE TITLE
Local autocomplete address search fails to find nearby address

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#240]
@randymeech was demoing Erasermap earlier today when this happened:

> [1 madison ave]
![2016-01-25 21 26 08](https://cloud.githubusercontent.com/assets/227472/12565620/47ea680a-c383-11e5-9ca5-e6f2d009d891.png)

> But [madison ave] shows 1 Madison Avenue, also in autocomplete:
![2016-01-25 21 26 19](https://cloud.githubusercontent.com/assets/227472/12565633/55b50396-c383-11e5-9090-bc475a402886.png)

> And fulltext search works as expected:
![2016-01-25 21 27 12](https://cloud.githubusercontent.com/assets/227472/12565648/67b4ffec-c383-11e5-912b-3a670f150682.png)

## Next Steps
- [ ] Test [pelias/acceptance-tests#188]
- [ ] Diagnose
- [ ] Fix

**Comment by missinglink** [comment]
This issue is due to the 2gram filter, it will likely effect *all* single-digit house numbers; if you search for number 11 it should return the correct result.

One solution would be https://github.com/pelias/api/pull/300, let's discuss this.

**Comment by orangejulius** [comment]
I am pleased to announce that this issue looks to have been resolved! Both [autocomplete](http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=40.744131&focus.point.lon=-73.990424&text=1%20madison%20ave) and [search](http://pelias.github.io/compare/#/v1/search%3Ffocus.point.lat=40.744131&focus.point.lon=-73.990424&text=1%20madison%20ave) return excellent results!

**Comment by dianashk** [comment]
Hooray! 🎉 
@orangejulius, let's add an acceptance test for resolved issues before closing them. This way we never break it again in the future.

**Comment by orangejulius** [comment]
Yup, there's already one for this in fact! It was failing only because it hadn't been updated to use `borough` instead of `locality`

**Comment by dianashk** [comment]
Awesome! Just saw that as I went to add it.
Winning!!! 🏆
