### ISSUE TITLE
Discuss possible type of documentation

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#241]
I came across this tutorial in a `zine` format, which I've not seen before. I think it's pretty amazing. It's fun, approachable, educational, and lots of other things I'm digging. Maybe we can make something similar for our hands-on tutorials? I'm particularly liking this format for attracting newbies.

http://jvns.ca/strace-zine-unfolded.pdf

**Comment by riordan** [comment]
I'm crazy head over heels for this (also Julia's an amazing human). 

Let's nail the traditional instructions first, test it with folks to make sure it's got all the steps, then ink our own. 

I wouldn't want to see us dump a ton into a zine that we'd have to rewrite large chunks of if we're missing something or it's unclear.

**Comment by orangejulius** [comment]
+1 to:
* we should make zines
* Julia is awesome
* we should make another pass over the docs first since paper is rather hard to patch

**Comment by dianashk** [comment]
Agreed that it's not at all a high priority and we have a long way to go with our current docs before something like this becomes a reality. But I wanted to leave future us a note and a link to this awesome genre of documentation. 

Hey _Future-Pelias-Team_, you guys are so awesome!

**Comment by kkowalsky** [comment]
looking through documentation tags and wow this is awesome. I'm a huge zine fan, especially [bubblesort zines](http://bubblesort-zines.myshopify.com/). @dianashk what about a mini-zine for SOTMUS?

**Comment by dianashk** [comment]
@kkowalsky, if we have the bandwidth to make something fun and educational happen in a zine format for SOTMUS I'm 1000% into it!  `💯x🔟` 🎆

**Comment by kkowalsky** [comment]
We have a zine!

**Comment by riordan** [comment]
!!!!!
