### ISSUE TITLE
Update ids for wof and oa importers

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#244]
Prefix data source, or path, to the id so we don't have conflicts.

- [x] openaddresses (pelias/openaddresses#38)
- [x] wof (they stay as pure, artisinal integers)

**Comment by orangejulius** [comment]
What format do we think would be good for WOF ids?

**Comment by orangejulius** [comment]
Unless anyone has any amazing ideas for what we could put in WOF ids, I propose that we designate WOF the only importer that can have integer only ids (they are artisinal, after all), and close this ticket as done. :)

**Comment by trescube** [comment]
:+1:
