### ISSUE TITLE
Feature Request: Have autocomplete allow for different sizes of returned result sets

### ISSUE THREAD

**Issue by msmollin** [pelias/pelias#249]
On mobile devices it would be nice to be able to limit the amount of results returned to increase speed of results back to the user, especially when cell service is poor.

**Comment by riordan** [comment]
We keep the number of results deliberately fixed to improve the odds of a query being cached.

That said, _mayyyybe_ it's possible to implement this at the cache layer itself, where we have a maximum autocomplete document and it trims results there.

**Comment by orangejulius** [comment]
We finally decided to add the `size` param back to autocomplete! So this is done now. 🎉
