### ISSUE TITLE
Guidelines for contributing

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#25]
Add guidelines for contributing to the Pelias repositories: CONTRIBUTING.md?

@kathleenld

**Comment by sevko** [comment]
Talked with @KathleenLD about this, and the first step is probably to set up a Pelias project template so that contributors can spawn new packages and have things Just Work, without having to instantiate all the boilerplate (`package.json`, `.travis.yml`, etc.).

**Comment by KathleenLD** [comment]
Closing this out-- CONTRIBUTING.md is live.
