### ISSUE TITLE
Add wof:dependency to Point in polygon

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#251]

**Comment by riordan** [comment]
cc @heffergm

**Comment by dianashk** [comment]
@riordan what's this one all about?

**Comment by trescube** [comment]
We'll need dependencies for addresses in, say, Puerto Rico.  Otherwise an address in San Juan, Puerto Rico will just look like city=San Juan and country=United States with no region set.  Dependencies should be treated like states/regions for the time.

**Comment by trescube** [comment]
pelias/wof-admin-lookup#13
