### ISSUE TITLE
Use WoF as core schema

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#252]
Currently using old 4shapes-inspired schema. But it means we miss things like "Macroregions" and "Macrocounties", which are necessary administrative regions in several countries.

Currently disabled:
- Empires
- Macrocounties
- Macroregions
- Macrohood
- Microhood
- Metro Area (currently none)

Of particular concern here is the lack of `macrocounties` and `macroregions`, which govern key parts of administrative hierarchy in the UK (e.g. Country:UK>Macroregion:England>locality:Sheffeld)

**Comment by dianashk** [comment]
All done here too! :boom:
