### ISSUE TITLE
Using layers=venue filter yields results from other layers

### ISSUE THREAD

**Issue by geocodingtakeaway** [pelias/pelias#253]
For example, in the search results of the query with the parameters `text=london&boundary.country=gb&layers=venue`, the first three results are from the layers county and locality.

The results from other layers seem to always have geonames as its source. Is this related to Who's On First?

**Comment by riordan** [comment]
Yeah; this is a known problem (hard to call out but it's in the documentation). Thank you for flagging it. 

You're absolutely correct that the only places this applies to are from Geonames. Our importer was preventing us from adequately targeting the right layer of things from Geonames, so results would frequently get mixed (@orangejulius has been trying to get this on our radar for some time now). 

We've recently refactored that importer code and should be pushing it live in the next few days to coincide with using who's on first as our core gazetteer.

**Comment by dianashk** [comment]
This has been fixed. We'll add an acceptance tests to verify and close this issue soon.
Thanks again for reporting it.
