### ISSUE TITLE
Update developer documentation for new admin lookup settings

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#257]
A lot has changed in the way we do admin lookup in our importers (a lot is still changing, so we can't really even do this at the time this ticket was written). To make sure everyone developing with Pelias knows what to expect, and to avoid situations like pelias/openstreetmap#93, we should do a careful pass through our developer documentation, especially repository READMEs, and make sure everything is clear and up to date.

**Comment by riordan** [comment]
:+1: 

This as the basis for a "writing your own importer" guide would be incredibly useful to future us (and the public).

**Comment by dianashk** [comment]
@orangejulius says it's done and will confirm and close when appropriate.

**Comment by orangejulius** [comment]
Places I've checked for out of date information:
- [x] https://github.com/pelias/admin-lookup README (updated with deprecation notice)
- [x] https://github.com/pelias/wof-admin-lookup
- [x] https://github.com/pelias/wof-pip-service
- [x] https://github.com/pelias/vagrant
- [x] https://github.com/pelias/openaddresses README
- [x] https://github.com/pelias/openstreetmap README
- [x] https://github.com/pelias/geonames README (updated from Quattroshapes -> WOF)
- [x] https://github.com/pelias/whosonfirst README (looks good)
- [x] https://github.com/pelias/pelias-doc/blob/master/installing.md
