### ISSUE TITLE
Make TravisCI configs better and more consistent across repos

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#258]
Most of our code repos are set up to use TravisCI to automatically run tests, but we have let things get a little out of date and some cleanup would be helpful. Here's some things we can do:

- [x] set `sudo: false` to use [container based environments](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments) which start up much faster
- [x] run unit tests and functional tests as [separate builds](https://docs.travis-ci.com/user/speeding-up-the-build/)
- [x] Make sure Node versions 0.10 and 0.12 are set to be tested
- [x] Remove any lingering flowdoc integration
- [x] Add Node versions 4.0, 4.1,4.3 and 5.6 to be tested, but with failures allowed for now

**Comment by dianashk** [comment]
WOW! Look at all those connected repos!

**Comment by dianashk** [comment]
I think this has been done everywhere. Safe to close this ticket?

**Comment by orangejulius** [comment]
Getting close. I just went through every repo and I think the following could all use a touch up:

- [ ] [pelias/schema](https://github.com/pelias/schema/blob/master/.travis.yml)
- [ ] [pelias/model](https://github.com/pelias/model/blob/master/.travis.yml)
- [ ] [pelias/query](https://github.com/pelias/query/blob/master/.travis.yml)
- [ ] [pelias/pbf2json](https://github.com/pelias/pbf2json/blob/master/.travis.yml)
- [ ] [pelias/line-interpolate-points](https://github.com/pelias/line-interpolate-points/blob/master/.travis.yml) Do we still use this?
- [ ] [pelias/config](https://github.com/pelias/config/blob/master/.travis.yml)

These repos don't have tests but probably should, so with a bit more work we could set something up

- [ ] pelias/address-deduplicator
- [ ] [pelias/logger](https://github.com/pelias/logger/blob/master/.travis.yml) (has a travis file but no tests. We should probably do some updating here at some point)

**Comment by orangejulius** [comment]
Okay, I've added connected PRs for every repo in pelias that I'm aware of us using. Let there be tests!
