### ISSUE TITLE
Strange spelling mistake or a language I don't know

### ISSUE THREAD

**Issue by sanderd17** [pelias/pelias#26]
When I click somewhere in West Flanders (or West-Vlaanderen in Dutch), see https://mapzen.com/pelias#loc=14,50.9382,3.0918

The typical address that appears is "xx street, town, West-vlanderen". That's wrongly capitalised, and misses an "a" to be correct Dutch. I'm not sure where the problem comes from, as the data is correct in OSM: http://www.osm.org/relation/416271

**Comment by mtmail** [comment]
The openstreetmap website times out looking at history but I double-checked with JOSM: the relation name "West-Vlaanderen" didn't change in the last years so we can rule out outdated OSM data or recent change.

**Comment by hkrishna** [comment]
Thank you @sanderd17 for bringing this to our attention. It is definitely strange how it misses an "a". I will have to get back to you shortly once I figure it out for myself. As far as capitalization is concerned, I think I know the culprit and I'll work on a fix soon. will keep you guys posted

**Comment by sevko** [comment]
"West-vlanderen" is missing an "a" because most of these addresses don't appear to have tag values indicating their administrative region (like `addr:province = West-Vlaanderen`), in which case we identify them by performing a lookup against the [Quattroshapes](http://quattroshapes.com/) polygon gazetteer. After checking the data, it seems like Quattro contains a polygon named "West-Vlanderen" instead of "West-Vlaanderen". We're hoping to migrate to a better polygon dataset at some point in the future since Quattro has lots of other data problems, and might even be able to use OSM relations in some cases.

**Comment by sanderd17** [comment]
Hmmm, well, the province isn't part of the address anyway. In case you're interested, usual addresses are 

  STREET NR
  PCODE LEVEL-8-BOUNDARY

like

  Westlaan 84
  8800 Roeselare

Though level-9 boundaries are also sometimes used, however, level-9 names can be ambiguous (the same name appearing multiple times through the country). And because There are too many municipalities, the province (level-6) can be added to place descriptions in order to clarify the region. Provinces, and their approx boundaries, are well-known by the public, but not part of an address.

So at most, we could add addr:city (though there's a debate whether that should be the level-8 or level-9 name) and addr:postcode. But not tagging those also avoids redundancy, since our boundaries (including postcode boundaries) are mapped pretty good.

But anyway, thanks for investigating it. I really look forward to new experiments with geocoders, as Nominatim has become a beast, and still doesn't give very good results in border-cases.

**Comment by hkrishna** [comment]
@sanderd17 there is a way to define how usual addresses are written in a particular country and this dictates the output format of the address when you are using the geocoder. 

https://github.com/pelias/api/blob/master/helper/outputSchema.json

Just make a pull request with the alpha3 (https://github.com/pelias/api/blob/master/test/unit/mock/alpha3.json) and the address schema. Please let me know if you have questions

**Comment by sevko** [comment]
We've also identified the cause of the lower-cased "v", and opened a separate issue for it (see above).

**Comment by hkrishna** [comment]
thanks @sevko!
