### ISSUE TITLE
/place API Geonames short name data source called something different from /search endpoint

### ISSUE THREAD

**Issue by msmollin** [pelias/pelias#261]
When looking at the documentation for /place - https://mapzen.com/documentation/search/place/ the docs uses a different short name from /search for Geonames ("gn" vs "ga") 

Is this a documentation error? Or are they actually different names?

If they are different names, why?

**Comment by riordan** [comment]
Great catch by @msmollin.

The abbreviation in our [`/search`](https://mapzen.com/documentation/search/search/#filter-your-search) documentation page has Geonames abbreviated (improperly) as `ga` rather than `gn`. Fix is on the way.
