### ISSUE TITLE
Bounding box in search results

### ISSUE THREAD

**Issue by millenbop** [pelias/pelias#264]
It's hard to guess a good zoom level for different results. It is possible to use the `layer` as a hint, but zoom levels would be very different if you search for countries like Australia or Luxembourg.

I therefore propose to include a bounding box in search results so maps easily can zoom to the correct level, perhaps in the `geometry` dictionary.

Right now search results can look like this `v1/autocomplete`:

```
{
	geometry = {
		coordinates = (
			"-112.03105",
			"41.13633"
		);
		type = Point;
	};
	properties = {
		confidence = "0.887";
		country = "United States";
		"country_a" = USA;
		county = "Davis County";
		gid = "gn:locality:5782320";
		id = 5782320;
		label = "Sunset, Davis County, UT";
		layer = locality;
		locality = Sunset;
		name = Sunset;
		region = Utah;
		"region_a" = UT;
		source = gn;
	};
	type = Feature;
}
```

**Comment by riordan** [comment]
Hi @millenbop; this is something we're looking to enable pretty soon as a part of our major Who's on First update. Hopefully should land in the next few weeks.

We're tracking the primary issue in pelias/api#398

**Comment by millenbop** [comment]
Awesome! Should I create issues on /api in the future?

**Comment by dianashk** [comment]
@millenbop, no you did the right thing. It was just a coincidence that we already had that issue in API. Usually issues touch several repos, so it's best to create them in the central pelias/pelias one as you have done.
