### ISSUE TITLE
Resolve 220k "neighborhoods" -> "neighbourhood"

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#289]
<img width="112" alt="google_hangouts" src="https://cloud.githubusercontent.com/assets/227472/13990199/d0abad1e-f0e9-11e5-8857-8fa54e175961.png">

In our new Who's on First schema, we have renamed the schema element `neighborhood` to `neighbourhood` (as it's always been named in the API).

That said, there are a few hangers-on somewhere.

**Comment by orangejulius** [comment]
It's from geonames, PR incoming:

```
{
   "took": 1398,
   "timed_out": false,
   "_shards": {
      "total": 16,
      "successful": 16,
      "failed": 0
   },
   "hits": {
    ...
   },
   "aggregations": {
      "lay": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "geonames",
               "doc_count": 220005
            }
         ]
      }
   }
}
