### ISSUE TITLE
New York City still parented by Brooklyn

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#295]
This is a data issue. Should be resolved at the source.

https://whosonfirst.mapzen.com/spelunker/id/85977539/

**Comment by trescube** [comment]
Discussed with Aaron, he created an issue with the start of a plan:

https://github.com/whosonfirst/whosonfirst-data/issues/238

**Comment by trescube** [comment]
The data team is currently working this out.

**Comment by dianashk** [comment]
This has been fixed with the addition of boroughs.
