### ISSUE TITLE
49 Kay Street

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#296]
Is it more important for the house number to match in the result or the street name?
We're seeing `49 De Kay Street` show up higher than `3`,`4`, and `5 KAY STREET`.

Separate issue here is that there are OA records with all caps coming through now, due to the fact that OA stopped normalizing their data for capitalization.

**Comment by orangejulius** [comment]
So this [query from the acceptance tests](http://pelias.github.io/compare/#/v1/search%3Ftext=49%20Kay%20Street) currently results that look right, as well as some that clearly aren't.

It feels like the address parsing improvements coming along with libpostal will help us return only fully correct results.
![screenshot_2016-07-01_18-15-55](https://cloud.githubusercontent.com/assets/111716/16535752/f4a5d2ae-3fb7-11e6-93b2-7b127db50f87.png)

**Comment by orangejulius** [comment]
This has been fixed nicely, probably by libpostal!
![screenshot_2016-10-12_11-24-08](https://cloud.githubusercontent.com/assets/111716/19316195/7e1f5d00-906e-11e6-8a03-9b737f9c72df.png)
