### ISSUE TITLE
Who's on First rollout

### ISSUE THREAD

**Issue by riordan** [pelias/pelias#301]
Launch steps for rollout of Who's on First

- [x] Fix all [test regressions](https://waffle.io/pelias/pelias?label=regression&milestone=Who%27s%20on%20First)
- [x] API warning for users of quattroshapes
- [x] Up to date documentation ([PR](https://github.com/pelias/pelias-doc/pull/96))
- [x] Pre-announce blog post
- [x] Email to all active users of Quattroshapes
- [x] Email to all active `/place` users
- [x] Pull the trigger!

**Comment by dianashk** [comment]
Things that need decisions:

- [ ] WOF id property names in result hierarchies: we need to somehow indicate that they are WOF ids
- [ ] bbox format
