### ISSUE TITLE
307 Green Street, Green Cove Springs, Fl  Search

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#304]
307 Green Street, Green Cove Springs, Fl

Produces some results way out there when checking 

[http://pelias.github.io/compare/#/v1/search?text=307 Green Street, Green Cove Springs, Fl](http://pelias.github.io/compare/#/v1/search%3Ftext=307%20Green%20Street,%20Green%20Cove%20Springs,%20Fl)

Also 302 Ruby Ave, Green Cove Springs, Fl is way off

302 Ruby Ave, Green Cove Springs, Fl  32043 is closer, but still not right except using `http:pelias.dev.mapzen.com` which first result is exactly right.

**Comment by orangejulius** [comment]
Hey @b-may,
It's been a while since you reported this (sorry about that). I'm showing the first result in Auburndale across the board now. Is that the right city or are all our environments wrong now?

**Comment by b-may** [comment]
Hi @orangejulius,

No problem. Auburndale is the wrong city. Green Cove Springs is in Clay County, FL and Auburndale is in Polk County, FL. 

Adding the zip code, e.g. `307 Green Street, Green Cove Springs, Fl 32043` produces the correct location in all three compare versions, but no zip code is still way off.

----

`302 Ruby Ave, Green Cove Springs, Fl` is still way off in Deland, FL (Volusia County) for all three compare versions.

`302 Ruby Ave, Green Cove Springs, Fl 32043` now returns the correct location in all three compare versions. 

FYI: Clay County has an address points layer and it shows the street name as Ruby Avenue. Parcel data shows the name as Ruby Street. 

Further testing:

`302 Ruby St, Green Cove Springs, Fl` is correct.
`302 Ruby St, Green Cove Springs, Fl 32043` is correct.

**Comment by orangejulius** [comment]
Hi from almost 4 years later!

Looks like this is yet another address that works fine now with our work to handle [Postal Cities](https://github.com/pelias/pelias/issues/396)
![Screenshot_2020-03-20_08-40-46](https://user-images.githubusercontent.com/111716/77179976-83588580-6a86-11ea-9638-352f6f6c045a.png)
