### ISSUE TITLE
Place lookup not found

### ISSUE THREAD

**Issue by ecgreb** [pelias/pelias#305]
The following feature exists in OSM data however /place lookup returns no results.

http://www.openstreetmap.org/way/392154008

https://pelias.mapzen.com/v1/place?ids=osm%3Avenue%3A392154008&api_key=search-BcgTWes

```
{
geocoding: {
version: "0.1",
attribution: "https://search.mapzen.com/v1/attribution",
query: {
ids: [
{
id: "392154008",
types: [
"osmnode",
"osmway"
]
}
],
private: false
},
engine: {
name: "Pelias",
author: "Mapzen",
version: "1.0"
},
timestamp: 1459963144500
},
type: "FeatureCollection",
features: [ ]
}
```

**Comment by orangejulius** [comment]
With our new WOF build it looks like this is now in there! Note that our ID format has changed, but any documents returned by `/v1/search` or `/v1/autocomplete` will return the correct ID.

http://pelias.github.io/compare/#/v1/place%3Fids=openstreetmap:venue:way:392154008

http://pelias.github.io/compare/#/v1/search%3Ftext=superior%20woodcraft,%20doylestown

**Comment by ecgreb** [comment]
This looks like good progress. So I noticed a couple things in the latest version of Eraser Map:

1. Superior Woodcraft no longer has a feature icon shown on the map (like Charles Seiz Florist) where as it used to prior to these changes. This means it can no longer be single tapped to perform a place search. Could this be due to the changes in ID format?

2. Long pressing on the building to reverse geocode produces the correct result but the label returned is "160 North Hamilton Street" rather than "Superior Woodcraft".

https://pelias.mapzen.com/v1/reverse?point.lat=40.311589714339284&point.lon=-75.13584951065829&api_key=search-BcgTWes

![image](https://cloud.githubusercontent.com/assets/464123/14541966/89273576-025a-11e6-92d2-618a9f886946.png)

**Comment by dianashk** [comment]
The icons on the map are coming from vector tiles, so this might be a question for @nvkelso.
As for the results of the reverse query, you can choose to look for the closest `venue` in results (with high confidence score) and only show an address if there aren't any venues around. We currently duplicate each venue that has an address and also we don't deduplicate or establish concordances between OSM and OpenAddresses, so a venue from OSM can also have its address be in OpenAddresses.

**Comment by nvkelso** [comment]
There was a change in the Bubble Wrap stylesheet a couple weeks ago responding to a bug with business venue icons. We now default to name only labels for building labels, and only features promoted to POIs receive the icons via a white listing mechanism in vector tiles. 

For the label only building names, I'll update Bubble Wrap to enable interactivity on them.

**Comment by nvkelso** [comment]
See: https://github.com/tangrams/bubble-wrap/issues/179

**Comment by nvkelso** [comment]
Agree with @dianashk that the long-press pin drop logic should probably be changed to prefer venues over addresses.

**Comment by dianashk** [comment]
@nvkelso also mentioned adding the ability to retrieve the same data from the building/label as you can from a POI marker in the tiles, so stay tuned for that feature in the near future.

**Comment by nvkelso** [comment]
This particular OSM feature [way/392154008](http://www.openstreetmap.org/way/392154008) looks to be added by @ecgreb, and is tagged industrial. For it to receive an icon, it needs to match one of the POI kind whitelisted tags – `building=industrial` is only labeled via name. 

Something like `craft=carpenter` seems appropriate to tag the data, and that data is already whitelisted in the tiles logic. I've updated the OSM feature at OSM.org, should be in tiles "soon".

**Comment by dianashk** [comment]
Hooray for team work and synergy!!! Thanks @nvkelso!

**Comment by ecgreb** [comment]
Actually Superior Woodcraft (and most other POIs in Doylestown) was added by @eringreb. Thanks for the info and the edit.

**Comment by orangejulius** [comment]
I think we've figured all this out, if there's anything Pelias related left, let us know and re-open this. Otherwise... :tada:
