### ISSUE TITLE
Handle P.O. Box addresses properly

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#306]
Disregard the PO BOX component of addresses and focus on the admin parts specified to return the region the box lies within.

**Comment by riordan** [comment]
This isn’t true for EVERY PO box but:
1. If it’s a US PO BOX
2. AND it has a Zip Code that’s in this [list from USPS](https://ribbs.usps.gov/mtcsa/documents/tech_guides/mtcsa.txt)
THEN its location is the post office for that zip code

SO… find the post office list that Stephen used to use, combine it with that list, parse out PO Box queries; and we’ve got locations!

via [USPS poboxes pdf](https://ribbs.usps.gov/mtcsa/documents/tech_guides/pbsaguide.pdf)

**Comment by missinglink** [comment]
in progress, I found this: https://github.com/davglass/zipcodes

**Comment by mtmail** [comment]
pinging @iandees because of his recent tweet https://twitter.com/iandees/status/722481909746507778
`I wrote a scraper for USPS post boxes last night for fun. Does the data already exist somewhere? Anyone care enough to see the data?`

**Comment by iandees** [comment]
Hi y'all! I am scraping the location for "blue boxes"/mail drop off points, not PO Boxes.

**Comment by mtmail** [comment]
ah sorry, my mistake

**Comment by rowanwins** [comment]
Just as a quick note on this, I'm doing some batch geocoding using Pelias on some historic inconsistently data. PO Boxes were/are one of the things giving me the most grief. 

I do like @riordan suggestion of matching a PO Box to a known locality of a post office - just not sure how this would get built into Pelias and/or WOF. I recently worked to improve the [Australian postcodes](https://github.com/whosonfirst-data/whosonfirst-data/issues/472) in WOF however Im not sure how the post office angle would fit in.

**Comment by rowanwins** [comment]
As another aside I have just created a simple little js module that looks for the presence of po box details in an address string. It's available as a [github repo](https://github.com/rowanwins/po-box) but I haven't yet thrown it on npm but you're welcome to check out the repo, the regex may be of some use to you. 

Hope it helps.

**Comment by dianashk** [comment]
Now that we have postalcodes in our index and libpostal parses po boxes correctly the results are sufficiently correct. They will point to the centroid of whatever admin area was provided with them. Here are a few examples.

[/v1/search?text=po box 123, furlong, pa](http://pelias.github.io/compare/#/v1/search%3Ftext=po%20box%20123,%20furlong,%20pa)

![screen shot 2017-05-08 at 3 43 05 pm](https://cloud.githubusercontent.com/assets/5446511/25821959/122e6aec-3405-11e7-86f7-9feeff8ed44c.png)

[/v1/search?text=po box 123, 18925](http://pelias.github.io/compare/#/v1/search%3Ftext=po%20box%20123,%2018925)

![screen shot 2017-05-08 at 3 43 58 pm](https://cloud.githubusercontent.com/assets/5446511/25822006/3f03d48a-3405-11e7-9818-b7d8acc31eff.png)
