### ISSUE TITLE
Address de-duper should be part of the import pipeline

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#31]
When we import any geospatial data into pelias index, they should undergo the following 
- de-duper: to make sure we dont have two points with the same name from one or more sources.

Ideally, a de-duper instance should be kept alive through out the import process across different sources (`geonames`, `osm`, `quattroshapes` etc) so that it catches duplicate names/ points before adding them to the ES index.

**Comment by riordan** [comment]
Import Pipeline deduplication is being moved into backlog. Temporary fix for duplicates is being handled in API. Duplicates in datasets are a feature, not a bug! Provenance FTW!

**Comment by riordan** [comment]
Also, part of pelias/api#339

Hi Harish's inbox.

**Comment by amnesia7** [comment]
Will this de-duplication, once applied, remove the current duplicates for `tower of london` (as an example) that the autocomplete and search both return?

**Comment by orangejulius** [comment]
As of https://github.com/pelias/openaddresses/pull/362 and https://github.com/pelias/pelias/issues/703 we have removed the address deduplicator.

At this time, most deduplication needs can be solved at query-time, and the complexity of the current address deduper has been too high to warrant any index-time deduplication.
