### ISSUE TITLE
Potter, PA

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#311]
Failing acceptance test. When using Potter, Pennsylvania the results are better (number 2) but still not right.

**Comment by orangejulius** [comment]
This looks to still be an issue: [Potter, PA](http://pelias.github.io/compare/#/v1/search%3Fsources=wof&text=Potter,%20PA), although the first result _is_ called Potter, PA. However it's a localadmin, where the test expects a county

**Comment by dianashk** [comment]
Already fixed on dev. Close once it makes it to prod.
