### ISSUE TITLE
Production branches

### ISSUE THREAD

**Issue by curiousc0w** [pelias/pelias#312]
Is there an idea of when WOF will be distributed to the production branches that are stable?

**Comment by orangejulius** [comment]
It was all merged last week actually! WOF records are [live](http://pelias.github.io/compare/#/v1/search%3Fsources=wof&text=london,%20uk) on mapzen search as well.

**Comment by curiousc0w** [comment]
@orangejulius 
Thank you!
Yesterday when I checked I didn't see a README.md updated but it looks like it was just recently added.
