### ISSUE TITLE
Cannot find 1306 E Vermont St, Indianapolis, IN, USA

### ISSUE THREAD

**Issue by trevorgerhardt** [pelias/pelias#316]
1306 E Vermont St, Indianapolis, IN 46202

Not found using Search: https://mapzen.com/products/search/?query=1306%20E%20Vermont%20St%2C%20Indianapolis%2C%20Indiana&endpoint=search&lng=-70.66670&lat=-33.45000&zoom=12

<img width="1661" alt="screenshot 2016-04-19 10 11 14" src="https://cloud.githubusercontent.com/assets/776780/14640259/225344aa-0617-11e6-8f0b-74a18c1d0e22.png">

Found using Google Maps: https://www.google.com/maps/place/1306+E+Vermont+St,+Indianapolis,+IN+46202/@39.772585,-86.1383217,17z/data=!3m1!4b1!4m2!3m1!1s0x886b508acf5e6fa9:0x7d2d532dbbe768ff

<img width="1665" alt="screenshot 2016-04-19 10 11 25" src="https://cloud.githubusercontent.com/assets/776780/14640306/557e078e-0617-11e6-859f-84071c1b18de.png">

How can I help track this down? Since addresses were found I suspect it's a data issue.

Thanks!

**Comment by trevorgerhardt** [comment]
Turns out Nominatim finds it: http://www.openstreetmap.org/search?query=1306%20E%20Vermont%20St%2C%20Indianapolis#map=19/39.77243/-86.13615

<img width="1670" alt="screenshot 2016-04-19 11 38 58" src="https://cloud.githubusercontent.com/assets/776780/14643065/559c50e8-0623-11e6-997f-1c274b77b30a.png">

**Comment by trevorgerhardt** [comment]
Using all sources in the query `sources=gn,oa,osm,wof` did not fix it. Is just `wof` the default for that when using Mapzen Search?

**Comment by orangejulius** [comment]
Hey @trevorgerhardt,
It looks like none of our datasets have this data. The link above from Nominatim shows that its actually an address interpolated from [TIGER](https://en.wikipedia.org/wiki/Topologically_Integrated_Geographic_Encoding_and_Referencing) data. The UI is a bit confusing here, and I've fallen for it before. If it was actually in OSM, clicking on the record on the bar on the left would show a node or way id.

It's also not in OpenAddresses, the only other data source we import that has address data:

```
julian@julian-mapzen ~/data/openaddresses/us/in $ grep  -i "Vermont St" marion_county.csv 
julian@julian-mapzen ~/data/openaddresses/us/in $ 
```

If it's an address that you have local knowledge about, definitely add what you know to OSM and it will show up not only in Pelias (we build weekly for Mapzen Search), but anywhere else that uses OSM data!

**Comment by trevorgerhardt** [comment]
I do not have local knowledge of the location. Is there any plan to use interpolated TIGER data as a fallback?

**Comment by orangejulius** [comment]
We are just beginning to do some research on interpolation. It's not clear what it will look like yet, but we've been thinking about doing interpolation based on OSM and/or OpenAddresses data instead of TIGER. While it would be more difficult, it would also work outside the relatively few countries that have address block data like the US. In any case it will be a few months.

**Comment by trevorgerhardt** [comment]
Good to hear! Is there a place to track progress and discussion about this? It definitely seems like a big step in the right direction.

**Comment by orangejulius** [comment]
Yes! There's now https://github.com/pelias/pelias/issues/328

**Comment by orangejulius** [comment]
Just happened to stop by this issue and figured I'd check in. The ever-forward march of open data progress has not _yet_ obviated the need for interpolation for this query. Maybe soon!

http://pelias.github.io/compare/#/v1/search%3Ftext=111%20Monument%20Circle,%20Indianapolis,%20IN
![screenshot_2016-07-01_16-36-59](https://cloud.githubusercontent.com/assets/111716/16533925/1ff55154-3faa-11e6-9b78-2f94779308a9.png)

**Comment by orangejulius** [comment]
Oops, I initially linked to the wrong image and URL. Fixed now!

**Comment by dianashk** [comment]
Hey @trevorgerhardt, I have all kinds of good news here!!!  🎉 

Interpolation has just launched, which is very exciting! Check out more details over at the [Mapzen blog](https://mapzen.com/blog/interpolation/).

Also, looks like OpenAddresses now has the exact address in question **AND** we are now interpolating correctly in this area for addresses that are not found in any of our datasets.

The original query for [1306 E Vermon St](http://pelias.github.io/compare/#/v1/search%3Ftext=1306%20E%20Vermont%20St,%20Indianapolis,%20IN,%20USA) now results in
```
1)	1306 E Vermont St, Indianapolis, IN, USA
```

And the search for an address that doesn't actually exist in the data, but could be interpolated, like [1307 E Vermont St](http://pelias.github.io/compare/#/v1/search%3Ftext=1307%20E%20Vermont%20St,%20Indianapolis,%20IN,%20USA) now returns the expected interpolated result.
```
1)	1307 East Vermont Street, Indianapolis, IN, USA
2)	East Vermont Street, Indianapolis, IN, USA
3)	East Vermont Street, Indianapolis, IN, USA
4)	East Vermont Street, Indianapolis, IN, USA
5)	East Vermont Street, Indianapolis, IN, USA
6)	1307 East Vermont Street, Indianapolis, IN, USA
7)	East Vermont Street, Indianapolis, IN, USA
8)	1307 East Vermont Street, Indianapolis, IN, USA
```

Let us know if you feel this issue has been resolved.

**Comment by orangejulius** [comment]
Looks like this has been all fixed for a while 🎉
