### ISSUE TITLE
document code with JSDoc-style block comments

### ISSUE THREAD

**Issue by sevko** [pelias/pelias#32]
I'm a fan of [JSDoc](http://usejsdoc.org/about-getting-started.html)-style documentation comments, since it's usually helpful to comprehensively document your module/function APIs (while the implementation itself should be self-documented, unless you're doing something quite clever). We won't be using the jsdoc utility to actually generate documentation, but I think it's a decent format to adhere to. I only typically use `@param` and `@return` tags, like in this verbose example:

```javascript
/**
 * Import all OpenAddresses CSV files in a directory into Pelias elasticsearch.
 *
 * @param {string} dirPath The path to a directory. All *.csv files inside of
 *    it will be read and imported (they're assumed to contain OpenAddresses
 *    data).
 * @param {object} opts Options to configure the import. Supports the following
 *    keys:
 *
 *      deduplicate: Pass address object through `address-deduplicator-stream`
 *        to perform deduplication. See the documentation:
 *        https://github.com/pelias/address-deduplicator-stream
 *
 *      admin-values: Add admin values to each address object (since
 *        OpenAddresses doesn't contain any) using `hierarchy-lookup`. See the
 *        documentation: https://github.com/pelias/hierarchy-lookup
 */
```

I'll eschew it for short/obvious functions.

Thoughts from @pelias/contributors ?

**Comment by dianashk** [comment]
Write up documentation standards and start applying that to new code.

**Comment by sevko** [comment]
Go for whatever. I'd personally recommend JSDoc-format comments for substantial functions with complex parameters, and less structured comments like the one shown below for simpler ones.

```javascript
/**
 * Draw a pixel of color `color` at screen coordinates (`x`, `y`), with indexing
 * beginning at 0 at the top-left corner for both axes.
 */
void drawPixel(x, y, color){
```

**Comment by missinglink** [comment]
FYI: This may be relevant https://github.com/documentationjs/documentation/blob/master/FAQ.md#why-use-documentation-instead-of-jsdoc
