### ISSUE TITLE
geonames / whosonfirst duplication

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#322]
we need to decide on the best way to deal with duplicate regions between the `geonames` and `whosonfirst` datasets.

eg:

```
/v1/autocomplete?text=wellington

1)  Wellington, New Zealand (geonames:region:2179538)
2)  Wellington, New Zealand (whosonfirst:locality:101915531)

/v1/autocomplete?text=auckland

1)  Auckland, New Zealand (geonames:region:2193734)
2)  Auckland, New Zealand (whosonfirst:locality:101914595)
```

in some cases the data doesn't appear to be in `whosonfirst`, such as:

```
/v1/autocomplete?text=paris

 1) Paris, France (geonames:venue:2988506)
 2) Paris, France (geonames:county:2968815)
 3) Paris, France (geonames:locality:2988507)
... no wof
```

**Comment by hyperknot** [comment]
Might be related to https://github.com/pelias/pelias/issues/333, wikimedia URL (both en and alternative language ones) might be a good key for connecting duplicates.

**Comment by orangejulius** [comment]
A leading contender here is #220

**Comment by dianashk** [comment]
I think [this PR](https://github.com/pelias/api/pull/687) will help resolve part of the concern here. Particularly in the case where the records are duplicated in geonames and whosonfirst. However, I think it's best to track the other issue separately. We still need to figure out a way to indicate to the user which layer the results are coming from when more than one with the same exact label are returned.

**Comment by orangejulius** [comment]
We have pretty solid cross-layer/cross-source deduplication as of https://github.com/pelias/api/pull/1230 now. We can consider this closed.
