### ISSUE TITLE
bbox missing from most search results

### ISSUE THREAD

**Issue by hyperknot** [pelias/pelias#326]
Hi, I'm using Mapzen search on maphub.net and I have to say that the new search engine is fantastic!  However the biggest issue I'm having is the missing bbox for the majority of search results.

This might not be important for many of your users, but for an interactive map it is critical to have bbox information on all search results, since the application needs to know if the user is interested in a city-scale feature or just a house.

**Comment by dianashk** [comment]
Hey @hyperknot, thanks for the feedback. Missing bboxes are a known issue for any records coming from the Geonames dataset. We only get centroids from those. One possible solution in the short-term would be to limit your search to only `openstreetmap`, `openaddresses`, and `whosonfirst`. All the geometries come from the `whosonfirst` dataset.

Your queries would look something like this:

[`https://search.mapzen.com/v1/search?api_key=<your_key>&sources=openstreetmap,openaddresses,whosonfirst&text=london, uk`](https://search.mapzen.com/v1/search?api_key=<your_key>&sources=openstreetmap,openaddresses,whosonfirst&text=london, uk)

Note that you might be missing a good part of the venue data that Geonames provides, but at least you will be sure to have bboxes. We are working on a solution for this and will hopefully begin to address it in the second half of this year. Let us know how this short-term fix works out.

**Comment by hyperknot** [comment]
Thanks I didn't realise that geonames doesn't have that data. But this bug is not only effecting geonames, many `openstreetmap` and `openaddresses` results have the same missing bbox as well.

**Comment by dianashk** [comment]
Within `openstreetmap` and `openaddresses`, where a result doesn't have a bbox, it indicates that it's a venue or address. If that's not the case, please make a note of those records in an issue and we will resolve it.

**Comment by hyperknot** [comment]
OK, it is clear now, so bbox is only present when source is in osm, oa, wof and layer is not address or venue. In that case there are no bugs, just the missing information from geonames duplicates (see #333).
