### ISSUE TITLE
Interpolation R&D

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#328]
Investigate various possible solutions for interpolation. Working prototypes would be ideal outcomes.

**Comment by missinglink** [comment]
https://github.com/pelias/pelias/wiki/Interpolation:-introduction

**Comment by missinglink** [comment]
https://github.com/pelias/pelias/wiki/Interpolation:-existing-standards

**Comment by missinglink** [comment]
https://github.com/pelias/pelias/wiki/Interpolation:-conflation

**Comment by missinglink** [comment]
https://github.com/pelias/pelias/wiki/Interpolation:-design-doc

**Comment by missinglink** [comment]
wiki files added to directory in `pelias/pelias` repo for future reference: https://github.com/pelias/pelias/tree/master/interpolation
