### ISSUE TITLE
Merge information from geonames and OSM results

### ISSUE THREAD

**Issue by hyperknot** [pelias/pelias#333]
Many properties are sometimes better in geonames database (like alternate names, geological feature types), while others are better in OSM (like bbox). This might be a really hard task, but it would be really important for high quality geological search results.

At the moment, pelias result is not showing duplicates, so I guess some duplicate detection is probably already taking place. If so, it'd be a simple task to take data from both sources and add the relevant source id to both osm and geonames.

example 1: search for `Naszály`:
geonames:locality:3047443, osm (1649423889), peak
geonames:venue:3047444, osm (1027822), city boundary
openstreetmap:venue:way:279569719, osm (279569719), mountain range

example 2: search for `Balaton`
geonames:locality:722670 / whosonfirst:locality:101843561 -> osm (1638031), lake

Now if pelias knows that these are duplicates, then it should take information from both of them instead of just using one. Most important would be bbox and a high quality type / label support. 

If the duplicate detection is not yet finished, I'd recommend wikimedia URLs (both english and alternative language ones) as probably a very good key for connecting duplicates.

**Comment by hyperknot** [comment]
Also, we have the very weird situation where searching with a **limited** 'sources': 'osm,oa,wof' limit would give **additional information** (like bbox) over a normal search.

For example:
https://search.mapzen.com/v1/search?text=nasz%C3%A1ly&api_key=search-uOD59t8&sources=osm%2Coa%2Cwof (whosonfirst:locality:101785801)
vs.
https://search.mapzen.com/v1/search?text=nasz%C3%A1ly&api_key=search-uOD59t8 (geonames:locality:3047443)

**Comment by missinglink** [comment]
related: https://github.com/pelias/pelias/issues/322

**Comment by missinglink** [comment]
thanks for the bug report @hyperknot, we are aware of duplicates between data sets and we're trying to figure out the best way to deal the issue.

geonames contains a mix of regional and venue information; some of which are duplicates of whosonfirst data, others duplicates of openstreetmap data.

we considered turning off the geonames importer by default but found that there was some really great data in that dataset which we still wanted to include in the index.

we're also reviewing the idea of only targeting certain 'feaure codes' in geonames, so we could leave some out.

I've linked a similar report above and added a dev milestone, at this stage I can't give you a date when the team will get to it but we are discussing it and are open for external ideas and contributions.

**Comment by missinglink** [comment]
re: your comment, the geonames dataset only contains point information, so unfortunately no bboxes for those records.

**Comment by hyperknot** [comment]
@missinglink thanks for the detailed reply. I think the best approach would be the following:
1. Detect duplicated features.
2. For all features which are found in more than one dataset, make them into whosonfirst features, merging all their "unique" information, like bbox, etc.
3. Keep their source id in a filed like 
```
sources: {
  geonames: 3047443, 
  osm: 1231231
}
```
4. This way, your result would contain not a geonames:locality but a whosonfirst:locality which also has a bbox.

**Comment by orangejulius** [comment]
Thinking about this a few years later, I don't think merging data from records between sources is a good path for Pelias. Instead we should help datasources used by Pelias contain the best, most complete, and most well linked data possible.

WOF, for example, has frequent updates and good concordances between Geonames IDs, Wikidata IDs, and more. 

We've continued to improve deduping logic in PRs such as https://github.com/pelias/api/pull/1230, and as WOF itself imports more data from Geonames, I don't see the problem of "all the data wanted is there, but not in a single dataset" being as much of an issue any more.
