### ISSUE TITLE
Can't find 5361 Michigan Avenue, Sanford, FL 32771

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#336]
[compare link](http://pelias.github.io/compare/#/v1/search%3Ftext=5361%20Michigan%20Avenue,%20Sanford,%20FL%2032771)

[5361 Michigan Avenue, Sanford, FL](http://pelias.github.io/compare/#/v1/search%3Ftext=5361%20Michigan%20Avenue,%20Sanford,%20FL) doesn't work either
[
5293 Michigan Avenue, Sanford, FL](http://pelias.github.io/compare/#/v1/search%3Ftext=5293%20Michigan%20Avenue,%20Sanford,%20FL) DOES work and its only about 1000ft east down the road - the difference is the OSM road type is residential at 5293 and track at 5361. Does pelias heavily and negatively weight highway type in OSM, i.e. if an address is along highway=track, it doesn't exist?

**Comment by dianashk** [comment]
Hey @b-may, thanks for flagging this. Here's what a bit of investigating uncovered.

1. In OSM these addresses are only available via interpolation (line data) which we currently do not support. So the strange results are not related to the `highway` tag applied to the `way`.
2. The one address we are able to find is coming from OpenAddresses (openaddresses.io) and it's not immediately clear why the other address so close by is not in the data. We'll dig into that a bit further.
3. Even given the data isn't all there, the sorting order of the results for housenumber `5361` is disturbing. We should be favoring results from the right city/state and with the matching street above others. We are currently working on a fix for this unfortunate behaviour.

**Comment by orangejulius** [comment]
Hey @b-may,
This query still looks broken in our latest build that includes OA data. Do you know if it was in the data you recently send to OA? Screenshot for reference:
![screenshot from 2016-06-13 12-20-14](https://cloud.githubusercontent.com/assets/111716/16014914/65dae06e-3161-11e6-8a20-e47968b642f5.png)

**Comment by trescube** [comment]
I looked thru the data zip from Mapwise and don't see 5631 Michigan Ave:

```
admins-MacBook-Pro-6% egrep -c "MICHIGAN AVE" florida_mapwise.csv
855
admins-MacBook-Pro-6% egrep -c "MICHIGAN AVE" florida_mapwise.csv | egrep "5631"
admins-MacBook-Pro-6%
```

**Comment by b-may** [comment]
I left counties out of the data set where I knew there were address points available for that county - in this case Seminole County. However, Seminole is not in OA yet. I created an OA issue for Seminole back in March, but it looks like nothing was done with it. I assumed someone would pick up the issue and get it into OA. There's a couple other counties like this. 

https://github.com/openaddresses/openaddresses/issues/1620

**Comment by trescube** [comment]
Ah, I'll create a source for Seminole today at some point.  Are other addresses from florida_mapwise.zip working out for you?

**Comment by b-may** [comment]
Yes, things are looking good. The zip code problem appears to be solved, too. 

I will do more testing and document issues later today.

**Comment by trescube** [comment]
With the OA data update, this issue is fixed:

![screen shot 2016-08-24 at 12 38 04 pm](https://cloud.githubusercontent.com/assets/658991/17939232/a9e2ac1e-69f7-11e6-92a1-8305e0f80fca.png)

However, the PiP data that we use doesn't have a locality/localadmin polygon for that particular area of Seminole County, FL.  Sanford, FL is [quite whole-y](https://whosonfirst.mapzen.com/spelunker/id/85932125/#12/28.7869/-81.2745).

**Comment by trescube** [comment]
Since we fixed the source issue, I'm closing this.
