### ISSUE TITLE
Re-engineer the address deduplicator

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#337]
As part of pelias we have a very functional and useful [address-deduplicator](https://github.com/pelias/address-deduplicator). At last count it removes something like 60 _million_ duplicate entries when importing all Openaddresses data. Since duplicate addresses (in theory) do nothing but slow Pelias down, this is pretty helpful.

However, there are some problems:
1.) It's quite slow and resource intensive during import: it can only handle around 500 requests/second and uses 50GB of disk space
2.) Operationally it's quite hard to set up: it requires allocating a bunch of scratch disk space, and runs as a separate Python Flask service, which has to be administered during imports
3.) It can run out of memory and crash, leading to failed imports
4.) Because it's written in Python, our Node.js heavy team doesn't really know how to work with it
5.) It's now using an out of date version of the OpenVenues address normalizer, rather than the latest libpostal builds

For all these reasons we've currently disabled it our planet builds for Mapzen Search, but it might be interesting to look into bringing it back in a rearchitected way.

The first step would be to identify if it will actually lead to any sort of performance or infrastructure benefits. The [pelias/loadtest](https://github.com/pelias/loadtest) utility could be used to compare performance.

After that, we could look at a new architecture. After recently digging into Node.js native addons, I have an idea of how this could work.
## Current Architecture

A python service takes in large (1000+) batch requests of addresses. It runs each of those addresses through the Openvenues address_normalizer, which generates a bunch of possible expansions. For example, it will expand abbreviations like `st` into `street`, `saint`, etc, so it can catch duplicates that are not as simple as exact text duplicates.

For each of those expansions, it takes the first couple characters of the lat/lon in geohash format, combines that with the expansion, and stores that key in LevelDB. Future requests then know if the address is a duplicate if it finds a key already exists [1]

Finally, there's a node-js stream in our address-deduplicator package that manages batching up items in the import stream and sending them off to the python server.
## Possible Proposed Architecture

At the very least, we should bring all the logic into Node.js. libpostal has a Node.js module, and it's quite fast. Querying LevelDB is also easy from Node. This would keep more execution in Node and probably be quite a bit more efficient.

However, we might be able to get rid of LevelDB entirely: right now we are simply storing a bunch moderate length keys, and checking for their existence. Could we build a Node.js native addon that stores those keys in some sort of prefix tree that is really space efficient? Remember that native addons can use more than 1GB of memory and are quite fast since they're written in C++.

[1] The rate of false positive duplicates is not currently known, but should also be investigated.

**Comment by trescube** [comment]
Does it give us any better data quality than by simply running `sort` and `uniq` on the input files?

**Comment by orangejulius** [comment]
@trescube. Definitely worth investigating, but we should also do that regardless, since it's quick and easy.

**Comment by easherma** [comment]
Couple thoughts:

* Might be worth it to check out [dedupe](https://dedupe.io/), a product recently launched by some friends of mine. Essentially works by creating a trained dataset, and you'd have plenty of data to train dedupe on in this case. 

* Python/Flask is pretty solidly within my wheelhouse, and I may end up needing/executing some sort of dedupe function on the backend of my particular use case. If there are any particular overlapping ideas, I might be able to help test them.

**Comment by orangejulius** [comment]
The deduplicator has been removed in https://github.com/pelias/openaddresses/pull/362 as part of https://github.com/pelias/pelias/issues/703, so we likely won't be doing this any time soon.
