### ISSUE TITLE
Use localized admin names when doing admin-lookup

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#339]
Currently we use only the English names for admin hierarchy components during import. The default admin names should be set to the localized versions of those names.

Searching for Seoul in Korean, for example like [/v1/search?text=서울](http://pelias.github.io/compare/#/v1/search%3Ftext=%EC%84%9C%EC%9A%B8)

results in stuff that's in Korean with English placenames. 

```
 1) 서울 한방병원, Seoul, South Korea
 2) 덜위치칼리지 서울, Seoul, South Korea
 3) 팔레트 서울, Seoul, South Korea
 4) 서울 양천도서관, Seoul, South Korea
 5) 서울 도성, Seoul, South Korea
 6) 서울/용문행, Munsan, South Korea
 7) 서울 양천우체국, Seoul, South Korea
 8) 서울 도성, Seoul, South Korea
 9) 서울 이동통신빌딩, Seoul, South Korea
10) 서울 공연초등학교, Seoul, South Korea
```

**Comment by dianashk** [comment]
Separate issue, but still worth noting here, is that we don't actually have Seoul indexed in Korean. Or at least it's not showing up here. I think all of our places imports (Geonames and WOF) are conditioned to only use English names for the actual names of things as well. So Seoul instead of 서울.

**Comment by vesameskanen** [comment]
Hi @dianashk, it would be great to get this issue resolved. We currently tackle this issue by a postprocessing model in middleware, which translates admin parts using a little dictionary (see https://github.com/pelias/api/pull/501 ). It would be more elegant to have the required multi-language admin entries indexed in Pelias, and fetch the translated names from the index using admin hierarchy ids.

This approach requires that WOF data includes all relevant name versions. Seoul in Korea seems to have a rich set of  names, but unfortunately,  Finnish data entries mainly provide only one name. So we need to improve the source data, too.

**Comment by dianashk** [comment]
@vesameskanen, would you be interested in contributing to WOF to help add the translations for the names? Maybe it can be done using your translation dictionary?

**Comment by vesameskanen** [comment]
@dianashk , I am interested in contributing. Maybe as follows:
- translator middleware should use ES index and admin ids to search for translations (not only a static external dictionary as in our current implementation). 
- importers should import all name.lang variations

BTW, we have experimented (in my PR #501) a solution, where api examines which language gave the best match, and the response is automatically translated to that language. The explicit 'lang=' api parameter is used when there are multiple equally good matches, and in reverse geocoding. This approach seems to work quite well.

**Comment by vesameskanen** [comment]
I quickly checked what is included in the original WOF data. Unfortunately it seems, that language versions of administrative areas of the western world are often excluded (Berlin, Helsinki, Stockholm, Brussels, etc.) Finnish data is being updated right now, so hopefully that will help in our national case, which I am mostly interested in.

**Comment by dianashk** [comment]
Consider doing this as part of the PIP admin lookup milestone for Q3 2016.

**Comment by vesameskanen** [comment]
Admin lookup should probably add all (or a list of configured) language versions of admin names. That  would ensure that strict address searches with 'street, number, city' would work in all cases.

**Comment by hannesj** [comment]
@dianashk Pelias is showing incorrect names for finnish local admins with umlauts after they were imported to whosonfirst. 

See [this issue](https://github.com/whosonfirst-data/whosonfirst-data/issues/99#issuecomment-239615652) for more details

**Comment by dianashk** [comment]
@vesameskanen, @hannesj, some initial work has been to fix this. Would be great to get your feedback on the [PR](pelias/wof-pip-service#62) now that it's in-review. We're going to kick off a build on our dev server tomorrow and early next week we will be able to test this functionality out in our compare app.

**Comment by vesameskanen** [comment]
Hi @dianashk ,

Thanks for the good news! This is definitely a step to the right direction. Name selection by language attributes of the parent country would work perfectly for us, but I'd like to ask one more improvement: please add all names which are included in 'lang_x_official' array, just as you suggested yourself in the PR. This would mean that the name defined by wof-pip-service becomes an array, but that's a fairly straightforward change.

A second issue which comes to my mind is the country name; if I remember correctly, that part of the WOF hierarchy must still use the English name, because attributes are associated using that identification. I think I tried translating 'Finland' to 'Suomi' at some point and certain things got broken.  Maybe you have already considered this in the new service. If not, and  if you find it useful,  can recheck what went wrong in those tests.

**Comment by dianashk** [comment]
This is going to be resolved during the upcoming `placeholder` integration where we will no longer be tied to the names stored in the admin hierarchy for venue and address records, but will instead be looking at the ids.

**Comment by dianashk** [comment]
All the work has been done for this and there is now a lang parameter to specify which language the results should be in. Waiting to close issue after it hits production.

**Comment by dianashk** [comment]
This functionality is now in production! 🎉
