### ISSUE TITLE
Feature request: Have a multiple reverse geocoding

### ISSUE THREAD

**Issue by samuelmanzanera** [pelias/pelias#342]
Hello, in my company we use mapzen often for several services. One of them it's reverse geocoding.
And we need to retrieve data by reverse geocoding for many topology elements. 
And so we're trying to improve performance because sometimes we need to reverse geocode many thousand of points. 
Will be possible to create endpoint to allow to reverse geocoding a collection of points ?

Best regards

**Comment by orangejulius** [comment]
Hey @samuelmanzanera,
Thanks for sending in this feature request. We've had batch geocoding (or reverse geocoding) on our radar for some time now. There are a lot of challenges but you can follow pelias/pelias#69 to see how things are going as we progress. :star2:

**Comment by aggied** [comment]
bump

**Comment by orangejulius** [comment]
Hello folks,
I'm doing some ticket pruning. This ticket looks to basically be a feature request for #69, so I'm going to close it as a duplicate. Please feel free to leave any batch geocoding related notes there, and of course also feel free to open other tickets for any thing else! :airplane:
