### ISSUE TITLE
Automate more of our pull request/release workflow

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#345]
At EmpireJS @gr2m gave a great talk about [building welcoming open source communities](http://hood.ie/blog/welcoming-communities.html) that probably got several of us thinking! There were many takeaways about general interaction but two specifically regarding automation of workflows I would love to see us implement immediately.
## Use [semantic-release](https://github.com/semantic-release/semantic-release) to automate NPM releases :airplane:

NPM releases has been something we've had a bit of discussion about and not always done perfectly. Some cases where things haven't worked great:
- Just today we had a user report [an issue](pelias/pelias#344) that we had fixed, but we hadn't released the fix in an NPM module yet
- I've accidentally included over 1GB of test data in an NPM release which caused no real harm, but slows everything down and takes up space needlessly
- Sometimes we just waste time trying to decide the right version

Semantic-release automatically does NPM releases whenever a new commit hits the master branch, on TravisCI, and automatically increments the version correctly based on the rules of [semantic versioning](http://semver.org/)! Commits simply have to be tagged with the appropriate prefix in the commit message to state whether they're bug fixes, new features, or breaking changes. There's apparently also a way to reject merges into master that don't properly tag the commits.
## Use [LGTM](https://lgtm.co/docs/overview/) to provide simple checks for code review :+1:

We are generally really good at doing at least a quick code review before any code is merged, so why not enforce that with a Github check? I'd also love to see us start to invite some of our awesome external contributors to become maintainers of pelias repositories, and having more of our preferred workflow automated will help us as we do that.

**Comment by orangejulius** [comment]
Update: I've enabled LGTM on pelias/wof-admin-lookup, so we can try it out.

**Comment by gr2m** [comment]
@orangejulius there is a hidden (at least it was undocumented awhile ago) feature in LGTM. When you have a group that is called "maintainers", then by default two people of this group must comment with LGTM. Otherwise you have to configure it

**Comment by orangejulius** [comment]
Another update: semantic-versioning is now turned on in https://github.com/pelias/openaddresses, and I've successfully published a patch release! There's also considerable TravisCI improvements inspired by the .travis.yml that semantic-versioning gave us. The tests run faster now!

**Comment by dianashk** [comment]
Wow! Way to swoop in get those in place. Can't wait to see how they work in practice. I agree that both of these tools are simple and awesome changes that will result in a much more streamlined workflow. Thanks @orangejulius!

**Comment by gr2m** [comment]
oh another tip, there is semantic-release@6.3.0 on the `@next` dist-tag. When you use that, you don’t need to workaround with the `travis_after_all` python script, it’s built in. See for example https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/.travis.yml

Glad to help out if you have any questions 👋

**Comment by orangejulius** [comment]
@missinglink what do you think about adding these in more places?

**Comment by missinglink** [comment]
:+1:

**Comment by orangejulius** [comment]
Oh, one more cool thing. We should add test coverage badges to our repos via Coveralls. The output in [Travis](https://travis-ci.org/hoodiehq/hoodie/builds/133007324) is quite nice, the [setup](https://github.com/hoodiehq/hoodie/blob/master/package.json#L74) is not hard at all.
