### ISSUE TITLE
Make new GIFs for the README

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#346]
## Calling all GIF makers! :phone: 

We have some great GIFs for explaining geocoders at the top of our README, but they are getting old. They don't even use any of the awesome Mapzen styles we now have. And they're based on the old pelias/demo which we no longer maintain. :cry:

We need new GIFs that use our latest interfaces from something like the [leaflet-geocoder](https://github.com/mapzen/leaflet-geocoder).

**Comment by kkowalsky** [comment]
![pelias-1](https://cloud.githubusercontent.com/assets/4246770/16500453/76d6d8cc-3eb9-11e6-85d8-f57894ba7b73.gif)

How does this one look? Thinking about how to do the reverse geocoding one...

**Comment by orangejulius** [comment]
woah nice! I don't know if we actually have reverse enabled in any of our current demos. @louh, do we?

Also, I just looked back at our _old_ GIF and realized we don't even show the right statue of liberty! (the first result which is clicked on is the statue of libery ferry terminal in New Jersey) :doh:

**Comment by louh** [comment]
I don't think we have reverse enabled in any _official_ demo but I did build it into this one: https://nyc-community-boards.surge.sh/#11/40.7116/-73.9720

The code to make this work with `leaflet-geocoder` is pretty straightforward: https://github.com/louh/nyc-community-boards/blob/gh-pages/src/js/main.js#L50-L75

Does `mapzen.js` do reverse yet @hanbyul-here?

**Comment by kkowalsky** [comment]
@louh this is wonderful thanks I'll hack this together for a great demo gif

and if it is this straight forward, maybe that can be an additional tutorial for the search docs?

**Comment by kkowalsky** [comment]
![pelias-2](https://cloud.githubusercontent.com/assets/4246770/16505357/6ed694ba-3ed1-11e6-8cdb-cfdb9a067987.gif)

**Comment by kkowalsky** [comment]
here's the reverse geocoding gif:
![pelias-2](https://cloud.githubusercontent.com/assets/4246770/16506005/a2429288-3ed4-11e6-8af0-7ef78824213f.gif)

**Comment by orangejulius** [comment]
@avulfson17 your next task is to replace the two gifs in [the README](https://github.com/pelias/pelias/blob/master/README.md) with these :)

**Comment by kkowalsky** [comment]
Great job @avulfson17! Do you want to close this issue?
