### ISSUE TITLE
Add acceptance test run to pelias-deploy:api

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#348]
what should be done if the tests fail?

**Comment by orangejulius** [comment]
The first of these tasks, running the acceptance tests whenever we deploy the API, is now done!

**Comment by dianashk** [comment]
Make 2 new tickets and track separately. The idea of verifying deployment to staging is a nice-to-have and could live in the `idea` column for now. The automation task is important and should be tracked sooner.

**Comment by orangejulius** [comment]
This is done, although the tests are run too frequently if anything: kicking off a new build starts with deploying the API, and the tests are run then. Immediately after this the Elasticsearch index is wiped and the build started, so it's somewhat useless, and the email is a bit confusing. But not a huge concern, and it can probably be fixed.
