### ISSUE TITLE
Add comma checks to all repos in jshint

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#349]
We have had subtle bugs caused by Javascript's problematic [comma operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator).

We'd like to use jshint to check for incorrect usage of this operator and warn against it.

See https://github.com/pelias/query/pull/23 for an example.

**Comment by orangejulius** [comment]
And here's an example of the code in question: https://github.com/pelias/query/pull/19

**Comment by orangejulius** [comment]
I believe we took care of this everywhere.
