### ISSUE TITLE
upgrade to nodejs 0.12.x

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#35]
this ticket is for any issues associated with the upgrade to nodejs version `0.12.x`.

**Comment by missinglink** [comment]
I am seeing this warning all over the place:

```bash
_writableState.buffer is deprecated. Use _writableState.getBuffer() instead.
```

**Comment by sevko** [comment]
Perhaps we should wait until we have more robust build reporting to make this switch, to make sure that things haven't silently regressed in weird ways? It seems unlikely that they would (feel like it'd be a pretty clear case of it runs/doesn't run at all), but might be a possibility (?).

**Comment by dianashk** [comment]
fences cannot support 0.12.x at this time. Keeping it under 0.10.35

**Comment by sevko** [comment]
Currently investigating this issue. Make sure to `rm -rf node_modules && npm install` if you encounter the following error under 0.12:

```javascript
/home/sevko/src/mapzen/openaddresses/node_modules/pelias-admin-lookup/node_modules/microtime/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/sevko/src/mapzen/openaddresses/node_modules/pelias-admin-lookup/node_modules/microtime/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/sevko/src/mapzen/openaddresses/node_modules/pelias-admin-lookup/node_modules/microtime/index.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by sevko** [comment]
The plan is for us to switch over to 0.12.x, and see how it works out in day-to-day dev work. If everything looks good, we'll try it out during our next dev/staging builds and potentially officially switch over. Unassigning myself since this is a group ticket.

**Comment by dianashk** [comment]
@heffergm, @missinglink is this done now? We are currently running 0.12.* on production. What else needs to be done, if anything, to close this out?

**Comment by heffergm** [comment]
We've been running 0.12.2 everywhere (where 'everywhere' is any hosted environment) since the end of April if not longer.

**Comment by dianashk** [comment]
thanks. closing this ticket.
