### ISSUE TITLE
Move all deprecated/obsolete repos to a pelias-deprecated org

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#350]
We have almost 80 repositories in the pelias org, which is starting to get cumbersome. Many of them are old and no longer used, so it would be nice if we didn't have to think about them all the time.

For us who at least know which are old and which are new, it's just an inconvenience. For new contributors it's probably pretty daunting at worst, and a waste of time at best (who wants to have to spend time making a mental list of which repositories to ignore?). We definitely want to figure out a way to remove this clutter from our lives.

However, we don't really want to delete code from the internet completely, for many reasons. Maybe a good way to keep old code around while cutting down on clutter is to create a pelias-depricated organization, and move all the stuff we no longer use there.

**Comment by trescube** [comment]
Good call but make sure you spell it "deprecated"

**Comment by orangejulius** [comment]
where is spell check for github repo names :P

**Comment by orangejulius** [comment]
I think this is done.
