### ISSUE TITLE
search results for San Francisco should not use math centroid

### ISSUE THREAD

**Issue by burritojustice** [pelias/pelias#356]
should return label centroid..

latitude	37.778008
longitude	-122.431272

not math centroid (halfway to the Farallons)

"features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.693976,
          37.759715
        ]
      },

**Comment by orangejulius** [comment]
I can confirm [this is broken](http://pelias.github.io/compare/#/v1/search%3Ftext=san%20francisco). 

![sf](https://cloud.githubusercontent.com/assets/111716/15913401/c22ce866-2da7-11e6-97fd-0bb0a21421a4.png)

I suspect what happens is the Geonames result (which has a Farallon-proof lat/lon) was coming up first until recently, so we didn't notice. Test cases with lat/lon have (finally) been added and the fix should go out in our build starting early tomorrow night, for release by early next week.

**Comment by orangejulius** [comment]
And, fixed! 
![screenshot from 2016-06-13 14-31-02](https://cloud.githubusercontent.com/assets/111716/16018672/7e3784a2-3173-11e6-9fb5-f62f6deb8748.png)

**Comment by trescube** [comment]
nice
