### ISSUE TITLE
We need a new architecture diagram

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#357]
Our current one still contains Quattroshapes :(

![current diagram](https://cloud.githubusercontent.com/assets/4467604/6944539/3b1cdd0e-d862-11e4-995d-0b376caacad6.png)

**Comment by orangejulius** [comment]
We could also probably do a better job on the right side. Eraser Map could be mentioned for example.

**Comment by kkowalsky** [comment]
I can do this, I *basically* have one done since the zine was made
[Untitled-4.pdf](https://github.com/pelias/pelias/files/370291/Untitled-4.pdf)

**Comment by orangejulius** [comment]
That would be awesome! I'm open for ideas of what we put on the right side, but it should definitely include Eraser Map. Anyone else have any ideas?

**Comment by trescube** [comment]
"Other API consumers"

**Comment by dianashk** [comment]
Could also list leaflet-plugin, or to be more general say `web apps`, `mobile (native) apps`, `backend services`
