### ISSUE TITLE
Fallback to PiP lookup when reverse fails

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#360]
When `/reverse` geocoding doesn't find an address or a venue, return the lowest level admin area the query point falls within.

This would also mean that `reverse` queries can start to limit the search to only `address` and `venue` layers.

**Comment by trescube** [comment]
This is in dev but hasn't made it to prod yet.

**Comment by dianashk** [comment]
Are there corresponding acceptance tests to validate that this feature is working in production? If not, please add a few. Thanks!

**Comment by trescube** [comment]
Handled in pelias/acceptance-tests#389
