### ISSUE TITLE
equinox san francisco fails to find the POI

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#363]
When searching for `equinox san francisco` the gym is expected to be found, instead we are returning `France Equinoxiale`, even though a focus point was specified in SF. :grimacing:

![image](https://cloud.githubusercontent.com/assets/5446511/16390961/00c756fe-3c73-11e6-8f78-ed531c8bc6b8.png)

Correct behavior is to prefer venues when a focus point is provided.

A few sample queries:

[with a focus point in SF](http://pelias.github.io/compare/#/v1/search%3Fpoint.lon=-122.431272&point.lat=37.778008&text=equinox%20san%20francisco):

```
 1) France Équinoxiale, Kourou, France
 2) Salle Équinoxe, La Tour-du-Pin, France
 3) San Francisco (El Tecolote), Mexico
 4) Ex-Hacienda San Francisco Cuexcomatepec, Mexico
 5) San Francisco el Naranjo, Mexico
 6) El Paraíso (San Francisco), Mexico
 7) San Francisco El Alto, Guatemala
 8) San Francisco el Rincón, Mexico
 9) San Francisco El Alto, Guatemala
10) Ejido San Francisco, Mexico
```

[with a focus point in SF and comma](http://pelias.github.io/compare/#/v1/search%3Fpoint.lon=-122.431272&point.lat=37.778008&text=equinox,%20san%20francisco):

```
 1) Equinox, London, England, United Kingdom
 2) Equinox, Castelmassimo, Italy
 3) Equinox, New Haven, CT, USA
 4) Equinox, Zürich, Switzerland
 5) Equinox, Washington, District of Columbia, USA
 6) Equinox, Madison, WI, USA
 7) Equinox, Bristol, England, United Kingdom
 8) Equinox, Manhattan, New York, NY, USA
 9) Equinox, Oostvoorne, Netherlands
10) Equinox, Paris, France
```

[focus point in SF and just `equinox`](http://pelias.github.io/compare/#/v1/search%3Fpoint.lon=-122.431272&point.lat=37.778008&text=equinox):

```
 1) Equinox, London, England, United Kingdom
 2) Equinox, Castelmassimo, Italy
 3) Equinox, New Haven, CT, USA
 4) Equinox, Zürich, Switzerland
 5) Equinox, Washington, District of Columbia, USA
 6) Equinox, Madison, WI, USA
 7) Equinox, Bristol, England, United Kingdom
 8) Equinox, Manhattan, New York, NY, USA
 9) Equinox, Oostvoorne, Netherlands
10) Equinox, Paris, France
```

**Comment by missinglink** [comment]
it looks like this is both an `input parsing` and a `query logic` issue.

```
/v1/autocomplete?point.lon=-122.431272&point.lat=37.778008&text=equinox, san francisco

 1)	Equinox Sports Club, San Francisco, CA, USA
 2)	Equinox Fitness, San Mateo, CA, USA
 ...
```

**Comment by trescube** [comment]
libpostal gets this correct:

```> equinox san francisco

Result:

{
  "house": "equinox",
  "city": "san francisco"
}```

**Comment by dianashk** [comment]
Looks like all the example queries are not setting the focus point parameter correctly. It should be `focus.point.[lat/lon]` and not just `point.[lat/lon]` as we have it above. It improves things in some of the cases, but still doesn't work for all of them.

**Comment by dianashk** [comment]
related to #564

**Comment by orangejulius** [comment]
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 

Autocomplete queries for [equinox san francisco](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=equinox%20san%20francisco) now return the gym!
![Screenshot_2019-10-03_15-56-57](https://user-images.githubusercontent.com/111716/66160081-5a872580-e5f7-11e9-9e20-5b764a741e28.png)
