### ISSUE TITLE
Update all repositories to specify pelias- NPM dependencies more precisely

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#366]
Pelias is made up of numerous [NPM](https://www.npmjs.com/) packages and many of those packages depend on other pelias packages. Right now we're a bit inconsistent with exactly how we specify what versions of those packages are acceptable, but we've been trending towards using [caret ranges](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004).

## What are caret ranges?

A version specifier like `^1.2.3` will accept any version equal to or greater than `1.2.3` but less than `2.0.0`. So basically the major version (see [semver.org](http://semver.org/) for the full details on semver) has to be `1`, and it has to be at least as new as `1.2.3`.

This is nice because when `1.2.4` or `1.3.0` are published, the package will pick it up without any work or code changes on our part.

## Problems with caret ranges

While caret ranges cut down on bookkeeping for all but major versions (which are defined to be breaking changes that require more work to accommodate), it means it's hard to control when new packages go out to production. If we spend a week verifying a set of changes on prod_build, and then deploy a new version of a packages right before sending that code to production, that package will go right to production, without any intermediate testing.

## Possible solutions

We want to move to something a bit more precise. Since we use the amazing [Greenkeeper](https://greenkeeper.io/) to automatically generate pull requests when new packages are released, we can easily ensure that every package update is tracked in git. The only question is whether we want to allow for silent patch version (bug fix) updates (via [tilde ranges](https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1)), or require _all_ updates to be explicitly accepted with a pull request.

Once we've decided, we should go through all our active repositories in the pelias Github org, and update both the version number and version specifier of each package.

## What to change

Some packages simply list the [latest](https://github.com/pelias/schema/blob/master/package.json#L41) version of another package. We should replace these with exact versions.

Some packages specify an older version, because of the flexibility of caret ranges. For example, pelias-wof-admin-lookup [depends on](https://github.com/pelias/wof-admin-lookup/blob/master/package.json#L24) pelias-wof-pip-service `^1.2.0`, but the latest version is [1.6.1](https://www.npmjs.com/package/pelias-wof-pip-service). In addition to switching to tilde ranges or exact versions as we decide, we should update the version numbers to represent what is currently latest.

**Comment by dianashk** [comment]
@orangejulius, this is a great breakdown of the issue. Thank you for taking the time to formulate and write it up. I'd love to see us use explicit version numbers because it's still relatively subjective what constitutes a minor change or bug fix and given the complexity of our system it's often hard (if not impossible) to account for all the implications a change will have on the rest of the system. Forcing the updates means that the dependency graph is much more visible. It also forces rerunning of all the tests in all the places a module is used to ensure compatibility. 

That's my $0.02 and I'd love to hear what others think is the right approach. I wonder if any of our external contributors and followers would kindly share their experiences with semantic versioning in node.js. The system we choose to adhere to will have a significant impact on their usage of our software.

**Comment by orangejulius** [comment]
Okay, so for `pelias-` packages, we'll use exact versions.

Do we want to change or standardize on anything for external NPM dependencies? Right now we're using a bit of everything, but have been trending towards silently accepting minor and patch releases (by using caret ranges)

**Comment by orangejulius** [comment]
Here's (I think) the full list of our repositories that should be checked for correct version specifiers:

https://github.com/pelias/acceptance-tests
https://github.com/pelias/address-deduplicator
https://github.com/pelias/admin-lookup
https://github.com/pelias/api
https://github.com/pelias/compare
https://github.com/pelias/config
https://github.com/pelias/dbclient
https://github.com/pelias/demo
https://github.com/pelias/fuzzy-tester
https://github.com/pelias/fuzzy-tests
https://github.com/pelias/geonames
https://github.com/pelias/loadtest
https://github.com/pelias/logger
https://github.com/pelias/model
https://github.com/pelias/openaddresses
https://github.com/pelias/openstreetmap
https://github.com/pelias/pbf2json
https://github.com/pelias/pelias
https://github.com/pelias/pelias-dashboard
https://github.com/pelias/pelias-doc
https://github.com/pelias/polygon-lookup
https://github.com/pelias/query
https://github.com/pelias/schema
https://github.com/pelias/text-analyzer
https://github.com/pelias/vagrant
https://github.com/pelias/whosonfirst
https://github.com/pelias/wof-admin-lookup
https://github.com/pelias/wof-pip-service

**Comment by orangejulius** [comment]
All done!

**Comment by orangejulius** [comment]
@missinglink now that we use (and strongly suggest everyone else use) docker images for deployments, the hidden danger of not using exact versions for pelias packages is mitigated. To avoid having to do _lots_ of merging of pelias packages going forward, what if we re-evaluated using carat ranges for our own packages

**Comment by orangejulius** [comment]
Update: We are going to use carat ranges for all our Pelias NPM dependencies.

Note: anyone who is deploying Pelias and is not creating some sort of stable build artefact (like an archive file or Docker image) which can be reliably deployed to a production environment, I'd advise you start doing that now. With this change, there's a chance that bad submodules within Pelias could instantly break your production build in a way that's hard to track down and revert from.

Let us know if you need help getting set up with our docker images which won't be susceptible to this problem.
