### ISSUE TITLE
Can't use autocomplete API in Ember app

### ISSUE THREAD

**Issue by allthesignals** [pelias/pelias#367]
Hello, I'm getting this error:
`XMLHttpRequest cannot load https://search.mapzen.com/v1/autocomplete?text=Boston&api_key=[mykey]. Request header field X-CSRF-Token is not allowed by Access-Control-Allow-Headers in preflight response.`

Here's the request header Ember generates (I think):

```
OPTIONS /v1/autocomplete?text=Boston&api_key=[mykey] HTTP/1.1
Host: search.mapzen.com
Connection: keep-alive
Access-Control-Request-Method: GET
Origin: http://lvh.me:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
Access-Control-Request-Headers: accept, x-csrf-token
Accept: */*
Referer: http://lvh.me:5000/developments/?placeSearch=Boston
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
```

I'm using AJAX directly in my Ember app, although it seems to be using OPTIONS. 

Here's my AJAX call function, which uses jQuery but an Ember addon wraps it for extended functionality (Using jQuery directly produces the same issue):

```
  autocompleteSearch: function() {
    let place = this.get('placeSearch');

    return this.get('ajax').request('https://search.mapzen.com/v1/autocomplete', {
      method: 'GET',
      dataType: "json",
      data: {
        "text": place,
        "api_key": "[mykey]"
      }
    });
}
```

**Comment by missinglink** [comment]
hi @allthesignals I haven't used Ember before but I suspect it's due to how it's executing a Cross-Domain request.

There's a section in our docs with some examples for jquery and angular https://mapzen.com/documentation/search/use-cors/ and I added a link to a jsfiddle app for each.

[This post](http://discuss.emberjs.com/t/ember-data-and-cors/3690/2) I found seems to suggest you can add the following options to your `request` config to enable `CORS` support:
```
crossDomain: true,
xhrFields: {withCredentials: true}
```

Sorry I didn't have time to test it, please let me know if it works and I will update our docs.

**Comment by missinglink** [comment]
The `OPTIONS` request is made before each `CORS` request in order to check the `Access-Control*` headers:

```
$ curl -v -X OPTIONS http://search.mapzen.com
* Rebuilt URL to: http://search.mapzen.com/
*   Trying 151.101.36.70...
* Connected to search.mapzen.com (151.101.36.70) port 80 (#0)
> OPTIONS / HTTP/1.1
> Host: search.mapzen.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Content-Length: 0
< Date: Tue, 05 Jul 2016 14:19:22 GMT
< Connection: keep-alive
< Cache-Control: public, max-age=120
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: GET, HEAD
< Access-Control-Allow-Headers: Authorization, Content-Type, Accept, Origin, User-Agent, Cache-Control, Keep-Alive, If-Modified-Since, If-None-Match, X-Requested-With
< Access-Control-Expose-Headers: Content-Type, Cache-Control, ETag, Expires, Last-Modified, Content-Length
< X-Served-By: cache-ams4442-AMS
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1467728362.539653,VS0,VE363
< 
* Connection #0 to host search.mapzen.com left intact
```

They are definitely set up correctly as it's working in both jQuery and Angular... must be a client config issue.

**Comment by allthesignals** [comment]
Hi @missinglink,

I definitely figure it's something to do with my client config, I'm just struggling to understand which layer to troubleshoot. Thank you for the suggestion, however, it seems to return this response:

```
XMLHttpRequest cannot load https://search.mapzen.com/v1/autocomplete?text=Boston&api_key=[api-key]. Response to preflight request doesn't pass access control check: A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://lvh.me:5000' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.
```

**Comment by missinglink** [comment]
hmm... what about this? http://stackoverflow.com/a/29950741

I don't think changing `Access-Control-Allow-Origin: *` is an option

**Comment by missinglink** [comment]
maybe this? http://emberigniter.com/modify-content-security-policy-on-new-ember-cli-app/

the author of the previous response says `This is a CSP issue not CORS`, I'm not sure what that means, and sounds like it's an Ember-specific function; which might be the source of your problems.

does the chrome inspector tell you the source file and line number that triggered the error?

**Comment by allthesignals** [comment]
Thanks for looking into it. I tried updating the CSP, but the error doesn't seem to be related to that (those errors usually explicitly complain about CSP). I'll ping some Ember people. For reference, here's the cURL of what Ember is sending:

```
curl 'https://search.mapzen.com/v1/autocomplete?text=Boston&api_key=search-5f1bwRf' -X OPTIONS -H 'Pragma: no-cache' -H 'Access-Control-Request-Method: GET' -H 'Origin: http://lvh.me:5000' -H 'Accept-Encoding: gzip, deflate, sdch, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: http://lvh.me:5000/developments/?placeSearch=B' -H 'Connection: keep-alive' -H 'Access-Control-Request-Headers: accept, x-csrf-token' --compressed
```

**Comment by missinglink** [comment]
ok, good luck, sorry I couldn't help.

using the jsfiddles for [jquery](http://jsfiddle.net/missinglink/fb6p0par/) and [angular](http://jsfiddle.net/missinglink/nchh8a9j/) should be useful for comparison.

let us know when you figure it out :)

**Comment by orangejulius** [comment]
Since this is a configuration issue, I'm going to mark it closed.
