### ISSUE TITLE
Q : Fuzziness and Phonetic matching during search ?

### ISSUE THREAD

**Issue by christopheblin** [pelias/pelias#369]
Hi,

I'd like to know if it is possible to support fuzziness and/or phonetic matching during search, preferably when the exact search does not match enough results.

I'd envisage a request parameter like fuzziness=true&phonetic=true&size=10 meaning that if there is not 10 results without fuzziness or phonetic then use them to complete the results (first fuzzinees and then phonetic).
This is particulary usefull for streets named after a person with a "difficult" name like "roosevelt" which can be typed as "rousevelte" (in french, pronounciation is the same for both words but fuzziness is also ok)

I know this is well supported in elasticsearch so maybe this is doable in pelias ...

Thanks for any inputs,

**Comment by orangejulius** [comment]
Hey @christopheblin,
Thanks for the question. We do intend to support fuzzy matching or typo correction, and already we have decent support, although not enough yet for your example. Searches for [some typos](http://pelias.github.io/compare/#/v1/search%3Ftext=rosevelt%20island), but [not others](http://pelias.github.io/compare/#/v1/search%3Ftext=rosevelt%20island) will return the [intended result](http://pelias.github.io/compare/#/v1/search%3Ftext=roosevelt%20island).

Right now our plan is that this always continues to be built in and there probably won't be flags needed to enable it. We're working on a [big upgrade](https://github.com/pelias/pelias/issues/152) to move to using [libpostal](https://github.com/openvenues/libpostal) to do a lot of our query parsing, which will enable us to return drastically better results. This will include not just more frequently returning the "right" results, but also excluding the "wrong" ones, which we can't really do now. As a result of that we're also discussing what to do with the size parameter. It might go away completely.
