### ISSUE TITLE
Admin areas with large bounding boxes can display poorly on leaflet maps

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#370]
Many admin areas, like the [Tokyo _region_](https://whosonfirst.mapzen.com/spelunker/id/85672817/#5/31.541/146.689) (but not the locality for the city of [Tokyo](https://whosonfirst.mapzen.com/spelunker/id/102031307/)), and [San Francisco](https://whosonfirst.mapzen.com/spelunker/id/85922583/#10/37.7850/-122.7278) cover very large regions beyond what we typically think of for that place.

After https://github.com/pelias/whosonfirst/pull/95, we use the `label centroid` when it exists, and indeed it does exist in all of these cases, which helps put the actual _point_ returned in Pelias results where humans expect, rather then in the mathematical center of a large area, but the bounding box itself is still very large. Leaflet uses this bounding box to choose the correct zoom level and still seems to center itself on the centroid of that bounding box.

Here's an example of how things look when searching for Tokyo and selecting the first result (the region):
![screenshot_2016-07-10_15-33-41](https://cloud.githubusercontent.com/assets/111716/16715636/e6db932c-46b3-11e6-8269-31d6bd9252d7.png)

And here's what happens with the second result (the much smaller bounding box locality), which works as expected:
![screenshot_2016-07-10_15-35-41](https://cloud.githubusercontent.com/assets/111716/16715647/1258824e-46b4-11e6-87eb-0201f58f1cf2.png)

## Possible solutions

So this is a combination of deduplication, display, and data.

We could...

### Improve deduplication to remove results for parent regions of the same name like this from search results
The Tokyo region, the county of San Francisco, the [county](https://whosonfirst.mapzen.com/spelunker/id/102063945/) and [region](https://whosonfirst.mapzen.com/spelunker/id/85682499/) of Berlin, etc are not really things most people search for, and are probably not often wanted in search results. We could possibly figure out how to remove them, although maybe not in all cases. This would also not work for San Francisco, where the city, which people do want, is the one with the unexpectedly large bounding box.

### Create a `label bounding box` property in WOF

This could be used to make more "human friendly" bounding boxes for records where the actual bounding box doesn't match up with what people normally expect. Downsides: requires us to manually edit all the records that we don't think are right, doesn't allow the "real" bounding box to be returned in Pelias results unless we send both, and in that case more client logic to use the right one is required.

### Change how we display these results in Leaflet

It's not clear how we'd do this, since the data is currently correct, but perhaps this in combination with the `label bounding box` could work.

This touches a lot of teams so...cc @dianashk, @trescube, @nvkelso, @thisisaaronland, @louh, would love feedback from all of you.

## Pelias Team Tool improvements

As an aside, note that our compare tool [does not](http://pelias.github.io/compare/#/v1/search%3Fsize=2&text=tokyo) take bounding boxes into account, so we were not aware of this issue. We should probably update the compare tool to use leaflet or perhaps mapzen.js exactly as most leaflet maps would, so we can catch this issue and others like it.

**Comment by nvkelso** [comment]
Good summary of options!

I favor curating a (small set of) `label bounding box` in Who’s On First
for these types of situations.

If the curated label bounding box is available for a feature then Pelias
would prefer it, else the basic math bbox (included on all features) would
be used.

**Comment by nvkelso** [comment]
Filed: https://github.com/whosonfirst/whosonfirst-data/issues/361

**Comment by dianashk** [comment]
@orangejulius, this write-up is fantastic! :rocket: :fireworks:

Also thanks @nvkelso for such a quick response. #teamwork

**Comment by orangejulius** [comment]
We've pushed the fix for this to production, and both Tokyo and San Francisco now look very nice in leaflet maps! :tada:
