### ISSUE TITLE
Check for housenumber === street in openaddresses imports

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#371]
OpenAddresses has problematic data, see [here](https://github.com/openaddresses/openaddresses/issues/1841), and we currently import as is. This results in a less than awesome experience when searching for stuff like [this](http://pelias.github.io/compare/#/v1/search%3Ftext=4th%20street).

Maybe we can at least check for this common case where the housenumber matches the street name and skip those addresses?

cc @trescube

**Comment by orangejulius** [comment]
It looks like the known instances of this phenomenon have been fixed in OA data. If anyone sees this again, feel free to re-open.
