### ISSUE TITLE
Improve admin hierarchy [PL-GG07]

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#38]
Make improvements to the admin hierarchy to ensure accurate and consistent results	.

related issues:
  * https://github.com/pelias/admin-lookup/issues/1

**Comment by dianashk** [comment]
Severyn is working on functional tests to quantify and verify "accurate and consistent"

**Comment by sevko** [comment]
This is essentially done, since we're using it in `pelias-openaddresses` and it's about to land in `pelias-openstreetmap`.
