### ISSUE TITLE
Proposal: use admin data from OA and OSM when there is none from Who's on First

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#389]
We frequently find that results returned from Pelias are missing admin fields (usually locality), when the underlying dataset (OpenAddreses or OpenStreetMap) has those fields. Some examples are https://github.com/pelias/pelias/issues/167, https://github.com/pelias/pelias/issues/269, and https://github.com/pelias/pelias/issues/387. We should consider using the admin data from OSM/OA when it's present, if nothing useful was returned from WOF.
## Reasons to not make this change
- Existing code is simple and straightforward, this would have to be implemented in each importer
- Inconsistent results might be returned for nearby records, depending on the whims of OSM contributors and the boundaries of data in WOF
## Reasons to make the change
- Fewer records would have no admin info
- It could be done even if admin-lookup is disabled
- Users would see more of the data from the underlying dataset that they expect to be there

I'm not 100% for making this change, but as more people report issues like the ones above, its starting to feel more and more helpful.

**Comment by dianashk** [comment]
There has been a trend of reports recently, which is interesting. However I'm also not 100% sold on this approach. As a first step, maybe we could log all the places where OSM record has locality data but admin-lookup fails to return a matching result. If the problem is very widespread we can think about possible solutions.

It is very important to us to also have the parent ids so that users can traverse the hierarchy and retrieve additional data about the parents. If we were to just grab the OSM tags we wouldn't have access to that type of data. 

Another option for the future, is to consider storing all the source properties in the record, much like WOF does. So the user could choose where to grab the data from, the original source or the curated Pelias properties.

**Comment by rowanwins** [comment]
Just my two cents as a someone just doing some initial investigation into Pelias (which I think is great btw!)...

1. This is probably completely obvious but I'll say it anyway - OSM & OA are very different datasets, hence I'd tackle them separately and the answer doesn't need to be the same for both of them. 

2. Building on @dianashk suggestion of retaining source properties (I like this idea at least for OA which is quite simple in it's data model) - at the moment it doesn't feel entirely clear what is from the source and what is derived from WOF, I wonder if there is a way to provide a slightly clearer distinction in the feature properties, for example...
````
{
    "type": "Feature",
    "geometry": {
    "type": "Point",
    "coordinates": [
        149.101575,
        -35.395275
    ]
},
"properties": {
    "id": "au/countrywide:3454353",
    "gid": "openaddresses:address:au/countrywide:3454353",
    "layer": "address",
    "source": "openaddresses",
    "source_id": "au/countrywide:3454353",
    "confidence": 0.95,
    "label": "10 Luffman Circuit, Gilmore, Australian Capital Territory, Australia"
    "sourceProps": {
        "name": "0 Luffman Circuit, Gilmore",
        "housenumber": "10",
        "street": "Luffman Circuit,",
        "postalcode": "2905",
    },
    "derivedProps": {
        "country": "Australia",
        "country_gid": "whosonfirst:country:85632793",
        "country_a": "AUS",
        "region": "Australian Capital Territory",
        "region_gid": "whosonfirst:region:85681493",
        "localadmin": "Gilmore",
        "localadmin_gid": "whosonfirst:localadmin:404550133",
        "locality": "Gilmore",
        "locality_gid": "whosonfirst:locality:101938911",
        "neighbourhood": "Gilmore",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85773365"
    }
}
}
`````

3.At the moment it feels like Pelias is very reliant on WOF, which isn't necessarily bad, but it does seem like another layer of complexity that may not be required when source datasets contain some of the required info, having said that I'm sure I'm still a bit naive in what WOF is bringing to the table :)

Cheers
Rowan

**Comment by orangejulius** [comment]
It's been a while since there's been any activity on this particular issue, but we frequently get questions regarding this proposal.

While it sounds like a nice way to quickly add missing administrative data to records imported into Pelias, supporting additional avenues for bringing in this data other than admin lookup would create a lot of problems.

Pelias relies on the fact that administrative data is not just a string with the name of the city, but instead the ID of another record that includes additional information like alternate names, translations, and more. A lot of the powerful features in Pelias would go away without that link.

Additionally, supporting multiple code paths for administrative data would increase the complexity of Pelias. It would be harder and slower to develop new features and fix bugs.

So at this point, I feel confident enough saying we won't ever do this to close this issue.

In the short term, the best way to improve administrative data in Pelias is simply to improve data in WOF.

However, what we _are_ moving towards in the future is a powerful [spatial service](https://github.com/pelias/spatial) that supports more than just WOF out of the box. This would provide a way to use administrative data from OSM or any other source. Stay tuned for more developments there.
