### ISSUE TITLE
Support postal cities and census designated places

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#396]
Places in less populated areas outside the bounds of a larger nearby city often use that city in their proper address. This makes sense, since the city might be the only place with a post office, and how else would people get letters?

However, it presents a problem for us, since our admin lookup reverse geocoding assumes strict definitions for cities. If a document has a latitude/longitude outside the boundary of a `locality`, it's not part of that place. It turns out this isn't really how the world works.

Many countries have databases (that involve postal codes, usually), to determine what city a place should _actually_ use in an address. Who's on First has a [ticket](https://github.com/whosonfirst-data/whosonfirst-data/issues/202) to add these sources, and if they do, we should use them as well.

We should also explore alternative sources of this data.

## Related issues

https://github.com/pelias/pelias/issues/269
https://github.com/pelias/pelias/issues/387
https://github.com/pelias/pelias/issues/184
https://github.com/pelias/pelias/issues/167

**Comment by orangejulius** [comment]
Time for an update, as there has been lots of activity linking to this issue, but none on the issue itself:

The postal cities problem is still a problem. We plan to fix it with a combination of using any administrative data sent along with address records in OpenAddresses (and possibly OSM). We'll use Placeholder at index time to convert the locality string into a Who's on First record. This ensures that all our administrative records have Who's on First IDs, can be translated to many languages, etc.

For places where OA data isn't enough, especially the United States, we'll look into mapping to city names via FIPS codes or postal codes.

**Comment by orangejulius** [comment]
Here is a collection of example cases from various linked issues, and their current status

| link | status |
| ---   | ----   |
| [/v1/search?text=7030 broomshedge trl, winter garden FL 34787](http://pelias.github.io/compare/#/v1/search%3Ftext=7030%20broomshedge%20trl,%20winter%20garden%20FL%2034787) | requires https://github.com/pelias/schema/pull/357 and https://github.com/pelias/wof-admin-lookup/pull/232 to be fixed |
| [/v1/search?text=507 POWERS AV, port orange,fl 32127](http://pelias.github.io/compare/#/v1/search%3Ftext=507%20POWERS%20AV,%20port%20orange,fl%2032127) | fixed |
| [/v1/search?text=hobrovej 18, 9510, denmark](http://pelias.github.io/compare/#/v1/search%3Ftext=hobrovej%2018,%209510,%20denmark) | not fixed (https://github.com/pelias/pelias/issues/387)
| [/v1/search?text=15364 Kensington Park Dr, Woodbridge, VA](http://pelias.github.io/compare/#/v1/search%3Ftext=15364%20Kensington%20Park%20Dr,%20Woodbridge,%20VA) (and all others from https://github.com/pelias/pelias/issues/607) | not fixed, even with https://github.com/pelias/wof-admin-lookup/pull/232 |
| [/v1/search?text=2801 fieldstone ct, orlando, fl](http://pelias.github.io/compare/#/v1/search%3Ftext=2801%20fieldstone%20ct,%20orlando,%20fl) | fixed with https://github.com/pelias/wof-admin-lookup/pull/232 |
| [/v1/search?text=304 bloomingfield drive, brandon, FL 33511](http://pelias.github.io/compare/#/v1/search%3Ftext=304%20bloomingfield%20drive,%20brandon,%20FL%2033511) | fixed with https://github.com/pelias/wof-admin-lookup/pull/232 |
| [/v1/search?text=2807 Southeast DELMAR Street, stuart, fl 34997](http://pelias.github.io/compare/#/v1/search%3Ftext=2807%20Southeast%20DELMAR%20Street,%20stuart,%20fl%2034997) | fixed with https://github.com/pelias/wof-admin-lookup/pull/232 |

**Comment by b-may** [comment]
Did something change with the postal cities fix? It appears to me that the following tests do not work right anymore. 

http://pelias.github.io/compare/#/v1/search%3Ftext=440%20S%20Combee%20Rd,%20Lakeland,%20FL%2033801

http://pelias.github.io/compare/#/v1/search%3Ftext=440%20S%20Combee%20Rd,%20Lakeland,%20FL%2033801

And here's another example that you would think should work, but doesn't. 

https://pelias.github.io/compare/#/v1/search%3Ftext=6701%20david%20barron%20dr,%20plant%20city%20fl

However, this works - https://pelias.github.io/compare/#/v1/search%3Ftext=6701%20david%20barron%20dr%2033567

**Comment by orangejulius** [comment]
@b-may the work from https://github.com/pelias/wof-admin-lookup/pull/232 is not yet enabled on geocode.earth, we're waiting on a couple fixes before turning it on. My comment above comes from looking at a test build with it enabled. It's coming soon though.

**Comment by orangejulius** [comment]
Hi all!

We have now enabled postal cities by default in pelias/config#129 :tada: 

New docker images will be generated shortly, for anyone running directly from `git` we recommend a `git pull` and `npm install`.

Let us know how it all works out :)
