### ISSUE TITLE
Proposal: Remove support for Node.js v5

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#401]
Node.js's [release schedule](https://github.com/nodejs/LTS#lts_schedule) alternates between even  and odd numbered releases, spaced 6 months apart. Even numbered releases get  have 18 months of backported features, follwed by 12 months of maintenance support to fix bugs and security vulnerabilities after the next version has come out. Odd numbered releases get none of that: they are no longer maintained as soon as the next version comes out.

As of this writing, Node.js v6 has been released, so v5 has officially reached [end of life](https://github.com/nodejs/LTS/issues/113#issuecomment-229575291).

In theory, I think this means no one should be using Node.js 5 if they want to ensure a bug and security vulnerability free experience. However, the Node.js release cycle is relatively new, so I think no one really knows what it _actually_ means.

For us removing Node.js 5 would mostly be helpful in that it would reduce the time our TravisCI builds take by 25%! For that reason alone I feel like we should get rid of it. I'll hapilly remove it as part of https://github.com/pelias/pelias/issues/334.

**Comment by missinglink** [comment]
:+1: should we keep it in the `known_failures`?

**Comment by orangejulius** [comment]
If we do that we don't get the reduction of number of jobs launched on Travis.
