### ISSUE TITLE
Investigate using Amazon Elasticsearch offering

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#402]
Look into available options for Amazon ES and see if they provide enough control to make using them realistic. Some considerations:

- would we be able to install plugins such as ICU on all machines in a cluster?
- is it cost-effective compared to rolling our own (take into account the marvel and kibana setups which we currently don't support)?

**Comment by dianashk** [comment]
Look into this for Q4

**Comment by orangejulius** [comment]
I spent about a day looking into this. Short answer: it works but is a little slower.

The details:

## Starting the cluster

This is pretty easy, and allows you to quickly configure a few basics like how many machines of what type should be used. There isn't much advanced configuration but you can do things like enable master nodes, which would be important for a production environment. It took about 15 minutes to bring up the cluster once I clicked go.

## Initial inspection

I first just took a look around. It looks like a normal Elasticsearch cluster, although one interesting change is that the cluster is accessed over port 80, not the 9200 default of Elasticsearch. I had to modify our chef scripts to allow for this change, but other than that it looks basically like an ES cluster.

## Running a full pelias planet build

There was an issue running the pelias/schema creation script. Apparently the ES cluster does not report plugins in the same way as a standard ES cluster. Support for custom plugins is disabled, which makes sense. Fortunately we only use the `icu` plugin, which is enabled by default in the Amazon service, so I commented that out and was able to run a build just fine.

The build completed in 1 day, 6 hours, 55 minutes ( our latest build in prod_build took 1 day, 4 hours, 49 minutes), so similar performance.

When the build was done all our acceptance-tests passed, so everything looks good on general functionality!

## Performance

I loadtested the cluster and compared it to tests I recently ran on our dev cluster, which has the same configuration (4x r3.xlarge machines). Performance was possibly a little worse, but [mostly similar](https://docs.google.com/spreadsheets/d/1uNXwou4MD3HcsfJrceL5QaVNxXNzMlv05_qxMaKbF1o/edit#gid=399821816)
![image 1](https://cloud.githubusercontent.com/assets/111716/19662362/1c2c107a-9a05-11e6-8d97-b008b6eea85a.png)
![image 2](https://cloud.githubusercontent.com/assets/111716/19662364/1eb6e766-9a05-11e6-9e52-ae457604b51c.png)

## Resizing
I tested changing the cluster from 4x r3.xlarge, to 5x r3.xlarge. We use 5 machines in prod_build so this would also mirror one of our existing configurations. Here's where things got weird. After changing the config, which was easy in the web interface, nothing happened for 15 minutes. Then, suddenly, the cluster started reporting it had 9 machines! Apparently Amazon's system for scaling is to spin up all new nodes, transfer _all_ the shards, and then shut down the old, idle machines. This feels pretty wasteful, as a lot more data has to move around. It took about 25 minutes before any shards were completely on a new machine. This means that in a production environment it would take 25 minutes to scale the cluster to handle higher load, which is a bit long. Our production environment can probably do it in 15.

It took about an hour and 20 minutes for the full scale up to complete!

## More loadtesting

I re-ran the same loadtest to see if the cluster now performed similarly to prod_build. It didn't even come close, and was only [marginally faster than before](https://docs.google.com/spreadsheets/d/1uNXwou4MD3HcsfJrceL5QaVNxXNzMlv05_qxMaKbF1o/edit#gid=1407639270).
![image 4](https://cloud.githubusercontent.com/assets/111716/19662513/dad8ea84-9a05-11e6-98fa-0adb3d360090.png)
![image 3](https://cloud.githubusercontent.com/assets/111716/19662514/dad90000-9a05-11e6-9b02-2187d4cf3b9c.png)

## Conclusion
While we don't quite support Amazon's Elasticsearch service out of the box, we easily could if it was required. Everything works more or less the same, but performance is a bit worse. It only makes sense if taking an absolute hands off approach to managing Elasticsearch is more important than cost or performance.
