### ISSUE TITLE
Remove support for Node.js 0.12

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#404]
Node.js 0.12 is pretty old, and will no longer be receiving _any_ updates after [December 31st, 2016](https://github.com/nodejs/LTS#lts_schedule) (this year!). Node.js 0.12 does not support any ES2016 features, and runs on a woefully old version of the V8 interpreter, so it's quite a bit slower than newer node versions. For all these reasons we want to be able to drop support for it in a clear and unambiguous way.

Now that https://github.com/pelias/pelias/issues/334 is finished we can choose a day to stop supporting Node 0.12. I propose August 31, 2016.

On that day we should:
 - [x] Update all documentation including repository readmes, installation docs, etc to note that Node4+ is required
 - [x] Remove Node 0.12 from all TravisCI tests
 - [x] Ensure all packages have an `engines` section requiring Node 4+ ([example for Node 0.12+ in Who's on First](https://github.com/pelias/whosonfirst/blob/master/package.json#L5))
 - [x] Put something about Node.js upgrades in the release notes
 - [x] Also do some other sort of notifying people using Pelias (that may not read Mapzen Search release notes) to let them know
 - [ ] Start using ES6 code if we want! :tada: 
 - [ ] Have a little party since we're finally free of old Node versions!

**Comment by dianashk** [comment]
https://github.com/pelias/pelias-doc/pull/158
