### ISSUE TITLE
Possible to make street types optional in search?

### ISSUE THREAD

**Issue by migurski** [pelias/pelias#405]
I’m searching for [30 W 26th St, Manhattan](http://pelias.github.io/compare/#/v1/search%3Ftext=30%20W%2026th%20St,%20Manhattan). It works fine but if I omit the "Street" (e.g. "30 W 26th Manhattan"), I get no results.

**Comment by missinglink** [comment]
This behaviour is likely to change soon, I'm hoping to refactor the behaviour for the interpolation milestone in a way that targets the road network first and then the house number second.

As a result we'll need to loosen the restrictions on which tokens are mandatory and which are optional.

The street name suffix is a tricky one as 'w 26' could potentially mean a lot of different things, we tend to pair street name tokens and consider 'main st' and 'main ave' as different terms in most contexts (but not all).

Will let you know, for now I would encourage users to use fully qualified street names where available.

**Comment by trescube** [comment]
While that work will work great for 5box geocoding, libpostal currently
doesn't parse it correctly without the street type:

> 18 Dickerson Shelter Island

Result:

{
  "house_number": "18",
  "suburb": "dickerson",
  "city": "shelter island"
}

Let's bring it up with Al.  I can't think of an example where a house
number means anything without the context of a street so we can probably
write the query to treat the "suburb" field as a street no street is
identified.  That should work in combination with Peter's work.

Regards,
Stephen

**Comment by migurski** [comment]
Thanks, makes sense. I look forward to seeing this token as optional.

**Comment by orangejulius** [comment]
As of https://github.com/pelias/schema/pull/310, street types are optional, so queries like [/v1/search?text=30 W 26th, Manhattan, new york](http://pelias.github.io/compare/#/v1/search%3Ftext=30%20W%2026th,%20Manhattan,%20new%20york) will now return results.

Note that many more matches may result, a search for [/v1/search?text=30 W 26th, Manhattan](http://pelias.github.io/compare/#/v1/search%3Ftext=30%20W%2026th,%20Manhattan), for example, returns results from all over the USA.
