### ISSUE TITLE
Broken link on pelias.io for Mapzen search documentation

### ISSUE THREAD

**Issue by haleystorm** [pelias/pelias#407]
Hey team! 

I was reading about your awesome geocoding engine when I noticed broken link.

broken link
https://github.com/pelias/pelias-doc/blob/master/index.html

my guess at the correct link
https://github.com/pelias/pelias-doc/blob/master/index.md

**Comment by dianashk** [comment]
Thanks for catching this! If you could also provide the link from which you saw this problem it would be really helpful. We really appreciate it. :)

**Comment by haleystorm** [comment]
http://pelias.io/

**Comment by dianashk** [comment]
Ah found it! Thanks again. Will fix asap.
