### ISSUE TITLE
Simplify API [PL-API01]

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#41]
* Do we need suggest and search?
* Can we drop suggest?
* Investigate ngram solution. Decided if we should wait for ES or implement ngrams.

related issues:
* https://github.com/elasticsearch/elasticsearch/issues/8909#issuecomment-74498046

**Comment by amnesia7** [comment]
@dianashk I assume you're aware of http://github.com/komoot/photon which is an autocompleter with a single end-point for calling the search/suggest API and from what I've found this provides a better and more consistent set of results returned when compared with both /search and /suggest which also seem to differ greatly between resultsets.

**Comment by dianashk** [comment]
Thanks @amnesia7. We are aware of photon. It's a great project. There is a breakdown of how pelias and photon compare [here](https://github.com/pelias/pelias/issues/92). Pelias is still relatively new and is in Beta. We are actively working towards major improvements, such as consolidating the suggest and search endpoints behind the scenes to yield more consistent results.

If you're finding specific bugs/shortcomings please throw a github issue our way.
