### ISSUE TITLE
superseded WOF records showing up in search results

### ISSUE THREAD

**Issue by burritojustice** [pelias/pelias#413]
Hello!
---
#### Here's what I did :innocent:
I [searched for a place](https://mapzen.com/products/search/?query=54%20Tiffany%20Avenue%2C%20San%20Francisco%2C%20CA%2C%20USA&endpoint=place&gid=openaddresses%3Aaddress%3Aus%2Fca%2Fsan_francisco%3A31899&selectedLat=37.74583&selectedLng=-122.42113&lng=-122.39199&lat=37.78822&zoom=12) and a superseded neighborhood showed up.

https://whosonfirst.mapzen.com/spelunker/id/85887469/#15/37.7437/-122.4199

Should have returned this:

https://whosonfirst.mapzen.com/spelunker/id/102112179/#15/37.7458/-122.4211

---
#### Here's what I got :scream_cat:

{
  "geocoding": {
    "version": "0.1",
    "attribution": "https://search.mapzen.com/v1/attribution",
    "query": {
      "ids": [
        {
          "source": "openaddresses",
          "layer": "address",
          "id": "us/ca/san_francisco:31899"
        }
      ],
      "private": false
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1472754102029
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.42113,
          37.745828
        ]
      },
      "properties": {
        "id": "us/ca/san_francisco:31899",
        "gid": "openaddresses:address:us/ca/san_francisco:31899",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us/ca/san_francisco:31899",
        "name": "54 Tiffany Avenue",
        "housenumber": "54",
        "street": "Tiffany Avenue",
        "postalcode": "94110",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "California",
        "region_gid": "whosonfirst:region:85688637",
        "region_a": "CA",
        "county": "San Francisco County",
        "county_gid": "whosonfirst:county:102087579",
        "locality": "San Francisco",
        "locality_gid": "whosonfirst:locality:85922583",
        "neighbourhood": "Transmission",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85887469",
        "label": "54 Tiffany Avenue, San Francisco, CA, USA"
      }
    }
  ],
  "bbox": [
    -122.42113,
    37.745828,
    -122.42113,
    37.745828
  ]
}
---
#### Here's what I was expecting :sparkles:

Return a record that is not superseded:

https://whosonfirst.mapzen.com/spelunker/id/85887469/#15/37.7437/-122.4199

---

**Comment by trescube** [comment]
The [flag](https://github.com/pelias/whosonfirst/blob/master/src/components/isActiveRecord.js#L9) that the Pelias WOF importer looks for is not present though other flags indicate that it is superseded.

**Comment by trescube** [comment]
In the original issue from @burritojustice, the WOF records have been swapped.  

This record is superseded:

https://whosonfirst.mapzen.com/spelunker/id/85887469/#15/37.7437/-122.4199

while this one is active:

https://whosonfirst.mapzen.com/spelunker/id/102112179/#15/37.7458/-122.4211

As you can see in the JSON blob, the superseded neighbourhood `Transmission` is being used instead of `La Lengua`.
