### ISSUE TITLE
Investigate why French postcodes are not found when searching by postcode only

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#415]
from: https://github.com/mapzen/leaflet-geocoder/issues/143

https://whosonfirst.mapzen.com/spelunker/id/421307215/#13/48.8869/2.3877 is not being found for the query `?text=75019`.

is this due to the `WOF` data not being imported or the query logic not matching it?

**Comment by orangejulius** [comment]
As far as I know, we have never had postalcodes imported as documents on their own in pelias, although we definitely should do it soon. I think the work would be very similar to the Who's on First venue importing, so it should be something we can tackle. We have lots of issues regarding this of course https://github.com/pelias/pelias/issues/111 https://github.com/pelias/pelias/issues/201 https://github.com/pelias/pelias/issues/396

**Comment by kazes** [comment]
Hi :) can you tell me if you can have a look at this in the next days please ? Or if I can be of any help maybe ? thanks !

**Comment by dianashk** [comment]
@kazes, we are still working hard to get the WOF venues importing into search service. Once that's done, we will tackle postcodes from WOF. Unfortunately, it will be longer than the next few days. 😞   We're aiming to have that work done by early-mid October.

**Comment by kazes** [comment]
That's alright, thank you :)

**Comment by kazes** [comment]
Hi, sorry to bother you again, did you have time to work on this issue please ? thanks !

**Comment by frontmodem** [comment]
Hello,
Any news for the implementation of a fix for this issue ?
Thanks for your feedback

**Comment by frontmodem** [comment]
Hello everyone,
@dianashk , Do you have any news for the implementation of a fix for this issue ?

Thanks for your feedback

**Comment by dianashk** [comment]
Hey all, sorry for lack of updates on this issue. We unfortunately haven't made much progress in the postal code functionality. We'll update this issue once we know more about when it might get done. 
Thanks for your patience and support.  :heart:

**Comment by kazes** [comment]
Thanks very much, I'll run a test in our app soon :)
