### ISSUE TITLE
Revisit API design [PL-API10]

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#42]
Revisit API design

**Comment by riordan** [comment]
same as pelias/pelias#41

**Comment by missinglink** [comment]
it would be nice to return the 'total matched results' despite the page length being set to 1-40, this is nice to have in order to derive a 'total pages' count and also for analytics, like 'how many mcdonalds in this bbox'

**Comment by riordan** [comment]
+1 to @missinglink's suggestion

I think you've stubbed out what that would/should look like quite nicely and opens up some more questions like:
- How would one paginate from those maximum number of results? Would they reformulate a query and ask for that total number of results?
- Is that a fundamentally different kind of question from Geocoding? It's certainly a kind of question that our dataset should be capable of answering.
- Would we be able to surface the match count without much of a performance impact?

**Comment by missinglink** [comment]
we get the total count for free, no additional logic would be required outside the code to expose it in the API
