### ISSUE TITLE
Searching for places with city returns no results

### ISSUE THREAD

**Issue by fahimk** [pelias/pelias#423]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I got :scream_cat:

https://search.mapzen.com/v1/autocomplete?layers=address&text=starbucks%20seattle

**Comment by orangejulius** [comment]
Hey @fahimk,
Thanks for reporting this. We've known about the [issue in general](https://github.com/pelias/pelias/issues/199) for a while. Right now our input parsing is very reliant upon commas to detect cities. So, [Starbucks, Seattle](http://pelias.io/compare/#/v1/autocomplete%3Ftext=Starbucks,%20seattle) works well.

Very soon, we'll be using [libpostal](https://github.com/openvenues/libpostal) to drastically improve our input parsing for the _search_ endpoint, but not for the autocomplete endpoint. We do intend to do some work to improve autocomplete too, but it [didn't make it into our Q4 goals](https://github.com/pelias/pelias/blob/32cc56815cb13a050c0a63960863b48a2b951f42/quarterly_goals/q4-2016.md), so it probably won't happen until early next year. Until then, commas are your friend.

**Comment by fahimk** [comment]
@orangejulius thanks for the response. Do you see any possible negative results that could happen if I just parse user input and put a comma between each word for every query?

**Comment by orangejulius** [comment]
That probably won't work :P Think of inputs like "penn station new york" or "seoul south korea". In general any time the name of the place, city, or country was more than one word it would not return what you want.

**Comment by rmglennon** [comment]
Updated example (via Desk 1230):

Autocomplete on "Jackson MS" or "Jackson Mississippi" returns various venue results and not the city name.

https://mapzen.com/search/explorer/?query=autocomplete&text=jackson%20ms

"properties": {
        "id": "6513937",
        "gid": "geonames:venue:6513937",
        "layer": "venue",
        "source": "geonames",
        "source_id": "6513937",
        "name": "Studio 6 Jackson Ms",
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Mississippi",

Results are as expected with those queries on /search, or with commas on /autocomplete.
https://mapzen.com/search/explorer/?query=autocomplete&text=jackson%2C%20ms

"properties": {
        "id": "85969693",
        "gid": "whosonfirst:locality:85969693",
        "layer": "locality",
        "source": "whosonfirst",
        "source_id": "85969693",
        "name": "Jackson",
        "accuracy": "centroid",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Mississippi",

**Comment by orangejulius** [comment]
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 

Both queries above now return correct results:

### [/v1/autocomplete?text=starbucks seattle](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=starbucks%20seattle)
![Screenshot_2019-10-03_16-04-19](https://user-images.githubusercontent.com/111716/66160128-7b4f7b00-e5f7-11e9-9926-32a0fc4def84.png)

### [/v1/autocomplete?text=jackson ms](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=jackson%20ms)
![Screenshot_2019-10-03_16-05-36](https://user-images.githubusercontent.com/111716/66160238-b3ef5480-e5f7-11e9-8b3a-150d0708289f.png)
