### ISSUE TITLE
30 w 26 st

### ISSUE THREAD

**Issue by trescube** [pelias/pelias#424]
Waiting on libpostal to understand numbered streets without suffix

**Comment by dianashk** [comment]
Oh man! It's really happening! We can finally find this one with the new libpostal! 🥇 

![screen shot 2017-04-20 at 4 47 16 pm](https://cloud.githubusercontent.com/assets/5446511/25251929/1c079e8c-25e9-11e7-8c03-2838a8ba4145.png)
