### ISSUE TITLE
1 Hämeenkatu, Tampere, Finland

### ISSUE THREAD

**Issue by trescube** [pelias/pelias#425]
Waiting on libpostal diacritical fixes

**Comment by dianashk** [comment]
This works in production and we have an acceptance test to flag future regressions! Closing the issue. 🎉 

![screen shot 2017-04-20 at 3 31 31 pm](https://cloud.githubusercontent.com/assets/5446511/25249061/7a5e139a-25de-11e7-8ddb-118fb821688a.png)
