### ISSUE TITLE
921 83 street, ny

### ISSUE THREAD

**Issue by trescube** [pelias/pelias#427]
This input is missing the `rd` ordinal portion of the street name which libpostal doesn't support.

**Comment by dianashk** [comment]
`rd` is referring to `3rd` instead of `Road`

**Comment by dianashk** [comment]
[query](http://pelias.github.io/compare/#/v1/search%3Ftext=921%2083%20street,%20ny) gets parsed by libpostal incorrectly where the housenumber is flagged as the postalcode. Not good news. :(

**Comment by dianashk** [comment]
Great news! Libpostal 1.0 no longer suffers from this.

![screen shot 2017-04-20 at 3 18 24 pm](https://cloud.githubusercontent.com/assets/5446511/25248556/b190d502-25dc-11e7-943a-2cd13a491537.png)

Moving the issue to in-review and can close it once the new libpostal is in production.
