### ISSUE TITLE
North West, Singapore

### ISSUE THREAD

**Issue by trescube** [pelias/pelias#428]
OSM (and therefore libpostal) doesn't support this as a region yet.

**Comment by orangejulius** [comment]
The results for this test are changing, but not necessarily getting better. We now return the correct result, but as result 8 following many clearly incorrect results.
![screenshot_2017-04-20_16-49-11](https://cloud.githubusercontent.com/assets/111716/25251999/6432ce66-25e9-11e7-9413-5f356a3f7165.png)

**Comment by trescube** [comment]
Fixed in pelias/api#850

**Comment by tigerlily-he** [comment]
Closing this issue since it has been fixed 
<img width="896" alt="screen shot 2017-08-01 at 3 51 59 pm" src="https://user-images.githubusercontent.com/13492525/28844153-bad497c0-76d1-11e7-89b8-48acb4e23cdb.png">
