### ISSUE TITLE
Add support for returning time zone when searching for a location

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#431]
When searching on an address or coordinate pair, include an option for time zone information.

This is similar to Google Maps Time Zone API.

https://developers.google.com/maps/documentation/timezone/intro

---

This came in through a user request. Original email (see support # 1067)

Seems like you already have the data somewhere because of the ability to return the estimated time of arrival in the local time zone from a routing query. Maybe you could add it optionally to a MapZen search result.

**Comment by michaelkirk** [comment]
Sorry to resurrect such a zombie issue. 

I had need for this feature and found this issue marked "closed as completed", which I assumed meant the feature was built, but I can't find any reference to it in the API documentation.

Does this feature exist? If not, is it something you'd be interested in having or was it ruled out of scope for pelias?

**Comment by missinglink** [comment]
It was considered out-of-scope, although we do publish the timezone boundaries at the bottom of this page https://geocode.earth/data/whosonfirst/legacy/
