### ISSUE TITLE
Search size parameter gives unexpected results in these address searches

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#434]
On this query, https://search.mapzen.com/v1/search?text=82+Whitney+Ave%2CHamilton%2COntario, specifying the size of 1 gives less accurate results than a size of 2 or even none at all.

with &size=1, the results are falling back to a centroid accuracy and source of geonames, with a confidence of 0.3

```
properties: {
id: "6093943",
gid: "geonames:region:6093943",
layer: "region",
source: "geonames",
source_id: "6093943",
name: "Ontario",
confidence: 0.3,
match_type: "fallback",
accuracy: "centroid",
country: "Canada",
country_gid: "whosonfirst:country:85633041",
country_a: "CAN",
region: "Ontario",
region_gid: "whosonfirst:region:85682057",
label: "Ontario, Canada"
}
```
  
with a size of 2 or more, or without specifying the size parameter, you get a point exact match from OpenAddresses.

```
properties: {
id: "ca/on/city_of_hamilton:61811",
gid: "openaddresses:address:ca/on/city_of_hamilton:61811",
layer: "address",
source: "openaddresses",
source_id: "ca/on/city_of_hamilton:61811",
name: "82 Whitney Avenue",
housenumber: "82",
street: "Whitney Avenue",
confidence: 1,
match_type: "exact",
accuracy: "point",
country: "Canada",
country_gid: "whosonfirst:country:85633041",
country_a: "CAN",
region: "Ontario",
region_gid: "whosonfirst:region:85682057",
locality: "Hamilton",
locality_gid: "whosonfirst:locality:101735515",
neighbourhood: "Ainslie Wood East",
neighbourhood_gid: "whosonfirst:neighbourhood:85874799",
label: "82 Whitney Avenue, Hamilton, Ontario, Canada"
}
```

@trescube found some other examples of the size giving unusual results (like 1 returns state, 2 is locality, and none is point) and will add notes about Elasticsearch hit numbers.

**Comment by trescube** [comment]
The reason that this is happening is because Pelias only requests `size` hits from ES.  Because all the fallback queries are queried for at once, the highest ranked documents get returned in descending score order.  Even though the `address` layer document does match, it may score lower than, say, a `city` layer document.  That's what's happening in this case.

**Comment by b-may** [comment]
This change in how the size parameter works messed up a large number of address geocode queries and I had to remove using the size parameter. Doing that brought back correct results. I like the old behavior.

**Comment by trescube** [comment]
We'll have a fix for this going into production today along with some acceptance tests on our end to make sure that the behavior is fixed.
