### ISSUE TITLE
Search Endpoint ignores Focus.point and changes query automatically

### ISSUE THREAD

**Issue by jmfield2** [pelias/pelias#436]
Hello,

We recently started using Pelias in the OpenTripPlanner deployment at the University of South Florida and noticed some strange results.  Some background, the deployment currently only handles trips for the Tampa Bay area, with the primary usage localized around the main Tampa campus; thus, we pass focus.point lat/lon and boundary.rect.{min,max}_{lat,lon} along with our requests to constrain the results in a hopefully meaningful way for the people using it.
### Issue 1

This is perhaps related to below, but some similar searches seem to ignore our focus point and return far away results first.

---
#### Here's what I did :innocent:

https://search.mapzen.com/v1/search?text=subwa&sources=osm&focus.point.lat=28.061062&focus.point.lon=-82.413200&boundary.country=US&boundary.rect.min_lat=27.279&boundary.rect.min_lon=-82.851&boundary.rect.max_lat=28.375&boundary.rect.max_lon=-82.012

and

https://search.mapzen.com/v1/search?text=subway&sources=osm&focus.point.lat=28.061062&focus.point.lon=-82.413200&boundary.country=US&boundary.rect.min_lat=27.279&boundary.rect.min_lon=-82.851&boundary.rect.max_lat=28.375&boundary.rect.max_lon=-82.012

_(the only difference is an extra Y)_

---
#### Here's what I got :scream_cat:

```
query": {
    "text": "subwa",
    "size": 10,

    "neighbourhood_gid": "whosonfirst:neighbourhood:85881941",
    "label": "Subway, St. Petersburg, FL, USA"
```

and 

```
query": {
    "text": "subway",
    "size": 10,

"neighbourhood_gid": "whosonfirst:neighbourhood:85889751",
"label": "Subway, Tampa, FL, USA"
```

---
#### Here's what I was expecting :sparkles:

I was expecting to see the same or similar results to the second query in the first.  Instead, the results in the first case are not prioritized at all - they bounce from one end of the area to the other.

---
#### Here's what I think could be improved :trophy:

Either add to the documentation when certain parameters might not be used, or make /search always prioritize results based on a provided focus.point.
### Issue 2

Requests with a space, but no quotes, are parsed and autocorrected. 

---
#### Here's what I did :innocent: (apikey omitted)

https://search.mapzen.com/v1/search?text=%22burger%20k%22&sources=osm&focus.point.lat=28.061062&focus.point.lon=-82.413200&boundary.rect.min_lat=27.279&boundary.rect.min_lon=-82.851&boundary.rect.max_lat=28.375&boundary.rect.max_lon=-82.012

---
#### Here's what I got :scream_cat:

```
query": {

    "text": "\"burger k\"",
    "size": 10,
}

...
    county_gid": "whosonfirst:county:102085759",
    "neighbourhood": "Vizcaya",
    "neighbourhood_gid": "whosonfirst:neighbourhood:85888675",
    "label": "Burger King, Pinellas County, FL, USA"

```

---
#### Here's what I did :innocent: (apikey omitted)

https://search.mapzen.com/v1/search?text=burger%20k&sources=osm&focus.point.lat=28.061062&focus.point.lon=-82.413200&boundary.country=US&boundary.rect.min_lat=27.279&boundary.rect.min_lon=-82.851&boundary.rect.max_lat=28.375&boundary.rect.max_lon=-82.012

---
#### Here's what I got :scream_cat:

```
"label": "K, East Lake-Orient Park, FL, USA"
"query": {
"text": "burger k",
"parsed_text": {
"street": "burger",
"query": "k"
},
```

---
#### Here's what I was expecting :sparkles:

I was expecting results similar to what you get if you actually send search for "burger k".

---
#### Here's what I think could be improved :trophy:

Either the documentation could probably be improved here to warn that the /search endpoint will change the search query as shown above, and recommend that all queries are properly quoted to ensure the intent of the user is maintained.

Thank you!

@barbeau
https://github.com/CUTR-at-USF/usf-mobullity/issues/362

**Comment by orangejulius** [comment]
Hey @jmfield2,
Thanks for reporting this. Looking at the referenced ticket which shows screenshots of your UI, I think the [autocomplete](https://mapzen.com/documentation/search/autocomplete/) endpoint is more appropriate for your use case. Our `search` endpoint is for fully completed inputs, such as those coming from a database or some sort of bulk input. The `autocomplete` endpoint is designed to handle requests when a human is typing something in one character at a time. So it's not as smart, but very fast, and doesn't assume the user has typed in the name of a place completely.

The classic example is when typing in "London". A query against `search` for "Lond" returns the [little known city of Lond, Pakistan](http://pelias.github.io/compare/#/v1/search%3Ftext=lond), whereas a query against `autocomplete` for "Lond" returns [London, England](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=lond).

For your queries, using the `autocomplete` endpoint (which supports most of the same parameters as `search`) works much better in [both](http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=osm&focus.point.lat=28.061062&focus.point.lon=-82.413200&boundary.country=US&boundary.rect.min_lat=27.279&boundary.rect.min_lon=-82.851&boundary.rect.max_lat=28.375&boundary.rect.max_lon=-82.012&text=subwa) [cases](http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=osm&focus.point.lat=28.061062&focus.point.lon=-82.413200&boundary.country=US&boundary.rect.min_lat=27.279&boundary.rect.min_lon=-82.851&boundary.rect.max_lat=28.375&boundary.rect.max_lon=-82.012&text=burger%20k).

One good practice, that we use in the [search demo](https://mapzen.com/products/search/) on mapzen.com, is to query the `autocomplete` endpoint on keystrokes, but send the same query to the `search` endpoint if the user hits enter. That way you can take advantage of both endpoints where they perform best. I'd also recommend checking out the [Mapzen.js](https://github.com/mapzen/mapzen.js) SDK, which can help facilitate that setup (it's the same code!).

I think you're right that the documentation needs to be updated. Right now our documentation is in a very reference style which means all the information is there, but you might have to read a lot to get started. We're already in the process of adding more documentation for specific use cases that should help out, so stay tuned.

**Comment by jmfield2** [comment]
Thanks!  We have considered that autocomplete might work better for us.  Based on your example link, it does seem like this endpoint will respect our focus.point parameter better .. Does that mean the search endpoint not respecting focus.point in certain cases is how it was designed to work?

**Comment by orangejulius** [comment]
The focus.point parameter on both endpoints should have the same purpose. It's hard to describe but the idea is focus.point tries to [return nearby results in general but also return results that are far away but are deemed important and are good matches for the input text](https://mapzen.com/documentation/search/search/#prioritize-results-by-proximity).

This is so that, for example, a user can be searching for local results, but if they type in the name of a big, far away city, they can still get that result to move around on the map. This is obviously not important for your use case, but you are correctly using the [bounding_box parameter](https://mapzen.com/documentation/search/search/#search-within-a-rectangular-region) (which, unlike focus.point, _is_ strict: nothing outside the bounding box will ever be returned in results) to make things work how you suggest.

The difference in behavior is that the search endpoint isn't meant to be given incomplete queries, so when it sees an exact match, it will return it much higher. For the Burger King example, the search endpoint believes you are literally searching for a place called "Burger K", which it didn't find, but it did find a place called "K", which is at least an exact match for one word.

The focus.point parameter is by far the hardest thing to tune in the Pelias geocoder, and there are definitely cases where it doesn't work as expected, but in this case, I _think_ it's doing the right thing for you, as long as you use autocomplete. Since your interface allows people to type in queries and run them a character at a time, autocomplete is definitely what you want to use anyway. Try switching it over and let us know how it works. We're happy to keep answering questions :)

**Comment by hannesj** [comment]
@orangejulius an issue here is that the autocomplete endpoint doesn't support bounding_box, so you can't do autocomplete searches if you need also stricter filtering by area.

**Comment by orangejulius** [comment]
@hannesj good point! the team talked this morning and we're going to add bounding box support to autocomplete so that they have parity there. It turns out for the example queries even without a bounding box, focus does the right thing. But surely the bounding box will help sometimes.

**Comment by orangejulius** [comment]
Hey @jmfield2, we added boundary.rect to autocomplete in our latest release, which went out yesterday. If you haven't yet tried out your queries with the autocomplete endpoint, definitely do and let us know how it works!

**Comment by barbeau** [comment]
@orangejulius Thanks, that's great!  We'll check it out.

On a related note - is there any reference documentation that lists the supported parameters for Search and Autocomplete in a concise manner?  Something similar to Javadocs?  

The [Mapzen Search](https://mapzen.com/documentation/search/) page lists this info in a narrative form, which is great for a tutorial but makes it a little harder to digest the summary of the APIs.  We're pulling together a [Java client for Pelias](https://github.com/CUTR-at-USF/pelias-client-library) and trying to architect this with common parameters for the various API endpoints pulled into superclasses.  Reference docs would make this easier, although we can still extract this out of the existing narrative docs.

**Comment by orangejulius** [comment]
Hey @barbeau,
There was not, at least not for search (strangely, there was one for autocomplete). But I've just submitted a PR to add one: https://github.com/pelias/pelias-doc/pull/161. It will show up in the official docs soon.

**Comment by barbeau** [comment]
@orangejulius Ah, I see the [autocomplete reference docs now](https://mapzen.com/documentation/search/autocomplete/#available-autocomplete-parameters) - thanks for updating the search docs to include a reference too!
