### ISSUE TITLE
Paris locality has different hiearchies in Geonames vs WOF

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#439]
Searching for [Paris, France](http://pelias.github.io/compare/#/v1/search%3Ftext=paris,%20france) results in 

```
1)  Paris, France (geonames locality) <--- see table below
 2) Paris, France (geonames county)
 3) Paris, France (whosonfirst locality) <--- see table below
 4) Paris 15, Paris, France
 5) Paris 18, Paris, France
 6) Paris 20, Paris, France
 7) Paris 19, Paris, France
 8) Paris 13, Paris, France
 9) Paris 16, Paris, France
10) Paris 17, Paris, France
```

| prop | val:geonames | val:whosonfirst |
| --- | --- | --- |
| layer | locality | locality |
| source | geonames | whosonfirst |
| name | Paris | Paris |
| country_gid | 85633147 | 85633147 |
| macroregion_gid | 404227465 | 404227465 |
| region_gid | 85683497 | 85683497 |
| macrocounty_gid | 404227749 | 404227749 |
| **_county**_ | **_Paris-4E-Arrondissement**_ | **_Paris-7E-Arrondissement**_ |
| **_county_gid**_ | **_102067591**_ | **_102068177**_ |
| locality | Paris | Paris |
| **_locality_gid**_ | **_whosonfirst:locality:2988506**_ | **_whosonfirst:locality:101751119**_ |

This causes the deduper to fail at query time and so we see what looks to be identical results.

**Comment by orangejulius** [comment]
No longer an issue

![image](https://user-images.githubusercontent.com/111716/66239234-54f91080-e6c7-11e9-9164-92be0e124855.png)
