### ISSUE TITLE
301 Commons Park S, Stamford, CT 06902

### ISSUE THREAD

**Issue by trescube** [pelias/pelias#440]
libpostal thinks 'CT' is the street.

**Comment by dianashk** [comment]
Added acceptance test. 
Libpostal 1.0 has fixed this issue. Moving to `in review` and should close once libpostal 1.0 is in prod.

**Comment by orangejulius** [comment]
Confirmed this is now fixed on dev!
![screenshot_2017-04-20_16-47-18](https://cloud.githubusercontent.com/assets/111716/25251914/0ee17872-25e9-11e7-9ff5-b0e490616036.png)
