### ISSUE TITLE
Any chance the API is returning long/lat pair rather than lat/long pair?

### ISSUE THREAD

**Issue by pdebruic** [pelias/pelias#441]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
copy pasted the 'coordinates' from the response example here https://mapzen.com/documentation/search/response/
 into maps.google.com

---
#### Here's what I got :scream_cat:
and it showed a spot SE of Mogadishu, not in London

e.g.

https://www.google.com/maps/place/0°07'31.5%22S+51°30'05.7%22E/@-0.1244115,47.0038364,6z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d-0.125422!4d51.501581

---
#### Here's what I was expecting :sparkles:
I was expecting to see somewhere in london

e.g. 

https://www.google.com/maps/place/51°30'05.7%22N+0°07'31.5%22W/@51.5015833,-0.1276054,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d51.5015833!4d-0.1254167
---
#### Here's what I think could be improved :trophy:
Write somewhere in the docs that the 'coordinates' part of the response returns the longitude in the first array slot and latitude in the second.  

Or change the array to the more (?) customary (? no idea if thats true) lat/long pair.

**Comment by orangejulius** [comment]
Hey @pdebruic,
Thanks for writing in! You are correct that we return results in longitude, latitude format. This is required by the [GeoJSON spec](http://geojson.org/geojson-spec.html#positions). However, there's no reason at all we shouldn't mention this explicitly in our documentation (we already have a link to the GeoJSON spec, but coordinate order is definitely worthy of mention), so thanks for bringing it up. We'll add something.
