### ISSUE TITLE
sw longspur lane, FL, 34990

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#444]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I think could be improved :trophy:

Not sure if this is related to the "city dominance" and "fallback" issues. As you are probably well aware, those issues in general are wreaking havoc on a large number of searches. If you know the correct (and in the database) street number then its less of a problem. Reliance on an accurate street number falls apart when you wither don't know it, get it slightly wrong, or you are looking for an address within say retail plaza that has one parcel centroid address in the database, but in reality there's 10+ addresses there.

**Comment by dianashk** [comment]
Looks like we have the street in the index, according to [this query](http://pelias.github.io/compare/#/v1/search%3Ftext=southwest%20longspur%20lane,%20FL,%2034990)

libpostal is parsing this query in a strange way, where `sw` is set to the query property and street is `longspur lane`. This is how the version of libpostal we're using is working (which is different from the current stable release).

**Comment by dianashk** [comment]
Things are improving here. Libpostal 1.0 is now getting the query parsing right, but we are not able to interpolate the housenumber so we just fallback to street centroids.

![screen shot 2017-04-20 at 4 00 04 pm](https://cloud.githubusercontent.com/assets/5446511/25250135/724c0686-25e2-11e7-904b-2bc16be815a3.png)
