### ISSUE TITLE
edgewater, fl

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#445]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I think could be improved :trophy:

Why a neighborhood have a higher confidence score than a town?

**Comment by trescube** [comment]
Thanks for pointing out the issue!  We'll add this to our acceptance tests and this should be fixed soon once we enable city+state geocoding using our new fallback methodology.

**Comment by b-may** [comment]
OK, great. Any timeline on the fix?

**Comment by trescube** [comment]
I'm actively working on it, hopefully it will be released by the end of the month.

**Comment by b-may** [comment]
Awesome, thanks.

**Comment by dianashk** [comment]
Deploying the change enabling libpostal to handle `city, state` queries. So this should be fixed in 15 minutes or so.

**Comment by dianashk** [comment]
Fixed! :clap:

**Comment by dianashk** [comment]
![screen shot 2016-11-16 at 11 14 25 am](https://cloud.githubusercontent.com/assets/5446511/20355010/e7452a2c-abed-11e6-835b-9cc93863cf77.png)
