### ISSUE TITLE
Distant Administrative area names should not appear in results unless they represent highly populated metropolitan areas [PL-CG04]

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#45]
Example:

request for `Soho (+NY geo bias)`
results should contain `Soho, New York` first
results should also contain `Soho, London` (assuming that's a highly populated/popular location)

**Comment by missinglink** [comment]
@dianashk I am happy to mark this as `wont-fix` as I feel the behaviour we have now is fine, should we close it?

**Comment by dianashk** [comment]
I would keep the story around, but we can remove it from the v1.0 milestone if we feel it's not going to buy us much at this time.

**Comment by riordan** [comment]
Closing for duplicate reasons, but is also useful to pelias/api#328.
