### ISSUE TITLE
2640 san antonio dr, milton,fl

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#452]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

http://pelias.github.io/compare/#/v1/search%3Ftext=2640%20san%20antonio%20dr,%20milton,fl

---
#### Here's what I was expecting :sparkles:

In `"parsed_text": {
        "postalcode": "2640",
        "street": "san antonio dr",
        "city": "milton",
        "state": "fl"
      },`

Expected house number to be returned in the number field. The house number is returned as a postalcode instead.

---

**Comment by b-may** [comment]
@orangejulius Update: Late last year I added a bunch of code to my "pelias geocoder wrapper code" that utilized libpostal to pre-process an address into components and do custom lookups based on presence / absence of city and zip code to help get better results by bypassing some of the known problems with pelias, especially relating to the postal zip code and city issues. It worked pretty well until you guys started enforcing a small limit on free libpostal lookups this month. I know there's been many changes to pelias since then. So, I stripped out all the extra code and I'm running it just using search without libpostal pre-processing and revisiting a list of known problem addresses and reporting results back. 

Current results for this address:
2640 san antonio dr 32583 - exact match
2640 san antonio dr milton, fl - falls back to city
2640 san antonio dr milton, fl 32583 - falls back to city

So, problem not solved.

**Comment by b-may** [comment]
@orangejulius After checking a few more addresses, it looks like the postal cities problem still has not been solved and its still really hurting geocoding accuracy / capability out of the box. 

As I understand it, the parsed_text response returned from /search is better than is was in say Nov 2016, right? I.e. should get same results as calling /libpostal, right?

**Comment by orangejulius** [comment]
Yet another one solved with our postal cities work! https://github.com/pelias/pelias/issues/396
