### ISSUE TITLE
Periodically seeing "No living connections" while running importers

### ISSUE THREAD

**Issue by glifchits** [pelias/pelias#453]
Hey team! 

I was using your awesome geocoding engine when I noticed something **a bit concerning**.
Let me tell you more about it.

I'm inclined to believe the solution is an Elasticsearch optimization, but I suspect the Pelias team has seen this before so I'm asking you!

---
#### Here's what I did :innocent:

I am running Pelias using Docker containers. I've got an Elasticsearch node in its own Docker container. The schema has been added.

---
#### Here's what I got :scream_cat:

When I run an importer (here I have logs from my instance of the OpenStreetMap importer), I'm _periodically_ getting these issues where the Elasticsearch client loses its connection with Elasticsearch. The connections are definitely configured properly -- data is added to the index (as the logs reveal), and the Elasticsearch server is available on localhost:9200. But the connection just drops and then comes back. Why would this happen?

```
...
openstreetmaps_1  | 2016-11-08T21:05:31.175Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634166 St Joseph / Dussere lon=-75.527306, lat=45.469837
openstreetmaps_1  | 2016-11-08T21:05:31.178Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634167 St Joseph / Dussere lon=-75.527618, lat=45.469913
openstreetmaps_1  | 2016-11-08T21:05:31.179Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634168 St Joseph / Edgar Brault lon=-75.519539, lat=45.473804
openstreetmaps_1  | 2016-11-08T21:05:31.181Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634169 St Joseph / Gabriel lon=-75.518303, lat=45.474628
openstreetmaps_1  | Elasticsearch WARNING: 2016-11-08T21:05:31Z
openstreetmaps_1  |   Unable to revive connection: http://localhost:9200/
openstreetmaps_1  |
openstreetmaps_1  | Elasticsearch WARNING: 2016-11-08T21:05:31Z
openstreetmaps_1  |   No living connections
openstreetmaps_1  |
openstreetmaps_1  | 2016-11-08T21:05:31.186Z - error: [dbclient] esclient error Error: No Living connections
openstreetmaps_1  |     at sendReqWithConnection (/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/transport.js:207:15)
openstreetmaps_1  |     at next (/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
openstreetmaps_1  |     at nextTickCallbackWith0Args (node.js:420:9)
openstreetmaps_1  |     at process._tickCallback (node.js:349:13)
openstreetmaps_1  | 2016-11-08T21:05:31.187Z - error: [dbclient] invalid resp from es bulk index operation
openstreetmaps_1  | 2016-11-08T21:05:31.188Z - info: [dbclient] retrying batch [500]
openstreetmaps_1  | Elasticsearch WARNING: 2016-11-08T21:05:31Z
openstreetmaps_1  |   Unable to revive connection: http://localhost:9200/
openstreetmaps_1  |
openstreetmaps_1  | Elasticsearch WARNING: 2016-11-08T21:05:31Z
openstreetmaps_1  |   No living connections
openstreetmaps_1  |
openstreetmaps_1  | 2016-11-08T21:05:31.217Z - error: [dbclient] esclient error Error: No Living connections
openstreetmaps_1  |     at sendReqWithConnection (/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/transport.js:207:15)
openstreetmaps_1  |     at next (/openstreetmap/node_modules/pelias-dbclient/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)
openstreetmaps_1  |     at nextTickCallbackWith0Args (node.js:420:9)
openstreetmaps_1  |     at process._tickCallback (node.js:349:13)
openstreetmaps_1  | 2016-11-08T21:05:31.218Z - error: [dbclient] invalid resp from es bulk index operation
openstreetmaps_1  | 2016-11-08T21:05:31.219Z - info: [dbclient] retrying batch [500]
openstreetmaps_1  | 2016-11-08T21:05:31.256Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634170 St Joseph / Grey Nuns lon=-75.536812, lat=45.465744
openstreetmaps_1  | 2016-11-08T21:05:31.265Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634171 St Joseph / Grey Nuns lon=-75.535759, lat=45.46603
openstreetmaps_1  | 2016-11-08T21:05:31.268Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634172 St Joseph / Jeanne D'arc lon=-75.540726, lat=45.46402
openstreetmaps_1  | 2016-11-08T21:05:31.269Z - info: [openstreetmap-points] openstreetmap:venue:node:4404634173 St Joseph / Marenger lon=-75.541664, lat=45.463356
...
```

---
#### Here's what I was expecting :sparkles:

I was expecting the import to run without Elasticsearch errors.

---
#### Here's what I think could be improved :trophy:

Perhaps some documentation in the INSTALL.md on what a good Elasticsearch configuration should look like.

**Comment by orangejulius** [comment]
Hey @glifchits,
Thanks for the report, this is interesting. Of course we've seen this error but usually in the context of one of us forgetting to start Elasticsearch on our local dev machines. I have two thoughts about what this could be.

The first, but less likely, is to blame the shiny new technology and say Docker is somehow screwing things up. I've heard that one "shouldn't run databases in a docker container" but there also doesn't seem to be any specific reason why. Containers are really just processes like anything else and so in theory one would hope it works, especially on a local machine.

The other possibility is that Elasticsearch has been overloaded and is dropping connections. In most of our experience, the bottleneck for importing is in our Node.js importers, as they do quite a bit of processing of data before sending it over to Elasticsearch, but it's possible that's not always the case. Check that Elasticsearch isn't using a huge amount of CPU or disk. If it is, there are some ways to tune the importers to be more forgiving.

**Comment by glifchits** [comment]
Thanks for getting back to me @orangejulius! Yeah, I would disagree the statement that running databases in a container is a bad thing. I'm very successfully using PostgreSQL from a Docker container in another app I have. FWIW however, for our Postgres setup the actual data is on a host mounted Docker volume. I haven't configured Elasticsearch that way, so perhaps it's worth looking into that.

Just to provide an update, I think this is unique to the OpenStreetMap importer. That import completed earlier this morning and now I'm running the OpenAddresses importer, the logs look clean.

Can you point me to some ways of tuning the importers?

**Comment by orangejulius** [comment]
Interesting. The OSM importer is by far our slowest, so it puts the least load on Elasticsearch.

The main tunable thing I know of is the [batch size](https://github.com/pelias/dbclient/blob/master/src/Batch.js#L5). Unfortunately you'll literally have to edit that line in the pelias-dbclient code in the `npm_modules` directory, since it's not really exposed all the way through to configuration. Other than that Pelias handles the main configuration things itself. 

Even that batch size should only matter if Elasticsearch is actually overloaded, which may not be the case. Was there high CPU usage from Elasticsearch? What sort of hardware are you running everything on? Also, you might want to check the Elasticsearch logs which on my dev machine at least are in `/var/log/elasticsearch`. The more info you send my way the more I can help.

**Comment by glifchits** [comment]
Hey @orangejulius, I was working on getting those numbers for you, but the OSM importer is working now without this issue. I am not closing this issue just yet because I want to try the other importers. All I did in the meantime was mount a Docker volume for my Elasticsearch data.
