### ISSUE TITLE
Discussion: entry point name for componentized geocoding

### ISSUE THREAD

**Issue by trescube** [pelias/pelias#455]
We'll soon be releasing componentized geocoding to production and we'd like some input from our users.  Conceptually, component geocoding is geocoding/searching using inputs that are already split up.  Currently Pelias only supports 1box geocoding where an text analysis engine has to split, say, `30 West 26th Street, New York, NY` into:

```
{
  "housenumber": "30",
  "street": "West 26th Street",
  "locality": "New York",
  "region": "NY"
}
```

With componentized geocoding, the input has already been split up.  An example request is (not live in prod at this moment):

`http://pelias.github.io/compare/#/v1/beta/component%3Faddress=30%20West%2026th%20Street&locality=New%20York&region=NY`

This is theoretically easier since any potential errors introduced by the text analyzer have been obviated by putting the onus of parsing on the caller instead of on the geocoding service itself.  

What we're looking for is input from our users on the entry point name for componentized geocoding.  For testing purposes, we'll be deploying componentized geocoding to `/v1/beta/component` but we're not married to that .  Please comment on how we could name this to be perfectly clear as to its intent.  With this release, we're introducing a section where beta features will be deployed for testing and feedback before final inclusion into standard Pelias.  Feel free to reply with any other feedback on the operation of this style of geocoding.

As implied by the name "beta", we make no guarantees that beta features will provide consistent answers or even behave rationally as we work out the details.  That is, don't develop long term solutions against beta endpoints.  We'll be updating our release notes to reflect when features move from beta to supported production.  

More details about componentized geocoding can be found [here](https://github.com/pelias/pelias/tree/master/milestones/component_geocoding).

**Comment by louh** [comment]
This is great. I can see this used as essentially a results filter - for an application catering to NYC residents, for example, you could still have the one input box, but all you need to do is ask for an address and feed the city and state automatically to the API. (Let me know if this wouldn't work this way?)

I don't have any good suggestions for endpoint names but my initial reaction is that "component" is not precise enough. I'll keep thinking about it though.

**Comment by easherma** [comment]
Just my opinion, I think some variation of '5 box' would be more specific. Component is a vague term that is used broadly in many contexts, whereas 5-box is specific to geocoding. Worst case scenario someone doesn't know what 5-box means, a little bit of explanation clears that up and does double duty explaining what you're doing by using that endpoint.

**Comment by mtmail** [comment]
Nominatim calls those structured queries though I'm not claiming that it's more descriptive.

**Comment by rowanwins** [comment]
Yay glad to hear this is getting close! I like @mtmail suggestion around something like 'structured'.

**Comment by dianashk** [comment]
We went with `structured` and it is now in production. You can use it via `/v1/search/structured`. Cheers!
