### ISSUE TITLE
Unexpected results for Berkeley with size parameter

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#460]
We had a similar issue, https://github.com/pelias/pelias/issues/434, which we thought was fixed.

However, this came in through support.

First, if I try to look up this address in Berkeley (2000 Center Street, Berkeley CA 94720) using size=1:

https://search.mapzen.com/v1/search?api_key=mapzen-xxxxxx&text=2000%20Center%20Street%2C%20Berkeley%20CA%2094720&size=1

I see a single result, with .3 confidence, located in Vietnam (coordinates: [105.08333,9.08333])

Now if I re-submit the search request, but with size=10:

https://search.mapzen.com/v1/search?api_key=mapzen-xxxxxx&text=2000%20Center%20Street%2C%20Berkeley%20CA%2094720&size=10

I see a single result, with .8 confidence, but it is the expected Berkeley CA location (coordinates: [-122.26931,37.870148] )

**Comment by therealtakeshi** [comment]
Same behavior for me, with a different request and additional constraint parameters.

[https://search.mapzen.com/v1/search?api_key=mapzen-XXXXXX&text=2224%2CHighland%20Park%20Cir&region=TX&postalcode=75701&size=10](https://search.mapzen.com/v1/search?api_key=mapzen-XXXXXX&text=2224%2CHighland%20Park%20Cir&region=TX&postalcode=75701&size=10) returns the expected TX address first, with a FL address second.

[https://search.mapzen.com/v1/search?api_key=mapzen-XXXXXX&text=2224%2CHighland%20Park%20Cir&region=TX&postalcode=75701&size=1](https://search.mapzen.com/v1/search?api_key=mapzen-XXXXXX&text=2224%2CHighland%20Park%20Cir&region=TX&postalcode=75701&size=1) returns the FL address, not the TX one.

**Comment by orangejulius** [comment]
This looks like the same issue as https://github.com/pelias/pelias/issues/562, which I'm happy to say we fixed recently with https://github.com/pelias/api/pull/874. This code should be making its way to production soon. The example query from @therealtakeshi already passes on dev!
![screenshot from 2017-05-12 12-03-19](https://cloud.githubusercontent.com/assets/111716/26006640/316bbd84-370b-11e7-9ea5-ec1fbe38910b.png)
