### ISSUE TITLE
canal rd, deltona, fl

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#463]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

http://pelias.github.io/compare/#/v1/search%3Ftext=canal%20rd,%20deltona,%20fl
---
#### Here's what I got :scream_cat:

http://pelias.github.io/compare/#/v1/search%3Ftext=canal%20rd,%20deltona,%20fl
---
#### Here's what I was expecting :sparkles:

It returned the proper address, but libpostal returned deltona as a neighborhood - its a city of 85,000.

`"parsed_text": {
        "street": "canal rd",
        "neighbourhood": "deltona",
        "state": "fl"
      },
`

---
#### Here's what I think could be improved :trophy:

Return Deltona as a city instead of a neighborhood.

**Comment by orangejulius** [comment]
Hey @b-may,
I think we missed this bug report a while back, sorry about that. I'm also not sure this is something we would consider a bug. Libpostal often parses things strangely (it has a hard job, so we have to cut it some slack), and we do a lot to work around that, which (hopefully) is why we return the right result here.

I doubt we can ever promise that the `parsed_text` section is anything but informative for debugging. If you're using it for something and this is impacting you, I'd suggest not doing that :p

Instead I would take a look at the record's `locality` field which is correct :)
