### ISSUE TITLE
Setup production build and instance of interpolation service

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#468]
- [ ] automate the build
- [ ] store data snapshots in private S3 bucket
- [ ] update API installation to download the latest snapshot
- [ ] update pelias config with a path to address.db and street.db

**Comment by missinglink** [comment]
build steps:

1. update interpolation docker script to expose the bash scripts in the `./scripts` dir
2. document the ENV vars and how they can be overridden from outside the container
3. perform a full build using a docker container
4. create a virtual machine which will perform regular builds, this needs to have adequate HDD space
5. configure the virtual machine to run a cronjob which updates data and kicks off a build
6. upload build files to s3 bucket for distribution

api steps:

1. update api code base to communicate with the interpolation web service via the network
2. configure the api to read a config variable of where the network service can be found, fail gracefully
3. create a virtual machine which will run the service, this needs to be on the same net as the api machines
4. create a strategy to update the service machine when a new build has been uploaded to s3

**Comment by orangejulius** [comment]
This was a Mapzen Search task, not relevant for Pelias
