### ISSUE TITLE
Puerto Rico

### ISSUE THREAD

**Issue by bdon** [pelias/pelias#470]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=geonames&text=puerto%20rico

---
#### Here's what I got :scream_cat:
 1)	Puerto Rico, Municipio de Orocovis, USA
 2)	Puerto Rico, Colombia
 3)	Puerto Rico, Paraguay
 4)	Puerto Rico, Colombia
 5)	Puerto Rico, Colombia
 6)	Puerto Rico, Spain
 7)	Puerto Rico, Mexico
 8)	Puerto Rico, Mexico
 9)	Puerto Rico, Mexico
10)	Los Fresnos de Puerto Rico, Mexico

---
#### Here's what I was expecting :sparkles:
A result for Puerto Rico (the political entity) or Puerto Rico (the physical island), instead of just a county

---
#### Here's what I think could be improved :trophy:
The political entity or physical island should be in the top 10

**Comment by bdon** [comment]
Perhaps this is a duplicate of #384 #236

**Comment by bdon** [comment]
This definitely works now based on this demo: https://pelias.github.io/leaflet-plugin/ :P

**Comment by orangejulius** [comment]
Woah, blast from the past! We definitely have improved results for Puerto Rico in the last 5(!) years. 🇵🇷
