### ISSUE TITLE
Prefer lbl:bbox property over geom:bbox property when available

### ISSUE THREAD

**Issue by stepps00** [pelias/pelias#472]
Hello Pelias!

Who's On First has, on rare occassion, a `"lbl:bbox"` property for administrative features. If this field exists, it should be preferred over the `"geom:bbox"` property. 

The `"geom:bbox"` field is a machine generated bounding box that considers all areas of a given feature. The new `"lbl:bbox"` field is hand-crafted and represents the bounding box of a sub-section of a feature (what most would generally consider that "place").

An example of this can be seen in the WOF record for [France](https://whosonfirst.mapzen.com/spelunker/id/85633147/#2/30.3/-1.6); the geometric bounding box stretches to include outlying islands of Reunion and Martinique. However, a bounding box that only includes the main areas of France (shown below in red) was added in a `"lbl:bbox"` property field and should be the preferred default zoom for France.

(This property is currently in the records of [France](https://whosonfirst.mapzen.com/data/856/331/47/85633147.geojson), the [US](https://whosonfirst.mapzen.com/data/856/337/93/85633793.geojson), and [Tokyo](https://whosonfirst.mapzen.com/data/856/728/17/85672817.geojson).)

<img width="680" alt="screen shot 2016-12-01 at 1 52 54 pm" src="https://cloud.githubusercontent.com/assets/18567700/20814185/861b5c76-b7cd-11e6-97ce-4deeee8a3bc6.png">

**Comment by orangejulius** [comment]
Hey @stepps00,
We've supported lbl:bbox [since August 9th](https://github.com/pelias/whosonfirst/pull/122)! It looks like the France bbox hasn't made it in, but Tokyo and SF work great. See https://github.com/pelias/pelias/issues/370 for more info :)
