### ISSUE TITLE
500 Error returned for invalid request

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#474]
There was recently a 500 error in the production service caused by the following type of request:

`/v1/reverse?layers=address&layers=address&point.lat=undefined&point.lon=undefined%20&size=1&size=1&sources=osm&sources=osm`

We should fix that so the error coming back is in the 400 range to indicate an invalid request instead of internal server error.

Hooray for graphs! :)

**Comment by missinglink** [comment]
fixed by https://github.com/pelias/api/pull/746

**Comment by orangejulius** [comment]
Fixed by https://github.com/pelias/api/pull/753 as well
