### ISSUE TITLE
Use file path from WOF meta files rather than computing ourselves

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#477]
The path to whosonfirst data files in the bundles is currently being calculated in the code for ~~both https://github.com/pelias/whosonfirst and~~ https://github.com/pelias/wof-pip-service/.

Previously, it was fairly easy to take 8 or 9 digit WOF ids and calculate the path. However, some WOF ids are now 10 digits, and our calculation code fails.

As it turns out there's no need whatsoever to calculate these paths, since the paths are actually included in the WOF meta files.

Connects https://github.com/pelias/whosonfirst/issues/174

**Comment by orangejulius** [comment]
I-told-you-so's from @thisisaaronland can be sent to 30 W 26th St, New York, NY

**Comment by orangejulius** [comment]
On a related note, we've decided that any errors either reading files, or parsing the JSON, in both whosonfirst and wof-pip-service, should cause the entire import to quit. The possibility of swallowing errors (even if there is logging) and allowing the import to "complete" when there are issues with the data is not something we want to have to deal with.

**Comment by thisisaaronland** [comment]
The above lacks documentation still so related is this:

https://github.com/whosonfirst/go-whosonfirst-uri#example

**Comment by orangejulius** [comment]
Update: the whosonfirst repository already gets this correct. The wof-pip-service does still need to be updated though.

**Comment by ge-fa** [comment]
> Update: the whosonfirst repository already gets this correct. The wof-pip-service does still need to be updated though.

Is this done by now? I'm unsure because this ticket got closed, however, I'm still running into erros like the ones described [here](https://github.com/pelias/openstreetmap/issues/215). Also, the checkbox of 'wof-pip-service' in the first post is still unchecked. Any clarification would be greatly appreciated!

Thanks in advance and for your work!

**Comment by orangejulius** [comment]
Hey @ge-fa,
The code to fix the bug was recently [merged](https://github.com/pelias/wof-pip-service/pull/74), but that module needs to be updated in our importers, and then have the importers merged to our production branches before everyone can use it without tweaking things on their own. My guess is we won't release anything more until after the holidays. In the meantime the errors can be safely ignored, as they don't represent any major losses of data. Of course if you do run into any issues please let us know.

**Comment by orangejulius** [comment]
To make things easier, we'll keep this ticket open until the changes from pelias/wof-pip-service#74 make their way into our importer production branches.

**Comment by ge-fa** [comment]
@orangejulius Thanks for your fast response and the clarification, highly appreciated! Actually I've used the 'master' branch instead of 'production', because I thought this got into 'master' already. I'll keep an eye on this. Happy holidays to you and all and thanks again!

**Comment by orangejulius** [comment]
This error should now be completely gone, let us know if not!

https://github.com/pelias/wof-pip-service/pull/74 made it into https://github.com/pelias/wof-admin-lookup as of version 2.11.0, which is now used in all the production importer branches, so it should have stopped as of a few weeks ago.
