### ISSUE TITLE
Libpostal API down?

### ISSUE THREAD

**Issue by b-may** [pelias/pelias#479]
Hey team! 

Sorry for posting in possibly the wrong place, but I couldn't find where to post issues about mapzen libpostal API. 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

libpostal.mapzen.com/parse?api_key=search-mykey=6621+Forrest+Street+Hollywood%2C+FLORIDA+33024

---
#### Here's what I got :scream_cat:

nothing

---
#### Here's what I was expecting :sparkles:

A result. Problem started at about 11:10am today.

---

**Comment by trescube** [comment]
Your request appears to be missing a text parameter

**Comment by b-may** [comment]
Sorry - I copy/pasted wrong - this should be an accurate request:

libpostal.mapzen.com/parse?api_key=search-mykey&address=6621+Forrest+Street+Hollywood%2C+FLORIDA+33024

**Comment by trescube** [comment]
Is the issue that your key is not working?  I think search-mykey is a general or demo key that's not meant to be used in production.

**Comment by trescube** [comment]
But if you just didn't want to include your actual key and still getting an error, then that's another issue.

**Comment by b-may** [comment]
I just replaced my actual key with "mykey". It doesn't work without a key either. http://libpostal.mapzen.com/parse?address=6621+Forrest+Street+Hollywood%2C+FLORIDA+33024

Its been working great for a few weeks and just stopped this morning.

**Comment by trescube** [comment]
Sorry to let this go for so long for this answer but we don't manage this instance.  I'll include Aaron in this once I'm off mobile.

**Comment by thisisaaronland** [comment]
My bad. The servers didn't come up after they got rebooted (after today's kernel-patching funtime). They are back up and should be picked up by the API proxy shortly.

**Comment by b-may** [comment]
Its working for me now - Thanks!

So is this the proper place to report problems with mapzen libpostal api?

**Comment by dianashk** [comment]
Hey @b-may, thanks as always for reporting issues as you come across them! If a Mapzen hosted service is down or having issues for any reason I'd recommend reporting that to the Mapzen support email: hello@mapzen.com
It will be routed properly from there. 

Cheers!
