### ISSUE TITLE
Structured geocoding feedback in Austria

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#485]
This came in through support. After chatting with @dianashk, let's get these into an issue for future review.

1) To verifiy and address and bring a location marker i want to find the exact address and if it doesnt exist maybe bring alternatives. But when i query an exisiting address with country, address and postalcode i get the correct address but also others, this would be fine but there is no way to automatically tell (by confidence or match type) which is the correct address

i.e: 
search.mapzen.com/v1/search/structured?address=Gilmstrasse 12&country=Austria&postalcode=6130

the confidence is always 1 and match type is exact even though there is a different postal code.

2) Another issue is when i search for an exact house number and address why do i get multiple results when the exact same has been found also with confidence 1 and match typen exact.

search.mapzen.com/v1/search/structured?address=Pertisau 17d&country=Austria&postalcode=6213

**Comment by martinlierschof** [comment]
I am happy to help wherever I can.

**Comment by orangejulius** [comment]
I think this is related to https://github.com/pelias/pelias/issues/484 which was opened just recently and is something we need to fix.

The confidence score code also has to be updated. Fortunately I think we have logic for reducing the confidence score appropriately based on postal code matches for use in `/v1/search`. I think we can use it here if we aren't already.

**Comment by orangejulius** [comment]
It looks like this is fixed, we now return the correct address with the correct postal code for the first result:

[/v1/search/structured?address=Gilmstrasse 12&country=Austria&postalcode=6130](https://pelias.github.io/compare/#/v1/search/structured%3Faddress=Gilmstrasse%2012&country=Austria&postalcode=6130)
![Screenshot_2019-10-09_13-11-33](https://user-images.githubusercontent.com/111716/66504039-55622480-ea96-11e9-92b6-d51825c5422b.png)
