### ISSUE TITLE
City centroid fallback for street name searches in Acerra, Italy

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#486]
OpenStreetMap has streets for the city of Acerra, Italy, but the search results are falling back to the locality centroid when a street name is given. There is no OA data for this area and appears to be no street numbers in OSM.

Here are a couple of samples (you can also add source = osm, but no change) using both search and structured:

- http://pelias.github.io/compare/#/v1/search/%3Ftext=Via%20Alessandro%20Manzoni%20acerra%20italy
The street: http://www.openstreetmap.org/way/226197267

- http://pelias.github.io/compare/#/v1/search/structured/%3Faddress=Via%20Francesco%20De%20Sanctis&locality=acerra
The street: http://www.openstreetmap.org/way/226196549

This came in from a user (see support 1382), where the support request was written in Italian, too. Basically, the summary is that there is OSM streets data and Nominatim can find it, but not Mapzen Search.

**Comment by nvkelso** [comment]
Verified searching for `Via Alessandro Manzoni acerra italy` via OSM.org does result in a street feature, while Mapzen Search demo returns only city.

**Comment by smemorex** [comment]
thanks,
and there is no result using openaddresses like datasoource

**Comment by orangejulius** [comment]
Hm, interesting. I tried for a while to construct a query that would find this street, and couldn't come up with anything. Based on [this query](http://pelias.github.io/compare/#/v1/search%3Fsize=40&boundary.rect.min_lat=40.91&boundary.rect.max_lat=40.94&boundary.rect.min_lon=14.3&boundary.rect.max_lon=14.4&text=Via%20Alessandro%20Manzoni) my guess is it's not in the Mapzen Search builds right now. That could be because it's not being imported, or it might not be in the underlying dataset for the [polylines](https://github.com/pelias/polylines) importer.

The polylines data is a few months old at this point (I think, its not totally clear). Each of these roads have been around in some form in OSM for several years, so it's possible the process for building the OSM road network used by the polylines importer is missing them. @missinglink can tell us more hopefully.

**Comment by smemorex** [comment]
So importing road and Civic Number on openaddresses from a shape file should fix mapzen search ?

**Comment by nvkelso** [comment]
Individual addresses, but not necessarily street names alone.

I'll upload file to S3 for you tomorrow.

**Comment by smemorex** [comment]
Hello,
So After uploading new data search Will work and i Will find also building number and Street like other city, Can you confirm?

**Comment by smemorex** [comment]
hello,
i still see same problem here, data were uploaded?

**Comment by smemorex** [comment]
it seems that data was uploaded


http://results.openaddresses.io/?runs=all#runs

but i still have same problem on mapzen search

**Comment by nvkelso** [comment]
I tried a few addresses from the OpenAddress source in Mapzen.com's Pelias demo and I still don't see any results either.

**Comment by nvkelso** [comment]
@orangejulius or @trescube for assistance, please.

**Comment by trescube** [comment]
We haven't released a data build in a few weeks due to some source polygon issues when performing admin lookups on addresses.  I'll get back to you when I get a time frame on a fix.

**Comment by nvkelso** [comment]
@smemorex It looks like the data is now appearing in Mapbox search that powers the search box on OpenAddresses.io, look for `Via Leonardo da Vinci 9, 80011 Acerra Napoli, Italy`.

**Comment by smemorex** [comment]
@nvkelso @trescube many and many thanks  for your work and for your help , 
sorry but do you think it can be possible that problem will be solved/analyzed before 10 january or surely more weeks are needed?

 @nvkelso yes i see it , even if it don't show it on autocompletion until i put postal code, and i can't see building number on autocompletition for example if i search via alessandro manzoni 9 on openaddresses.io i can't find it but for example it show

Via Alessandro Manzoni 9, 80031 Brusciano Napoli, Italy

**Comment by nvkelso** [comment]
We’ll know more in the next few days. It’ll easy be easy or hard, as the
saying goes ;)

**Comment by smemorex** [comment]
@nvkelso @trescube i don't know if can help , but i installed a local pelias copy and load only file created by nvkelso and i see that search work but i can't see information like city and nation . street ,housenumber and coordinate are right

**Comment by nvkelso** [comment]
We cleared the last issues (we hope), and a prod build is in progress.

For your local Pelias build your probably missing a build hierarchy "pip" step to process the data.

**Comment by dianashk** [comment]
We are kicking off a new build with the latest polylines data later today and hoping to have it ready for production by end of day on Friday 13th. Hopefully, this will still be timely enough for you, @smemorex. Sorry for the delay.

**Comment by orangejulius** [comment]
Hey all,
We've had updated polylines data builds for a while now, and this street is now showing up!
![streets](https://cloud.githubusercontent.com/assets/111716/23962189/ab075e6a-0983-11e7-9fa0-f9c3e2d50023.png)

As mentioned in our [release notes](https://mapzen.com/documentation/search/release-notes/#13-march-2017), we're currently running data a few weeks old, but in general in the future the data should update every week along with everything else.

Let us know if there are any other issues!
