### ISSUE TITLE
handle OA records with no HASH property

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#487]
it seems like a bunch of the OA records still don't have a `HASH` property, eg:

```bash
$ head /data/oa/us/nj/statewide.csv 
LON,LAT,NUMBER,STREET,UNIT,CITY,DISTRICT,REGION,POSTCODE,ID,HASH
-74.4226095,39.3689364,729,LEXINGTON AVE,,,,,,,
-74.4147457,39.3689073,29,N VERMONT AVE,,,,,,,
-74.4227321,39.3688336,219,N DELAWARE AVE,,,,,,,
-74.4220756,39.3648725,901,ATLANTIC AVE,,,,,,,
-74.4345249,39.3666268,400,N KENTUCKY AVE,,,,,,,
-74.415292,39.3684783,19,IRVING AVE,,,,,,,
-74.4330455,39.3606627,1729,ATLANTIC AVE RR,,,,,,,
-74.4646897,39.3464363,1,S PLAZA PL,,,,,,,
-74.4637452,39.3456241,4601,ATLANTIC AVE,,,,,,,
```

(that's from a fresh download of `openaddr-collected-global.zip` within an hour of writing this).

this means that search results don't actually generate GID values correctly for these records, eg:

```
      "properties": {
        "id": "us/nj/statewide:0",
        "gid": "openaddresses:address:us/nj/statewide:0",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us/nj/statewide:0",
        "name": "729 Lexington Ave",
        "housenumber": "729",
        "street": "Lexington Ave",
```

cc/ @iandees

**Comment by iandees** [comment]
This would be a good ticket for openaaddresses/machine.

**Comment by trescube** [comment]
I think the reason for this may be that the source hasn't been successfully exported since [April 30th](http://results.openaddresses.io/sources/us/nj/statewide) whereas the hash functionality was added on [August 22nd](http://results.openaddresses.io/sources/us/nj/statewide) so the data in the big .zip file is cached.

**Comment by orangejulius** [comment]
I believe all OA records now have hashes, so this is no longer relevant. If I'm wrong, someone let me know :)
