### ISSUE TITLE
locality issue

### ISSUE THREAD

**Issue by oliverbienert** [pelias/pelias#489]
Hi all,

The following query returns 2 street features, one with and one without a `locality` property:
```
http "https://search.mapzen.com/v1/autocomplete?text=Heimstraße 9, 10965 Berli&sources=osm&boundary.rect.min_lat=52.0153&boundary.rect.max_lat=53.0148&boundary.rect.min_lon=12.2333&boundary.rect.max_lon=15.0238&api_key=mapzen-s5dAvaM"
```

When I look up the osm node id, the record HAS an `addr:city` tag, so my question how is that `locality` property being built?
Is that because you don't use OSM administrative data but WOF exclusively?

**Comment by oliverbienert** [comment]
Ah, this has already been issued: #387
So maybe a candidate for #389?

**Comment by orangejulius** [comment]
Yes this is probably the same issue as #387. I hope we can solve it with whatever we do to support postal cities (https://github.com/pelias/pelias/issues/396), because we'd rather not have to implement #389. It will add more data in some cases, but we'll lose consistency.
