### ISSUE TITLE
Spatially constrain data downloads at setup time

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#506]
Provide a way to spatially constrain the data download in the local instance setup with something like a bounding box. This should apply to all data sources being ingested:
- [x] OpenAddresses (cc @migurski)
- [x] OpenStreetMap
- [x] Who's on First (cc @thisisaaronland)
- [x] Geonames ?? (is this used by MOD project?)

**Comment by dianashk** [comment]
Be able to specify a list of areas, not necessarily adjoined.

**Comment by dianashk** [comment]
### Update:

- [x] [whosonfirst filtering PR](pelias/whosonfirst#243) is in-review
- [x] [openaddresses filtering PR]() is in-review
- [ ] openstreetmap will only support a download url and no additional filtering will be performed
- [x] geonames will not be supported

**Comment by orangejulius** [comment]
Geonames does already have a downloader built in, and it can be constrained by country. Instead of saying it's not supported could we somehow utilize that?

**Comment by dianashk** [comment]
This is all done! 🚀
