### ISSUE TITLE
Improve production build process

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#507]
Currently, we don't have a solid fallback plan for build failures and are only running a single build each week. 

The proposal is to run continuous builds using `production` branches and latest data snapshots. If any of those builds are successful, which they should all be presumably, they should automatically be promoted to production without human intervention.

In addition to those stable builds, once a week we will run a build using the `staging` branches and latest data snapshots. If this build is successful, it will be promoted to production and the all the `staging` branches will be merged to `production` as well, so that all future stable builds can use that latest code.

**Comment by dianashk** [comment]
As a first step in this direction, we did the following today:

- [x] switch our `prod_build` configuration to always use the `production` branches (and latest data, for now)
- [x] updated `prod_build` to attempt running every 24 hours, and expect that it will automatically fail if another build is in-progress
- [x] updated `dev2` configuration to build off of the `staging` branches (and latest data, for now)

This means we are now in a state where we should always have a recent production build with fresh data. From now on, staging builds will NOT be allowed to go directly to production. We will have to merge the code from `staging` to `production` branches at which point it will get picked up by the continuous production build cycle.

There is still work to be done to get this process to where we'd like it to ultimately be.

- [ ] automate roll-up of successful production build directly to the production environment (builds and API changes alike)
- [ ] implement a mechanism for snapshotting the latest data from all sources and then having all the build environments use those snapshots based on their needs
- [ ] `dev2` (staging) builds should use last known *good* data snapshot identified by the last stable production build
- [ ] `prod_build` should always snapshot the latest data at build time and once a build is successfully complete that data snapshot should be marked as `stable` so other builds can use it
- [ ] `interpolation` build and `admin-lookup-service` should also use the data snapshot system, although the details of which versions to use are still to be determined

There is probably more, so please add things I've missed.

**Comment by orangejulius** [comment]
This is a Mapzen search issue
