### ISSUE TITLE
Limiting layers to `address` disables interpolation

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#508]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

I ran a query for an address I expect to be interpolated, like so:
> [/v1/search?text=1307 E Vermont St, Indianapolis, IN, USA](http://pelias.github.io/compare/#/v1/search%3Ftext=1307%20E%20Vermont%20St,%20Indianapolis,%20IN,%20USA)
That resulted in the expected interpolated address as the top record. However, it also came back with street centroids, which I wanted to avoid seeing in the results.
```
1)	1307 East Vermont Street, Indianapolis, IN, USA
2)	East Vermont Street, Indianapolis, IN, USA
3)	East Vermont Street, Indianapolis, IN, USA
4)	East Vermont Street, Indianapolis, IN, USA
5)	East Vermont Street, Indianapolis, IN, USA
6)	1307 East Vermont Street, Indianapolis, IN, USA
7)	East Vermont Street, Indianapolis, IN, USA
8)	1307 East Vermont Street, Indianapolis, IN, USA
```

So I added a filter to the query, to only show items from the `address` layer. This is the new query I ran: 
> [/v1/search/layers=address&text=1307 E Vermont St, Indianapolis, IN, USA](http://pelias.github.io/compare/#/v1/search%3Flayers=address&text=1307%20E%20Vermont%20St,%20Indianapolis,%20IN,%20USA)
This resulted in no interpolated results showing up at all, and the quality of the results drastically changed.
```
 1)	1401 E Vermont St, Indianapolis, IN, USA
 2)	126 E Vermont St, Indianapolis, IN, USA
 3)	3336 E Vermont St, Indianapolis, IN, USA
 4)	1216 E Vermont St, Indianapolis, IN, USA
 5)	510 E Vermont St, Indianapolis, IN, USA
 6)	724 E Vermont St, Indianapolis, IN, USA
 7)	542 E Vermont St, Indianapolis, IN, USA
 8)	1413 E Vermont St, Indianapolis, IN, USA
 9)	514 E Vermont St, Indianapolis, IN, USA
10)	2816 E Vermont St, Indianapolis, IN, USA
```
---
#### Here's what I was expecting :sparkles:
I would expect that interpolated addresses still show up when layers are limited `address` only, since these are still technically addresses. I would also expect to not see street centroid results when an interpolated address has been found for the query. Furthermore, it's unclear why there are 2 identical interpolated results in the first query: shouldn't they be de-duplicated in the API after the ES results are retrieved?

**Comment by orangejulius** [comment]
Furthermore, setting `size=1` also seems to disable interpolation: http://pelias.github.io/compare/#/v1/search%3Fsize=1&text=1307%20E%20Vermont%20St,%20Indianapolis,%20IN,%20USA
![screenshot from 2017-02-28 11-36-00](https://cloud.githubusercontent.com/assets/111716/23414471/180be9e4-fdaa-11e6-9186-7225b98b8aca.png)

**Comment by stevevance** [comment]
I came across the same problem tonight when trying out interpolation...

[my API call to Mapzen Search](https://search.mapzen.com/v1/search?text=1625%20n%20humboldt%20blvd%2C%20chicago%2C%20il&boundary.circle.lat=41.809148&boundary.circle.lon=-87.618538&boundary.circle.radius=100&layers=venue,address,locality,localadmin&api_key=search-zN8_XgQ) has `layers=venue,address,locality,localadmin` parameter. The non-real address isn't found. 

Pass no `layers` parameter and the non-real address is "found" via interpolation.

**Comment by orangejulius** [comment]
This does not seem to happen any more, but I can't think of what might have solved it. @missinglink any ideas?

**Comment by missinglink** [comment]
The interpolation engine kicks in when the user input contains a housenumber yet elasticsearch doesn't have that number and so returned a street instead.

I'm guessing the bug was that by omitting the `street` layer this functionality no longer worked as expected.

I'm not sure how it was fixed if it's no longer the case.
