### ISSUE TITLE
Problems in Washington, DC

### ISSUE THREAD

**Issue by evansiroky** [pelias/pelias#509]
Yes, there may be a lot of [problems in Washington, DC](https://mapzen.com/blog/mapzen-bans-trump/), but here is one that I think y'all can fix:

---
#### Here's what I did :innocent:

I'm trying to geocode any address with the text "Washington, DC" using the `search` url.

---
#### Here's what I got :scream_cat:

Using `search`, any address with "Washington, DC" doesn't seem to work.  However, they do seem to work with `autocomplete`.

| Query | Using `search` | Using `autocomplete` |
|---|---|---|
| 1150 K St NW, Washington, DC | [link](http://pelias.github.io/compare/#/v1/search%3Ftext=1150%20K%20St%20NW,%20Washington,%20DC) | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1150%20K%20St%20NW,%20Washington,%20DC) |
| 3060 16th St NW, Washington, DC | [link](http://pelias.github.io/compare/#/v1/search%3Ftext=3060%2016th%20St%20NW,%20Washington,%20DC) | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=3060%2016th%20St%20NW,%20Washington,%20DC) |
| 1705 P St NW, Washington, DC | [link](http://pelias.github.io/compare/#/v1/search%3Ftext=1705%20P%20St%20NW,%20Washington,%20DC) | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1705%20P%20St%20NW,%20Washington,%20DC) |

---
#### Here's what I was expecting :sparkles:

I am expecting that the `search` option is able to geocode the address just as good as the `autocomplete` option.

**Comment by martinburch** [comment]
@evansiroky Looks ok to me! Try again?
![image](https://cloud.githubusercontent.com/assets/2335284/23403787/a10d8352-fda9-11e6-8071-cd06ae506a9e.png)

**Comment by trescube** [comment]
Here's the structured request:  http://pelias.github.io/compare/#/v1/search/structured%3Faddress=1150%20K%20St%20NW&locality=Washington

Interestingly it doesn't contain DC as an abbreviation for District of Columbia.  That would be the problem.  It works when expanded to the full name:

http://pelias.github.io/compare/#/v1/search%3Ftext=1150%20K%20St%20NW,%20Washington,%20District%20of%20columbia

**Comment by trescube** [comment]
Thanks for reporting!  We'll get this fixed in (hopefully) the next data build.

**Comment by missinglink** [comment]
hi @evansiroky, how are we doing with this issue, can it be marked as resolved now?

**Comment by dianashk** [comment]
This looks to be fixed in production at this time! 🎉  🎈 

![screen shot 2017-05-30 at 4 37 36 pm](https://cloud.githubusercontent.com/assets/5446511/26603865/591069bc-4556-11e7-80d3-05b4e912a79f.png)

Closing the issue, but please reopen if there are still problems in Washington, DC that we can fix. 🤣
