### ISSUE TITLE
Scoring based on the admin area it belongs to [PL-AG05]

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#51]
Inherit score from enclosing admin area

related issues:
* https://github.com/pelias/admin-lookup/issues/5
* https://github.com/pelias/pelias/issues/46

**Comment by hkrishna** [comment]
We should write a couple of acceptance test cases for this. 

Once this get into a dev env and after we make sure the water is flowing through all the pipes (schema change, importer pipeline, admin lookup, api change etc) we should be able to come up with a few cool test cases. Hold off until then
