### ISSUE TITLE
Autocomplete can't handle apartments, suites, units, etc.

### ISSUE THREAD

**Issue by evansiroky** [pelias/pelias#510]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

I am trying to geocode an address with an apartment, suite, unit, etc pattern in the text query using `autocomplete`.  It seems like `autocomplete` can work just fine when these patterns are omitted.

---
#### Here's what I got :scream_cat:

Whenever an apartment... pattern is included, the `autocomplete` service can't seem to find anything.

| Query | Using `autocomplete` without apartment... pattern | Using `autocomplete` with apartment... pattern |
|---|---|---|
| 420 NW 11th Ave UNIT 1105, Portland, OR | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=420%20NW%2011th%20Ave,%20Portland,%20OR) | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=420%20NW%2011th%20Ave%20UNIT%201105,%20Portland,%20OR) |
| 2033 1st Ave APT 3, Seattle, WA | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=2033%201st%20Ave,%20Seattle,%20WA) | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=2033%201st%20Ave%20APT%203,%20Seattle,%20WA) |
| 834 5th Ave # 78A, New York, NY | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=834%205th%20Ave,%20New%20York,%20NY) | [link](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=834%205th%20Ave%20%23%2078A,%20New%20York,%20NY) |

---
#### Here's what I was expecting :sparkles:

I am expecting autocomplete to be able to successfully geocode an address with an apartment, suite, unit, etc pattern in the text query.

**Comment by missinglink** [comment]
definitely a parser issue, looks like the parser is interpreting them as `regions`, which is clearly wrong.

```
"regions": [
  "UNIT 1105",
  "Portland"
],
```

thanks for the great bug report @evansiroky we'll discuss how to deal with it.

see https://github.com/pelias/api/issues/795 for more background information on the two different parsing libs we use

**Comment by orangejulius** [comment]
This is on the TODO list for the near future as part of https://github.com/pelias/pelias/issues/510, any updates will be posted there :)
