### ISSUE TITLE
Same incorrect results for all text search strings ending with 'UK'

### ISSUE THREAD

**Issue by martinburch** [pelias/pelias#513]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

Searching for `Liverpool UK` or `Manchester UK` or `London UK`
https://search.mapzen.com/v1/search?text=Liverpool%20UK&api_key=mapzen-dHMK8tN&layers=coarse&size=1
https://search.mapzen.com/v1/search?text=Manchester%20UK&api_key=mapzen-dHMK8tN&layers=coarse&size=1
https://search.mapzen.com/v1/search?text=London%20UK&api_key=mapzen-dHMK8tN&layers=coarse&size=1

---
#### Here's what I got :scream_cat:
Same result for Ukong, Malaysia in all cases
```
{
  "geocoding": {
    "version": "0.2",
    "attribution": "https://search.mapzen.com/v1/attribution",
    "query": {
      "text": "London UK",
      "size": 1,
      "layers": [
        "continent",
        "country",
        "dependency",
        "macroregion",
        "region",
        "locality",
        "localadmin",
        "macrocounty",
        "county",
        "macrohood",
        "borough",
        "neighbourhood",
        "microhood",
        "disputed"
      ],
      "private": false,
      "querySize": 1
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1488283931936
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          114.85,
          4.55
        ]
      },
      "properties": {
        "id": "1737767",
        "gid": "geonames:locality:1737767",
        "layer": "locality",
        "source": "geonames",
        "source_id": "1737767",
        "name": "Ukong",
        "confidence": 0.54,
        "accuracy": "centroid",
        "country": "Malaysia",
        "country_gid": "whosonfirst:country:85632739",
        "country_a": "MYS",
        "region": "Sarawak",
        "region_gid": "whosonfirst:region:85675177",
        "county": "LIMBANG",
        "county_gid": "whosonfirst:county:1108696449",
        "locality": "Ukong",
        "locality_gid": "whosonfirst:locality:1737767",
        "label": "Ukong, Malaysia"
      }
    }
  ],
  "bbox": [
    114.85,
    4.55,
    114.85,
    4.55
  ]
}
```
---
#### Here's what I was expecting :sparkles:
Same as result for `London United Kingdom` (or `Liverpool United Kingdom` or `Manchester United Kingdom`)
https://search.mapzen.com/v1/search?text=London%20United%20Kingdom&api_key=mapzen-dHMK8tN&layers=coarse&size=1
```
{
  "geocoding": {
    "version": "0.2",
    "attribution": "https://search.mapzen.com/v1/attribution",
    "query": {
      "text": "London United Kingdom",
      "parsed_text": {
        "city": "london",
        "country": "united kingdom"
      },
      "size": 1,
      "layers": [
        "continent",
        "country",
        "dependency",
        "macroregion",
        "region",
        "locality",
        "localadmin",
        "macrocounty",
        "county",
        "macrohood",
        "borough",
        "neighbourhood",
        "microhood",
        "disputed"
      ],
      "private": false,
      "querySize": 1
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1488284031166
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.099076,
          51.509648
        ]
      },
      "properties": {
        "id": "101750367",
        "gid": "whosonfirst:locality:101750367",
        "layer": "locality",
        "source": "whosonfirst",
        "source_id": "101750367",
        "name": "London",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "centroid",
        "country": "United Kingdom",
        "country_gid": "whosonfirst:country:85633159",
        "country_a": "GBR",
        "macroregion": "England",
        "macroregion_gid": "whosonfirst:macroregion:404227469",
        "region": "City of Westminster",
        "region_gid": "whosonfirst:region:85684061",
        "locality": "London",
        "locality_gid": "whosonfirst:locality:101750367",
        "label": "London, England, United Kingdom"
      },
      "bbox": [
        -0.4984345,
        51.297207,
        0.27894,
        51.6843015
      ]
    }
  ],
  "bbox": [
    -0.4984345,
    51.297207,
    0.27894,
    51.6843015
  ]
}
```

---
#### Here's what I think could be improved :trophy:
`UK` should be recognized as an alternative to `GB` for the country `United Kingdom`/`GBR`/`United Kingdom of Great Britain and Northern Ireland`
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Exceptional_reservations

This doesn't seem to be the case now. Here's a structured search showing no results for UK:
http://search.mapzen.com/v1/search/structured?locality=Manchester&country=UK
http://search.mapzen.com/v1/search/structured?country=UK
but this works:
http://search.mapzen.com/v1/search/structured?locality=Manchester&country=GB
http://search.mapzen.com/v1/search/structured?locality=Manchester&country=United%20Kingdom

**Comment by dianashk** [comment]
Hey @martinburch! 👋  Thank you for your feedback. You are totally right that this currently doesn't work. We are in the midst of our [Alt-Names](http://pelias.io/milestones/alt_names/) milestone, so I'm going to add this issue to the list of things we'd like to address. I believe once we have the ability to specify alternate names for admin areas we will be able to easily add UK as an alias for United Kingdom. Please let us know if there are other such failures so we can be sure to add them to our acceptance test suite.

Stay tuned 📺  to our [Alt-Names](http://pelias.io/milestones/alt_names/) milestone for updates.

**Comment by orangejulius** [comment]
Hey everyone,
Wow, this is quite embarrassing that we ever got this wrong.

In any case, our work with alt-names and the Placeholder service appears to have taken care of this quite well.

Let us know if there are any more issues like this.

http://pelias.github.io/compare/#/v1/search%3Ftext=liverpool%20UK
![image](https://user-images.githubusercontent.com/111716/42793654-1f29e9ca-8949-11e8-8056-3efe47823055.png)

http://pelias.github.io/compare/#/v1/search%3Ftext=manchester%20UK
![image](https://user-images.githubusercontent.com/111716/42793672-33a77002-8949-11e8-8e54-252a9cd70222.png)
