### ISSUE TITLE
Adding Custom Data and allow querying

### ISSUE THREAD

**Issue by jerryhall** [pelias/pelias#516]
Hi all. Your search tool does rock. Great to see it built with Elastic as well!

I have several custom datasets like:

1. Crime data (unique codes, descriptions, categories), 
2. Business data (that hasn't made it into openstreetmaps yet or has data not typically put in OSM (owner name) eg (business name, address, owner name, license type etc. +). 
3. I also have some layers that may be in OSM but, I'm using my own to be sure it's the most current (until I can hire others to help :). That could be council districts, old census tracts (2010, 2000, 1990 etc). 

I've built my map in Mapzen/Tangram and the search works great against typical layers (admin, schools, parks etc).

So, my question is, is there a way to include various cols from my datasets to be sure they're added in the search function? I also limit or steer results to specific bounds (LA County, CA) and that works great. I still get out-of-bounds results but, much fewer.

Thanks much!

**Comment by dianashk** [comment]
Hey @jerryhall! 👋  Thank you for reaching out. We're glad to hear your initial experience with Pelias has been successful.
Is it safe to assume that you're hosting your own instance of Pelias? When setting up your instance, which importers to do you run as part of your build? The only way to get custom datasets into your index would be to write a new importer. It's best to start with an existing one that supports ingesting similar data formats, for example if you have csv files you can start with the `openaddresses` importer as a foundation.

If you want to add columns to existing importers, such as `openstreetmap` for example, you can just fork that importer, `pelias-schema`, and `pelias-model`. Those parts will allow you to add the new columns to the Elasticsearch schema and our document generator, as well as the importer code that pulls the data out of OSM and populates the documents.

You will also need to update the query logic in API if you want the ability to search those new columns directly and/or return that data in the geojson results.

We'd be happy to chat about this process in more detail if you're interested. You can find us on our [gitter](https://gitter.im/pelias/pelias) channel.

Cheers!

**Comment by jerryhall** [comment]
Hi Diana (yea for women coders! need 100x more :)

Thanks for your help. I'm using the Pelias search function that came via the Mapzen API. Is there any way I can temporarily dovetail my datasets with that API? My production site is on a virtual hosting setup until I can migrate it all over to my AWS EC2? 

Thanks again!
