### ISSUE TITLE
State of California does not show up as top result

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#522]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

[/v1/search%3Fsources=wof&text=california](http://pelias.github.io/compare/#/v1/search%3Fsources=wof&text=california)

---
#### Here's what I got :scream_cat:

```
 1)	California Cove, Laguna Woods, CA, USA
 2)	California Cottages, Foster City, CA, USA
 3)	California Court, Lake Forest, CA, USA
 4)	California City, CA, USA
 5)	California Heights, Long Beach, CA, USA
 6)	California Colony, Mission Viejo, CA, USA
 7)	California Maison, San Jose, CA, USA
 8)	California Crest, Mission Viejo, CA, USA
 9)	California Ridge, Santa Clara County, CA, USA
10)	California Landings, Fontana, CA, USA
```
---
#### Here's what I was expecting :sparkles:

I was hoping to see California, USA as the first result.

---
#### Here's what I think could be improved :trophy:
It seems like results should be showing up ordered by increasing granularity, so less granular records are higher in the results.

**Comment by laxatives** [comment]
Seeing similar behavior where a vague query often matches with something much more specific. `California` -> `California Cove` and `Clifton, VA` -> `Clifton Forge, VA`, despite having some additional contextual information like zip codes or region.

**Comment by missinglink** [comment]
the WOF record has no population info:

https://whosonfirst.mapzen.com/spelunker/id/85688637

**Comment by orangejulius** [comment]
Fixed now!
http://pelias.github.io/compare/#/v1/search%3Fsources=wof&text=california
![image](https://user-images.githubusercontent.com/111716/42793806-de4c5b9e-8949-11e8-9cd2-45c81ef17b5b.png)
