### ISSUE TITLE
Leave leading 0's in US housenumbers

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#524]
We started [removing these leading 0's](https://github.com/pelias/openaddresses/pull/110) a while back, but it looks like that may have been a bad idea because our friends in Portland just reported the following issue.

>This line from the OpenAddresses importer looks like a bug for Portland:  record.NUMBER = _.trimStart(record.NUMBER, '0');
https://github.com/pelias/openaddresses/blob/master/lib/streams/cleanupStream.js#L22
>
>In Portland, there are Zero-Leading Addresses that are different from non-Zero-Leading addresses.  Said another way, there could be two separate residences ~1 mile apart, that have almost the exact same address, with the only differentiation being a leading-zero on the number (not really a number in that case).  Trimming off leading zeros from address numbers is not a valid practice for addresses in Portland.
>
>see: https://en.wikipedia.org/wiki/Portland,_Oregon#Neighborhoods “East-West addresses in this area are denoted with a leading zero (instead of a minus sign). This means 0246 SW California St. is not the same as 246 SW California St. Many mapping programs are unable to distinguish...”
>
![screen shot 2017-03-23 at 2 01 45 pm](https://cloud.githubusercontent.com/assets/5446511/24262725/550c45bc-0fd1-11e7-99d6-8cbe1721db85.png)

**Comment by zgoda** [comment]
Could #651 be related to this? Not house number but postal code gets stripped of leading "0" in search.

**Comment by missinglink** [comment]
It's possible that this is related.

note: we also have an [elasticsearch token filter named removeAllZeroNumericPrefix](https://github.com/pelias/schema/blob/master/settings.js) which also strips leading zeros:

```
"removeAllZeroNumericPrefix" :{
  "type" : "pattern_replace",
  "pattern" : "^(0*)",
  "replacement" : ""
},
```

**Comment by zgoda** [comment]
Well, that's quite unfortunate but Pelias finds some postal codes with leading zeros, for example searching for "07-300" returns 07300, Saint-Barthelemy-Le-Plain, France:

https://mapzen.com/search/explorer/?query=search&text=07-300 and https://mapzen.com/search/explorer/?query=search/structured&postalcode=07-300

What's missing is "07-300" postal code http://www.geonames.org/postalcode-search.html?q=07-300&country=

**Comment by missinglink** [comment]
Yes, it seemed logical from the mathematical perspective that additional preceding 0's have no semantic value.

It turns out, although uncommon, that some countries and cities assign a semantic value to additional zeros, treating them more like strings than numbers.

Some work will need to be done to remove the 0 trimming code and test the effect of that change internationally.

**Comment by zgoda** [comment]
It's not that uncommon, [at least in Poland](https://en.wikipedia.org/wiki/List_of_postal_codes_in_Poland#00-09). Country capital has "00-" to "04-", and some "05-".

**Comment by missinglink** [comment]
@zgoda let's not conflate the street number and postalcode issues, I don't believe we strip 0's from postalcodes.

**Comment by zgoda** [comment]
OK, so I assume this is not related. Thank you.

**Comment by orangejulius** [comment]
This change has made it to our production branches and will be reflected in any new builds.

Here's a comparison of Mapzen Search (not updated, going away), geocode.earth(change will be reflected in the next build), TriMet's Pelias (the next build should get this change), and a build on my local machine from the other day. Note the additional OA record with the correct address on the localhost build all the way to the right.
![image](https://user-images.githubusercontent.com/111716/36210970-de04227e-116d-11e8-93ab-943c66442438.png)

**Comment by orangejulius** [comment]
This was fixed in https://github.com/pelias/openaddresses/pull/310
