### ISSUE TITLE
interpolation sorting

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#528]
currently we don't re-sort interpolated results, in the case where there are one-or-more housenumber level accuracy results, we should consider sorting the more granular matches so they appear first.

eg:
```
1)	Lancaster Drive Northeast, Hayesville, OR, USA
2)	Lancaster Drive Northeast, Cedar Rapids, IA, USA
3)	Lancaster Drive Northeast, Salem, OR, USA
4)	521 Lancaster Drive Northeast, Four Corners, OR, USA
```

vs:
```
1)	521 Lancaster Drive Northeast, Four Corners, OR, USA
2)	Lancaster Drive Northeast, Hayesville, OR, USA
3)	Lancaster Drive Northeast, Cedar Rapids, IA, USA
4)	Lancaster Drive Northeast, Salem, OR, USA
```

note: for requests using the `focus.point` API it might be best to leave the sorting as-is.

**Comment by dianashk** [comment]
This is done, however the `focus.point` parameter is not considered. We always sort addresses higher. However, the order of the addresses shouldn't change relative to each other, so this should not be a problem.
