### ISSUE TITLE
Interpolated results are not returned when housenumber parsed as "query"

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#532]
Libpostal sometimes parses address queries with the housenumber in the `query` (or `postalcode`!) field instead of the `number` field. This is handled correctly for exact matches, but not interpolated results. It appears the API will only query the interpolation server if the `number` field is present.

We should consider adding better logic to detect when the `query` field is present but looks like a housenumber. Ideally this would happen in the text-analyzer module, so that it can be used elsewhere.

Here's an [example query](http://pelias.github.io/compare/#/v1/search%3Ftext=15%20call%20st,%20billerica,%20MA) (note the probduild result)
![screenshot from 2017-03-29 16-34-29](https://cloud.githubusercontent.com/assets/111716/24475578/4daa5030-149e-11e7-94b2-1413dcaa6347.png)

This issue was exposed when [Massachusetts broke](https://github.com/openaddresses/openaddresses/issues/2693) in OA data.

**Comment by dianashk** [comment]
Works with libpostal 1.0 (note `parsed_text` in prod vs dev)

![screen shot 2017-04-20 at 3 36 57 pm](https://cloud.githubusercontent.com/assets/5446511/25249256/477d7316-25df-11e7-9d1c-3886b43a90c9.png)

**Comment by orangejulius** [comment]
This individual case was fixed, but I suspect the general issue remains. If we come across any we should reopen this ticket.

**Comment by dianashk** [comment]
libpostal has been trained specifically to not make this type of mistake anymore, so presumably, this class of problems is no longer problematic.
