### ISSUE TITLE
Fallback queries need improved analyzers

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#534]
Fallback queries are very sensitive to exact text matches on the street property. Missing `street` or `road` results in no matches, for example. Same problem with pre and post directionals, such as `NE` or `W` for example.

This works: [/v1/search?text=533 NE Holladay st, Portland, OR 97232](
http://pelias.github.io/compare/#/v1/search%3Ftext=533%20NE%20Holladay%20st,%20Portland,%20OR%2097232)

This doesn't: [/v1/search?text=533 NE Holladay, Portland, OR 97232](
http://pelias.github.io/compare/#/v1/search%3Ftext=533%20NE%20Holladay,%20Portland,%20OR%2097232)

**Comment by orangejulius** [comment]
Is this the same as https://github.com/pelias/pelias/issues/484?

**Comment by dianashk** [comment]
Those might be similar, but this one is not as much concerned with synonyms as with omitted parts. Good to keep track of both for now.

**Comment by orangejulius** [comment]
As part of https://github.com/pelias/schema/pull/310, we rolled out improved analyzers for street fields that solve the particular issue of street components all being required.

The following queries all now return the address `533 NE Holladay St` in Portland:

- [/v1/search?text=533 Holladay St, Portland, OR 97232](http://pelias.github.io/compare/#/v1/search%3Ftext=533%20Holladay%20St,%20Portland,%20OR%2097232)
- [/v1/search?text=533 NE Holladay, Portland, OR 97232](http://pelias.github.io/compare/#/v1/search%3Ftext=533%20NE%20Holladay,%20Portland,%20OR%2097232)
- [/v1/search?text=533 Holladay, Portland, OR 97232](http://pelias.github.io/compare/#/v1/search%3Ftext=533%20Holladay,%20Portland,%20OR%2097232)

Note that _incorrect_ street components won't result in matches. So the following queries will not work:

- [/v1/search?text=533 NW Holladay St, Portland, OR 97232](/v1/search?text=533 NW Holladay St, Portland, OR 97232)
- [/v1/search?text=533 Holladay Ave, Portland, OR 97232](http://pelias.github.io/compare/#/v1/search%3Ftext=533%20Holladay%20Ave,%20Portland,%20OR%2097232)
