### ISSUE TITLE
Allow `city+state` queries to be handled by libpostal

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#535]
We are currently still using addressit and old-style query logic to address `city+state` queries. It would be ideal to switch them to the new fallback query logic and libpostal. Same goes for `state+country`.

**Comment by trescube** [comment]
What example are you seeing for `city+state` that falls back to addressit?  [Here's the code](https://github.com/pelias/api/blob/master/query/search.js#L167-L178) that enables it.  The same goes for [`city+country`](https://github.com/pelias/api/blob/master/query/search.js#L180-L192).

**Comment by dianashk** [comment]
This is no longer relevant since the `placeholder` integration has gone live for admin-only queries. Closing. 🎈
