### ISSUE TITLE
Special characters are replaced in API response (borough parameter)

### ISSUE THREAD

**Issue by jengeb** [pelias/pelias#536]
I am using the Mapzen Search API and need the `borough` return value for my application. Special characters, e.g. ö, are replaced by normal ones, e.g. o. 

![screenshot from 2017-04-03 15-10-43](https://cloud.githubusercontent.com/assets/3831683/24611012/03e94532-1881-11e7-95b5-1db951f0593d.png)

In this example the return value of `borough` should be Tempelhof-Sch**ö**neberg.

By the way, I experience the same result in my app using `sources=osm` although openstreetmap shows the data correctly.

**Comment by missinglink** [comment]
hey @jengeb, we don't actually strip those characters for display, we're simply providing them verbatim as we got them from our data providers.

for Openstreetmap that can be a mix of German and German-on-an-Englisch-keyboard, for other sources it may have gone through diacritical flattening at some point.

in regards to Schöneberg, we are sourcing the data from here: https://whosonfirst.mapzen.com/spelunker/id/1108815557/#11/52.4406/13.3737

i'm currently working on a language flag which should allow the user to switch display languages but in this case there's no alternative languages to display.

cc/ @stepps00 @dphiffer, hey guys, is there some way we can easily add the German versions of these strings via the spelunker web interface?

**Comment by stepps00** [comment]
@missinglink - the `wof:name` of a feature should not include these special characters, but we do store non-English variant and preferred names in the `name` properties.

In this case, the record has the following name, Tempelhof-Schöneberg:

```
"name:ger_x_preferred":[
        "Tempelhof-Sch\u00f6neberg"
    ],
```

You should see this property in the Spelunker, as well as the [raw GeoJSON](https://whosonfirst.mapzen.com/data/110/881/555/7/1108815557.geojson) of the record. This should be the case for all admin features in Berlin (see: https://github.com/whosonfirst-data/whosonfirst-data/issues/161).

**Comment by missinglink** [comment]
:+1: @stepps00 sorry I think I missed it in that file.

**Comment by stepps00** [comment]
@missinglink - no problem! That name property _should_ be in all admin features in Berlin. Let me know if you have any other questions about those records.

**Comment by jengeb** [comment]
Thank you for your replies! Is there any chance of including the `ger_x_preferred` or the `spatial_alias` property of Who's On First spelunker?

**Comment by missinglink** [comment]
@jengeb we are actively working on a more robust internationalization feature, please track the progress of https://github.com/pelias/api/pull/850

I am hopeful that this issue will be revolved within the next 30 days :)

**Comment by missinglink** [comment]
see: https://github.com/pelias/placeholder for more info

**Comment by missinglink** [comment]
note: when this feature rolls out you will only get the German version of the names if your browser sets its 'Accept-Language' header appropriately.

if it's set as Japanese or English then those strings will be returned instead, the default is English.

see https://github.com/pelias/api/pull/832 for more info.

**Comment by jengeb** [comment]
@missinglink Thank you for informing me about the current project plans and the time frame.
