### ISSUE TITLE
Geonames admin records have invalid WOF ids

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#539]
Here's a bug report from a user:

>Hey, guys! I think I found a bug in Mapzen search... Looks like it's
returning invalid WOF IDs when the source isn't Who's on First. Check
it out:
>
>https://search.mapzen.com/v1/search?text=Happy%20Valley,%20OR&sources=geonames&size=1
>
>In that case, it returns a Geonames record with a WOF ID of
`whosonfirst:locality:5730183`, which doesn't exist. (It's the same as
the geonames ID: `geonames:locality:5730183`)
>
>The correct WOF ID is `whosonfirst:locality:101715871`... If you switch
to only return whosonfirst records, you get the right lcoality ID:
>
>https://search.mapzen.com/v1/search?text=Happy%20Valley,%20OR&sources=wof&size=1
>
>Hope that's helpful!

**Comment by orangejulius** [comment]
This is a dupe of https://github.com/pelias/geonames/issues/107, right?
