### ISSUE TITLE
Streamline how API access all new microservices

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#550]
Now that we have interpolation and pip services to call out to from API, and placeholder soon to come, we should clean up all the inconsistencies and loose ends with regards to how they are integrated into our API code.

- [ ] make sure they are all represented the same way in pelias-config
- [ ] document how to add them to pelias-config
- [ ] add retry logic around all requests to these services
- [ ] use a common logging scheme for all requests going out as well as success and error responses
- [ ] combine code into common modules where possible

Am I missing anything?

**Comment by orangejulius** [comment]
@trescube I think this is done :)

**Comment by orangejulius** [comment]
This _is_ done
