### ISSUE TITLE
Reverse queries return admin results when point close or on centroid of admin area

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#551]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
First I forwarded geocoded a few countries and then thought it would be *fun* to feed the centroid results into `/reverse` to see what places are right at the centers of the countries.

So the reverse query for the United States ended up like this:

[/v1/reverse?point.lon=-96.999668&point.lat=39.715956](http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lon=-96.999668&point.lat=39.715956)

---
#### Here's what I got :scream_cat:
You can see the results give me United States first, which is not what one would expect unless `layers=coarse` was specified.

![screen shot 2017-04-22 at 2 11 36 pm](https://cloud.githubusercontent.com/assets/5446511/25306917/a1fdb5b2-2765-11e7-9fcf-00205ce489c0.png)

---
#### Here's what I was expecting :sparkles:
I would expect only `address` and `venue` records to show up in `reverse` queries unless otherwise specified via the `layers` parameter.

**Comment by trescube** [comment]
That expected behavior lines up with the end goal of where we're trying to get /reverse to. We didn't adjust any of the non-coarse logic yet so the United States happened to be the thing at any layer closest to that lat/lon.

**Comment by dianashk** [comment]
Looks like it's been fixed!!! :tada:

![screen shot 2017-07-27 at 11 52 47 am](https://user-images.githubusercontent.com/5446511/28679743-2c80571a-72c2-11e7-92d3-a53c54263bc4.png)
