### ISSUE TITLE
Harden dependency on libpostal

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#552]
Currently, if pelias-config specifies `parser: addressit` instead of the expected `parser: libpostal`, exceptions are thrown upon incoming requests. Since we have no intention of supporting Pelias without `libpostal` we should make that clear to users by removing the config parameter and documenting the hard dependency more explicitly.

Startup of API should also fail if libpostal is not properly installed or could not be loaded for some reason.

**Comment by dianashk** [comment]
Already moving in this direction with a default set to libpostal.

**Comment by orangejulius** [comment]
I think we've solved this now that we use the libpostal service.
