### ISSUE TITLE
Pelias (or Libpostal?) does not deal well with German streetnames written together/apart

### ISSUE THREAD

**Issue by dpprdan** [pelias/pelias#555]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

In German streetnames, the 'straße' (street), 'weg' (way), 'allee' (alley), etc. are sometimes written together with the "main" name (e.g. Bergstraße) or as a separate word (e.g. Berliner Straße). 

(Rule of thumb: When it's a place or a name, it is written apart, but that's not always true, see below. Actually I don't even know, whether there really are strict rules for this, so I suppose the same streetname could be written as one word in one place and apart in the other). 

Problem is: Pelias (on search.mapzen.com) does not find an address, when the streetname is not written correctly. Nominatim does.

---
### Example 1 Schauenburger Straße 25, Kiel 
(should be 'Schauenburgerstraße', which indeed is an exception to the rule above):

---
#### Mapzen :scream_cat:

https://search.mapzen.com/v1/search?text=Schauenburger%20Stra%C3%9Fe%2025,%20Kiel,%20Germany&size=1

{"geocoding":{"version":"0.2","attribution":"https://search.mapzen.com/v1/attribution","query":{"text":"Schauenburger Straße 25, Kiel, Germany","parsed_text":{"street":"schauenburger strasse","number":"25","city":"kiel","country":"germany"},"size":1,"private":false,"lang":{"name":"German","iso6391":"de","iso6393":"deu","defaulted":false},"querySize":1},"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1493223930743},"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[10.13489,54.32133]},"properties":{"id":"2891122","gid":"geonames:locality:2891122","layer":"locality","source":"geonames","source_id":"2891122","name":"Kiel","confidence":0.6,"match_type":"fallback","accuracy":"centroid","country":"Germany","country_gid":"whosonfirst:country:85633111","country_a":"DEU","region":"Schleswig-Holstein","region_gid":"whosonfirst:region:85682517","county":"Kiel","county_gid":"whosonfirst:county:102064125","locality":"Kiel","locality_gid":"geonames:locality:2891122","label":"Kiel, Germany"}}],"bbox":[10.13489,54.32133,10.13489,54.32133]}

Without the addition of "Germany" Pelias would even put me in Kiel, WI, USA. 🤣 

--- 
#### Nominatim 😇 

https://nominatim.openstreetmap.org/search/Schauenburger%20Strasse%2025,%20Kiel?format=json&addressdetails=1&limit=1

[{"place_id":"85803814","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"way","osm_id":"99866964","boundingbox":["54.3326375","54.3327367","10.1338606","10.1340565"],"lat":"54.33269365","lon":"10.1339583907643","display_name":"25, Schauenburgerstraße, Brunswik, Kiel, Schleswig-Holstein, 24105, Deutschland","class":"building","type":"yes","importance":0.321,"address":{"house_number":"25","road":"Schauenburgerstraße","city_district":"Brunswik","city":"Kiel","county":"Kiel","state":"Schleswig-Holstein","postcode":"24105","country":"Deutschland","country_code":"de"}}]

---
### Example 2 Holtenauerstraße 51, Kiel
(should be Holtenauer Straße)

---
#### Mapzen :scream_cat:
https://search.mapzen.com/v1/search?text=Holtenauerstra%C3%9Fe%2051,%20Kiel,%20Germany&size=1

{"geocoding":{"version":"0.2","attribution":"https://search.mapzen.com/v1/attribution","query":{"text":"Holtenauerstraße 51, Kiel, Germany","parsed_text":{"street":"holtenauerstrasse","number":"51","city":"kiel","country":"germany"},"size":1,"private":false,"lang":{"name":"German","iso6391":"de","iso6393":"deu","defaulted":false},"querySize":1},"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1493223630930},"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[10.13489,54.32133]},"properties":{"id":"2891122","gid":"geonames:locality:2891122","layer":"locality","source":"geonames","source_id":"2891122","name":"Kiel","confidence":0.6,"match_type":"fallback","accuracy":"centroid","country":"Germany","country_gid":"whosonfirst:country:85633111","country_a":"DEU","region":"Schleswig-Holstein","region_gid":"whosonfirst:region:85682517","county":"Kiel","county_gid":"whosonfirst:county:102064125","locality":"Kiel","locality_gid":"geonames:locality:2891122","label":"Kiel, Germany"}}],"bbox":[10.13489,54.32133,10.13489,54.32133]}

--- 
#### Nominatim 😇 

https://nominatim.openstreetmap.org/search/Holtenauerstra%C3%9Fe%2051,%20Kiel?format=json&addressdetails=1&limit=1

[{"place_id":"83960005","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"way","osm_id":"96391952","boundingbox":["54.3324583","54.3326415","10.1319823","10.1322512"],"lat":"54.3325499","lon":"10.1321167704516","display_name":"51, Holtenauer Straße, Brunswik, Kiel, Schleswig-Holstein, 24105, Deutschland","class":"building","type":"yes","importance":0.221,"address":{"house_number":"51","road":"Holtenauer Straße","city_district":"Brunswik","city":"Kiel","county":"Kiel","state":"Schleswig-Holstein","postcode":"24105","country":"Deutschland","country_code":"de"}}]

---
### Example 3 Fritz Reuter Strasse 100, Kiel
(should be Fritz-Reuter-Strasse 100, so this problem applies to hyphenated streetnames as well).

https://search.mapzen.com/v1/search?text=Fritz%20Reuter%20Strasse%20100,%20Kiel,%20Germany&size=1

{"geocoding":{"version":"0.2","attribution":"https://search.mapzen.com/v1/attribution","query":{"text":"Fritz Reuter Strasse 100, Kiel, Germany","parsed_text":{"street":"fritz reuter strasse","number":"100","city":"kiel","country":"germany"},"size":1,"private":false,"lang":{"name":"German","iso6391":"de","iso6393":"deu","defaulted":false},"querySize":1},"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1493224550429},"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[10.13489,54.32133]},"properties":{"id":"2891122","gid":"geonames:locality:2891122","layer":"locality","source":"geonames","source_id":"2891122","name":"Kiel","confidence":0.6,"match_type":"fallback","accuracy":"centroid","country":"Germany","country_gid":"whosonfirst:country:85633111","country_a":"DEU","region":"Schleswig-Holstein","region_gid":"whosonfirst:region:85682517","county":"Kiel","county_gid":"whosonfirst:county:102064125","locality":"Kiel","locality_gid":"geonames:locality:2891122","label":"Kiel, Germany"}}],"bbox":[10.13489,54.32133,10.13489,54.32133]}

Again, Nominatim can locate this address successfully.

---
#### Here's what I think could be improved :trophy:

If Nominatim can find it, Pelias should find it. So I guess Pelias (or Libpostal?!) should become space- and hyphen-agnostic.

**Comment by orangejulius** [comment]
Hi @dpprdan,
Thanks for reporting this. These are some great test cases. We have [known about](https://github.com/pelias/schema/issues/65) this issue for some time, and fortunately we are approaching the fix for this situation in one of our goals for this quarter, known as [alt names](http://pelias.io/milestones/alt_names/). Basically, right now Pelias has no understanding of the possibility of a place having multiple names (either multiple official names, names in different languages, or different styles of writing the exact same name as seen here). As we build the infrastructure for supporting multiple types of names for the same place, we can finally solve this!

Since you've given us all these great test cases, we'll keep this issue open until we can verify they're all fixed.

**Comment by dpprdan** [comment]
Thanks @orangejulius! 

So alt names would also cover "wrong", i.e. misspelled names? I.e. I would consider e,g, "Haupt Straße" a misspelled version of "Hauptstraße" (Main Street), since I don't think it is ever officially spelled that way. So I presume it would not be in the alt names of WOF or OSM (but I don't know. Can I look them up for a particular street somewhere?). 

Also what about Gaussstraße, Gauss Straße, Gausstraße, Gaus Straße, or Gauß-Straße as mis-/alt-spellings of Gaußstraße? Of the alternative spellings of "Gaußstrasse 52, Hamburg" Mapzen currently finds "Gaussstraße" only, Nominatim only "Gaussstraße", "Gauss Straße" and "Gauß-Straße".

Would it help if I provide more test cases here as I stumble upon them?

**Comment by dpprdan** [comment]
This issue seems to have been fixed in the meantime, i.e. the following return exact matches:

1. [Schauenburger Straße 25, Kiel](https://pelias.github.io/compare/#/v1/search?text=Schauenburger+Stra%C3%9Fe+25%2C+Kiel)
2. [Holtenauerstraße 51, Kiel](https://pelias.github.io/compare/#/v1/search?text=Holtenauerstra%C3%9Fe+51%2C+Kiel)
3. [Fritz Reuter Strasse 100, Kiel](https://pelias.github.io/compare/#/v1/search?text=Fritz+Reuter+Strasse+100%2C+Kiel)
4. [Gauß-Straße 52, Hamburg](https://pelias.github.io/compare/#/v1/search?text=Gau%C3%9F-Stra%C3%9Fe+52%2C+Hamburg)
5. [Gaussstrasse 52, Hamburg](https://pelias.github.io/compare/#/v1/search?text=Gaussstrasse+52%2C+Hamburg)
