### ISSUE TITLE
Standup a production instance of Placeholder

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#557]
Implement all the docker/chef scripts required to run `placeholder` in all environments.
While doing it write all the docs!

**Comment by dianashk** [comment]
The service is up and running with all required chef scripts and deploy commands.
Last thing to check on is if the data builds are automated. cc @orangejulius

**Comment by orangejulius** [comment]
There is _not_ currently any sort of automated build for placeholder. The data we're currently downloading from S3 across all environments in Mapzen Search was uploaded on May 26th, 2017.

**Comment by missinglink** [comment]
this can probably be tackled as part of the packer work, let's discuss at standup

**Comment by orangejulius** [comment]
This is an old Mapzen Search-related issue. Closing.
