### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#559]
# Where are we now?
- [ ] determine slowest queries and see how we can improve them
- [ ] determine max per-user qps limits
- [ ] determine capacity for various levels of infrastructure size
- [ ] document current scaling procedure so it's easy to get it right when adding new machines to the ES cluster

# Where do we want to be?
Research the following
- [ ] docker-swarm
- [ ] kubernetes
- [ ] vanilla chef (no op[s|z]works)
- [ ] Mini-ES-cluster
- [ ] Amazon AMIs

**Comment by orangejulius** [comment]
This is a Mapzen Search issue, although of course we do want to make all queries faster. We'll use more focused issues for those :)
