### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#560]
Further streamline the build process by adding more automated scheduling, validation, and rollups. Implement a higher level of abstraction for existing processes to make them more accessible via interfaces like Slack, for example. Possibly build an internal dashboard for managing all the builds in all of our environments.

- [ ] keep a failing build loaded on prod_build for investigation and do not start new builds until the failing state has been cleared manually
- [ ] move merging slack-bot to AWS

Connected to pelias/pelias#506
Connected to mapzen/pelias-deploy#6

**Comment by orangejulius** [comment]
Connected to https://github.com/mapzen/pelias-deploy/issues/6

**Comment by orangejulius** [comment]
This is an old Mapzen issue, nothing to do with Pelias
