### ISSUE TITLE
Alternate Names for POIs

### ISSUE THREAD

**Issue by fpurcell** [pelias/pelias#568]
When folks in Portland search for things named PDX, PCC and MLK, they are looking for Portland's Airport, Portland Community College and SE Martin Luther King Blvd.  

In TriMet's current geocoder, we have a list of synonyms that currently get loaded into SOLR: https://github.com/OpenTransitTools/loader/blob/master/ott/loader/solr/conf/synonyms.txt

The instance of Pelias that TriMet will replace SOLR will need to be loaded with a similar set of synonyms and alternate names: 
https://mapzen.com/products/search/?query=PDX&endpoint=autocomplete

So having a way to define alternative naming would be good.  I can see multiple data sources supplying the original POI (e.g., think "Portland International Airport" is from both OSM and OA; we also have a lot of transit landmarks that have common alternative names / abbreviations).   

Question: should alt naming come from the source, or a separate synonyms file?

**Comment by missinglink** [comment]
There are a few different ways we can deal with alternative names:

- synonym substitution ([example](https://github.com/pelias/schema/blob/master/street_suffix.js))
- importing a document twice with different names
- using an alternative `name` field as opposed to `name.default` (this will require some dev work)

regarding `autocomplete` we need to be careful with synonym substitutions like these:

```
p => portland
b => beaverton
c => clackamas
g => gresham
h => hillsboro
```

**Comment by missinglink** [comment]
also regarding synonym substitution for autcomplete, discuss `expansion vs. contraction` as per [jitter issues](https://github.com/pelias/pelias/issues/165).

**Comment by missinglink** [comment]
note: you can view a 4000+ line compiled version of the pelias schema here https://github.com/pelias/schema/blob/master/test/fixtures/expected.json

the javascript code in the pelias/schema repository is compiled together to create this file.

**Comment by orangejulius** [comment]
Support for custom synonyms was added in https://github.com/pelias/schema/pull/310. This helps users of Pelias customize their own instance with any abbreviations, aliases, or alt names that are important to them.
