### ISSUE TITLE
Configurable Default Coordinates for Location Bias

### ISSUE THREAD

**Issue by fpurcell** [pelias/pelias#569]
We'd like to define a focus lat & lon in pelias.json, and have the Pelias API use that coordinate as the default value for sorting results (e.g., default values for focus.point.lat & focus.point.lon).   

If a call to the Pelias API also sends the focus.point.lat=46.5&focus.point.lon=-122.6 URL parameters, then the Pelias API will override the default values for that request.

Even with the smaller regional dataset that the TriMet instance of Pelias will operate with, we still have ambiguous street addresses between towns ... and we want the results a customer sees to be sorted by towns closest to Portland (e.g., the value of our default focus coordinate):
https://search.mapzen.com/v1/autocomplete?text=710%20main%20st&focus.point.lat=46.5&focus.point.lon=-122.6&api_key=search-nHajqWA

**Comment by dianashk** [comment]
This is probably best accomplished via a new middleware similar to our existing [sizeCalculator](https://github.com/pelias/api/blob/master/middleware/sizeCalculator.js) in API.

You can add the new middleware component to the list in the [router code](https://github.com/pelias/api/blob/master/routes/v1.js#L114) after calcSize and pass `peliasConfig.api` down into the setup function.

The parameters of interest would be found in `req.clean.focus.point.lat` and `req.clean.focus.point.lon`.

When adding to pelias-config, the new values should go under the `api` object and perhaps be further grouped under another object, like `api.defaultQueryParams`.

Let us know if you need any help. Looking forward to the PR! ✨
