### ISSUE TITLE
New Transit Elements for both Searchabilty and Linkability

### ISSUE THREAD

**Issue by fpurcell** [pelias/pelias#570]
TriMet's search tools have always allowed searching via either a unique Stop ID, or else the actual name of the stop.  The practice of using stop ids is now very common among our customers (i.e., 10% of trips are planned with a stop id used as a search term).  Example trip: https://trimet.org/#/planner/form/from=2&to=2114.  I would venture to guess that many other agencies are similar in this regard.   

## Proposal 

I propose we add 4 new 'transit' elements to the Pelias model, in order to both allow searching on a unique id field, and also to support existing search->result page flows.  We need all 4 of the following proposed elements in order to create a generic solution that other transit agencies could use, and follows data standards from GTFS.

| Element        | Description     |
| ----------- |-------------
| transit_id = ["type":"string"]  | for stops, this is where stop_id would reside; for Park & Rides or Transit Centers, the landmark_id, etc… |
| transit_code = ["type": "string”] | borrowing from GTFS’s stop_code, this is the public facing representation of the ‘id’ and just like stop_code, if transit_code is null, then an application would not show any id … and searches would be based on name alone, and not name and/or code.|
|transit_agency_id = ["type": "string"]|this field has parallels to GTFS’s agency_id values|
|transit_agency_name = ["type": "string"]|this is the public facing name of the agency|

See:
  - https://developers.google.com/transit/gtfs/reference/stops-file
  - https://developers.google.com/transit/gtfs/reference/agency-file

## Why are Transit Elements Needed in a Geocoder?  
1. About 10% of public trip planning searches are based on Stop IDs.  Internally within TriMet, tools with a SOLR search form allows our employees to search by asset numbers.  For example, ticket vending machines have known IDs, which can be used in searching ... so different types of data, from stop landmarks to TVMs, have ids commonly used in a search step.  Thus, the transit_code element (along with transit_agency_name) added to Elasticsearch will be it's own searchable element in the index.

1. Beyond the search step, certain pages need an id (rather than a coordinate) from a search to then render a result page … a lat/lon or name is not enough to uniquely identify a stop ... only the stop_id can reliably be used to render a specific stop landing page.  Take a look at this page: https://trimet.org/#/tracker/stop/2.  After the customer searches for a stop, it's the transit_id (and agency_id, if multiple agencies are to be a part of a single system, ala the new MOD interface) elements that are then needed to further render the result page.

For example, typing the number ‘2’ into https://trimet.org/#/tracker/stop brings up stop pages for stop id 2.  After you visit this transit tracker search page, it then flows from search form to the tracker page result for the selected stop ... such a flow needs that transit_id element to move from one page to the next, and render that specific result.  Having access to the stop_id element in the geocoder result is needed to support this page flow.  (Further, if multiple transit agencies’ stop data are put into a Pelias index, agency_id is needed to distinguish overlaps in the stop id namespace, etc...).

Finally: making the system more general to other transit agencies would mean adopting rules in GTFS around _id and _code, where the _code element is the public facing identifier.  For TriMet’s stops, the _id == _code, but that’s not the case with other agencies’ stop data (and may not be the rule with other datasets, like P&Rs and TCs).  And thus, it would be the _code element that would be indexed for search within Elasticsearch.

**Comment by vesameskanen** [comment]
For your information, we have written a GTFS to pelias importer available here:

[https://github.com/HSLdevcom/pelias-gtfs ]

Currently we place the plain stopcode into name.short field, to allow searching using the pure code. The full descriptive name is the na,e.default field. Stop_id can be retrieved from the actual document id used for storing the data into Elasticsearch. Agency related attributes are not stored; only the transit type is stored as a gategory information.

**Comment by fpurcell** [comment]
Going to close ... workaround per Vesa's suggestion is to encode the stop_id and agency_id in the id of each ES/Pelias record.
