### ISSUE TITLE
Why is "aeroway:aerobridge" a result in the "venue" search layer?

### ISSUE THREAD

**Issue by stevevance** [pelias/pelias#573]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
I was searching for a business to see if it had an office marked in OSM, using this API call: 
````
https://search.mapzen.com/v1/search?text=M14%20LAND%20INVESTMENTS%20LLC&boundary.circle.lat=41.809148&boundary.circle.lon=-87.618538&boundary.circle.radius=100&layers=venue,address,locality,localadmin&api_key=KEY
````

---
#### Here's what I got :scream_cat:
One of the results was this jet bridge at O'Hare airport, which came from the "venue" layer. 

````
 {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -87.888509,
                    41.97381
                ]
            },
            "properties": {
                "id": "way:489961032",
                "gid": "openstreetmap:venue:way:489961032",
                "layer": "venue",
                "source": "openstreetmap",
                "source_id": "way:489961032",
                "name": "M14 Jetway",
                "confidence": 0.661,
                "accuracy": "point",
                "country": "United States",
                "country_gid": "whosonfirst:country:85633793",
                "country_a": "USA",
                "region": "Illinois",
                "region_gid": "whosonfirst:region:85688697",
                "region_a": "IL",
                "county": "Cook County",
                "county_gid": "whosonfirst:county:102084317",
                "localadmin": "Chicago",
                "localadmin_gid": "whosonfirst:localadmin:404496273",
                "locality": "Chicago",
                "locality_gid": "whosonfirst:locality:85940195",
                "borough": "North Side",
                "borough_gid": "whosonfirst:borough:958020405",
                "neighbourhood": "O'Hare International Airport District",
                "neighbourhood_gid": "whosonfirst:neighbourhood:1024608977",
                "label": "M14 Jetway, North Side, Chicago, IL, USA"
            },
            "bbox": [
                -87.888574,
                41.973694,
                -87.888445,
                41.973926
            ]
        }
````

---
#### Here's what I was expecting :sparkles:
I wasn't expecting this to be here because I don't consider it a venue or point of interest. The gate it's attached to *might* be a point of interest, but surely the jet bridge is not. 

---
#### Here's what I think could be improved :trophy:
Remove `aeroway:aerobridge` objects from the "venue" search layer.

**Comment by dianashk** [comment]
Hey, @stevevance! Thanks for this excellent issue report! It's super helpful to have links and example results included in the ticket. Also, it seems like you've done the work of tracking it down to our OSM tag whitelist already, which is awesome. That list of tags we import needs to be revisited.
Would it make more sense to include that sort of record in the `polylines` index or not have it in Pelias at all? Just thinking a user might want to be able to search for a bridge by name. What are your thoughts?

**Comment by stevevance** [comment]
I don't think jet bridges at airports should be included in any Pelias layer because I don't think it's anything that one would want to search for by name (also, how do you name a jet bridge?). If one needs that they should use Nominatim and search for jet bridges in a specific geography.

**Comment by missinglink** [comment]
Looks like the [default feature whitelist](https://github.com/pelias/openstreetmap/blob/master/config/features.js) is too broad here, specifically `'aeroway+name'`.

I remember writing some code to give better control over how to pick 'n choose tags, it's documented [here](https://github.com/pelias/pbf2json#advanced-usage).

@stevevance would you be able to draft a proposal to change it?

**Comment by stevevance** [comment]
I see a lot of potentially useful "aeroway" values [on the wiki](http://wiki.openstreetmap.org/wiki/Aeroways), but I don't see a way in the documentation to eliminate "aerobridge" as a value. 

Is this a valid option?
`-tags="aeroway!~aerobridge"`

**Comment by missinglink** [comment]
unfortunately not, it doesn't currently support 'everything except x', although I could add that.

looking at the [taginfo values](https://taginfo.openstreetmap.org/keys/aeroway#values) there are a bunch of other tags we probably want to exclude, such as:

- `parking_position`: 'A location where an airplane can park'
- `holding_position`: A point behind which aircraft are considered clear of a crossing way
- `windsock`: An object that shows pilots wind direction and speed.
- `light`
- `model_runway`
- `parachute_dropzone`
- `proposed`

the `aeroway` tag seemed to actually have many more tags not applicable for geocoding. I remember a while back working on autocomplete features and finding venues named 'A', 'B', 'C' etc. eventually figured out these were airport gates!

what about instead of adopting a blacklist we go with a whitelist, something like this:

```
# general air travel
aeroway=terminal -- An airport passenger building
aeroway=gate -- A gate number at an airport where passengers wait before boarding their flight

# less common terminal types
aeroway=aerodrome -- An airport (other than heliport)
aeroway=helipad -- a landing area or platform for helicopters
aeroway=airstrip -- A field or area where light aircraft can land and take off from.
aeroway=heliport
aeroway=areodrome
aeroway=spaceport
aeroway=landing_strip
aeroway=airfield
aeroway=airport
```

after that, the keys seem to be very uncommonly utilized

**Comment by missinglink** [comment]
node:279230739 would still be included:

```bash
# proposed change

$ grep "M14" chicago.new.json 
{"id":279230739,"type":"node","lat":41.973693600000004,"lon":-87.8884452,"tags":{"aeroway":"gate","name":"M14","ref":"M14"}}
```

but the jetway (way:489961032) would be excluded:

```bash
# current behaviour

$ grep "M14" chicago.old.json 
{"id":279230739,"type":"node","lat":41.973693600000004,"lon":-87.8884452,"tags":{"aeroway":"gate","name":"M14","ref":"M14"}}
{"id":489961032,"type":"way","tags":{"aeroway":"aerobridge","name":"M14 Jetway","path":"footpath"},"centroid":{"lat":"41.973810","lon":"-87.888509"},"nodes":[{"lat":"41.973926","lon":"-87.888574"},{"lat":"41.973694","lon":"-87.888445"}]}
```

is that what you're looking for @stevevance ?

**Comment by missinglink** [comment]
opened a PR here https://github.com/pelias/openstreetmap/pull/280, feedback welcome

**Comment by stevevance** [comment]
`is that what you're looking for @stevevance ?`
Yep!

**Comment by missinglink** [comment]
great, it's on it's way to production now :)
