### ISSUE TITLE
Upgrade all Travis tests to use new Ubuntu version

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#575]
TravisCI [recently added support](https://blog.travis-ci.com/2016-11-08-trusty-container-public-beta/) for Ubuntu 14. While Ubuntu 12 is still the default, the newer version of Ubuntu can now be selected.

In general Ubuntu 14 has newer packages and will probably make it much easer to keep all our tests running properly.

In particular, Ubuntu 14 does not require installing a newer version of gcc to compile Node.js modules. Something close to half the runtime for most of our Travis runs is currently taken up by this installation, so we have the potential to make our tests run much faster.

A test branch for Openaddresses runs in [~1 minute 30](https://travis-ci.org/pelias/openaddresses/builds/226559106) with these changes, compared to [~2 minutes 15 - 3 minutes](https://travis-ci.org/pelias/openaddresses/builds/223332024) on master.

**Comment by dianashk** [comment]
@orangejulius, please leave a description of what the change should look like and others can help get this done.

**Comment by orangejulius** [comment]
Here's an example of the changes involved. They're quite straight forward: 

* change the distribution to `trusty` (ubuntu's codename for [version 14.04](https://en.wikipedia.org/wiki/List_of_Ubuntu_releases#Ubuntu_14.04_LTS_.28Trusty_Tahr.29))
* Remove all of the gcc-4.8 related lines. gcc-4.8 is required for building Node.js modules. it was not included by default in Ubuntu 12, but _is_ included in Ubuntu 14.

![image](https://user-images.githubusercontent.com/111716/28684586-eec73892-72d2-11e7-800c-9b91690e3e10.png)
https://github.com/pelias/openaddresses/compare/test-travis-trusty

**Comment by orangejulius** [comment]
Oh good news! Travis has already started making [trusty the default](https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming?utm_source=web&utm_medium=banner&&utm_campaign=trusty-default) so that first line won't be needed. Only removing all the gcc-4.8 lines will be required.

**Comment by orangejulius** [comment]
September 1st is now far behind us and Travis has [rolled out Ubuntu 14 (trusty) as the default](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status) on schedule! I've updated the OA testing branch and submitted it as a PR(https://github.com/pelias/openaddresses/pull/288), and we should make similar PRs to our other main repositories as soon as we can. It really should make our builds twice as fast!
