### ISSUE TITLE
Country in querystring does not prioritize locations in said country.

### ISSUE THREAD

**Issue by jessalfredsen** [pelias/pelias#577]
Hey team! 

I am using your awesome geocoding engine and enjoying it a lot! 

---
#### Here's what I did :innocent:

One of my use cases are geocoding Twitter location fields. This is a unformatted text field, but one of the most common formattings are `[City], [Country/Country code]`, fx `Copenhagen, Denmark` or `Durham, UK`. 

---
#### Here's what I got :scream_cat:

`Durham, England` and `Durham, UK`  resolves to Durham, ON, Canada 

[pelias.io/compare/Durham, UK](http://pelias.github.io/compare/#/v1/search%3Ftext=Durham,%20UK)
![screen shot 2017-05-17 at 10 45 23](https://cloud.githubusercontent.com/assets/3910075/26145783/0bdd61bc-3aee-11e7-9b1e-509077e1580d.png)

[pelias.io/compare/Durham, England](http://pelias.github.io/compare/#/v1/search%3Ftext=Durham,%20England)
![screen shot 2017-05-17 at 10 44 56](https://cloud.githubusercontent.com/assets/3910075/26145794/180ef5a4-3aee-11e7-90a6-20ae03592da7.png)
In the case of `Durham, England` I see pelias.dev.mapzen.com resolving it to Arkansas, USA 😱 

##### Some further details:
When looking at the json result from the API (`search.mapzen.com/v1/search`), I see that the query is parsed correctly:
```javascript
{
...
"parsed_text": {
"name": "Durham",
"regions": [
"Durham",
"England"
],
"admin_parts": "England"
}
...
}
```

So even though the `admin_parts` are parsed as England the result with the highest confidence is 

```javascript
"properties": {
"id": "5944369",
"gid": "geonames:county:5944369",
"layer": "county",
"source": "geonames",
"source_id": "5944369",
"name": "Durham",
"confidence": 0.956,
"accuracy": "centroid",
"country": "Canada",
"country_gid": "whosonfirst:country:85633041",
"country_a": "CAN",
"region": "Ontario",
"region_gid": "whosonfirst:region:85682057",
"region_a": "ON",
"label": "Durham, ON, Canada"
}
```

even though this result 

```javascript
"properties": {
"id": "2650628",
"gid": "geonames:locality:2650628",
"layer": "locality",
"source": "geonames",
"source_id": "2650628",
"name": "Durham",
"confidence": 0.734,
"accuracy": "centroid",
"country": "United Kingdom",
"country_gid": "whosonfirst:country:85633159",
"country_a": "GBR",
"macroregion": "England",
"macroregion_gid": "whosonfirst:macroregion:404227469",
"region": "County Durham",
"region_gid": "whosonfirst:region:85684523",
"locality": "Durham",
"locality_gid": "geonames:locality:2650628",
"label": "Durham, England, United Kingdom"
}
```

has England in both the label and as macroregion. The results with England in the macroregion and label scores a confidence of **0.734** where as the Canada result scores **0.956**.

---
#### Here's what I was expecting :sparkles:

My question is if a name of a country in the query string shouldn't prioritize locations in that country?

---
#### Here's what I think could be improved :trophy:

This works quite well for major cities, [London](http://pelias.github.io/compare/#/v1/search%3Ftext=London) resolves to the largest London, which is the one in UK. Where as [London, Canada](http://pelias.github.io/compare/#/v1/search%3Ftext=London,%20Canada) correctly resolves to the London in Canada, as well as the [London, USA](http://pelias.github.io/compare/#/v1/search%3Ftext=London,%20USA) also resolves to the Londons in USA. This is also the case for Paris and other major cities with ubiquitous names, but not for smaller cities like Durham, UK.

Any feedback on this will be much appreciated 🖖  and also in general thanks for a great product 💃 

Cheers,
Jess 🇩🇰

**Comment by martinmalek** [comment]
+1

**Comment by missinglink** [comment]
Good news, we've been working on a [new parsing library](https://github.com/pelias/placeholder) which we're starting to roll out this week.

We are fairly confident that issues like this will be completely resolved using the new library, with the new behavior being 'only give me places called Durham inside of places called England, nothing else', so not only will the ordering issue be resolved, but also the results will be fewer, more targeted and less noisy.

Have a play with [the demo](http://parser.wiz.co.nz/demo/).

The Placeholder (that's the name :) parser will be rolled out gradually:

- Support for returning results in multiple languages (expected this week)
- Use Placeholder for all 'admin only' queries (queries containing no venue or address component, expected within 2 weeks)
- Use Placeholder to establish the parentage of all search queries (hopefully completed this quarter)
- Adapt the library to support autocomplete queries (no timeframe at this stage)

Let's track this issue as an acceptance test for https://github.com/pelias/api/pull/850

**Comment by missinglink** [comment]
oh :man_facepalming: our data has this labeled as `County Durham` instead of `Durham`, I'll open an issue to resolve this as a synonym issue.

**Comment by missinglink** [comment]
In fact, referring to it as `County Durham, UK` or `County Durham, England` returns the correct result first.

**Comment by mleginus** [comment]
@missinglink thanks for your help!

**Comment by missinglink** [comment]
@mleginus looks like this is now resolved, I'm going to close it. 

```
/v1/search?text=Durham, UK

1)	County Durham, England, United Kingdom
```
