### ISSUE TITLE
Structured queries with postalcode + admin areas don't find postalcode

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#578]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

[/v1/search/structured?postalcode=94110&region=California](http://pelias.github.io/compare/#/v1/search/structured%3Fpostalcode=94110&region=California)

---
#### Here's what I got :scream_cat:

![screen shot 2017-05-19 at 11 04 48 am](https://cloud.githubusercontent.com/assets/5446511/26254007/23aaad5e-3c83-11e7-933e-ba95bcb3a8f5.png)

---
#### Here's what I was expecting :sparkles:

The postal code exists in the index and is found when searching for it without additional admin areas specified.

[/v1/search/structured?postalcode=94110](http://pelias.github.io/compare/#/v1/search/structured%3Fpostalcode=94110)

![screen shot 2017-05-19 at 11 06 29 am](https://cloud.githubusercontent.com/assets/5446511/26254182/a83f682a-3c83-11e7-8c27-273ccb9512c7.png)

---
#### Here's what I think could be improved :trophy:

Without the ability to limit by additional admin areas it's impossible to account for same postalcodes in different countries, which is very common. We need to be able to return postalcodes as first-class objects and not just use them as nice to have conditions.

**Comment by burritojustice** [comment]
also search for a street name and a state usually returns the centroid of the state (but not always)

see 
`Robert E. Lee St` and `Virginia`
`Robert E. Lee St` and `Texas`
`Robert E. Lee Ave` and `Texas`
`Robert E. Lee` and `Texas`

**Comment by dianashk** [comment]
Can't wait to use @tigerlily-he's new awesome api debugger to dig into this issue!

**Comment by rabidllama** [comment]
I have had a quick look around and I think the issue lies in the middleware/trimByGranularityStructured.js file. in the layers list, postalcode is missing and if I add it, then I get the postalcode record in the list. I don't know the ins and outs of adding this and whether it causes problems elsewhere, but the tests seem to run ok.

**Comment by dianashk** [comment]
Update: this is now on staging and should roll out to production by end of the week. 🌮

**Comment by dianashk** [comment]
Fixed and in production. :rocket:

![Screen Shot 2017-10-16 at 12.06.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/54e4bf1081dbf91d007ab6d3/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236455f56b7191a379ed0c2b57415c4abc21254d58eeb9cb74fce36f34985619e8d5385b26903c10ffbb831bbe05bb278b4fd0e0b4834dc0fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34be94c52a4133666e0703e6e0a.png)

**Comment by rabidllama** [comment]
Hi Diana, sorry I didn't get chance to look at it over the past few weeks as I have been away on holidays. Glad that it has all gone through though and I will get our instance updated asap :)
