### ISSUE TITLE
Can't search text: "text_analyzer.parse is not a function"

### ISSUE THREAD

**Issue by dr0i** [pelias/pelias#579]
I am trying to install pelias with `OpenAddresses` as solely data base.
Elasticsearch (ES) indexing was succesful. I can curl ES e.g. like ` curl 'http://localhost:9200/pelias/_search?q=bonn'` and get results. However, `curl  'http://localhost:3100/v1/search?text=bonn` results in the error message: `{"error":"text_analyzer.parse is not a function"}`.

**Comment by dr0i** [comment]
Going to install the recommended `libpostal` text analyzer as it sounds like it has could have something to do with it.

**Comment by dr0i** [comment]
Btw., `npm test` in `api` gives one error:

    19.519Z - error: [api] RequireTransport: failed to connect to interpolation service

but passes ok:

     636 tests
     1419 passed
     Pass!

**Comment by dr0i** [comment]
Changed something and restarted, now I got : 

     error: [api] elasticsearch error [query_parsing_exception] [match] analyzer [peliasQueryFullToken] not found, with { index="pelias" & line=1 & col=53 }

**Comment by orangejulius** [comment]
Hi @dr0i!
Thanks for reporting these issues. I do believe you're right that enabling libpostal should fix your first error. I've opened a PR to make it the default in the future, which we've been talking about doing for a while anyway.

Your second issue regarding the Elasticsearch error is something we've seen before. Did you use the https://github.com/pelias/schema/ repo to set up the schema? Unfortunately Elasticsearch tries a little too hard to be easy to use, and will allow you to proceed with using Pelias before properly setting up  the schema. Errors like this would be the result. Let us know if that helps and please reach out if you have any other questions!

**Comment by dr0i** [comment]
Hi @orangejulius,
creating the index using https://github.com/pelias/schema/  did the job - thx for your help!
