### ISSUE TITLE
Boost matching street names or other layers when using a focus point with autocomplete

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#587]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
A user contacted us through support about some unexpected results when using a focus point with autocomplete. 

With a focus point:
[/v1/autocomplete?focus.point.lat=51.3&focus.point.lon=-0.29&text=Broomfield Road surbiton](http://pelias.github.io/compare/#/v1/autocomplete%3F&focus.point.lat=51.3&focus.point.lon=-0.29&text=Broomfield%20Road%20surbiton)
No focus point: 
[/v1/autocomplete?text=Broomfield Road surbiton](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Broomfield%20Road%20surbiton)

---
#### Here's what I got :scream_cat:
The results are actually not as good when a focus point is included. None of the top 10 results are the expected location. They are all points (addresses), but not in the correct area.

https://mapzen.com/search/explorer/?query=autocomplete&text=broomfield%20road%20surbiton&focus.point.lat=51.3&focus.point.lon=-0.29

 10 Broomfield Road, London, England, United Kingdom
 85 Broomfield Road, Chelmsford, England, United Kingdom
 3 Broomfield Road, Coventry, England, United Kingdom
 1 Broomfield Road, Coventry, England, United Kingdom
 2 Broomfield Road, Coventry, England, United Kingdom
 7 Broomfield Road, Coventry, England, United Kingdom
 9 Broomfield Road, Coventry, England, United Kingdom
 11 Broomfield Road, Coventry, England, United Kingdom
 15 Broomfield Road, Coventry, England, United Kingdom
 19 Broomfield Road, Coventry, England, United Kingdom

---
#### Here's what I was expecting :sparkles:
This is the expected result (the first one returned without the focus point)
https://mapzen.com/search/explorer/?query=place&ids=openstreetmap%3Astreet%3Apolyline%3A3270145

"properties": {
        "id": "polyline:3270145",
        "gid": "openstreetmap:street:polyline:3270145",
        "layer": "street",
        "source": "openstreetmap",
        "source_id": "polyline:3270145",
        "name": "Broomfield Road",
        "street": "Broomfield Road",
        "accuracy": "centroid",
        "country": "United Kingdom",
        "country_gid": "whosonfirst:country:85633159",
        "country_a": "GBR",
        "macroregion": "England",
        "macroregion_gid": "whosonfirst:macroregion:404227469",
        "region": "Kingston upon Thames",
        "region_gid": "whosonfirst:region:85684387",
        "locality": "London",
        "locality_gid": "whosonfirst:locality:101750367",
        "neighbourhood": "Surbiton",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85790841",
        "label": "Broomfield Road, London, England, United Kingdom"
      },

---
#### Here's what I think could be improved :trophy:
@dianashk and I chatted about this. It looks like the focus point tunes the search to return results that are venues and addresses (points), but overlooks matching street names or features from other layers. 

We should look at boosting based on layer in https://github.com/pelias/api/blob/master/query/autocomplete_defaults.js

**Comment by PetrDlouhy** [comment]
Hi, I have similar problem with the autocomplete. When I specify focus point, I got many address points, but many other results are suppressed. I tried to set layers, but it's order doesn't seem to change anything.

My case is, that when I am searching city Plzeň (Pilsen) inside Prague, Plzeň doesn't appear in the search box:
https://search.mapzen.com/v1/autocomplete?format=json&focus.point.lat=50.07099999999993&focus.point.lon=14.37458999999967&boundary.country=CZE&text=plzen

**Comment by missinglink** [comment]
hey, thanks for the bug report, this is a known issue and we are planning some new work to fix it in Q3 2017.

**Comment by missinglink** [comment]
you can track the progress of this, and other improvements to our autocomplete endpoint in https://github.com/pelias/pelias/milestone/3

**Comment by orangejulius** [comment]
The focus point query now returns many streets including the intended result.

I suspect this was fixed in https://github.com/pelias/api/pull/1162, where we removed a query clause that was limiting focus.point queries from boosting only venues and addresses. :tada:
