### ISSUE TITLE
Discuss data/search quality

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#59]
Discuss our approach to data quality and search quality.

#### Original data source:
 * evaluate data using common data quality dimension, as described here: http://www.qas.co.uk/blog/data-quality/3-2-1-start-measuring-data-quality/
  * generate and publish error logs where possible so there are actionable items for the community to tackle
 * publicize computed metrics and track over time, which each update to original data source. This will create a viral loop for fixing these issues.

#### Pelias import filtering:
 * show quantitive improvement in the data set, e.g.
  * duplicates went from 20% to 0%
  * wikipedia tags went from 30% to 45%

#### Pelias search quality:
 * build out acceptance test suite and crowdsource test cases
 * head-to-head result comparisons with competitor services (nominatim)

**Comment by dianashk** [comment]
Discuss how to set expectations in acceptance tests results. When should `priorityThresh` be set to 10/5/3/1 and how is that decided?

**Comment by lokkju** [comment]
What about when original data sources seems correct (nominatim returns a correct result using OSM data), but pelias seems incorrect (mis-geocodes the address).

An example would be "964 5TH AVE, SAN DIEGO, CA 92101"

**Comment by dianashk** [comment]
@lokkju, that would just be considered a falling test. Thanks for providing that test case. We'll be sure to add it to our test suite.

**Comment by riordan** [comment]
This has been a great way to spur discussion of improving search quality. Now that it's a constant part of the process of the team, I'm going to close the ticket.
