### ISSUE TITLE
Validate and improve the Pelias getting started guide

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#591]
It's been a while since we've gone through and validated all the steps in our getting started guide. Some things have surely changed and some things were never explained well, to begin with. Let's fix that.

- [x] Follow the [setup instructions](https://github.com/pelias/pelias/blob/master/INSTALL.md) to get a local instance of Pelias up and running with only data for New York City loaded.

Ensure all existing importers have been set up and executed:
- [x] openstreetmap (with admin-lookup)
- [x] openaddresses (with admin-lookup)
- [x] geonames (with admin-lookup)
- [x] polylines
- [x] whosonfirst
- [x] interpolation

Ensure the newly setup API instance has the following features/utilities working as expected:
- [x] point-in-polygon service is running and being used for `/reverse` geocoding requests
- [x] interpolation service is running and being used for `/search` geocoding requests with addresses
- [x] `placeholder` service is running and being used for language support and admin-only `/search` queries

**Comment by dianashk** [comment]
There is an [awesome PR from an external contributor](https://github.com/pelias/pelias/pull/567) that we'd love to merge as soon as we can, but it still needs to be thoroughly reviewed. That could be done as part of this task to avoid duplicating work that's already been done elsewhere.

**Comment by tigerlily-he** [comment]
Related Pull Requests that fixed bumps in the installation process: 

- [moved 'parser' placeholder url part to service config](https://github.com/pelias/api/pull/907)
- [fix stdin redirection](https://github.com/pelias/interpolation/pull/66)
- [recompile pbf2json on all architectures](https://github.com/pelias/pbf2json/pull/43) & [Update pbf2json to the latest version 🚀](https://github.com/pelias/openstreetmap/pull/283)
