### ISSUE TITLE
Autocomplete for "nashville" against sources=wof doesn't return Nashville, TN

### ISSUE THREAD

**Issue by simonw** [pelias/pelias#592]
If I hit autocomplete with the string "nashville" I don't get back Nashville, Tennessee.

Example URL: http://search.mapzen.com/v1/autocomplete?sources=wof&layers=locality,county,neighbourhood,borough,localadmin&api_key=mapzen-XXX&text=nashville

Results (reformatted to just ID and label):

85816591 East Nashville, Nashville, TN, USA
85855987 West Nashville, Nashville, TN, USA
85893481 South Nashville, Nashville, TN, USA
85980525 Nashville, NC, USA
85936711 Nashville, GA, USA
85920767 Nashville, AR, USA
404497063 Nashville, IL, USA
420529213 Nashville, USA
85893473 North Nashville, Nashville, TN, USA
404494819 Nashville, WI, USA

None of these are Nashville, TN.

**Comment by simonw** [comment]
If I leave "neighourhood" out from the list of layers, I get this: http://search.mapzen.com/v1/autocomplete?sources=wof&layers=locality,county,borough,localadmin&api_key=mapzen-XXX&text=nashville

85980525 Nashville, NC, USA
85936711 Nashville, GA, USA
85920767 Nashville, AR, USA
404497063 Nashville, IL, USA
404494819 Nashville, WI, USA
404516193 Nashville, MO, USA
404509973 Nashville, MN, USA
404475413 Nashville, ME, USA
85939951 Nashville, IL, USA
101723183 Nashville, TN, USA

Hooray! We got back Nashville, TN - but it was in 10th place. It's clearly the most "famous" Nashville out of those options, so ideally it would come up first. Maybe autocomplete could take population into account when calculating relevancy?

**Comment by simonw** [comment]
Incidentally, this Nashville is particularly interesting: https://whosonfirst.mapzen.com/spelunker/id/420529213/ - it's a Neighourhood in the USA with no region (state) attached to it. I found this through a bug in my code that was expecting region to be populated for all US neighbourhoods. Should I open a separate bug for this, maybe in one of the whosonfirst repos?

**Comment by missinglink** [comment]
thanks for the bug report.

we are currently planning some bugfixes & improvements to the `/v1/autocomplete` endpoint. we have been focussed on `/v1/search` for some time and need to get back to fixing some of these autocomplete 'balance' issues.

**Comment by missinglink** [comment]
the search endpoint (in dev, soon in production) returns:

```
 1)	Nashville, TN, USA
 2)	Nashville, NC, USA
 3)	Nashville, GA, USA
 4)	Nashville, AR, USA
 5)	Nashville, KS, USA
 6)	Nashville, IN, USA
 7)	Nashville, MI, USA
 8)	Nashville, IL, USA
 9)	Nashville, OH, USA
10)	Nashville, IL, USA
11)	Nashville, WI, USA
12)	Nashville, MO, USA
13)	Nashville, MN, USA
14)	Nashville, ME, USA
```

@simonw how do those results look to you for `?text=nashville`?

**Comment by simonw** [comment]
Those results look perfect, I'd love to be able to get those I have to be able to get those from autocomplete as well as search

**Comment by missinglink** [comment]
I'm on it, will let you know when I have an update

**Comment by orangejulius** [comment]
I'm not sure when it changed, but Nashville is now returned first for autocomplete queries.

It's likely population data was missing in Who's on First, and was added at some point.

http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=nashville
![image](https://user-images.githubusercontent.com/111716/45192369-f6d4d200-b215-11e8-8a38-323652b26c30.png)
