### ISSUE TITLE
Speed up OSM build

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#595]
[edit] missinglink

the pelias OpenStreetMap importer has been highlighted as one of the slower builds, from my understanding, it can take >1 day to build.

my suspicion is that there are some significant bottlenecks in the import process which can be removed, with the grand plan of using what's learned speeding up the OSM build to speed up all importers.

the goal is to try to run the planet OSM build in <3 hrs, it's an ambitious goal yet achievable. the grand future goal is to try and bring our full build cycle down to <1 day.

on top of import speed, there are other design goals to consider:
- [ ] not making the code clarity/ops setup more complex.
- [ ] reducing the overall disk & ram requirements rather than increase them.
- [ ] avoiding periods of build instabilities due to new software/ configuration.

**Comment by missinglink** [comment]
the OSM build process is split into several stages, each of which has room for improvement:

#### download the data

the planet file is hosted at planet.openstreetmap.org, two options for speeding up the download are:

- hosting the data closer to our data center in an AWS us-east bucket. (already available internally for mz employees)
- using a more advanced download utility such as `aria2`

**Comment by missinglink** [comment]
my two main points of focus are `3.` and `4.`, due to the volume of data in the `PBF` file and the amount of records requiring PIP, small per-cycle improvements in these areas will add up to large savings overall.

**Comment by orangejulius** [comment]
Since https://github.com/pelias/pbf2json/pull/70, the OSM importer is significantly faster and is no longer a specific bottleneck for builds! :tada:
