### ISSUE TITLE
Test and validate docker compose setup process

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#596]

**Comment by tigerlily-he** [comment]
- [ ] Check that Elasticsearch starts and connects 

Ensure all existing importers have been set up and executed:

- [ ]  openstreetmap (with admin-lookup)
- [ ]  openaddresses (with admin-lookup)
- [ ]  geonames (with admin-lookup)
- [ ]  polylines
- [ ]  whosonfirst
- [ ]  interpolation

**Comment by missinglink** [comment]
hey @tigerlily-he is there anything more I can do to help here?

we should also add

- [ ] document process for using docker and docker-compose on OSX
