### ISSUE TITLE
Add acceptance tests for universities

### ISSUE THREAD

**Issue by tigerlily-he** [pelias/pelias#598]
Create acceptance tests that query university names to test parser. 

- Including affiliated umbrella university network
- university has name of city in a different region
- apostrophe in name
- university that has a street with identical name in a different part of the country
- removing diacritics
- finding a particular college (without including the locality/region) when there are many with the same name
- English translation of university name
- university name in native language
- finding regional campus with the general university name
- omit comma when specifying locality/region of university when there are many with the same name
- include comma when specifying locality/region of university when there are many with the same name

**Comment by missinglink** [comment]
see https://github.com/endSly/world-universities-csv/blob/master/world-universities.csv

**Comment by tigerlily-he** [comment]
Points of Failure

- [ ] addresses and names of places in English of places where the main language is not English 
- [ ] Abbreviations of non-English words (eg. "Av." for "Avenida, "nte." for "Norte", "st." for "Straße")
- [ ] Abbreviations of states and provinces outside the United States
