### ISSUE TITLE
Need abbreviation for states in AUS

### ISSUE THREAD

**Issue by tigerlily-he** [pelias/pelias#601]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

I was searching for the US Consulate in Australia:  16 St. George’s Terrace Perth, WA, Australia

http://pelias.github.io/compare/#/v1/search%3Ftext=16%20St.%20George%E2%80%99s%20Terrace%20Perth,%20WA,%20Australia

---
#### Here's what I got :scream_cat:
The results are fallbacks to Australia, the country

1)	Australia
2)	Australia
---
#### Here's what I was expecting :sparkles:

http://pelias.github.io/compare/#/v1/search%3Ftext=16%20St.%20George%E2%80%99s%20Terrace%20Perth,%20Western%20Australia,%20Australia

When "WA" is expanded to "Western Australia," an exact address match is found.

---
#### Here's what I think could be improved :trophy:

Abbreviations for states in Australia

**Comment by orangejulius** [comment]
Both these queries now work the same! Thanks for adding the abbreviations!!! 🎉 
![image](https://user-images.githubusercontent.com/111716/30752374-1ad2befa-9f8a-11e7-8cef-43423eba07af.png)

There are still Australian region abbreviation issues when searching for the actual regions, but those are tracked in #631 and we expect Placeholder data updates to help with that.
