### ISSUE TITLE
Union College Kentucky gives incorrect results without comma

### ISSUE THREAD

**Issue by tigerlily-he** [pelias/pelias#602]
#### Here's what I did :innocent:

I am searching for a venue called "Union College" located in Kentucky. I enter "Union College Kentucky" (no comma)
http://pelias.github.io/compare/#/v1/search%3Ftext=union%20college%20kentucky

---
#### Here's what I got :scream_cat:

1)	Union, KY, USA
 2)	Union Village, Union, KY, USA
 3)	Union Community Center, Union, KY, USA
 4)	Union Bluffs, Union, KY, USA
 5)	Union Baptist Church, Union, KY, USA
 6)	Union Presbyterian Church, Union, KY, USA
 7)	Union Bluffs Drive, Union, KY, USA
 8)	Union City Building, Union, KY, USA
 9)	Union Fire/ESA, Union, KY, USA
10)	Union Emergency Services Alliance Station
---
#### Here's what I was expecting :sparkles:

I was expecting "Union College, Barbourville, KY, USA" which I get when I include a comma:

http://pelias.github.io/compare/#/v1/search%3Ftext=Union%20College,%20Kentucky

---
#### Here's what I think could be improved :trophy:
 Without Comma | With Comma 
--- | ---
 "parsed_text": <br> "state": "KY", <br> "regions": [ <br> "Union College" <br>] <br> } | "parsed_text": {<br> "name": "Union College", <br>"state": "KY", <br>"regions": [ <br> "Union College" <br>], <br>"admin_parts": "Kentucky"<br> }

Filtering by layers=venues doesn't help either: http://pelias.github.io/compare/#/v1/search%3Flayers=venue&text=Union%20College%20Kentucky

Without the comma, adding the city name falls back to the locality: http://pelias.github.io/compare/#/v1/search%3Ftext=Union%20College%20Barbourville%20Kentucky 

Part of https://github.com/pelias/pelias/issues/598

**Comment by trescube** [comment]
addressit does a terrible job when there are no commas splitting the parts of the query (and libpostal doesn't handle this situation yet).

**Comment by tigerlily-he** [comment]
Similar issue with ["Washington University St. Louis":](http://pelias.github.io/compare/#/v1/search%3Fboundary.country=USA&text=washington%20university%20st%20louis)

Expected result is ["Washington University, Clayton, MO, USA":](http://pelias.github.io/compare/#/v1/search%3Fboundary.country=USA&text=washington%20university,%20st%20louis)

The interesting aspect is that the full university name is ["Washington University _**in**_ St. Louis"](https://wustl.edu/). (The record in OSM is just "Washington University".) The "in" throws results off even more. Furthermore, the university is in Clayton, a suburb right outside the city of St. Louis, though it is part of St. Louis county. 

["Washington University in St. Louis" query, bounded by country=USA](http://pelias.github.io/compare/#/v1/search%3Fboundary.country=USA&text=washington%20university%20in%20st%20louis)

**Comment by orangejulius** [comment]
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 

Both the Union College and Washington University queries now return the correct result first without commas, for search _and_ autocomplete
![Screenshot_2019-10-03_16-06-55](https://user-images.githubusercontent.com/111716/66160386-0c265680-e5f8-11e9-9d90-14bbfa5b51a8.png)
![Screenshot_2019-10-03_16-08-38](https://user-images.githubusercontent.com/111716/66160410-147e9180-e5f8-11e9-9620-20b9dd347adc.png)

:
