### ISSUE TITLE
Language code is not supported for /autocomplete

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#604]
#### Here's what I did :innocent:
Testing language code with search and autocomplete after a user reported that autocomplete was not working. 
http://pelias.github.io/compare/#/v1/search%3Flang=ru&text=london,%20uk
http://pelias.github.io/compare/#/v1/autocomplete%3Flang=ru&text=london,%20uk

---
#### Here's what I got :scream_cat:
Search shows localized text
1)	Лондон, England, Великобритания
2)	London, England, Великобритания
3)	London, England, Великобритания
4)	London, England, Великобритания
5)	London, England, Великобритания
6)	London, England, Великобритания
7)	London, England, Великобритания

English results appear for autocomplete
 1)	London, England, United Kingdom
 2)	London, England, United Kingdom
 3)	Greater London, England, United Kingdom
 4)	East London, South Africa
 5)	East London, South Africa
 6)	London, ON, Canada
 7)	East New London, New London, CT, USA
 8)	New London County, CT, USA
 9)	Londonderry County Borough, Londonderry, Northern Ireland, United Kingdom
10)	New London, CT, USA

---
#### Here's what I was expecting :sparkles:
Expecting localized text to appear with autocomplete

---
#### Here's what I think could be improved :trophy:
Make language code work for both /autocomplete and /search

**Comment by missinglink** [comment]
definitely a bug, looking at the code it *should be enabled..

**Comment by rmglennon** [comment]
`lang` doesn't seem to return localized results with place either.

http://pelias.github.io/compare/#/v1/place%3Flang=de&ids=whosonfirst:locality:101750367

Confirmed to return results on /search, /search/structured, and /reverse...not working on /autocomplete or /place.

**Comment by dianashk** [comment]
I believe it currently works only for forward admin only search queries. We
identified that it's due to the configuration for the language service not
being set correctly in our chef files. Should be able to fix it quickly.

**Comment by missinglink** [comment]
Tested again today and still not fixed.

**Comment by dianashk** [comment]
Finally fixed in production! Sorry for the delay. Enjoy!

**Comment by dianashk** [comment]
<img width="603" alt="screen shot 2017-09-05 at 3 46 59 pm" src="https://user-images.githubusercontent.com/5446511/30080437-9ef48fb0-9251-11e7-8ac1-0c9fd94c44a0.png">

<img width="616" alt="screen shot 2017-09-05 at 3 48 15 pm" src="https://user-images.githubusercontent.com/5446511/30080456-a99bbae2-9251-11e7-90e6-49efa4cb032a.png">
