### ISSUE TITLE
http://pelias.io/compare giving 404 error

### ISSUE THREAD

**Issue by evansiroky** [pelias/pelias#606]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

I began creating a new issue and went to http://pelias.io/compare as recommended.

---
#### Here's what I got :scream_cat:

404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: compare
RequestId: **************************
HostId: **************************

---
#### Here's what I was expecting :sparkles:

I was hoping the website would load.

---
#### Here's what I think could be improved :trophy:

Either the website can get fixed, or the guidelines for creating issues can be changed if that service is no longer available.

**Comment by missinglink** [comment]
The compare app was working yesterday, thanks for reporting the bug, it seems to be a hosting issue.

The team uses that app daily for debugging so I'll try and get it fixed ASAP.

**Comment by missinglink** [comment]
@evansiroky oh actually it's still working, the url is http://pelias.github.io/compare not http://pelias.io/compare, sorry for the confusion, I will update the PR template.

**Comment by orangejulius** [comment]
We can and should add a redirect, since I'm sure there are other broken links. I'll look into it.
