### ISSUE TITLE
Search inaccuracies for Woodbridge, VA

### ISSUE THREAD

**Issue by evansiroky** [pelias/pelias#607]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

I was trying to use the search API to geocode a bunch of addresses in the vicinity of Woodbridge, VA.

Here is a list of sample addresses:

> 3937 Hartlake St, Woodbridge, VA
> 16861 Reef Knot Way, Woodbridge, VA
> 12497 Lolly Post Ln, Woodbridge, VA
> 12462 Machester Way, Woodbridge, VA
> 5700 Wink Way, Woodbridge, VA
> 3474 Wainscott Pl, Woodbridge, VA
> 12197 Seaford Ct, Woodbridge, VA
> 15364 Kensington Park Dr, Woodbridge, VA
> 12044 Willowood Dr, Woodbridge, VA
> 11913 Cotton Mill Dr, Woodbridge, VA

---
#### Here's what I got :scream_cat:

Every single one of these addresses is resolving as "Woodbridge, VA"

---
#### Here's what I was expecting :sparkles:

I was expecting each address to geocode to it's actual address / position.

**Comment by evansiroky** [comment]
I'm observing a lot of other cases where a search query results in a fallback to the city or zip code.  Some problematic areas in my dataset include:  Stafford, VA;  Manassas, VA; Falls Church, VA; Alexandria, VA; Vienna, VA.

If I average the `confidence` metric that is returned over all 2,941 of my entries, I get 0.758.  Does that mean this geocoding is only 76% accurate?

Sorry, can't share the rest of my dataset.

**Comment by trescube** [comment]
Hi @evansiroky, thanks for the feedback!

Unfortunately the polygons we use list the city as [Lake Ridge, VA](https://whosonfirst.mapzen.com/spelunker/id/101729239/#12/38.6844/-77.3042) and not [Woodbridge, VA](https://whosonfirst.mapzen.com/spelunker/id/101729255/#13/38.6537/-77.2390) for those points.  I'm familiar with Woodbridge and our polygons are very strict from an administrative perspective but don't always conform to what are called "postal cities" (cities as dictated by the USPS).  That is, an address's lat/lon may fall strictly within Lake Ridge but is effectively Woodbridge to the USPS.  [Woodbridge, VA](https://www.google.com/maps/place/Woodbridge,+VA+22191/@38.6364026,-77.2934373,13z/data=!3m1!4b1!4m5!3m4!1s0x89b65593c31c6ffb:0x72326e8a35e46e0!8m2!3d38.6581722!4d-77.2497049) on Google maps is much smaller than the details for individual addresses like [3937 Hartlake St, Woodbridge, VA](https://www.google.com/maps/place/3937+Hartlake+St,+Woodbridge,+VA+22192/@38.700057,-77.3309437,17z/data=!3m1!4b1!4m5!3m4!1s0x89b656d9a53fd9c3:0xf87e070f7d23855a!8m2!3d38.700057!4d-77.328755).  The addresses do work with Lake Ridge, VA, however, but there's obviously no way for you to know which it should be.  

We're approaching fixing these issues on 2 fronts: 
- [our data team](https://whosonfirst.mapzen.com/) is hard at work on incorporating postal cities but it's not been released yet
- our address search is currently very strict and these examples are a good candidates for "check the neighboring towns for the address, too" (this is on our medium-term radar)

The combination of these two will result in a sufficiently strict-yet-relaxed approach to geocoding but unfortunately we can't fix the issue you're seeing right now.

**Comment by evansiroky** [comment]
I just did a comparison of the results in my dataset by using both the autocomplete and search APIs.  Neither API on its own performs very well in terms of finding exact addresses.  The autocomplete API found a result only 61% of the time.  The search API did always find a result, but it was only address-level confidence about 52% of the time.  However, since both APIs return different results, I found that 92% of the time either the autocomplete or the search API returned an address-level confidence result.  When the autocomplete API does return a result, it is seems that it returns either no results or the address-level confidence result.  

Therefore, I have now implemented my bulk-geocoder to first make a call to the autocomplete API and if no result is found there, it tries the search API.  This of course results in many more API requests.  It would be nice to not have to do this.

**Comment by orangejulius** [comment]
This is probably part of the [postal cities](https://github.com/pelias/pelias/issues/396) issue.

**Comment by orangejulius** [comment]
Hello!

I am here with an exciting update! Our recent work on postal cities support (see #396) means that _every_ one of the above queries now works correctly.

Here are screenshots from our compare tool for a few of them. I've also updated the original issue text so that all the addresses are clickable links.
![Screenshot_2020-03-05_10-00-50](https://user-images.githubusercontent.com/111716/76010783-56be3e80-5ec8-11ea-93ee-6de0d4510f4e.png)
![Screenshot_2020-03-05_10-00-39](https://user-images.githubusercontent.com/111716/76010785-5756d500-5ec8-11ea-89f2-71b7718838fa.png)
![Screenshot_2020-03-05_10-00-26](https://user-images.githubusercontent.com/111716/76010787-5756d500-5ec8-11ea-8ded-8feb15386554.png)
