### ISSUE TITLE
openaddressesUK

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#617]
the UK has its own open addresses project with [downloads](https://alpha.openaddressesuk.org/developers/download).

if the licensing is appropriate it would be great to include this address data in the `interpolation` and `elasticsearch` indices.

**Comment by tigerlily-he** [comment]
The project is in "hibernating" mode [since a year ago](https://alpha.openaddressesuk.org/blog/2015/07/27/a-time-for-going-to-bed) so it doesn't look like it's maintained. That being said, the addresses collected is still better than no addresses at all.

**Comment by trescube** [comment]
There a couple of openaddresses sources in the UK that we're waiting to hear back on licensing. Apparently the UK govt is not shy about suing people who expose their data, and it's exorbitantly expensive.

**Comment by orangejulius** [comment]
The site appears to be down now. I guess this won't be coming soon :(
