### ISSUE TITLE
Multiple issues with structured search in Switzerland

### ISSUE THREAD

**Issue by magbeat** [pelias/pelias#622]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Case 1
https://mapzen.com/search/explorer/?query=search/structured&address=S%C3%A4gereistrasse%2010&postalcode=8152

#### Case 2
https://mapzen.com/search/explorer/?query=search/structured&postalcode=8808

---
#### Case 1
10 Sägereistrasse, Wilchingen, Switzerland
10 Sägereistrasse, Neuhausen am Rheinfall, Switzerland
10 Sägereistrasse, Mümliswil-Ramiswil, Switzerland
10 Sägereistrasse, Malans, Switzerland

#### Case 2
8808, Franekeradeel, Netherlands
8808, Freienbach, Switzerland

---
#### Case 1
Searched for Sägereistrasse 10 in 8152 Glattbrugg. eg. https://nominatim.openstreetmap.org/search.php?q=s%C3%A4gereistrasse+10%2C+8152&polygon_geojson=1&viewbox=

But the Sägereistrasse in Glattbrugg is not in the list. All of the results have completely different postalcodes.

#### Case 2
Postalcode of Freienbach is 8807 and not 8808. 8808 is Pfäffikon. See: 
https://www.plz-postleitzahl.ch/suchresultate.cfm?plz=8808&land=CH
https://www.plz-postleitzahl.ch/suchresultate.cfm?plz=8807&land=CH

Or more offical but less convenient:
https://www.post.ch/de/pages/plz-suche

---
### The Big Picture
I was looking for the geocodes of the following (valid) two addresses and was not able to find a valid lookup for any combinations of the search or structured search.

Sägereistrasse 10
8152 Glattbrugg

https://nominatim.openstreetmap.org/search.php?q=S%C3%A4gereistrasse+10%2C+8152+Glattbrugg&polygon_geojson=1&viewbox=

and

Huobstrasse 16
8808 Pfäffikon

https://nominatim.openstreetmap.org/search.php?q=huobstrasse+16%2C+8808+pf%C3%A4ffikon&polygon_geojson=1&viewbox=

Both lookups work in Nominatim.

Cheers,
Markus

**Comment by missinglink** [comment]
investigation notes:

> case 1

we have [this OSM entity](https://nominatim.openstreetmap.org/details.php?place_id=71652741) in our system:

```bash
/v1/search?text=Sägereistrasse, Zürich, Switzerland

      "properties": {
        "id": "polyline:6236966",
        "gid": "openstreetmap:street:polyline:6236966",
        "layer": "street",
        "source": "openstreetmap",
        "source_id": "polyline:6236966",
        "name": "Sägereistrasse",
        "street": "Sägereistrasse",
```

the issue here is related to how the 'fallback' scenario works, when a user specifies a house number, matching streets are omitted if an exact house number match was not found in elasticsearch.

since the introduction of `pelias/interpolation` we should probably return a mix of streets and addresses for these sorts of queries and let the interpolation service handle the house numbers.

note: this is the same behavior for both `/search` and `/search/structured`

cc @trescube

**Comment by missinglink** [comment]
> case 2

@magbeat if you're confident that the postcode is wrong, would you please edit http://www.openstreetmap.org/way/321385083 and set it to the correct one?

**Comment by magbeat** [comment]
@missinglink Thanks for your answer. As far as I understand OSM it seems to be correct. (see screenshots). Freienbach has the postcode 8807 and Pfäffikon 8808. There seems to be an issue with priorities which I, as an OSM beginner, do not understand. See: https://nominatim.openstreetmap.org/details.php?place_id=209354637

The search for the postcode 8808 does not retunr Pfäffikon but Freienbach. Anyway it's not a problem at the pelias geocoding engine. Sorry for that.

![freienbach](https://user-images.githubusercontent.com/1089410/29412140-d1a1a12c-8357-11e7-9912-b076daf465ed.png)
![pfaeffikon](https://user-images.githubusercontent.com/1089410/29412144-d46f017e-8357-11e7-9df8-503da135000c.png)

**Comment by magbeat** [comment]
The postcodes of Liechtenstein seem to be missing in the API:

https://mapzen.com/search/explorer/?query=search/structured&postalcode=9496
vs.
https://www.openstreetmap.org/search?query=9496#map=19/47.06687/9.50181

and

https://mapzen.com/search/explorer/?query=search/structured&postalcode=9490
vs.
https://www.openstreetmap.org/search?query=9490#map=19/47.13614/9.52009

Is there a reason for that?

**Comment by missinglink** [comment]
@magbeat Openstreetmap doesn't usually provide geometries for postal codes.

There are many addresses and venues *tagged* with a [postal_code](http://wiki.openstreetmap.org/wiki/Key:postal_code), and we do [copy those fields](https://github.com/pelias/openstreetmap/blob/acec9d303d5a783eceab108f1da32a146f30757a/schema/address_osm.js) in to our search records, the postcode is returned with the API results.

Very few postcode *geometries* (ie. the outline border of the postcode) are available in openstreetmap.

You can see from [this entry](http://nominatim.openstreetmap.org/details.php?place_id=209559365) that the result returned from nominatum is a 'place' (ie. not an openstreetmap primitive: node,way,relation).

I'm not sure how the postcode centroid is calculated in nominatum, but it's likely the center of mass of a [concave hull](http://ubicomp.algoritmi.uminho.pt/local/concavehull.html) of all the points which are tagged with that postal_code.

That's actually not a bad way of doing it, we don't do that, instead, we prefer to source polygon data which we can use to enrich arbitrary point data sources which have the postcode information missing, using a [point-in-polygon](https://en.wikipedia.org/wiki/Point_in_polygon) algorithm.

Our polygon dataset is called 'whosonfirst' and I see there was a Swiss postcode import as [issue #1](https://github.com/whosonfirst-data/whosonfirst-data-postalcode-ch/issues/1) back in 2016.

It looks like there may be an issue with that import, [as seen here](https://whosonfirst.mapzen.com/spelunker/search/?q=9490&iso=ch&placetype=postalcode), I will flag that up with the whosonfirst team to see what happened to the CH postcodes.

The structured endpoint is looking for a 'thing' named 9490 and not 'things which have a postcode of 9490' and so it's not returning anything.

Hope that makes sense :)

**Comment by missinglink** [comment]
There is also an issue where one of the postcodes has a lat/lon of 0,0 which I will open another bug report for, plus I'll mention that to the whosonfirst team and see if it can be corrected in the data.

**Comment by missinglink** [comment]
[this postal boundary](https://whosonfirst.mapzen.com/spelunker/id/538938593/) looks good and [can be found](https://mapzen.com/search/explorer/?query=search/structured&postalcode=8523).

so.. I'm starting to think that the data source does not contain all of the postcodes in Switzerland or an import error has occurred, still looking in to it.

**Comment by missinglink** [comment]
ok, I got a bit mixed up, these postcodes are in Liechtenstein not in Switzerland correct?

I have opened an issue here https://github.com/whosonfirst-data/whosonfirst-data/issues/898 which we can use to track the progress.

The data team are pretty busy with lots of requests from all around the globe, it would be super helpful if you could find an open data source of postal polygons for Liechtenstein and add it to that issue.

An example of the [import for Switzerland](https://github.com/whosonfirst-data/whosonfirst-data-postalcode-ch/issues/1) can be used as a template, you don't need to do the actual import if you don't feel confident but sourcing the data and linking the licence is super helpfup.

**Comment by missinglink** [comment]
this ticket is becoming a bit unmanageable due to containing many different issues, please open new issues for anything that's not directly related to what's been discussed above.

**Comment by mtmail** [comment]
> I'm not sure how the postcode centroid is calculated in nominatum, but it's likely the center of mass of a concave hull of all the points which are tagged with that postal_code.

Not sure about the exact algorithm but you're correct in that Nominatim does pre-calculation of postcode centroid at index time. Centroids don't get updated during incremental updates, e.g. when a place with that postcode gets deleted.

**Comment by magbeat** [comment]
@missinglink @mtmail thank you both for your detailed answers! This all makes sense, even for me as a noob. I have commented on the issue you created for me. If you like we could close this issue as everything is answered or brought up on an other project. As you suggest I will open a new issue if something else comes up. Thanks again!

**Comment by missinglink** [comment]
Closing this issue, I have created separate tickets for the tasks to fix issues mention here.

Thanks for the feedback @magbeat
