### ISSUE TITLE
Support multiple boundary.country parameters in a request

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#624]
#### Here's what I did :innocent:

This came in through support (see desk 882). The user is looking for a way to filter by multiple countries with autocomplete, although this applies to other endpoints as well.

Example query: https://mapzen.com/search/explorer/?query=search&text=ymca&boundary.country=GBR%2CIRL&focus.point.lat=-33.856680&focus.point.lon=151.215281

---
#### Here's what I got :scream_cat:

`[ERROR] GBR,IRL is not a valid ISO2/ISO3 country code`

---
#### Here's what I was expecting :sparkles:

The ability to use something like `boundary.country=GBR,IRL` or `boundary.country=GB&boundary.country=DE` with separate query parameters to filter by multiple countries, similar to`layers` and `sources`.

---
#### Here's what I think could be improved :trophy:

@dianashk confirmed that using multiple countries is not currently supported. If the countries are close enough, then you could use `boundary.rect` param, or do some filtering on your own based on the records.

**Comment by orangejulius** [comment]
This would be a great first issue for anyone looking to do take on a small task in Pelias. Reach out to us if you'd like help getting started.

**Comment by sayanb1983** [comment]
@orangejulius I would love to work on this issue. Can you please give me a few pointers as to how to get started on this?

**Comment by sayanb1983** [comment]
> This would be a great first issue for anyone looking to do take on a small task in Pelias. Reach out to us if you'd like help getting started.

@orangejulius I would love to work on this issue. Can you please give me a few pointers as to how to get started on this?

**Comment by orangejulius** [comment]
This was completed in https://github.com/pelias/api/pull/1281
