### ISSUE TITLE
Typing par for autocomplete returns smaller towns near the top, rather than Paris

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#627]
#### Here's what I did :innocent:
This came in through support (see Desk 888).

The user was using autocomplete to search for "par":
http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=wof&layers=country,locality&text=par

We can use this as an acceptance test with work to add placeholder service and other equivalency with search endpoint.

---
#### Here's what I got :scream_cat:
These are the top results:

 Pār Naogaon, Bangladesh
 Bollullos Par del Condado, Spain
 Paraguay
 Paris, France
 Parbhani, India
 Paraná, Argentina
 Paramaribo, Suriname
 Paradise, NV, USA
 Kabupaten Padang Pariaman, Indonesia
 Parque de la Madre, Ecuador

---
#### Here's what I was expecting :sparkles:
Expecting Paris or maybe Paraguay to be higher, especially if you are entering this as type-ahead with feedback in a drop-down list.

---
#### Here's what I think could be improved :trophy:
More equivalency with Search, which gives Paris, France first.

**Comment by orangejulius** [comment]
The results are looking a little better now:

```
     1) Paraguay
     2) Paris, France
     3) Paranaque, Philippines
     4) Parque de la Madre, Ecuador
     5) Kabupaten Padang Pariaman, Indonesia
     6) Parbhani, India
     7) Paraná, Argentina
     8) Paramaribo, Suriname
     9) Paradise, NV, USA
    10) Parung, Indonesia
```

**Comment by orangejulius** [comment]
Going to call this solved. In general, over time these sorts of queries should get better and better as more population data makes it into WOF.
