### ISSUE TITLE
Postalcodes missing when apartment number provided

### ISSUE THREAD

**Issue by stevage** [pelias/pelias#628]
#### Here's what I did :innocent:

Searching for "1 Dalgety St, St Kilda" [yields a result](https://mapzen.com/products/search/?query=1%20Dalgety%20Street%2C%20St%20Kilda%2C%20Australia&endpoint=place&gid=openaddresses%3Aaddress%3Aau%2Fcountrywide%3Afe0603f319265c23&selectedLat=-37.86064&selectedLng=144.97923&lng=144.91059&lat=-37.77733&zoom=11.715471152809831) that contains a postcode.

Searching for "1/1 Dalgety St, St Kilda" [yields a result](https://mapzen.com/products/search/?query=1%2F1%20Dalgety%20Street%2C%20St%20Kilda%2C%20Australia&endpoint=place&gid=openaddresses%3Aaddress%3Aau%2Fvictoria%3A50a14a8b5a195d42&selectedLat=-37.86064&selectedLng=144.97923&lng=144.91017&lat=-37.77667&zoom=11.715471152809831) that contains no postalcode.

#### Here's what I was expecting :sparkles:

Both results to contain the correct postalcode.

At the moment I guess I could work around it by launching two queries, one without the unit/apartment number, and combining them, but I'd really like to understand what's going on here, to know if there will be other cases where the postcode is missing.

(Mostly concerned with Australian data.)

**Comment by missinglink** [comment]
hi @stevage.

the query below shows two different results:

- "1 Dalgety Street, St Kilda, Australia" `au/countrywide:ec09ec7832917284`
- "1/1 Dalgety Street, St Kilda, Australia" `au/victoria:50a14a8b5a195d42`

both of these results was sourced from the [openaddresses project](http://results.openaddresses.io/), you can see the source file names and hashes in the id property, eg: file `au/countrywide` and hash `ec09ec7832917284`.

it seems like the `countrywide` file contains postalcodes while the `victoria` does not, this may be due to which fields were available from the govt.

- http://data.gov.au/dataset/geocoded-national-address-file-g-naf
- http://services.land.vic.gov.au/landchannel/content/vicmapdata?productID=1

we don't iterate over all the records trying to copy postalcode information, although we might consider doing this in the future.

```javascript
/v1/search?size=2&text=1 Dalgety St, St Kilda

{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://pelias.mapzen.com/v1/attribution",
    "query": {
      "text": "1 Dalgety St, St Kilda",
      "parsed_text": {
        "number": "1",
        "street": "dalgety st",
        "neighbourhood": "st",
        "city": "kilda"
      },
      "size": 2,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      },
      "querySize": 20
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1503491520297
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          144.979234,
          -37.860644
        ]
      },
      "properties": {
        "id": "au/countrywide:ec09ec7832917284",
        "gid": "openaddresses:address:au/countrywide:ec09ec7832917284",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "au/countrywide:ec09ec7832917284",
        "name": "1 Dalgety Street",
        "housenumber": "1",
        "street": "Dalgety Street",
        "postalcode": "3182",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "point",
        "country": "Australia",
        "country_gid": "whosonfirst:country:85632793",
        "country_a": "AUS",
        "region": "Victoria",
        "region_gid": "whosonfirst:region:85681497",
        "county": "Port Phillip (C)",
        "county_gid": "whosonfirst:county:102049535",
        "localadmin": "St Kilda (Vic.)",
        "localadmin_gid": "whosonfirst:localadmin:404540293",
        "locality": "St Kilda",
        "locality_gid": "whosonfirst:locality:101933573",
        "neighbourhood": "St Kilda South",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85780681",
        "label": "1 Dalgety Street, St Kilda, Australia"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          144.979235,
          -37.860644
        ]
      },
      "properties": {
        "id": "au/victoria:50a14a8b5a195d42",
        "gid": "openaddresses:address:au/victoria:50a14a8b5a195d42",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "au/victoria:50a14a8b5a195d42",
        "name": "1/1 Dalgety Street",
        "housenumber": "1/1",
        "street": "Dalgety Street",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "point",
        "country": "Australia",
        "country_gid": "whosonfirst:country:85632793",
        "country_a": "AUS",
        "region": "Victoria",
        "region_gid": "whosonfirst:region:85681497",
        "county": "Port Phillip (C)",
        "county_gid": "whosonfirst:county:102049535",
        "localadmin": "St Kilda (Vic.)",
        "localadmin_gid": "whosonfirst:localadmin:404540293",
        "locality": "St Kilda",
        "locality_gid": "whosonfirst:locality:101933573",
        "neighbourhood": "St Kilda South",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85780681",
        "label": "1/1 Dalgety Street, St Kilda, Australia"
      }
    }
  ],
  "bbox": [
    144.979234,
    -37.860644,
    144.979235,
    -37.860644
  ]
}
```

**Comment by missinglink** [comment]
opened PR https://github.com/openaddresses/openaddresses/pull/3354 to fix the source data

**Comment by stevage** [comment]
Wow, thanks so much for diving into this so quickly. That's incredible.

**Comment by andrewharvey** [comment]
> if you are interested in contributing, you can open an issue with them directly, or review the mapping files to try to import the missing fields.

I know it's easy to overlook but please if everyone could check for existing PRs before opening a new one, just like it's expected for issues.

I've seen this twice today alone where new PRs have been opened where the same fix has already been submitted in a PR weeks or months earlier.

**Comment by missinglink** [comment]
Thanks @andrewharvey, I know it can be frustrating when duplicate PRs are created and when PRs take a long time to get merged.

I'm sorry if you felt my PR was in any way a replacement for your own. I think, in this case, a combination of the two will yield the best results for the community.

I have sent Ian a private message to follow up on your PR and would be happy to revisit mine after yours is merged.

**Comment by orangejulius** [comment]
This is now fixed, since @andrewharvey's PR in OpenAddresses was merged! We now have postalcodes for these addresses in Mapzen Search! Thanks all <3

http://pelias.github.io/compare/#/v1/search%3Fsize=2&text=1%20Dalgety%20St,%20St%20Kilda
![image](https://user-images.githubusercontent.com/111716/30552618-9b4626e2-9c6c-11e7-9fe0-52fd7d869233.png)
