### ISSUE TITLE
Australian region abbreviations

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#631]
we provide a `region_a` property for USA states but not for AU states:

```
        "region_a": "CA",
        "label": "California, USA"

...

        "region": "New South Wales",
        "region_gid": "whosonfirst:region:85681545",
        "label": "New South Wales, Australia"
```

the state abbreviation data is available in WOF eg. https://whosonfirst.mapzen.com/spelunker/id/85681497/

**Comment by andrewharvey** [comment]
This sounds the same as https://github.com/pelias/pelias/issues/601

**Comment by orangejulius** [comment]
It looks like there are now abbreviations for Australia in Who's on First (thanks to https://github.com/whosonfirst-data/whosonfirst-data/pull/841), and addresses and other records pick them up (as mentioned in #601)

However, searching for regions themselves do not yet show abbreviations:

http://pelias.github.io/compare/#/v1/search%3Ftext=New%20South%20Wales
![image](https://user-images.githubusercontent.com/111716/30551855-f5a037ac-9c69-11e7-87b3-103d7874883e.png)
