### ISSUE TITLE
After 8/25/17 release, Search and Autocomplete no longer return correct results

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#632]
#### Here's what I did :innocent:

This came in through support (see Desk 922). It appears something went wrong with these queries on the latest production release (pushed out on 8/25/17) and it might need to be patched. 

From the user:

"I use mapzen for months and until today, never had a problem. I need to autocomplete and geocodes addresses in rural area in france, and until today it worked very well. 

search and autocomplete on openaddresses no longer return all results, I've tried several addresses in several regions, rural areas and cities and didn't found one address." 

---
#### Here's what I got :scream_cat:

For example with "le chesneau, surfonds" : 
`https://search.mapzen.com/v1/autocomplete?text=le%20chesneau,%20surfonds&boundary.country=FR&sources=openaddresses&layers=address` return nothing. 

`https://search.mapzen.com/v1/search?text=le%20chesneau,%20surfonds&boundary.country=FR&sources=openaddresses&layers=address` return results but not the correct result. 

On the compare tool:
http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=oa&layers=address&boundary.country=FRA&text=le%20chesneau,%20surfonds

---
#### Here's what I was expecting :sparkles:

"If I search on https://openaddresses.io/, correct result is found, and with mapzen, correct result was found for months, but not today."

---
#### Here's what I think could be improved :trophy:

@orangejulius was investigating.

**Comment by rmglennon** [comment]
After investigation, @dianashk determined it was related to a change in OA licensing. Records tagged with "share-alike" licensing are not currently imported.

https://github.com/openaddresses/openaddresses/commit/ba6137f4171d72b3fc501916c1e5cd30e5d8e314

See also https://github.com/pelias/pelias/issues/634 regarding the import.

**Comment by dianashk** [comment]
This data is now back in production. Thanks all for reporting the issue and your patience while we get the fix out.

![screen shot 2017-09-19 at 1 58 37 pm](https://user-images.githubusercontent.com/5446511/30607420-f3d685aa-9d42-11e7-91c9-b994713408c7.png)
