### ISSUE TITLE
Import OA share-alike data sources

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#634]
We would like to start ingesting the share-alike data from OA, which we are currently not pulling in to avoid licensing confusion.
Here are some of the tasks we need to think through as part of this effort.

Immediate steps:
- [x] update the build process to download and import the share-alike zip file
   - [x] `pelias/openaddresses`
   - [x] `pelias/interpolation`
- [x] update `pelias-docs` licensing details to explain that OA sources are not homogenous in terms of licensing and it's not safe to assume that they are all non-share-alike

Beyond the immediate changes, we need to design and implement a cohesive licensing communication strategy. This work will be tracked under the [Licensing milestone](https://github.com/pelias/pelias/milestone/57).

**Comment by orangejulius** [comment]
https://github.com/pelias/pelias-doc/pull/210 is intended to cover the documentation updates required here

**Comment by orangejulius** [comment]
This is mostly a Mapzen Search task, and importing share-alike OA data has been the standard for full planet Pelias builds for some time.
