### ISSUE TITLE
Reverse geocoding: fallback on streets

### ISSUE THREAD

**Issue by Platzii** [pelias/pelias#639]
Hi guys

Could it be possible to receive an update on the status of this page on the wiki: https://github.com/pelias/pelias/wiki/Reverse-Geocoding,-Part-Deux

More specific on the 3rd point in "Ideal Functionality" where it says the reverse geocoder will return a street if the coordinate could not be matched to an (interpolated) house number.

Since interpolation works now, it would be awesome to see this feature appear on the short-term roadmap! 😄 

Kind regards
Simon

**Comment by orangejulius** [comment]
Hey @Platzii,
We're taking a look at tasks for the next round of improvements for reverse geocoding (and that document is still the gold standard for what we want reverse to eventually do). Right now we have autocomplete improvements as the next big ticket item we're working on, but reverse is a top candidate for work after that, which would probably be done towards the end of the year.

Thanks for checking in!

**Comment by orangejulius** [comment]
Oh, looks like this is also covered in https://github.com/pelias/pelias/issues/637. Lets track the status of this feature there.
