### ISSUE TITLE
Pelias Leaflet Plugin

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#64]
It could be cool to have a leaflet plugin that puts a 'search' icon on the (leaflet) map. Upon clicking the icon, a test box appears where in the user can start geocoding using pelias' geocoding service.

![screen shot 2015-03-20 at 5 30 14 pm](https://cloud.githubusercontent.com/assets/840737/6761188/d4416bc0-cf26-11e4-8363-eb6028feeae9.png)

This depends on when the geocoding service is live and there is a well documented API sign up process.

**Comment by bcamper** [comment]
:+1:

**Comment by sevko** [comment]
Awesome idea. We should make this happen sometime soon.

**Comment by hkrishna** [comment]
https://github.com/pelias/leaflet-geocoder

**Comment by dianashk** [comment]
Done! :smiley:
