### ISSUE TITLE
Place returns venue version of record when address was requested

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#643]
#### Here's what I did :innocent:

This came in through support (see Desk 980)

1. Search for Hansaring (this is simplified from the user's query)
http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Hansaring
2. Use the gid of the first result for Hansaring 96 and do a place search on it
http://pelias.github.io/compare/#/v1/place%3Fids=openstreetmap:address:node:2420772655

---
#### Here's what I got :scream_cat:

Properties from autocomplete:

```
"properties": {
        "id": "node:2420772655",
        "gid": "openstreetmap:address:node:2420772655",
        "layer": "address",
        "source": "openstreetmap",
        "source_id": "node:2420772655",
        "name": "Hansaring 96",
        "housenumber": "96",
        "street": "Hansaring",
        "accuracy": "point",
        "country": "Germany",
        "country_gid": "whosonfirst:country:85633111",
        "country_a": "DEU",
        "region": "Nordrhein-Westfalen",
        "region_gid": "whosonfirst:region:85682513",
        "region_a": "NRW",
        "macrocounty": "Köln",
        "macrocounty_gid": "whosonfirst:macrocounty:404227541",
        "county": "Köln",
        "county_gid": "whosonfirst:county:102063715",
        "locality": "Köln",
        "locality_gid": "whosonfirst:locality:101752771",
        "label": "Hansaring 96, Köln, Germany"
      }
```

Then, take this gid openstreetmap:address:node:2420772655 and do a place search:

```
"properties": {
        "id": "node:2420772655",
        "gid": "openstreetmap:venue:node:2420772655",
        "layer": "venue",
        "source": "openstreetmap",
        "source_id": "node:2420772655",
        "name": "Centro Hotel Royal",
        "housenumber": "96",
        "street": "Hansaring",
        "accuracy": "point",
        "country": "Germany",
        "country_gid": "whosonfirst:country:85633111",
        "country_a": "DEU",
        "region": "Nordrhein-Westfalen",
        "region_gid": "whosonfirst:region:85682513",
        "region_a": "NRW",
        "macrocounty": "Köln",
        "macrocounty_gid": "whosonfirst:macrocounty:404227541",
        "county": "Köln",
        "county_gid": "whosonfirst:county:102063715",
        "locality": "Köln",
        "locality_gid": "whosonfirst:locality:101752771",
        "label": "Centro Hotel Royal, Köln, Germany"
      }
```

---
#### Here's what I was expecting :sparkles:

Expecting the osm:address record to be returned and not the venue version.

When you do place with openstreetmap:venue:node:2420772655, the venue record comes back.

---
#### Here's what I think could be improved :trophy:

Behind the scenes, this is finding a record from OSM that is originally a venue that also contains a full address.

In those cases, we create two records, one in the address layer without venue name and the other in venue layer with all the information.

The place endpoint should not be returning the venue version of the record when address has been requested.

(thanks to @dianashk for explanation about the two records)

**Comment by rschreijer** [comment]
I'd like to note that the `postalcode` field is missing as well.

**Comment by orangejulius** [comment]
We have had other issues like this, such as the following query:
[
http://pelias.github.io/compare/#/v1/Place%3Fids=whosonfirst:country:123](
http://pelias.github.io/compare/#/v1/Place%3Fids=whosonfirst:country:123)
![image](https://user-images.githubusercontent.com/111716/30393081-efc1d66e-988c-11e7-94d5-64055f0c00c1.png)

In this case there is no Who's on First record with ID 123, but the underlying Elasticsearch query is searching for any record with ID 123, and finds a Geonames locality

**Comment by orangejulius** [comment]
We should have a fix for the originally reported issue in https://github.com/pelias/api/pull/1036.

The issue I reported is actually a different one, and is being discussed over in https://github.com/pelias/pelias/issues/672.
