### ISSUE TITLE
Follow-up with update based on recent WOF changes

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#645]
Determine what if anything needs to be changed as a result of the work listed in this [WOF issue](https://github.com/whosonfirst/whosonfirst-properties/pull/35)

Refer to @nvkelso's [comment here](https://github.com/whosonfirst-data/whosonfirst-data/pull/823#issuecomment-327340235)

**Comment by nvkelso** [comment]
The upstream work in WOF will still land...
