### ISSUE TITLE
Android browser blocks access to https search URL

### ISSUE THREAD

**Issue by mmmelissa** [pelias/pelias#650]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
In Android browser, I navigated to ```https://search.mapzen.com/v1/autocomplete?focus.point.lat=49.271275&focus.point.lon=-123.090434&api_key=<my key>&text=ubc```

---
#### Here's what I got :scream_cat:
Console: ```The page at https://search.mapzen.com/v1/autocomplete?focus.point.lat=49.271275&focus.point.lon=-123.090434&api_key=<my key>&text=ubc displayed insecure content from file:///android_asset/webkit/android-weberror.png```

 ~~As a temporary workaround, I am not able to call the search API with http because then other browsers complain about mixed content.~~ Ignore this distracting comment :)

---
#### Here's what I was expecting :sparkles:
```{"geocoding":{"version":"0.2","attribution":"http://pelias.mapzen.com/v1/attribution","query":{"text":"ubc","parser":"addressit","parsed_text":{},"tokens":["ubc"],"size":10,"private":false,"focus.point.lat":49.271275,"focus.point.lon":-123.090434,"lang":{"name":"English","iso6391":"en","iso6393":"eng","defaulted":false}},"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1506279525221},"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.238497,49.256455]},"properties":{"id":"way:37892654","gid":"openstreetmap:venue:way:37892654","layer":"venue","source":"openstreetmap","source_id":"way:37892654","name":"UBC track","distance":10.902,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"UBC track, BC, Canada"},"bbox":[-123.239538,49.255782,-123.237484,49.257317]},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.238486,49.250072]},"properties":{"id":"way:24315277","gid":"openstreetmap:venue:way:24315277","layer":"venue","source":"openstreetmap","source_id":"way:24315277","name":"UBC Farm","housenumber":"3461","street":"Ross Drive","distance":11.032,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"UBC Farm, BC, Canada"},"bbox":[-123.242735,49.247748,-123.233225,49.251703]},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.23888,49.25074]},"properties":{"id":"6955981","gid":"geonames:venue:6955981","layer":"venue","source":"geonames","source_id":"6955981","name":"UBC Farm","distance":11.044,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"UBC Farm, BC, Canada"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.244578,49.2608]},"properties":{"id":"way:258978380","gid":"openstreetmap:venue:way:258978380","layer":"venue","source":"openstreetmap","source_id":"way:258978380","name":"UBC skatepark","distance":11.279,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"UBC skatepark, BC, Canada"},"bbox":[-123.244818,49.260667,-123.244223,49.260903]},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.245512,49.2642]},"properties":{"id":"way:99136527","gid":"openstreetmap:venue:way:99136527","layer":"venue","source":"openstreetmap","source_id":"way:99136527","name":"UBC Hospital","housenumber":"2211","street":"Wesbrook Mall","postalcode":"V6T 2B5","distance":11.314,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"UBC Hospital, BC, Canada"},"bbox":[-123.246858,49.263553,-123.24507,49.264765]},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.24809,49.25884]},"properties":{"id":"node:1117560886","gid":"openstreetmap:venue:node:1117560886","layer":"venue","source":"openstreetmap","source_id":"node:1117560886","name":"Bean UBC","distance":11.558,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"Bean UBC, BC, Canada"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.250629,49.264962]},"properties":{"id":"node:4232369894","gid":"openstreetmap:venue:node:4232369894","layer":"venue","source":"openstreetmap","source_id":"node:4232369894","name":"UBC Bookstore","distance":11.68,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"UBC Bookstore, BC, Canada"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.09951,49.279224]},"properties":{"id":"node:4364253211","gid":"openstreetmap:venue:node:4364253211","layer":"venue","source":"openstreetmap","source_id":"node:4364253211","name":"UBC Learning Exchange","housenumber":"612","street":"Main Street","distance":1.104,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","locality":"Vancouver","locality_gid":"whosonfirst:locality:101741075","neighbourhood":"Chinatown","neighbourhood_gid":"whosonfirst:neighbourhood:85866521","label":"UBC Learning Exchange, Vancouver, BC, Canada"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.144491,49.179515]},"properties":{"id":"way:106993015","gid":"openstreetmap:venue:way:106993015","layer":"venue","source":"openstreetmap","source_id":"way:106993015","name":"UBC Rowing Club","distance":10.938,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","locality":"Richmond","locality_gid":"whosonfirst:locality:101741081","neighbourhood":"City Centre","neighbourhood_gid":"whosonfirst:neighbourhood:85894879","label":"UBC Rowing Club, Richmond, BC, Canada"},"bbox":[-123.145264,49.179239,-123.143865,49.179798]},{"type":"Feature","geometry":{"type":"Point","coordinates":[-123.237943,49.250765]},"properties":{"id":"node:1234993971","gid":"openstreetmap:venue:node:1234993971","layer":"venue","source":"openstreetmap","source_id":"node:1234993971","name":"UBC Farm Market","distance":10.977,"accuracy":"point","country":"Canada","country_gid":"whosonfirst:country:85633041","country_a":"CAN","region":"British Columbia","region_gid":"whosonfirst:region:85682117","region_a":"BC","neighbourhood":"West Point Grey","neighbourhood_gid":"whosonfirst:neighbourhood:85865029","label":"UBC Farm Market, BC, Canada"}}],"bbox":[-123.250629,49.179239,-123.09951,49.279224]}```

---
#### Here's what I think could be improved :trophy:
Something about your ssl certificate or server config??

**Comment by missinglink** [comment]
Hi @mmmelissa,

Browser mixed content warnings happen when an `https` URL is requested and the resulting web page includes links to `http` content, meaning that a user is given the impression of being secure when some content is actually not encrypted.

In the case of our API, we are serving a single `https` JSON file with no embedded links to other content, so a mixed content warning for a JSON API is not possible.

What's probably happening is that your browser is injecting content into the frame as part of a browser plugin (such as a JSON formatter).

If the plugin is injecting non-https content then you will see such warnings, I can confirm using the 'Network' tab of my chrome inspector that, after the original JSON content is loaded, my browser plugins request visual assets to pretty print the JSON in my browser (such as the icons for expand/contract).

Please try disabling any plugins you have and trying again, or using an HTML client such as [search explorer](https://mapzen.com/search/explorer/).

**Comment by mmmelissa** [comment]
Thanks @missinglink, I shouldnt have mentioned my hypothetical workaround as it is distracting (and wouldnt have made sense due to mixed content issues anyway). 

When I use the Android native browser (4.3.1-b0ba9333b0) with default settings and plugins disabled, the ![search explorer](https://mapzen.com/search/explorer/) produces the error ```NETWORK_ERR: XMLHttpRequest Exception 101``` 

With browser defaults + plugins disabled I still get the same issue mentioned above.

**Comment by missinglink** [comment]
ping @msmollin, any ideas Matt?

**Comment by msmollin** [comment]
Hmmm I have a few (cc @sarahlensing for more). 

First @mmmelissa what version of Android are you running? 

Second, what device are you running it on? 

Third: how are you attempting to display the content? Is this an Android Browser Webview component inside your own app? Android's Browser application?  If your device has it, can you confirm this happens in Chrome as well?

I'm currently looking for an older device that might still have this app installed. I can't get it to happen on anything running Android 6.0 and later.

**Comment by mmmelissa** [comment]
This happens on multiple more-than-a-few-years-old androids. The one I have with me at work is Android 4.3.1 on a Samsung-SGH-1747

For troubleshooting, I am pasting the above url into the browser address bar. However, the full webapp I am troubleshooting lives at vancouver.bikerouteplanner.com. None of it is minified yet. You can see where I am calling Mapzen in the geocoder.js file.

I have no problems with chrome either by pasting the url into the browser directly or using it in my web app. 

Thanks for the help.

**Comment by matteblair** [comment]
The original error about `insecure content from file:///android_asset/webkit/android-weberror.png` sounds like the resulting page is loading an image from a local asset file and the WebView/Browser is treating that as insecure mixed content :\

You may need to load this page in a WebView with custom settings for it to work correctly (or just use Chrome, of course). I would look into the `WebSettings` for a `WebView`: https://developer.android.com/reference/android/webkit/WebSettings.html In particular, the `MIXED_CONTENT` options seem relevant: https://developer.android.com/reference/android/webkit/WebSettings.html#setMixedContentMode(int)

**Comment by mmmelissa** [comment]
This is a _web_ application btw. Im not building a native app. 

I should be able to navigate to the mapzen url above in any browser, no?

**Comment by msmollin** [comment]
Unfortunately it’s not that simple :/ depending on browser implementation different browsers implement SSL differently. 

The Android Broswer implementation is dated at this point (and is not packaged in Android 4.4 and forward, with google chrome having fully replaced it). I’ve been trying to track down a device in the office that still has it installed but we don’t seem to have one. 

My suspicion is that you’re encountering an SSL error where Android Browser app is having an issue handling Mapzen Search’s ssl certificates related to dropping support for SSLv3 (we ran into something similar recently in the native mobile SDKs). Unfortunately it’s hard to confirm that suspicion without a device available :/

We’ll keep looking but in the mean time your app should work fine on the vast majority of devices (4.4 and newer) which ship without the Android Browser application. I tested this on an older Nexus device running 4.4 and everything looked fine in Chrome

**Comment by mmmelissa** [comment]
Its good piece of mind that most people wont encounter this. And if they do, my error messages offer workarounds. Thanks everyone for looking into it!

**Comment by matteblair** [comment]
I tried this on a Galaxy Nexus running 4.2.2 and got the same result:
```
W/chromium( 4243): external/chromium/net/http/http_stream_factory_impl_job.cc:865: [0926/172437:WARNING:http_stream_factory_impl_job.cc(865)] Falling back to SSLv3 because host is TLS intolerant: search.mapzen.com:443
E/chromium( 4243): external/chromium/net/socket/ssl_client_socket_openssl.cc:792: [0926/172437:ERROR:ssl_client_socket_openssl.cc(792)] handshake failed; returned -1, SSL error code 1, net_error -107
E/Tab     ( 4243): onReceivedError -11 https://search.mapzen.com/v1/autocomplete?focus.point.lat=49.271275&focus.point.lon=-123.090434&api_key=<my_api_key>&text=ubc Couldn't establish a secure connection.
--------- beginning of /dev/log/system
W/InputMethodManagerService(  376): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41dd76a0 attribute=null, token = android.os.BinderProxy@41aaabf8
W/browser ( 4243): Console: The page at https://search.mapzen.com/v1/autocomplete?focus.point.lat=49.271275&focus.point.lon=-123.090434&api_key=<my_api_key>&text=ubc displayed insecure content from file:///android_asset/webkit/android-weberror.png.
```
The log makes it pretty clear that the Android Browser is falling back to SSLv3 and then failing to establish a secure connection, as suspected.

**Comment by missinglink** [comment]
heya, thanks everyone for looking into this, it sounds like this bug only affects fairly old devices and there is, unfortunately, nothing we can do on our end to fix it.

In the interest of ticket management, I'm going to close this issue. If you feel it's unresolved or have any more info to add in the future, please feel free to comment below.
