### ISSUE TITLE
Illegal shift value, must be 32..63; got shift=0

### ISSUE THREAD

**Issue by heyarne** [pelias/pelias#656]
Hi there,

I have noticed that I get an elasticsearch error when using the `boundary.rect` parameter with your provided API. I'm not quite sure whether this comes from passing in incorrect parameters, but I think it's an error bubbling up from further down below.

---
#### Here's what I did :innocent:
[/v1/autocomplete?sources=openaddresses&boundary.rect.min_lat=52.7945&boundary.rect.min_lon=12.6398&boundary.rect.max_lat=52.2387&boundary.rect.max_lon=14.1367&text=Elsenstr](http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=openaddresses&boundary.rect.min_lat=52.7945&boundary.rect.min_lon=12.6398&boundary.rect.max_lat=52.2387&boundary.rect.max_lon=14.1367&text=Elsenstr)

---
#### Here's what I got :scream_cat:
``` json
HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Authorization, Content-Type, Accept, Origin, User-Agent, Cache-Control, Keep-Alive, If-Modified-Since, If-None-Match, X-Requested-With
Access-Control-Allow-Methods: GET, HEAD
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Type, Cache-Control, ETag, Expires, Last-Modified, Content-Length, X-ApiaxleProxy-Qpd-Left, X-ApiaxleProxy-Qpm-Left, X-ApiaxleProxy-Qps-Left, X-Cache
Cache-Control: public, max-age=60
Connection: keep-alive
Content-Length: 666
Content-Type: application/json; charset=utf-8
Date: Thu, 28 Sep 2017 13:50:59 GMT
Fastly-Restarts: 1
X-ApiaxleProxy-Qps-Left: 5
X-Cache: MISS
X-Cache-Hits: 0
X-Served-By: cache-hhn1522-HHN
X-Timer: S1506606659.372869,VS0,VE221
charset: utf8
etag: W/"29a-3CYhjKMh9/diG5XgaiUf9tHh4jI"
x-powered-by: mapzen

{
    "features": [],
    "geocoding": {
        "attribution": "http://pelias.mapzen.com/v1/attribution",
        "engine": {
            "author": "Mapzen",
            "name": "Pelias",
            "version": "1.0"
        },
        "errors": [
            "[illegal_argument_exception] Illegal shift value, must be 32..63; got shift=0"
        ],
        "query": {
            "boundary.rect.max_lat": 52.2387,
            "boundary.rect.max_lon": 14.1367,
            "boundary.rect.min_lat": 52.7945,
            "boundary.rect.min_lon": 12.6398,
            "lang": {
                "defaulted": true,
                "iso6391": "en",
                "iso6393": "eng",
                "name": "English"
            },
            "parser": "addressit",
            "private": false,
            "querySize": 20,
            "size": 10,
            "sources": [
                "openaddresses"
            ],
            "text": "Elsenstr"
        },
        "timestamp": 1506606659542,
        "version": "0.2",
        "warnings": [
            "Invalid Parameter: query"
        ]
    },
    "type": "FeatureCollection"
}
```

---
#### Here's what I was expecting :sparkles:
I thought I could restrict the searched area to Berlin's bounding box but unfortunately had to fall back to focus.point and manual filtering. Is this a temporary error? When googling I found in-progress elasticsearch issues, I hope this is only temporary.

Keep up the good work! Love all of it.

**Comment by heyarne** [comment]
Oops, I realized my `min_lat > max_lat`! My mistake. Sometimes voicing a problem out loud helps.

**Comment by missinglink** [comment]
still a very interesting message, haven't seen that one before..

**Comment by missinglink** [comment]
oh here it is: https://github.com/elastic/elasticsearch/issues/18458

**Comment by missinglink** [comment]
The API should be checking the min vs. max values and emitting an error, this is a bug.

**Comment by orangejulius** [comment]
Hi all,
@pbackx was nice enough to fix this in https://github.com/pelias/api/pull/1050. We'll close this issue once it makes it to Mapzen Search production in the very near future.

**Comment by orangejulius** [comment]
this is indeed fixed. Thanks for the report!
