### ISSUE TITLE
UK postal codes require space

### ISSUE THREAD

**Issue by rymohr** [pelias/pelias#659]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:

Searched for the UK postal code `W105QB` 
http://pelias.github.io/compare/#/v1/search%3Ftext=W105QB

---
#### Here's what I got :scream_cat:

No features returned.

---
#### Here's what I was expecting :sparkles:

The search works fine when space is included `W10 5QB`
http://pelias.github.io/compare/#/v1/search%3Ftext=W10%205QB

---
#### Here's what I think could be improved :trophy:

Would be great if these postal codes would work with and without the space.

**Comment by dianashk** [comment]
This is really helpful feedback! Thanks @rymohr!

We should look into updating the importer to provide alt-names for postalcodes, for example if the postalcode has punctuation or hyphens or whitespace, index both the original and a version without all that stuff.

**Comment by rmglennon** [comment]
Possibly related issue with postal codes that use a hyphen.

Incorrect results (returns France, not Poland)
https://mapzen.com/search/explorer/?query=search/structured&postalcode=77-400

Search on address containing that postal code and you get result with `postalcode: 77-400`.
https://mapzen.com/search/explorer/?query=search&text=7%20Polna%2C%20Z%C5%82ot%C3%B3w

This came in through support (see Desk 1347):

"I'm trying to create query to search utility on Mapzen to find some locations by postal code.
I put as text "77-400" (postal code) and there is no results, but when I put as text "7 Polna, Złotów" - there is a place with this code in result."

**Comment by rmglennon** [comment]
Another case through support (see desk 1368)

"if we search for a UK postcode i.e. "NN4 7BF" with a space it works perfectly, if I search for it without a space no results come up."

**Comment by orangejulius** [comment]
We should be able to fix this with https://github.com/pelias/whosonfirst/pull/369

**Comment by orangejulius** [comment]
Confirmed fixed now
![image](https://user-images.githubusercontent.com/111716/51224876-d112b480-18fc-11e9-9cc8-402ecc1424ff.png)
