### ISSUE TITLE
Software design document for Pelias (as a standalone product)

### ISSUE THREAD

**Issue by sevko** [pelias/pelias#66]
**NOTE: This ticket refers specifically to standalone Pelias source code, and not the documentation of Mapzen Search/Pelias. web service.**

While all of our repos typically have comprehensive READMEs (and less relevantly, decent in-code documentation), there isn't much in the way of a high-level overview of Pelias. We should work on maintaining some write-ups of the entire Pelias architecture, how the significant number of Node packages ties into that, etc. Perhaps it'd make sense to maintain this sort of documentation on a `pelias.github.io` landing page. A [blog post](https://mapzen.com/blog/pelias-setup-tutorial) that I wrote a while ago serves as a good example of what I have in mind.

**Comment by orangejulius** [comment]
This is what our documentation is now :)
