### ISSUE TITLE
can't find 1600 Pennsylvania Ave, Washington DC

### ISSUE THREAD

**Issue by burritojustice** [pelias/pelias#661]
Hey team! 

---
#### Here's what I did :innocent:

a user on twitter had a hard time searching for `1600 Pennsylvania Ave, Washington DC`

---
#### Here's what I got :scream_cat:

[/v1/search?text=1600 Pennsylvania Ave, Washington DC](https://pelias.github.io/compare/#/v1/search%3Ftext=1600%20Pennsylvania%20Ave,%20Washington%20DC)
---
#### Here's what I was expecting :sparkles:

The full address is `1600 Pennsylvania Avenue Northwest, Washington, DC` or `1600 Pennsylvania Avenue NW, Washington, DC`

We were expecting a fairly complete but not totally address like `1600 Pennsylvania Ave, Washington DC` to be found -- instead in only returns the entire district.

https://mapzen.com/search/explorer/?query=search&text=1600%20Pennsylvania%20Ave%20Washington%20DC

---
#### Here's what I think could be improved :trophy:

Give results for `DC` a higher confidence score -- right now it comes in as #20 but has a confidence score of ` "confidence": 0.658`, higher than the results listed ahead of it.

https://mapzen.com/search/explorer/?query=search&text=1600%20Pennsylvania%20Ave%2C%20DC&size=40

Return addresses for searches like `1600 Pennsylvania Ave, Washington DC`:

https://mapzen.com/search/explorer/?query=search&text=1600%20Pennsylvania%20Ave%20Washington%20DC

**Comment by orangejulius** [comment]
Looks like this works now! We need to improve our deduplication to account for post-directionals though.
![Screenshot_2019-05-15_07-14-18](https://user-images.githubusercontent.com/111716/57771573-11364800-76e1-11e9-83b0-b7b9e4a808a9.png)
