### ISSUE TITLE
Search for "Paris" at a focus point near Paris, TX still results in Paris, France at the top

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#666]
#### Here's what I did :innocent:

This came in through support (see Desk 1132).

"I have a question, when executing the following query:

[/v1/search?focus.point.lat=40.7764&focus.point.lon=-110.3728&text=paris](http://pelias.github.io/compare/#/v1/search%3Ffocus.point.lat=40.7764&focus.point.lon=-110.3728&text=paris)

I am getting back Paris France first, instead of Paris Texas. Could you explain me why?"

---
#### Here's what I got :scream_cat:

From Rhonda - the first two results are Paris, France (locality + region), and the third one is Paris, TX. Putting Paris, France first seems correct, as this focus point is in Utah and more than 100km away, which is the beyond the local boosting effect. This query may need a boundary.country or circle/rectangle to limit the results further.

 1)	Paris, France
 2)	Paris, France
 3)	Paris, TX, USA
 4)	Paris, TN, USA
 5)	Paris, IL, USA
 6)	Paris, OH, USA
 7)	Paris, OH, USA
 8)	Paris, ME, USA
 9)	Paris, ID, USA
10)	Paris, MO, USA

_However_, choosing a focus point that is within Paris, TX still results in Paris, France, and that seems unexpected.

---
#### Here's what I was expecting :sparkles:

Try this query: http://pelias.github.io/compare/#/v1/search%3Ffocus.point.lat=33.7568&focus.point.lon=-95.5362&text=paris

These coordinates are near Paris, TX, so it is expected that the Paris, TX would be prioritized. 

1)	Paris, France
 2)	Paris, France
 3)	Paris, TX, USA
 4)	Paris, TN, USA
 5)	Paris, IL, USA
 6)	Paris, OH, USA
 7)	Paris, OH, USA
 8)	Paris, ME, USA
 9)	Paris, AR, USA
10)	Paris, MO, USA

---
#### Here's what I think could be improved :trophy:

Autocomplete on this focus location returns local Paris, TX venues.

http://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=33.7568&focus.point.lon=-95.5362&text=paris

 1)	KGDD-AM (Paris), Lamar County, TX, USA
 2)	Paris Country Club, Lamar County, TX, USA
 3)	Days Inn Paris, Paris, TX, USA
 4)	Paris Regional Medical Center North Campus, Paris, TX, USA
 5)	Dubuis Hospital of Paris, Paris, TX, USA
 6)	Paris Regional Medical Center, Paris, TX, USA
 7)	Holiday Inn Express Hotel & Suites Paris, Paris, TX, USA
 8)	Paris Fire Department Station 1, Paris, TX, USA
 9)	La Quinta Inn & Suites Paris, Paris, TX, USA
10)	Comfort Inn & Suites Paris, Paris, TX, USA

**Comment by orangejulius** [comment]
It's possible queries to placeholder are not properly taking `focus.point` into account. We [do have code](https://github.com/pelias/sorting/blob/master/index.js#L67-L94) to handle this (I think), but some investigation is required to make sure it's working properly.

@missinglink any ideas?

**Comment by orangejulius** [comment]
Update: it looks like it _does_ work correctly, but WOF `megacities` (of which Paris is one) are always sorted first.

Here's a similar query to the first, but the focus point is near `Paris, Tennessee`, not Paris Texas.
[/v1/search?focus.point.lat=36&focus.point.lon=-88&text=paris](http://pelias.github.io/compare/#/v1/search%3Ffocus.point.lat=36&focus.point.lon=-88&text=paris)
![image](https://user-images.githubusercontent.com/111716/46960133-cfbabd00-d06b-11e8-9fd5-5fbd6bf81f9a.png)


In _this_ query, `Paris, TN` come second, with `Paris, TX` third.

In the original query, `Paris, TX` is second
![image](https://user-images.githubusercontent.com/111716/46960176-ea8d3180-d06b-11e8-8e16-1b525a455f98.png)

**Comment by orangejulius** [comment]
I can confirm via the [acceptance tests](https://github.com/pelias/acceptance-tests/blob/master/test_cases/placeholder_sorting.json#L56-L74) that this is the expected behavior.
