### ISSUE TITLE
No results available for given street/city combination

### ISSUE THREAD

**Issue by ecgreb** [pelias/pelias#67]
When searching for "203 Union Street Doylestown PA" no results are found for Union Street in Doylestown. Results are available for Union Street in other cities, and results are available for other streets in Doylestown (like Main Street) but nothing for the given street and city.

**Comment by tallytalwar** [comment]
Another example being:

301 Commons Park S, Stamford, CT 06902

Results are available for places having "Park" and "Commons" in different Connecticut cities.

**Comment by hkrishna** [comment]
At the moment, our address parser is pretty basic and all it does is looks for a delimiter (```comma```) and uses everything that follows ```,``` as the given city/state/country. 

So, @ecgreb, ```203 Union Street, Doylestown PA``` should the results you expect. ANd @tallytalwar I think in your case when you search for ```301 Commons Park S, Stamford, CT``` it finds addresses in ```CT``` however, doesnt find the address you query for - this could be a data issue.

**Comment by tallytalwar** [comment]
But how come nominatim was able to find it?

And even if say there is a data issue, should it not give results prioritizing state, then city... But I do not see any result from Stamford (or near stamford) in the list of suggested searches/places. Maybe it should prioritize based on a metric say distance from the given city.

**Comment by dianashk** [comment]
The Stamford address is in osm as a way, not an address.
https://nominatim.openstreetmap.org/details.php?place_id=2577056971
Would that have an impact on the results?

The idea of sorting results by proximity to centroid of the admin area
specified in the query is good. This would again be feasible after we start
parsing the addresses smarter.


On Monday, April 6, 2015, Varun <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> But how come nominatim was able to find it?
>
> And even if say there is a data issue, should it not give results
> prioritizing state, then city... But I do not see any result from Stamford
> (or near stamford) in the list of suggested searches/places. Maybe it
> should prioritize based on a metric say distance from the given city.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/pelias/issues/67#issuecomment-90206333>.
>


-- 
Diana Shkolnikov

267-243-1110
diana@mapzen.com

**Comment by stevevance** [comment]
@hkrishna Have you heard of ````usaddress```` [from DataMade](https://github.com/datamade/usaddress)? It reads a string and parses the different address parts.

**Comment by dianashk** [comment]
@stevevance `usaddress` looks like a great starting point. Thanks. We will need to eventually find something that handles international address as well.

**Comment by dmunch** [comment]
Just had a quick look into `useaddress`, actually it's probabilistic and you can train it for different address patterns using http://parserator.datamade.us/ 

Not sure however how big the effort is to train it for lots of different countries.

**Comment by missinglink** [comment]
I'm self-assigning this to investigate the potentially missing street data, this relates well to another ticket I'm currently working on.

related: https://github.com/pelias/pelias/issues/22

**Comment by cathydeng** [comment]
hey everyone - yep, usaddress is a probabilistic parser, and it performs pretty well on US addresses with all sorts of patterns/formats. you actually can't train the model on http://parserator.datamade.us/ - that just uses our existing model to parse new addresses.

we did put together a toolkit, https://github.com/datamade/parserator, for setting up new probabilistic parsers & training models. making a UK parser would involve some config tweaks (defining the possible address components in the UK, etc) & preparing labeled training data

I'd be happy to chat if you have any questions

**Comment by missinglink** [comment]
cc/ @thatdatabaseguy re: libpostal

**Comment by amnesia7** [comment]
Is the basic parser also the reason why I need to actually type in the `,` between the address parts when using the autocomplete on https://mapzen.com/pelias/ ?
Also, would the address parsing also allow things like returning places in `NY` if I actually type `new york` as part of the autocompleter?

**Comment by trescube** [comment]
Create an acceptance test

**Comment by trescube** [comment]
We'll pull some acceptance tests from this issue but the core address matches probably won't happen due to missing data.  We will, however, fallback to the coarse geocode.   Report to Al that 'CT' is broken.

**Comment by trescube** [comment]
Original issue fixed, moved `301 Commons Park S, Stamford, CT 06902` to #440
