### ISSUE TITLE
Pelias currently cannot store records from two sources with the same layer and ID

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#672]
The way we store records in Elasticsearch could potentially lead to a situation where two different records cannot co-exist, and despite successfully indexing both records, only one would be stored permanently. The other would essentially be lost, even though our [GID structure](https://github.com/pelias/documentation/blob/master/response.md#gid) is able to distinguish between the two records.

This has been a known issue since early 2016: https://github.com/pelias/model/pull/21#issuecomment-174699606

## Example

Within a single index, Elasticsearch requires the combination of the `_type` and `_id` fields to be unique. Currently we store the `layer` of a record in the `_type` field, and the ID of the record from it's original data source as the `_id` field.

Here are some examples of that mapping on real records:

| Pelias GID | Elasticsearch `_type` | Elasticsearch `_id` |
| --- | ------ | ---------- |
| openstreetmap:address:node:2420772655 | address | node:2420772655 |
| whosonfirst:locality:101750367 | locality | 101750367|
| openaddresses:address:us/ca/merced:f0564efd16b6821c | address | ca/merced:f0564efd16b6821c |
| geonames:locality:123 | locality | 123 |

From that table it's clear that the `source` value of the record is essentially lost. If a record from one source has the same layer and ID as another source, only one of them can be stored in Elasticsearch (probably whichever one was indexed last, which may not always be the same between builds).

In practice, only Geonames and Who's on First IDs could be the same, as they both use plain integer IDs. OSM IDs are always prefixed by either `node` or `way`, since there can be both a node and way with the same integer ID (this caused some confusion in https://github.com/pelias/api/issues/414). OpenAddresses IDs are prefixed with the source filename and either a unique hash derived from the entire record, or an integer that represents the line number in the source file if no hash was generated (which I believe is now never the case, as there is always a hash).

We don't know of any cases where a Who's on First and Geonames record in the same layer have the same integer ID, but it could happen. Either way it's currently possible to [craft a /place endpoint query](https://github.com/pelias/pelias/issues/643#issuecomment-329251375) that asks for a (nonexistent) Who's on First record but returns a real Geonames record. That's very confusing.

### Use GID as Elasticsearch ID

One solution would be to store the Pelias GID in the Elasticsearch `_id` field. This would allow us to disregard the `_type` field completely, which is convenient since [types are eventually going to be removed from Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html).

We have already almost completely removed usage of the `_type` field from within Pelias. We've found that having queries for the `source` field use a different mechanism than queries for the `layer` field to be confusing (we already have dedicated fields for both, so using the `_type` field is also redundant).

As an added bonus, this would make the `/place` endpoint Elasticsearch query even simpler. Instead of having to parse out the different GID components, we would query for it directly.

The only other change we might have to make to the schema is to add an explicit `source_id` field, but that would be no problem at all. (Edit: this is incorrect, we already have a `source_id` field, and don't need it)

### ~Use the full query API for place endpoint queries, instead of multi-get~

**edit 2019/07/05** : _This method won't actually fix the problem, since it would do nothing to prevent document collisions in Elasticsearch_

~The `/place` endpoint currently uses the [mget](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html) API, which only allows querying for `_type` and `_id`. It's perfectly suited for the Place endpoint queries. However we could use the normal full query API we use elsewhere, and explicitly filter on `source`, `layer`, and `id`.~

~This would actually remove quite a bit of code from the API, since we would only have to have one interface to Elasticsearch. It wouldn't fix the underlying (but unlikely) data loss issue, but it also wouldn't require any schema changes. Overall it's probably not as good of a solution as the first one.~

**Comment by orangejulius** [comment]
Hi everyone,
This is still an issue, and I believe we should solve it with method 1 listed above. As it would technically be a breaking change to the interface between Elasticsearch and the API, this would have to be done carefully. However, I think I know a way where we could do it in a backward compatible way.

Basically, we would change our IDs in Elasticsearch to be the full GID, and add a `source_id` field. However, this would all be done _after_ and API change is made that searches for both the old `id`/`_type` combo, and the new `id`. Only one would ever be found in most cases, so this should work.

This would be a good issue for someone looking to do a little Elasticsearch work, so feel free to reach out to me if you'd like to get started.

**Comment by orangejulius** [comment]
This is now an important issue to fix. With [Elasticsearch 6](https://github.com/pelias/pelias/issues/719) support on the horizon, removing all use of the Elasticsearch `_type` field is a blocking task, and doing so without addressing this issue would in fact make it much worse (no two documents could exist with the same `id`, regardless of `source` or `layer`).

As mentioned before the solution to this problem is to store the full Pelias GID (`source:layer:id`) in the Elasticsearch `_id` field, where currently we merely store the `id` from the original source.

The `_id` and `_type` fields are really only used in two places in the Pelias code:

1. Querying for individual records via the `/v1/place` endpoint
2. Generating response JSON from Elasticsearch documents in `helper/geojsonify.js`

Here is a plan that should allow us to change what is stored in the Elasticsearch `_id` field without any breaking change.

1. Ensure all code in `helper/geojsonify.js` uses the `source`, `layer`, and `source_id` fields in a record, rather than the `_id` field, to calculate the Pelias GID and generate GeoJSON for Pelias responses. The source_id field is technically redundant and could be removed in the long run, but will be very helpful for this transition
2. Modify the `/v1/place` endpoint to look for two possible records for each GID being queried: one where the `_type` is the layer and the `_id` is the `source_id`, and another where the `_id` is the Pelias GID. Only one will ever be present and this will ensure that the same API code will work before and after changing what actually goes into each document in Elasticsearch
3. After enough time has passed to feel reasonably sure that people have had a chance to upgrade their API, modify `pelias/model` so that the Pelias GID is stored in the `_id` field. At the same time, it may make sense to reeavluate the functionality of some of the helper methods such as `setSourceId` and `setType`
4. Again, some time later, modify the `/v1/place` endpoint so it only searches for documents based on the Pelias GID and the `_id` field.

To do this in a backwards compa

**Comment by missinglink** [comment]
Sounds good!

One thing you didn't mention here is that we could set the _id to null and I believe ES would generate a random ID for us?

I believe the shard balancing (what ES calls routing) is based on a modulo of the _id, so an even distribution of that algorithm would be ideal in order to get balanced shards

**Comment by orangejulius** [comment]
Avoiding all use of Elasticsearch `_id`s is interesting. It would be nice to ensure faster imports and even shard distribution. On the other hand, that would potentially mean we could have duplicate documents with the same GID. Definitely worth exploring before proceeding.

**Comment by orangejulius** [comment]
I just tested the behavior of Elasticsearch 5.6 when no `_id` is specified in a bulk import. As expected, it does mean that running an importer multiple times on the same data would create duplicate records in Elasticsearch.

This would be a big change in behavior and I think we'd rather avoid having to deal with communicating that to the community.

In my opinion it's better to keep assigning `_id`s, but do it more intelligently.

@missinglink let me know if you'd prefer to do it differently, or I'll merge https://github.com/pelias/api/pull/1329 tomorrow to get us started on the migration path for our GIDs so we can move onto ES6!

**Comment by Joxit** [comment]
:+1: to keep assigning `_id`s :slightly_smiling_face:
