### ISSUE TITLE
is there a way to make Pelias not care about a comma?

### ISSUE THREAD

**Issue by fpurcell** [pelias/pelias#673]
Compare:

[/v1/search?text=Starbucks Lake Oswego](https://pelias.github.io/compare/#/v1/search%3Ftext=Starbucks%20Lake%20Oswego)
[/v1/search?text=Starbucks, Lake Oswego](https://pelias.github.io/compare/#/v1/search%3Ftext=Starbucks,%20Lake%20Oswego)

Note that w/out a comma between Starbucks and Lake Oswego (a city in Oregon), we don't get any Starbucks locations...

From Diana (10/18/2017):
This is due to the fact that we currently don’t use the placeholder service for venue queries. i think we’ll add that ability in the near future.  libpostal parses the query correctly with or without the comma. we just don’t build the query properly using the parts it identified.  would be a great issue to add to pelias/pelias if you could...

**Comment by orangejulius** [comment]
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 
![Screenshot_2019-10-03_15-51-06](https://user-images.githubusercontent.com/111716/66159274-a933c000-e5f5-11e9-8db3-602c941ee0d3.png)
