### ISSUE TITLE
v1/autocomplete matches against foreign-language version

### ISSUE THREAD

**Issue by vincent-eb** [pelias/pelias#674]
Hello!

---
#### Here's what I did :innocent:

Hit:
   
[/v1/autocomplete?sources=wof&layers=locality,region,borough&text=vene](https://pelias.github.io/compare/#/v1/autocomplete%3Fsources=wof&layers=locality,region,borough&text=vene)
[/v1/autocomplete?sources=wof&layers=locality,region,borough&text=venezia](https://pelias.github.io/compare/#/v1/autocomplete%3Fsources=wof&layers=locality,region,borough&text=venezia)

---
#### Here's what I got :scream_cat:

The results list `Venice, Italy` as an option (note first query has `text=vene`). 
If I continue to enter `text=venezia`, the only match that returns is `Venice, Italy`. Further if I search `text=venice`, `Venice, Italy` is not included in any of the responses but `Venice, Florida` and other places are. 

---
#### Here's what I was expecting :sparkles:

`text=venice` to match and return `Venice, Italy` in addition to `Venice, Florida` etc. And `Venezia` to not match against anything, instead of matching against `Venice, Italy`

**Comment by missinglink** [comment]
hi @vincent-eb we are currently working on some improvements to `/v1/autocomplete` which should bring it closer to the results provided by `/v1/search` for queries which are for administrative areas such as towns/cities/regions.

Regarding the display language, you may specify `?lang=it` to use Italian labels where available.

As far as I can tell, we have 2 records for `Venice Italy`, one is for the City and one is for the Greater Region of the same name.

I will keep this bug report open and add it to our current milestone, thanks!

**Comment by orangejulius** [comment]
This looks fixed now!
<img width="643" alt="Screen Shot 2019-05-14 at 3 29 22 PM" src="https://user-images.githubusercontent.com/111716/57726301-1a7dd100-765d-11e9-928b-8224f4c75b55.png">

It was probably solved by https://github.com/pelias/whosonfirst/pull/423 along with https://github.com/pelias/pelias/issues/786
