### ISSUE TITLE
interpolate addresses at query time

### ISSUE THREAD

**Issue by sevko** [pelias/pelias#68]
Now that some elasticsearch records will contain house numbers (along with other address data), it should be possible for us to approximate the location of an address if we don't have an exact match. For instance, if our index contains `1 Pelias Place` and `5 Pelias Place`, a query for `3 Pelias Place` should return the midpoint of the line segment between those two addresses. This will obviously fail when we're dealing with curved roads, but that should be a non-issue if we restrict interpolations to points that are within ~20 (?) meters of one another.

We'd need to:
1. identify that a given query is searching for an address
2. extract the house number
3. figure out whether a 100% match was returned
4. if not, sort the results by house number relative to the number searched for (see pelias/pelias#62)
5. interpolate a location between the top two results, _if_ they're tolerably close

**Comment by sevko** [comment]
Address data is now being populated by both the OSM and OpenAddresses importers, so this is becoming achievable. (cc @hkrishna)

**Comment by missinglink** [comment]
This street is a great test-case for this: http://www.openstreetmap.org/way/4685718

Rigaer Straße has numbering up one side and alternating odd/even numbering one street away on Weidenweg

**Comment by riordan** [comment]
For the US, the Census Bureau releases an annual dataset called [TIGER/line](http://www.census.gov/geo/maps-data/data/tiger-line.html) that's every street centerline in the United States with data specifically for line interpolation geocoding. This is what drives the [PostGIS Tiger Geocoder extension](http://postgis.net/docs/Extras.html#Tiger_Geocoder) that Enigma recently built some [very effective tooling](http://blog.enigma.io/spin-up-the-tiger-geocoder-quickly/) to simplify.

It's also what lets [Nominatim](http://wiki.openstreetmap.org/wiki/Nominatim/Installation#Installing_Tiger_housenumber_data_for_the_US) return US addresses not hand-labeled in OSM.

Wouldn't solve every sparse area, but would at least get us excellent coverage in the US.

**Comment by riordan** [comment]
Also, we're a mere month away from 2015's TIGER release!
