### ISSUE TITLE
Using polygon as boundary

### ISSUE THREAD

**Issue by svenkoer** [pelias/pelias#680]
Hey,

Currently Pelias supports countries, rectangles, circles as well as overlapping areas of the three shapes as boundaries. Did you consider adding support for polygons? I know it's a bit of an exotic use case. Nevertheless do you think it would be especially difficult (or easy) to add support for polygons?

**Comment by svenkoer** [comment]
Hi @missinglink that is good to know. I think we can work with that. I guess this will then be added to a milestone once the decision is made?

**Comment by missinglink** [comment]
Yes, we usually post our upcoming quarterly goals at http://pelias.io, It's not scheduled for this year but it's definitely on the list for next year.

**Comment by missinglink** [comment]
If you could provide more information on how you would like to use the feature, we can use that information to influence the design plan.

**Comment by svenkoer** [comment]
We might be able to use this feature by setting up pseudo WoF regions which would be the polygons we need as boundaries.

**Comment by orangejulius** [comment]
If and when we implement support for filtering by whosonfirst ID, we'll provide updates here: https://github.com/pelias/api/issues/373
