### ISSUE TITLE
Better search results with autocomplete than search with this address in Rochester, NY (postal cities)

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#683]
#### Here's what I did :innocent:
This came in through support (see Desk 1223).

Searching for 3405 Culver Rd, Rochester NY 14622

[/v1/autocomplete?text=3405 Culver Rd, Rochester NY 14622](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=3405%20Culver%20Rd,%20Rochester%20NY%2014622)

[/v1/search?text=3405 Culver Rd, Rochester NY 14622](http://pelias.github.io/compare/#/v1/search%3Ftext=3405%20Culver%20Rd,%20Rochester%20NY%2014622)

This address appears to be officially within Irondequoit, and can be found in /search if you use Irondequoit instead of Rochester, which means it is likely a "postal cities" situation.

---
#### Here's what I got :scream_cat:
Autocomplete finds the exact match, but Search falls back to the street. 

Autocomplete
"properties": {
        "id": "us/ny/statewide:dd1f5acbaffe2c1a",
        "gid": "openaddresses:address:us/ny/statewide:dd1f5acbaffe2c1a",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us/ny/statewide:dd1f5acbaffe2c1a",
        "name": "3405 Culver Road",
        "housenumber": "3405",
        "street": "Culver Road",
        "postalcode": "14622",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "point",

Search
"properties": {
        "id": "polyline:21314970",
        "gid": "openstreetmap:street:polyline:21314970",
        "layer": "street",
        "source": "openstreetmap",
        "source_id": "polyline:21314970",
        "name": "Culver Road",
        "street": "Culver Road",
        "confidence": 0.8,
        "match_type": "fallback",
        "accuracy": "centroid",

---
#### Here's what I was expecting :sparkles:
Search to return the same result. If you search for the actual locality name, search does find it.

https://mapzen.com/search/explorer/?query=search&text=3405%20Culver%20Rd%2C%20Irondequoit%20NY%2014622

---
#### Here's what I think could be improved :trophy:
This could be a postal cities issue. See also https://github.com/pelias/pelias/issues/396

**Comment by orangejulius** [comment]
This appears to have been fixed at some point. Both search and autocomplete now return the correct address with the locality set to `Rochester`:
![Screenshot_2019-03-28_14-45-07](https://user-images.githubusercontent.com/111716/55184308-2f171000-5168-11e9-9855-b5e64a3e5f34.png)
