### ISSUE TITLE
Russian street has dissappeared in latest builds

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#685]
See [/v1/search?text=Фурштатская улица Saint Petersburg 191028](http://pelias.github.io/compare/#/v1/search%3Ftext=%D0%A4%D1%83%D1%80%D1%88%D1%82%D0%B0%D1%82%D1%81%D0%BA%D0%B0%D1%8F%20%D1%83%D0%BB%D0%B8%D1%86%D0%B0%20Saint%20Petersburg%20191028)
![image](https://user-images.githubusercontent.com/111716/33036920-f2e8bea6-cdfd-11e7-8efc-f107054e767f.png)

Its unclear if this is a build failure, or data change.

**Comment by missinglink** [comment]
looks like this change was rolled out to production, without a copy of the old results/ids its hard to guess where those addresses were coming from.

do you remember anything more about them, like were they osm/oa?

**Comment by orangejulius** [comment]
Doh, I don't have the id :( We can load an old build to get it next week if we need to.

The streets are from OSM, and originally it was [this acceptance test](https://github.com/pelias/acceptance-tests/blob/master/test_cases/international.json#L177-L197, which is now failing.

**Comment by orangejulius** [comment]
I don't think we'll be able to debug the cause of this, and I can't remember what the original impetus for reporting this particular issue was.
