### ISSUE TITLE
Unrelevant results when query is parsed as a neighbourhood name

### ISSUE THREAD

**Issue by amatissart** [pelias/pelias#687]
Hey team! 

---
#### Here's what I did :innocent:
http://pelias.github.io/compare/#/v1/search%3Ftext=porte%20dauphine
"Porte Dauphine" is both a neighbourhood and a subway station in Paris, France.

---
#### Here's what I got :scream_cat:
```javascript
{
  "geocoding": {
    "version": "0.2",
    "attribution": "http://pelias.mapzen.com/v1/attribution",
    "query": {
      "text": "porte dauphine",
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "neighbourhood": "porte dauphine"   // Parsed as a Neighbourhood
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1511263588624
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          -87.014718,
          45.016525
        ]
      },
      "properties": {
        "id": "102081831",
        "gid": "whosonfirst:county:102081831",
        "layer": "county",
        "source": "whosonfirst",
        "source_id": "102081831",
        "name": "Door County",     // Not really relevant :(
        "confidence": 0.4,
        "match_type": "fallback",
        "accuracy": "centroid",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Wisconsin",
        "region_gid": "whosonfirst:region:85688517",
        "region_a": "WI",
        "county": "Door County",
        "county_gid": "whosonfirst:county:102081831",
        "continent": "North America",
        "continent_gid": "whosonfirst:continent:102191575",
        "label": "Door County, WI, USA"
      },
      "bbox": [
        -87.762476,
        44.675192,
        -86.249548,
        45.44423
      ]
    },
    ...
```

---
#### Here's what I was expecting :sparkles:
Results for "porte dauphin" are actually much more relevant :
http://pelias.github.io/compare/#/v1/search%3Ftext=porte%20dauphin

---
#### Here's what I think could be improved :trophy:
When the query "porte dauphine" is parsed as a neighbourhood, results are retrieved exclusively from wof (via Placeholder), although no relevant document is found.

Also note that a neighbourhood "Quartier de la Porte Dauphine" exists in wof : https://whosonfirst.mapzen.com/spelunker/id/85873981/

Should the placeholder query be more permissive ?
Should a variant name be added in wof for that specific query ?
Or maybe the search pipeline could be improved to handle such cases when placeholder gives poor results ?

**Comment by missinglink** [comment]
I have updated 85873981 in the 'Boundary Issues' system to add "Porte Dauphine" and a common colloquial name for 'Quartier de la Porte Dauphine' in French.

This won't be enough to solve the issue, I will bring it up in our team meeting today, thanks for the report @amatissart

**Comment by orangejulius** [comment]
This looks to be fixed, the query above now returns the city! 🎉 
<img width="426" alt="Screen Shot 2019-05-13 at 8 02 58 AM" src="https://user-images.githubusercontent.com/111716/57620024-97258800-7555-11e9-8f89-cad26b01b9fa.png">
