### ISSUE TITLE
Postal cities issue when searching for addresses in Conroe, Montgomery County, TX

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#696]
#### Here's what I did :innocent:

This came in through support (see Desk 1323):

Searching for 1606 Cafe Dumonde, Conroe, Texas 77304

[1606 Cafe Dumonde, Conroe, Texas 77304](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1606%20Cafe%20Dumonde,%20Conroe,%20Texas%2077304)

---
#### Here's what I got :scream_cat:

This address should be returning as 1606 Cafe Dumonde, Conroe, Texas 77304, United States but it's showing as "1606 Cafe Dumonde, The Woodlands, TX, USA".

```
"properties": {
        "id": "us/tx/montgomery:362b4d9cae5e711f",
        "gid": "openaddresses:address:us/tx/montgomery:362b4d9cae5e711f",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "us/tx/montgomery:362b4d9cae5e711f",
        "name": "1606 Cafe Dumonde",
        "housenumber": "1606",
        "street": "Cafe Dumonde",
        "postalcode": "77304",
        "accuracy": "point",
        "country": "United States",
        "country_gid": "whosonfirst:country:85633793",
        "country_a": "USA",
        "region": "Texas",
        "region_gid": "whosonfirst:region:85688753",
        "region_a": "TX",
        "county": "Montgomery County",
        "county_gid": "whosonfirst:county:102081435",
        "locality": "The Woodlands",
        "locality_gid": "whosonfirst:locality:101727415",
        "neighbourhood": "Alden Bridge",
        "neighbourhood_gid": "whosonfirst:neighbourhood:85893749",
        "label": "1606 Cafe Dumonde, The Woodlands, TX, USA"
      }
```

Note that if you use /search, it falls back to the city because that endpoint is more sensitive to having the exact city name.

---
#### Here's what I was expecting :sparkles:

The locality should be Conroe.

There appears to be good geometry for Conroe and The Woodlands in WoF, and they do not overlap. Also, the OpenAddresses data shows this location as being in Conroe, so Search overrides it.

---
#### Here's what I think could be improved :trophy:

Fix postal cities issue or use the source data as it appears in OA.

**Comment by orangejulius** [comment]
Definitely connects https://github.com/pelias/pelias/issues/396

**Comment by orangejulius** [comment]
This address doesn't come up at all in the autocomplete query above now.

However, a search query returns an interpolated result with the correct locality:

[/v1/search?text=1606 Cafe Dumonde, conroe, tx, USA](http://pelias.github.io/compare/#/v1/search%3Ftext=1606%20Cafe%20Dumonde,%20conroe,%20tx,%20USA)

```
    1) 1606 Cafe Dumonde, Conroe, TX, USA
```

It looks like the OA data source was broken, I've opened https://github.com/openaddresses/openaddresses/pull/4471 to fix it.

**Comment by orangejulius** [comment]
OpenAddresses source is fixed, so this is now fixed!
<img width="421" alt="Screen Shot 2019-05-13 at 7 57 00 AM" src="https://user-images.githubusercontent.com/111716/57619743-b5d74f00-7554-11e9-8e1e-1c0a7d66cd90.png">
