### ISSUE TITLE
ES 5+

### ISSUE THREAD

**Issue by dkuida** [pelias/pelias#698]
Hi all

I am using successfully pelias on a custom data, unfortunately I cannot share the importers as they are proprietary - what I do want to do is to add support for Elastic Search 5, as there are are few migration issues.

What I am looking for is first to know if there is an active or even abandoned branch that I can work on, and any direction or highlights known

**Comment by orangejulius** [comment]
Hey @dkuida,
Thanks for asking! There is a discussion about ES5 over in https://github.com/pelias/pelias/issues/461.

The good news is we do have branches where everything works. I don't recall exactly where they all live, but they are all linked in that issue and as far as I know, the checklist of things todo in the comments is still up to date.

We haven't thought much about ES 5 support in a while, but it's past time we support it. My feeling is that we will merge it soon after the holidays, early next year. 

Please test things out and let us know how it goes.

**Comment by dkuida** [comment]
thanks, I will be happy to report progress and help with issues
