### ISSUE TITLE
170M entries missing after full planet import

### ISSUE THREAD

**Issue by dominikkukacka** [pelias/pelias#707]
Hey team,
How many entries should a planet build contain? Somehow after running all the importers I only got 331M entries. It should be 509M no?

![image](https://user-images.githubusercontent.com/243319/35501125-471c4828-04d9-11e8-9876-b3a991ff218f.png)

Any idea what is missing?

**Comment by orangejulius** [comment]
Hey @dominikkukacka,
Here's the latest stats from our build for geocode.earth
![image](https://user-images.githubusercontent.com/111716/35661854-eb6abcec-06e2-11e8-8d98-b1a9c710ae57.png)

It looks like you're missing a lot of addresses, some venues, and almost all of the streets (but you have more postalcodes!)

The streets only come from the `polyline` importer, so something must be broken there. Addresses mostly come from the OpenAddresses importer, so odds are something there is wrong too. Either there's a problem with multiple importers, or something common between them. Take a look at the PIP service, as well as Elasticsearch itself for errors during the import.

Let me know what you find or if you need suggestions for what to dig into, I'd be very curious to find out what it is.

**Comment by dominikkukacka** [comment]
Hey @orangejulius,
thanks for the answer! I got many errors on the *polylines importer* such as:
```
[polyline] polyline document error PeliasModelError: invalid axis: longitude, 180.317625
[polyline] polyline document error PeliasModelError: invalid boundingBox, property 'upperLeft.lon' must be within range -180 to 180
[polyline] invalid polyline row F2S<UD�^Ddg@�:��^F��f~��Z�    wD5>t��f^Wm�9p�ö:f�^]��o�����L��فH�
```
and so on. Is there any possibility to debug this?

As of the *openaddresses importer*, I got some dbclient errors:
```
[dbclient] [429] type=es_rejected_execution_exception, reason=rejected execution of org.elasticsearch.transport.TransportService$4@25ae843 on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@2653d053[Running, pool size = 8, active threads = 8, queued tasks = 56, completed tasks = 1956908]]
[dbclient] transaction error reached max retries
```

>Take a look at the PIP service
I have a pretty old version of pelias due to some major changes of functionality we need. I am not sure the PIP service was introduced back then. What exactly does it do and when does it provide data? 

Thanks

**Comment by orangejulius** [comment]
The PIP service is used as a replacement for the in-process point-in-polygon lookup that was previously used. Both of them need to load Who's on First data. They're mostly the same code though.

The openaddresses importer is getting the error I kinda suspected. I think the module that manages sending bulk indexing requests to Elasticsearch does not have proper throttling, and it can overwhelm even moderate sized Elasticsearch clusters. We're taking a look at that over at https://github.com/pelias/dbclient/issues/76

**Comment by orangejulius** [comment]
Between pelias/dbclient#76 and https://github.com/pelias/dbclient/pull/108, this should be solved now.

Looking back, it's certainly a case of the importers overwhelming Elasticsearch.

If anyone is still seeing behavior like this today, please post some info about your import process such as:

- total hardware configuration (CPU, RAM, disk) given to elasticsearch and importers
- number of importers run at once
- Elasticsearch version
