### ISSUE TITLE
Does Pelias run with node.js version 8?

### ISSUE THREAD

**Issue by jengeb** [pelias/pelias#711]
Dear Pelias Team,

Thank you very much for your service. I think about running an instance of Pelias and read the [installation instructions](http://pelias.io/install.html). This documentation recommends using node 4 or 6. Is it possible to use node 8 as well?

Best,
Jenny

**Comment by orangejulius** [comment]
Hey @jengeb,
Thanks for asking. I do believe everything works on Node.js 8 now.

The main tracking issue for this is https://github.com/pelias/pelias/issues/612, and you can see we have a pull request for our [dockerfiles](https://github.com/pelias/pelias/issues/612) repo (an easy way to get started running pelias), to move our docker images to node 8.

We'll also probably be [dropping support for Node.js 4 soon](https://github.com/pelias/pelias/issues/693).

Any feedback you can provide on how well things do or don't work with Node.js 8 is much appreciated :)

**Comment by jengeb** [comment]
Hi @orangejulius,

Thanks for your quick and very informative response and sorry about the duplicate issue.
