### ISSUE TITLE
Pelias.io docker links to the deprecated repository

### ISSUE THREAD

**Issue by Flaburgan** [pelias/pelias#727]
On the home page of pelias.io, the link targets https://github.com/pelias-deprecated/dockerfiles instead of pelias/. I grepped the files but wasn't able to find pelias-deprecated string in this repo. The readme.md directly in github has the good link, maybe you just didn't push the last version to pelias.io?

**Comment by orangejulius** [comment]
Hey @Flaburgan,
We moved the repository from the `pelias` org to the `pelias-deprecated` org, and Github understands that natively, setting up appropriate redirects. Thus, all links to the repository's old location in the `pelias` org will still work, including those on [pelias.io](https://pelias.io)

**Comment by Flaburgan** [comment]
Well, it looks like the opposite is going on: the link at "To try out Pelias quickly, use our Dockerfiles setup." is targeting `pelias`, but there is a redirection and clicking on it end on https://github.com/pelias-deprecated/dockerfiles.

**Comment by orangejulius** [comment]
I think part of the confusion is that we hadn't updated any of the links at all until just now. You should now see all the links go to github.com/pelias/docker. This bypasses the whole deprecated/redirect issue since there are now no links to the old repo.

Let me know if that clears it up.
