### ISSUE TITLE
Village Korzkiew not found

### ISSUE THREAD

**Issue by pkubowicz** [pelias/pelias#729]
---
#### Here's what I did :innocent:
Searched http://pelias.github.io/compare/#/v1/search%3Ftext=Korzkiew

---
#### Here's what I got :scream_cat:
```{
  "geocoding": {
    "version": "0.2",
    "attribution": "https://geocode.earth/guidelines",
    "query": {
      "text": "Korzkiew",
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "city": "korzkiew"
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1531237709754
  },
  "type": "FeatureCollection",
  "features": []
}
```

---
#### Here's what I was expecting :sparkles:
Village in Poland: https://www.openstreetmap.org/relation/3274142

---

**Comment by pathmapper** [comment]
This is the OSM place node: https://www.openstreetmap.org/node/31901732

Looks like this is the same issue as described in https://github.com/pelias/pelias/issues/728.

If you are searching for **Korzkiew, Voivodeship Lesser Poland** the village is found:
http://pelias.github.io/compare/#/v1/search%3Ftext=Korzkiew,%20Voivodeship%20Lesser%20Poland

**Comment by pathmapper** [comment]
This is resolved and could be closed:
https://pelias.github.io/compare/#/v1/search%3Ftext=Korzkiew
