### ISSUE TITLE
Pelias SDK for Android

### ISSUE THREAD

**Issue by alex96frolov** [pelias/pelias#730]
Hey team! 

I want to know if there is Pelias SDK for Android. Can anyone help me with this?

**Comment by orangejulius** [comment]
Hey @alex96frolov,
There is https://github.com/pelias/pelias-android-sdk, which was worked on by another team at Mapzen. I have no idea what state it's currently in, but if you have a minute to check it out and report back, that would be appreciated. I hope it's useful to you.

**Comment by alex96frolov** [comment]
Hey @orangejulius ,
Yes, I tried this SDK but it seems not be working and maintained. Search requests gave me SSLHandshakeExceptions only. 
Now I want to try it in another way just performing search requests by myself.
I found Pelias API endpoints here https://github.com/pelias/documentation
but I don't understand what host should I use?
Can you help me please with this?

**Comment by orangejulius** [comment]
Pelias is not a service, it's only the code. You can set it up yourself or there are several instances of Pelias on the internet, some which cost money to use.

The pelias-android-sdk also likely has a default of `search.mapzen.com` which was run by Mapzen and shut down at the start of the year.

I'd suggest setting up your own Pelias using http://github.com/pelias/docker/, and then configuring the android SDK to use that. Unfortunately no one currently active on the Pelias team is really an android developer, so we can't help much with the SDK itself. Although we can probably get you some time with the original authors if it would help revive the project. Let us know how it goes.

**Comment by alex96frolov** [comment]
@orangejulius Thanks for reply!
Just ine question left.
Does Pelias Autocomplete support different languages for queries?

**Comment by orangejulius** [comment]
Hey @alex96frolov,
Almost missed this :)

Pelias does not _currently_ support querying in different languages when using the autocomplete endpoint. It does for the search endpoint, and will support autocomplete soon.

**Comment by orangejulius** [comment]
I'd be curious to hear if https://github.com/pelias/pelias-android-sdk is workable. However it looks like we've answered all the questions here, so I'm closing this issue. 

I'd love a report from someone on the android-sdk if they happened to check it out :)
