### ISSUE TITLE
Geo Sync Problem between OSM an openrouteservice

### ISSUE THREAD

**Issue by neo13476** [pelias/pelias#731]
Hey team! 

I have found an wrong database entry on openrouteservice an the team have told me, that they use pelias as a geocoder.
https://github.com/GIScience/openrouteservice-app/issues/241#issuecomment-409113226 

Wenn I am trying to find the adress "Lothringer Straße, Oberhausen", there is no result.

Then I haved tried to find the location on the map manually. The adress is named as:
Lothringer Straße, Styrum, Mülheim, Mülheim an der Ruhr , Nordrhein-Westfalen, Germany

Thats not correct. The street is located in the town "Oberhausen".
The city border is marked correct a little south ...

On originally map on osm.org the location is correctly found at "Lothringer Straße, Oberhausen".
I can (I) solve problems like this?

Regards
Tobias

**Comment by missinglink** [comment]
Hi all,

Streets are associated with the administrative hierarchy based on their midpoint.

So if a point measured 50% along a linestrong lies outside the city/country border, it will not be associated with that administrative area.

Is that what's happen here?

**Comment by missinglink** [comment]
The polygons can be huge so we don't generally store then in elasticsearch.

You can view them on the WOF site here: http://spelunker.whosonfirst.org/id/102063801

**Comment by nilsnolde** [comment]
Thanks @missinglink. Spelunker seems to be down atm. Before I open an issue at their place (and it's not really an issue): who is hosting it these days? Only found this oldish post from [@thisisaaronland](https://www.whosonfirst.org/blog/2018/01/02/chapter-two/)... Rather long and using mostly 'short-term' explanations what's gonna happen, where I assume we're past short-term.

And let me know if we can help in any way.

**Comment by thisisaaronland** [comment]
The Spelunker does not have HTTP -> HTTPS redirects at the moment. The correct URL is:

https://spelunker.whosonfirst.org/id/102063801/

**Comment by missinglink** [comment]
Just stumbled on this old issue, this seems to have been resolved some time ago, I'm going to close the issue now.

https://pelias.github.io/compare/#/v1/autocomplete?text=Lothringer+Stra%C3%9Fe%2C+Oberhausen&debug=1

<img width="697" alt="Screenshot 2022-03-16 at 12 07 33" src="https://user-images.githubusercontent.com/738069/158576721-fc5b7f16-ef37-4c4a-8a01-664bc9ce8d83.png">
