### ISSUE TITLE
A couple of wrong Canadian postal code coordinates

### ISSUE THREAD

**Issue by ivanakimov** [pelias/pelias#732]
Hey team! 

We're using your awesome geocoding engine when a customer noticed something interesting:

---
#### Here's what I did :innocent: & here's what I got :scream_cat:

Looks like geocoding for the following postal codes return wrong coordinates:
- `L0S 1S0` returns `[-79.336939, 43.05241]` -- https://api.geocode.earth/v1/search?api_key=XXX&text=L0S%201S0
- `L8N 2H4` returns `[-80.005818, 43.429765]` -- https://api.geocode.earth/v1/search?api_key=XXX&text=L8N%202H4

Big G says:
- `L0S 1S0` is approximately at `[-79.054933, 42.948323]`
- `L8N 2H4` is approximately at `[-79.865761, -80.005818]`

API says the source is `whosonfirst`. Not sure how to submit a data fix and on which side. Any suggestions?

**Comment by trescube** [comment]
Hey @ivanakimov, thanks for using Pelias!  Who's on First is the gazetteer that Pelias uses for places.  We don't directly control that data, even though it was developed at Mapzen along with Pelias.  For contributing data corrections please see: https://whosonfirst.org/docs/contributing/.

**Comment by ivanakimov** [comment]
Thanks for the quick response @trescube, I submitted an issue there. Not sure if we have the ability to submit data edits directly.

**Comment by trescube** [comment]
👍 Issues will work fine.  There are some editing tools but I'm not sure how actively they're maintained.

**Comment by orangejulius** [comment]
Yeah, in theory WOF does accept PRs, but in practice they have a fairly complicated workflow. They are just fine with issues, and thanks for this one!
