### ISSUE TITLE
Openrouteservice API rest search valid location name 0 restults

### ISSUE THREAD

**Issue by JulianDietz** [pelias/pelias#734]
Hey team! 

Im using the Openrouteservice API. I contacted them about my Issue and they told me to write an issue here, because they use pelias as geocoder.

---
#### Here's what I did :innocent:
Im using the Openrouteservice API in order to get coordinates for location name. They told me, that they use Pelias for this issue. 
The Problem is, that if use the full location name (e.g Aigenstadl) I get 0 Results.
But if I remove the last letter (eg. Aigenstad for Aigenstadl) I get some Results.
[Demo](https://maps.openrouteservice.org/)

---
#### Here's what I got :scream_cat:
I get 0 Results for the full location name (e.g Aigenstadl).
If I type in the location name without last character (eg. Aigenstad for Aigenstadl) I get some Results, including the full location name.

Can you confirm this Issue?

Regards
Julian

**Comment by Joxit** [comment]
Hi Julian,

This seems to be a data issue.
Aigenstadl is a village/distrinct of the city Freyung and this district is not in Who's On First.
When you type `Aigenstadl`, pelias parser libpostal detects that it is a city and then looks for a city with that name. But we don't have this entry in who's on first.

When you type  `Aigenstad` It looks in all the fields and sends you results (here addresses  or streets and not the village itself).

It seems that there is an entry in [geonames](http://www.geonames.org/search.html?q=Aigenstadl) but there are no fallback on geonames for city queries :confused:

**Comment by orangejulius** [comment]
This seems to be fixed, I get a good result from the following query

[/v1/search?text=Aigenstadl](https://pelias.github.io/compare/#/v1/search%3Ftext=Aigenstadl)
<img width="421" alt="Screen Shot 2019-05-13 at 8 00 06 AM" src="https://user-images.githubusercontent.com/111716/57619918-38f8a500-7555-11e9-9364-9920bd110b26.png">
