### ISSUE TITLE
RESTful Error Messages

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#74]
The overlimit error seems to be the wrong code? and missing a human readable error message.

```javascript
{
  "overLimit": {
    "code": 413,
    "message": "OverLimit Retry...",
    "details": "Error Details...",
    "retryAfter": "2015-04-06T19:26:35Z"
  }
}
```

**Comment by heffergm** [comment]
This is working as designed. The system will be replaced when api keys are rolled out. Closing as a noop.
