### ISSUE TITLE
Reverse Geocoding on a liste of custom GeoJson areas

### ISSUE THREAD

**Issue by Namec** [pelias/pelias#741]
Hello All,

currently i am looking to use Pelias strentgh to do some reverse geocoding in a list of GeoJson's Areas.

currently doig this by storing the geometries in an SQL database and then doing some SQL stuff, to make it work.

i am sure, that Pelias can do this more quickly than ever, while making me free some ressources for other tasks.

anyone already figured how to deal with this ?

**Comment by orangejulius** [comment]
Hi Namec,
Pelias doesn't currently support custom polygon data, however it is something we're looking at for the future. There isn't one now, but when there is a Github issue for tracking that work, I'll post it here.
