### ISSUE TITLE
Use WOEID as a tie breaker

### ISSUE THREAD

**Issue by hkrishna** [pelias/pelias#75]
We have ```woeid``` for various documents from the admin-lookup. We could potentially use this as a tie-breaker (if not anything big) (involves a pelias/script that looks for ```woeid``` in a given document and bump the ```_score``` value)

**Comment by sevko** [comment]
Why would WOEID correlate to score? If it's only being used since it's unique, we can probably get away with just using the document id.

**Comment by hkrishna** [comment]
in case of a tie between two points for a search query wherein one document has WOEID and the other document doesn't. We could weigh the former point higher because its more valuable. Does that sound reasonable?

**Comment by sevko** [comment]
Oh, that's interesting. Makes sense to me.

**Comment by sevko** [comment]
Will this apply only to Quattroshapes records imported via `quattroshapes-pipeline`, or do you want this to trickle down into records in `admin-lookup`? The former, right?

**Comment by hkrishna** [comment]
yeah, just the former. only the records that have a ```woe_id``` set on them - it may not just be ```quattroshapes```, it could any dataset that carries ```woe_id```

**Comment by riordan** [comment]
No longer relevant with Who's on First. We'll try to update popularity scores across different data types via WoF as well.

(hey @hkrishna @sevko. How're you guys doing?)
