### ISSUE TITLE
Many Londons returned for search query

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#751]
Running a standard search query for `London` returns _many_ instances of London:

[/v1/search?text=london, uk](http://pelias.github.io/compare/#/v1/search%3Ftext=london,%20uk)
![image](https://user-images.githubusercontent.com/111716/46960779-42786800-d06d-11e8-9db8-015426906680.png)

Looking at the GIDs, they are all different records:
```
"whosonfirst:locality:101750367"
"whosonfirst:locality:101914069"
"whosonfirst:locality:101914077"
"whosonfirst:locality:101914085"
"whosonfirst:locality:101914081"
"whosonfirst:locality:101914071"
"whosonfirst:locality:101914079"
```

However conceptually they don't feel very different. Are we not applying deduplication to records returned from Placeholder?

While not a high priority issue in itself, this particular query is the default query for the compare app, and I wonder if it's a confusing first experience with Pelias for many people.

**Comment by missinglink** [comment]
Looking at the code it seems the `dedupe` step is a "postProc" middelware, so it should be applied to all results regardless of their origin.

My guess is that this case is not correctly covered by `dedupe`

**Comment by missinglink** [comment]
I had a look at the code for this today and it's not incorrect after all, not pretty, but not incorrect :P

The reason this occurred is that each of those London records was parented by a different county (called a 'region' in WOF for some reason) and the code considered differing `region_id` values as distinct records.

This is certainly true in the USA where a `region` is a state, so any logic changes would need to be country-specific.

Fortunately, the data issue has been resolved so we probably don't need to do anything.

The following records have already been superceded and removed from WOF:

- https://spelunker.whosonfirst.org/id/101914069/
- https://spelunker.whosonfirst.org/id/101914077/
- https://spelunker.whosonfirst.org/id/101914085/
- https://spelunker.whosonfirst.org/id/101914081/

I've also opened a ticket to investigate removal of two more:

https://github.com/whosonfirst-data/whosonfirst-data/issues/1360

**Comment by orangejulius** [comment]
We've fixed this with proper data updates :)
