### ISSUE TITLE
Drop support for Node.js 6

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#752]
We should consider dropping support for Node.js 6 soon.

While version 6 won't go end of life until [April 2019](https://github.com/nodejs/Release#release-schedule), it might make sense to drop support sooner.

Some reasons include:
- Dramatic performance increases with each successive Node.js version (10 is much faster than 8 which is much faster than 6).
- Increased cost of testing: it takes extra time to run our tests against 3 Node.js versions instead of 2
- Dependencies dropping support for Node.js 6. We have already seen [better-sqlite3](https://github.com/JoshuaWise/better-sqlite3/commit/b7b79c1e1d775c622290aeacfed23030e33c33fd) drop Node.js 6, and as more packages start to do so, it may be harder to stay on top of feature and security updates.

Our Dockerfiles [already use Node.js 8](https://github.com/pelias/baseimage/blob/master/Dockerfile#L32), and barring any other good reason, I propose we drop support for Node.js 6 starting on October 23rd, which is when [Node.js 11 will be released](https://github.com/nodejs/Release#release-schedule) _(note: we won't immediately add support for Node.js 11, but might start testing it)_

**Comment by missinglink** [comment]
Fine with me, if the docker setup is running 8 without any issue then I don't see any reason not to.

Being on node 8+ and elasticsearch 5.6 is a huge improvement on modernizing the stack vs what we were running at Mapzen :)

**Comment by orangejulius** [comment]
Here's a list of repositories where we need to drop Node.js 6 support:

## services
- [x] api
- [ ] document-service
- [ ] pip-service
- [ ] placeholder
- [x] interpolation

## importers
- [ ] whosonfirst
- [ ] openaddresses
- [x] geonames
- [ ] polylines
- [ ] openstreetmap
- [ ] transit
- [ ] csv-importer

## support modules
- [ ] query
- [ ] pbf2json
- [ ] logger
- [ ] dbclient
- [ ] config
- [x] schema
- [ ] sorting
- [ ] microservice-wrapper
- [ ] mock-logger
- [ ] labels
- [ ] categories
- [ ] wof-admin-lookup
- [ ] fuzzy-tester
- [ ] model
- [ ] polygon-lookup
- [ ] analysis

**Comment by orangejulius** [comment]
I had a little time to finish this off. All Pelias packages now require Node.js 8 or greater. :comet:
