### ISSUE TITLE
cannot search filtering custom source

### ISSUE THREAD

**Issue by 11sma** [pelias/pelias#755]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it. 

---
#### Here's what I did :innocent:
First at all thanks to all "issuers" and all "answerers" I learnt some tips from issues. I read all the existent issues for find some similar. I didn't find it and then I'm creating this. Sorry if finally exist but I didn't see it :( 
Note: I'm using pelias/docker but the issue is about pelias engine more than docker fact.

With document-service and it's api rest I'm able to import some custom data (great!!). I'm able to "classify" the source with a tag "custom-data". These data is now in pelias and I can recovery with rest showing source "custom-data" and "openadresses", for example, if it proceed. Then I wanted to filter to show only "custom-data" using 
"search?text=barcelona&**sources**=custom-data" 

---
#### Here's what I got :scream_cat:
I've received an error :(
"errors":["'custom-data' is an invalid sources parameter. Valid options: osm,oa,gn,wof,openstreetmap,openaddresses,geonames,whosonfirst"]

---
#### Here's what I was expecting :sparkles:
I expected the pelias response getting only the results under "custom-data".

---
I need to find, with your help, the way to say pelias has to accept the "sources=custom-data". Maybe is only configuration file or maybe it's no possible nowadays. Any response succesful or unsuccesful due pelias limitation are welcome. 

Lot of Thanks to all.

**Comment by missinglink** [comment]
hi @11sma, we're actively working on opening up Pelias to better support custom data.

for now, you'll have to manually tell Pelias the name of your new sources/layers, there is a configuration option available to allow you to do this:
https://github.com/pelias/api/pull/1131

in the future, we hope to provide automatic detection of sources and layers when the server starts-up, however, my initial testing showed that the server can be unresponsive for several seconds during boot-up while it's doing that operation, so it's currently disabled until we decide how best to provide that functinality.

hope that helps!

**Comment by missinglink** [comment]
If you live life in the fast lane you can have a crack at getting the auto-detection code working, I put a basic example in the code already here: https://github.com/pelias/api/blob/master/helper/TypeMapping.js#L135

There is also a config option already in place which could be used to enable/disable this functionality: https://github.com/pelias/config/blob/master/config/defaults.json#L42

**Comment by 11sma** [comment]
Hi @missinglink the solution you provided works perfectly! Lot of thanks for it :) I used the first way, i don't live life in the fast lane ⚡️ :p

For someone who has the same problem:
in pelias.json inside the project.

inside api.target

`	"targets": {
		"auto_discover": false,
		"canonical_sources": ["whosonfirst", "openstreetmap", "openaddresses", "geonames", " *custom-data* "],
		"layers_by_source": {
			*"custom-data": ["custom-data"],*
			"openstreetmap": [ "address", "venue", "street" ],
			"openaddresses": [ "address" ],
			"geonames": [ "country", "macroregion", "region", "county", "localadmin", "locality", "borough", "neighbourhood", "venue"],
			"whosonfirst": [
			  "continent", "empire", "country", "dependency", "macroregion", "region", "locality",
			  "localadmin", "macrocounty", "county", "macrohood", "borough", "neighbourhood",
			  "microhood", "disputed", "venue", "postalcode", "continent", "ocean", "marinearea"
			]
		}
	}`

Don't forget 
pelias compose down
pelias compose up
!

A better explanation is refered in @missinglink comment [https://github.com/pelias/api/pull/1131](https://github.com/pelias/api/pull/1131)

**Comment by missinglink** [comment]
Good to hear you got it working @11sma 

A couple notes:
- You shouldn't edit `canonical_sources`, better to leave that unmodified
- The pelias config merges your config with the default config, so you can omit any parts which are already specified in the default config.

eg: only a very small change needs to be made to your config:

```
$ cat ~/pelias.json 
{
  "api": {
    "targets": {
      "layers_by_source": {
        "custom-data": ["custom-data"]
      }
    }
  }
}
```

... which will be merged with the defaults:

```bash
$ node -e "console.log( JSON.stringify(require('pelias-config').generate(), null, 2) );" | jq .api.targets
{
  "auto_discover": false,
  "canonical_sources": [
    "whosonfirst",
    "openstreetmap",
    "openaddresses",
    "geonames"
  ],
  "layers_by_source": {
    "openstreetmap": [
      "address",
      "venue",
      "street"
    ],
    "openaddresses": [
      "address"
    ],
    "geonames": [
      "country",
      "macroregion",
      "region",
      "county",
      "localadmin",
      "locality",
      "borough",
      "neighbourhood",
      "venue"
    ],
    "whosonfirst": [
      "continent",
      "empire",
      "country",
      "dependency",
      "macroregion",
      "region",
      "locality",
      "localadmin",
      "macrocounty",
      "county",
      "macrohood",
      "borough",
      "neighbourhood",
      "microhood",
      "disputed",
      "venue",
      "postalcode",
      "continent",
      "ocean",
      "marinearea"
    ],
    "custom-data": [
      "custom-data"
    ]
  },
  "source_aliases": {
    "osm": [
      "openstreetmap"
    ],
    "oa": [
      "openaddresses"
    ],
    "gn": [
      "geonames"
    ],
    "wof": [
      "whosonfirst"
    ]
  },
  "layer_aliases": {
    "coarse": [
      "continent",
      "empire",
      "country",
      "dependency",
      "macroregion",
      "region",
      "locality",
      "localadmin",
      "macrocounty",
      "county",
      "macrohood",
      "borough",
      "neighbourhood",
      "microhood",
      "disputed",
      "postalcode",
      "continent",
      "ocean",
      "marinearea"
    ]
  }
}
```

**Comment by 11sma** [comment]
perfect! I'm going to edit my comment to no confuse other developers!

Thanks

**Comment by missinglink** [comment]
@11sma FYI https://github.com/pelias/api/pull/1316 just landed which automatically detects sources and layers

it's disabled by default but you can enable it with:

```
    "api": {
        "targets": {
            "auto_discover": true
        },
```

**Comment by 11sma** [comment]
great it's a good new!!! Is it available to docker version?

**Comment by missinglink** [comment]
Yes, everything is automatically published to dockerhub so it's available in the `latest` tag on dockerhub.

**Comment by missinglink** [comment]
You can view all the releases available on docker (including dev branches) here:
https://hub.docker.com/r/pelias/api/tags

Most users run the `latest` tag as this represents our stable versions.
