### ISSUE TITLE
Issue with comma in autocomplete

### ISSUE THREAD

**Issue by amadeus-x1** [pelias/pelias#756]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
[autocomplete U-11 Gurgaon](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=U-11%20Gurgaon)
[autocomplete U-11, Gurgaon](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=U-11,%20Gurgaon)

---
#### Here's what I got :scream_cat:
The first query (the one without comma) returns 0 hits, but just with the addition of the comma, things seem to be working.

---
#### Here's what I was expecting :sparkles:
The query without comma should also retrieve *some* results.

From what I was make out with my limited knowledge of pelias, no hits seems to be stemming from this part of the elastic search query

```
{
    "must": [{
        "match": {
            "name.default": {
                "analyzer": "peliasQueryFullToken",
                "type": "phrase",
                "boost": 1,
                "slop": 3,
                "query": "U-11"
            }
        }
    }, {
        "constant_score": {
            "query": {
                "match": {
                    "name.default": {
                        "analyzer": "peliasQueryPartialToken",
                        "boost": 100,
                        "query": "Gurgaon",
                        "type": "phrase",
                        "operator": "and",
                        "slop": 3
                    }
                }
            }
        }
    }]
}
```

I went through the previous threads and it seems that addressit has some issues with handling of commas, is there a way to handle this?

**Comment by orangejulius** [comment]
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 

Note that I had to change the search to "Gurugram" which is apparently the [official city name](https://en.wikipedia.org/wiki/Gurgaon)

![Screenshot_2019-10-03_16-14-31](https://user-images.githubusercontent.com/111716/66160791-e64d8180-e5f8-11e9-9388-66b8113fe340.png)
