### ISSUE TITLE
reverse geocoding does not return streets

### ISSUE THREAD

**Issue by qmapDL** [pelias/pelias#759]
Hey team! 
I am testing pelias using the docker version installed on a internal server loading osm and polylines data. 
The reverse geocoder seems to be missing results:

---
#### Here's what I did :innocent:
http://pelias.github.io/compare/#/v1/reverse%3Fpoint.lon=12.528708&point.lat=42.006977
---
#### Here's what I got :scream_cat:
{
  "geocoding": {
    "version": "0.2",
    "attribution": "https://geocode.earth/guidelines",
    "query": {
      "size": 10,
      "private": false,
      "point.lat": 42.006977,
      "point.lon": 12.528708,
      "boundary.circle.lat": 42.006977,
      "boundary.circle.lon": 12.528708,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": false
      },
      "querySize": 20
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1543419938469
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527874,
          42.006793
        ]
      },
      "properties": {
        "id": "it/countrywide:023623b6eab12fce",
        "gid": "openaddresses:address:it/countrywide:023623b6eab12fce",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:023623b6eab12fce",
        "name": "81 Via Capoliveri",
        "housenumber": "81",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.8,
        "distance": 0.072,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "81 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527874,
          42.006793
        ]
      },
      "properties": {
        "id": "it/countrywide:8bd9d2fa6f116c91",
        "gid": "openaddresses:address:it/countrywide:8bd9d2fa6f116c91",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:8bd9d2fa6f116c91",
        "name": "76 Via Capoliveri",
        "housenumber": "76",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.8,
        "distance": 0.072,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "76 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527874,
          42.006776
        ]
      },
      "properties": {
        "id": "it/countrywide:a54719068e7da6d7",
        "gid": "openaddresses:address:it/countrywide:a54719068e7da6d7",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:a54719068e7da6d7",
        "name": "87 Via Capoliveri",
        "housenumber": "87",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.8,
        "distance": 0.073,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "87 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527773,
          42.006663
        ]
      },
      "properties": {
        "id": "it/countrywide:4458d5cbb4d5e017",
        "gid": "openaddresses:address:it/countrywide:4458d5cbb4d5e017",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:4458d5cbb4d5e017",
        "name": "89 Via Capoliveri",
        "housenumber": "89",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.8,
        "distance": 0.085,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "89 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527626,
          42.006802
        ]
      },
      "properties": {
        "id": "it/countrywide:5065e52ecdabe61e",
        "gid": "openaddresses:address:it/countrywide:5065e52ecdabe61e",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:5065e52ecdabe61e",
        "name": "79 Via Capoliveri",
        "housenumber": "79",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.8,
        "distance": 0.092,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "79 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527672,
          42.006551
        ]
      },
      "properties": {
        "id": "it/countrywide:0db3b44d8df5857f",
        "gid": "openaddresses:address:it/countrywide:0db3b44d8df5857f",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:0db3b44d8df5857f",
        "name": "91 Via Capoliveri",
        "housenumber": "91",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.8,
        "distance": 0.098,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "91 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.52757,
          42.006438
        ]
      },
      "properties": {
        "id": "it/countrywide:57d0a98b738ad6c6",
        "gid": "openaddresses:address:it/countrywide:57d0a98b738ad6c6",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:57d0a98b738ad6c6",
        "name": "93 Via Capoliveri",
        "housenumber": "93",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.7,
        "distance": 0.112,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "93 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527379,
          42.006811
        ]
      },
      "properties": {
        "id": "it/countrywide:43f80b49ac6a5499",
        "gid": "openaddresses:address:it/countrywide:43f80b49ac6a5499",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:43f80b49ac6a5499",
        "name": "77 Via Capoliveri",
        "housenumber": "77",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.7,
        "distance": 0.112,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "77 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527469,
          42.006325
        ]
      },
      "properties": {
        "id": "it/countrywide:a2c3a8b6e5e07ade",
        "gid": "openaddresses:address:it/countrywide:a2c3a8b6e5e07ade",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:a2c3a8b6e5e07ade",
        "name": "95 Via Capoliveri",
        "housenumber": "95",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.7,
        "distance": 0.126,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "95 Via Capoliveri, Rome, Italy"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          12.527367,
          42.006213
        ]
      },
      "properties": {
        "id": "it/countrywide:587717735c1323bd",
        "gid": "openaddresses:address:it/countrywide:587717735c1323bd",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "it/countrywide:587717735c1323bd",
        "name": "97 Via Capoliveri",
        "housenumber": "97",
        "street": "Via Capoliveri",
        "postalcode": "00138",
        "confidence": 0.7,
        "distance": 0.14,
        "accuracy": "point",
        "country": "Italy",
        "country_gid": "whosonfirst:country:85633253",
        "country_a": "ITA",
        "macroregion": "Lazio",
        "macroregion_gid": "whosonfirst:macroregion:404227517",
        "region": "Roma",
        "region_gid": "whosonfirst:region:85685461",
        "region_a": "RM",
        "localadmin": "Roma",
        "localadmin_gid": "whosonfirst:localadmin:404461721",
        "locality": "Rome",
        "locality_gid": "whosonfirst:locality:101752607",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "97 Via Capoliveri, Rome, Italy"
      }
    }
  ],
  "bbox": [
    12.527367,
    42.006213,
    12.527874,
    42.006811
  ]
}

---
#### Here's what I was expecting :sparkles:
The point I was searching lies exactly on "diramazione roma nord", nominatim reverse geocoder resolves this correctly: 
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=42.006977&lon=12.528708&zoom=18 
---

**Comment by orangejulius** [comment]
Hi @qmapDL,
Reverse geocoding doesn't currently consider the geometry for streets, only the centroid. We don't have a timeline for fixing this but plan to do it eventually.

This has been reported in https://github.com/pelias/pelias/issues/679 previously, so to keep our issue tracker clean I'm going to close this issue. Thanks for reporting it!
