### ISSUE TITLE
Minimum database size

### ISSUE THREAD

**Issue by avently** [pelias/pelias#76]
Hello!
I found Pelias is very interesting project. I'm just completed install instructions and saw the data size... It's not good for my purpose. Can you give me advice?

I want to use Pelias as better approach than Nominatim. 
I'm only interesting in a few number of fields: city/town, region, country, osm_id, osm_type=Node, class=place, lat&long and bounding box (I want reverse geocoding working too). Two or three languages and worldwide map with town population > 15000. 

That's all I need. Can I use Pelias for this purpose? And how to remove all unused data from .pbm file? And what data I should remove? I don't know how to setup Pelias...

Please, help

**Comment by dianashk** [comment]
Hi @avently! Welcome to pelias! We will be happy to help you set things up locally. 

Until your setup is successfully running locally, is there a reason you can't use our API at pelias.mapzen.com? It would be a great way to give pelias a try without committing to running a full instance on your own. 

What kind of request rates would you be looking at? just so we can be sure our instance will be able to support your volume.

**Comment by avently** [comment]
Hey, Diana! Are you understand russian? My english is bad:)

**Comment by dianashk** [comment]
I do! :) You can email me directly at diana@mapzen.com or just use Russian here, and I'll do my best to answer your questions.
