### ISSUE TITLE
Small doc store size after importing data

### ISSUE THREAD

**Issue by joseflorido** [pelias/pelias#762]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
I followed your installation from scratch guide and ran all the importers. After 3 days importing, I compared the data Dashing shows for my install to the one you guys have a Geocode.Earth (https://pelias-dashboard.geocode.earth/pelias) and looks like I got similar number of counts but my Doc store size is way smaller. I just wonder why can that be and if that can affect negatively to the geocoding.s

Thanks!

![image](https://user-images.githubusercontent.com/140987/50072028-a65fff80-0188-11e9-932a-e9f393f38b86.png)

**Comment by orangejulius** [comment]
Hey @joseflorido,
I'm not sure offhand what would cause this, but my suspicion is it's related to [admin lookup data not being present](https://github.com/pelias/wof-admin-lookup). 

One thing to try would be to run the [acceptance-tests](https://github.com/pelias/acceptance-tests/) and see what fails. If you see lots of records being returned correctly, but they don't have the correct neighbourhood, city, state, country, etc, then it's almost certainly admin lookup. If not, hopefully the acceptance-tests will provide another clue.

Let us know what you find out.

**Comment by orangejulius** [comment]
Hi @joseflorido,
Did re-downloading WOF data again help with this? As WOF data grows larger, we've been noticing more and more trouble getting everything to work properly, and we'd like to see what we can do to make things better.

**Comment by orangejulius** [comment]
This definitely looks to have been a case of missing admin data for admin lookup.

There have been some instability in WOF data as they go through some [growing pains](https://whosonfirst.org/blog/2019/05/09/changes/), so if anyone else is seeing things like this, the first thing to try is setting `"sqlite": true` in your [whosonfirst config](https://github.com/pelias/whosonfirst#configuration).
