### ISSUE TITLE
[Autocomplete] No Results for Foreign Language Queries

### ISSUE THREAD

**Issue by JulianSSS** [pelias/pelias#767]
Hey team and a happy new year! 

I was using your awesome geocoding engine when I noticed a bug.
Let me tell you more about it.

---
#### Here's what I did

I want to get Cairo, Egypt autocompleted as by
English writing
http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Cair
vs German Writing
http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Kair

---
#### Here's what I got :scream_cat:

For the English search term I get these:
1) **Cairo, Ägypten**
 2) **Kairo, Ägypten**
 3) New Cairo, Ägypten
 4) ...
For the German search term I get these:
 1) Gouvernorat de Kairouan, Tunesien
 2) Kairouan, Tunesien
 3) Kairuku-Hiri, Papua-Neuguinea
 4) ... (no Cairo following)

---

#### Here's what I was expecting :sparkles:

Autocomplete should search in its sources for names, venues, etc. in all language-specific names or at least, the input language should be specifiable as the output language is already.
When I autocomplete "Cair", I want to get the entity of Cairo and when I autocomplete "Kair", I want to get the entity of Cairo as result as well.

---
#### Here's what I think could be improved :trophy:

For any string given, pelias autocomplete should search for this string in all specified targets' names (e.g. venues, streets, cities, countries) in all their localized names (Al-Qahirah,Kaïro,Cairo,ካይሮ,O Caire,القاهرة,Cairo,Kairo,Cairo,El Cairo,カイロ,...).

**Comment by orangejulius** [comment]
Hello fellow Julian,
We added support for _searching_ in multiple languages to our search endpoint a while back, but never got around to adding it to autocomplete. It's a much more challenging task for autocomplete, but very much something we want to tackle.

Most of the work lies around the massive number of possible results that come from partial matches across all languages. It's quite hard to avoid seemingly irrelevant results swamp the obvious match. That said, we haven't really given this a shot in a couple years, and Pelias overall has advanced quite a bit and we have much better tools for a lot of those problems.

If you (or someone else), is interested in taking a look at prototyping some of the initial work for this, let me know and I can write up some pointers on what that might entail.

**Comment by missinglink** [comment]
A test-case mentioning this issue changed from fail->pass due to https://github.com/pelias/api/pull/1370
The following query now returns `de:Kairo` in position 1

https://pelias.github.io/compare/#/v1/autocomplete?lang=de&text=Kair
