### ISSUE TITLE
Add acceptance tests for name field token analysis

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#77]
When searching for a venue named `'Good Friends'` the `/search` endpoint currently fails to find this record [1] when entering the term `'friend'` [2] but the same record is successfully returned for the term `'friends'` [3].

This is probably an issue to do with how the `.name` field is being analysed and can probably be fixed easily with a schema update.

related: https://github.com/pelias/schema/issues/49

[1] http://pelias.mapzen.com/doc?id=osmnode:2352412653
[2] http://pelias.mapzen.com/search?input=friend&lat=52.50712&lon=13.32164
[3] http://pelias.mapzen.com/search?input=friends&lat=52.50712&lon=13.32164

**Comment by hkrishna** [comment]
Thank you for opening this issue. Your issue description nicely summarizes how and why we need to analyze (including at least a token filter that does stemming) our ```.name``` field.

**Comment by missinglink** [comment]
resolved by ngram release

**Comment by dianashk** [comment]
Should be added to acceptance tests as well.

**Comment by riordan** [comment]
Test wouldn't be specific enough for this query. Plus... you know... ¯\_(ツ)_/¯ 

hi @hkrishna!
