### ISSUE TITLE
Your homepage shows good statue of liberty results, live product does not

### ISSUE THREAD

**Issue by wysisoft** [pelias/pelias#772]
https://pelias.io/
shows a search for the statue of liberty and the first result is in manhattan and the second is at least in the US.
https://pelias.github.io/compare/#/v1/search%3Ftext=statue%20of%20liberty
shows the same behavior as my instance, where the first results are bad results. Any clues on how to get better behavior?

**Comment by orangejulius** [comment]
Hi @wysisoft,
You can achieve the same result by using the `focus.point` parameter to [specify a point around which results should be prioritized](https://github.com/pelias/documentation/blob/master/search.md#prioritize-around-a-point).

Both a [search query with that parameter](http://pelias.github.io/compare/#/v1/search%3Ffocus.point.lat=40.68&focus.point.lon=-74.04&text=statue%20of%20liberty) and a web map that uses the map center as a `focus.point`, like the [geocode.earth autocomplete demo app](https://geocodeearth.github.io/autocomplete-demo/) will return the right results.

![screenshot_2019-01-26_12-54-47](https://user-images.githubusercontent.com/111716/51792682-97964080-2169-11e9-9d24-325d79a805cd.png)
