### ISSUE TITLE
Venue Autocomplete Search cannot be combined with a location

### ISSUE THREAD

**Issue by heebj** [pelias/pelias#779]
Hey team! 

Currently it does not seem possible to put a venue and a location in the query text of the Autocomplete API. For example to search for Starbucks in Berlin I cannot intuitively type "Starbucks Berlin" as with Google Maps. This makes it unintuitive to use the Autocomplete API to search for venues of companies with a lot of stores. I know I can set a local focus but it is not quite the same...

https://api.geocode.earth/v1/autocomplete?text=Starbucks%20Berlin

Is this a feature which is on your roadmap?

Thanks a lot for your great work!
Julian

**Comment by NickStallman** [comment]
Try "school, <locality>" as I know this particular example does indeed work.
Although I just tried in Australia and indeed Starbucks wasn't working.

**Comment by heebj** [comment]
At first I also had the feeling that it works when I put a comma between the venue and location because it leads to different results but it seems more to act like an OR operator.
I also think it would be rather unintuitive to use a comma for searching a venue within a location because people are not used to it from similar search engines...

**Comment by orangejulius** [comment]
The autocomplete endpoint currently requires a comma to be a separator between addresses or venue names and administrative areas like a city.

So a query like the following will work:

[/v1/autocomplete?text=starbucks, berlin](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=starbucks,%20berlin)

We're looking at removing this restriction in the future.

It's also worth noting that the `/v1/search` endpoint is not as dependent on commas, but it doesn't handle partial input very well, so it can't be used to replace autocomplete.

**Comment by heebj** [comment]
It would be great if this restriction could be removed in the future :-)

**Comment by orangejulius** [comment]
This is (finally) fixed as of https://github.com/pelias/api/pull/1287 and the new Pelias parser!! :tada: 

[/v1/autocomplete?text=Starbucks Berlin](https://pelias.github.io/compare/#/v1/autocomplete%3Ftext=Starbucks%2520Berlin) now returns a list of Starbucks in Berlin.
![Screenshot_2019-10-03_15-48-34](https://user-images.githubusercontent.com/111716/66159144-61ad3400-e5f5-11e9-843b-7caa9037e928.png)

**Comment by heebj** [comment]
@orangejulius that's fantastic! Thanks a lot! :-)
