### ISSUE TITLE
How to open an account and get an api key?

### ISSUE THREAD

**Issue by dawnbuie** [pelias/pelias#780]
Hi 

I think since mapzen closed down and then was resurrected by linux foundation some important documentation was lost. I can't figure out how to get an account and api key - at least for Pelias search -

I really have looked everywhere. 

Thank you!

**Comment by orangejulius** [comment]
Hi @dawnbuie,
Pelias the open-source project itself doesn't have accounts or API keys. Mapzen ran a hosted instance of Pelias called Mapzen Search, which was shut down with the company. That's not coming back with the Linux Foundation move.

If you're looking to use Pelias, you can [set it up yourself](https://github.com/pelias/documentation/blob/master/getting_started_install.md), which is pretty quick for small geographic areas like a city. Alternatively, after Mapzen shut down, @missinglink and I set up a consultancy and hosted geocoding services offering around Pelias at [geocode.earth](https://geocode.earth). If you're looking for geocoding for a business, we might be able to help.

**Comment by LEDfan** [comment]
For me confusion was this page: https://www.mapzen.com/pricing/, I only noticed after reading this issue that the page is the past tense :see_no_evil: . (e.g. `How it worked`).

**Comment by orangejulius** [comment]
Oh that's good feedback @LEDfan, thanks. We finally do have the ability to change the website content for the first time in a few months now that everything has moved under the Linux Foundation.

I think the challenge is to "memorialize" so to speak the actual content from Mapzen the company, while also updating on the current state of things. I'll mention it to the people who manage the website.

**Comment by missinglink** [comment]
I'm closing this issue because it seems to be resolved.

Please head over to [geocode.earth](https://geocode.earth) and request a free trial API key.
