### ISSUE TITLE
[Autocomplete] Can't find exact localities with WOF filter

### ISSUE THREAD

**Issue by Joxit** [pelias/pelias#786]
Hey team :heart: ! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
[/v1/autocomplete?sources=wof&layers=localadmin,locality,region,macroregion,postalcode&text=rome](http://pelias.github.io/compare/#/v1/autocomplete%3Fsources=wof&layers=localadmin,locality,region,macroregion,postalcode&text=rome)

---
#### Here's what I got :scream_cat:
```
 1) Ciudad Nicolás Romero, Mexique
 2) Romeoville, IL, USA
 3) Rome, GA, USA
 4) Rome, NY, USA
 5) Römerberg, Allemagne
 6) Römerberg, Allemagne
 7) Rome Township, OH, USA
 8) Arquitecto Tomás Romero Pereira, Paraguay
 9) Romentino, Italie
10) Römerstein, Allemagne
```

---
#### Here's what I was expecting :sparkles:
Rome is a exact match for Rome, Italy and should be found. (Just like search did)
[/v1/search?sources=wof&layers=localadmin,locality,region,macroregion,postalcode&text=rome](http://pelias.github.io/compare/#/v1/search%3Fsources=wof&layers=localadmin,locality,region,macroregion,postalcode&text=rome)

---
#### Here's what I think could be improved :trophy:

I think, when wof only is selected, we should use placeholder, just like search do or improve ES requests for admin only matching.

**Comment by missinglink** [comment]
hmm.. yea if you exclude the filter you get the `geonames` result first.

I think the issue here is that the default name is `Roma` (ending with an 'a') and not `Rome` (ending with an 'e').
I've actually addressed this issue recently in https://github.com/pelias/whosonfirst/pull/423

The problem is that the data is wrong, the `eng_x_preferred` value should end with 'e' and not 'a'.

**Comment by missinglink** [comment]
Actually, we should be pulling in the `eng_x_variant` token for `Rome`.
Are you running a version which includes the PR above?

**Comment by missinglink** [comment]
related: https://github.com/whosonfirst-data/whosonfirst-data/pull/1554

**Comment by missinglink** [comment]
I tried some other major cities like Berlin, Paris, New York and they don't seem to suffer the same issue

**Comment by Joxit** [comment]
Yes, I saw the geonames results, but this was a bit weird for WOF.
Oh, maybe it's related to #767 because this was a french search (from one of my customers). So this may happen again on many of his requests... :confused: 
BTW, the `name:fra_x_preferred` is completly wrong, it should be Rome.

I did not use this PR, my latest build was on pelias-whosonfirst v2.30.2 with sqlite-supports.
I would probably do another build on my return from vacation.

**Comment by Joxit** [comment]
I tried `Londre` for `London` and it does not work, so this is a lack of multiple languages supports :disappointed:

**Comment by missinglink** [comment]
I see, honestly, I would like to make some changes to how the `name.*` fields are being queried in elasticsearch at the moment.
We have all the tokens indexed in diffeerent languages but we don't use them, which is a real pity.

There are also some changes going on over at WOF to deprecate `wof:name` in favour of `label:*` which we should support (gives per-lanaguage labels).

Thanks for bringing this up, I think the best thing to do here is refactor our language support to be less english-centic.

It would also be nice if abbreviations were handled better such as `?text=nyc`

**Comment by Joxit** [comment]
I see...

That means `label:*` will give us the full label of the locality? For exemple `Paris, France` instead of `Paris` with `wof:name`? That will be a big change!

Yes. Could we use the header `Accept-Lang` or query parameter `lang` in order to be more accurate while we search on ES? (in the future ofc) or this is useless when all is indexed? 

Abbreviations should be also good to have :+1:

**Comment by orangejulius** [comment]
Looks like https://github.com/pelias/whosonfirst/pull/423 fixed this!
<img width="809" alt="Screen Shot 2019-05-13 at 7 51 56 AM" src="https://user-images.githubusercontent.com/111716/57619488-08fcd200-7554-11e9-80d9-0cbcae08fa9a.png">
