### ISSUE TITLE
url not working for demo geocoding? 

### ISSUE THREAD

**Issue by rc5w** [pelias/pelias#794]
I'm trying to evaluate whether I want to use your product, but the geocoding link doesn't work: 
https://www.mapzen.com/products/search/geocoding/

The map doesn't load. Can you fix?

**Comment by orangejulius** [comment]
Hi @rc5w,
Mapzen is a company that shut down at the end of 2017. If you're looking for hosted geocoding, try out https://geocode.earth/. It's run by the same team (full disclosure, myself included!).

Let me know if you have any questions.
