### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by sophia-xll** [pelias/pelias#797]
Hello, everyone.
    I have extract all geojson in   `whosonfirst-data-latest.db` to disk,and use `py-mapzen-whosonfirst-utils` tool to write meta csv files. when import wof to elasticsearch:

`sudo pelias import wof`
    
Error occurs:
```
	info: [whosonfirst] Loading wof-locality-latest.csv records from /data/whosonfirst/meta
	……
	info: [dbclient-whosonfirst]  paused=false, transient=1, current_length=0, indexed=3168500, batch_ok=6337, batch_retries=0, failed_records=0, ocean=7, marinearea=305, continent=8, empire=21, country=212, dependency=77, disputed=190, macroregion=94, region=4258, persec=900, locality=2970168, localadmin=150614, macrocounty=958, county=41573, borough=15
	info: [dbclient-whosonfirst]  paused=false, transient=0, current_length=410, indexed=3177000, batch_ok=6354, batch_retries=0, failed_records=0, ocean=7, marinearea=305, continent=8, empire=21, country=212, dependency=77, disputed=190, macroregion=94, region=4258, persec=850, locality=2978668, localadmin=150614, macrocounty=958, county=41573, borough=15
	info: [dbclient-whosonfirst]  paused=false, transient=1, current_length=247, indexed=3184500, batch_ok=6369, batch_retries=0, failed_records=0, ocean=7, marinearea=305, continent=8, empire=21, country=212, dependency=77, disputed=190, macroregion=94, region=4258, persec=750, locality=2986168, localadmin=150614, macrocounty=958, county=41573, borough=15

	<--- Last few GCs --->

	[1:0x41d18b0]  1559134 ms: Scavenge 1348.3 (1420.3) -> 1347.7 (1420.3) MB, 3.0 / 0.0 ms  (average mu = 0.363, current mu = 0.369) allocation failure 
	[1:0x41d18b0]  1559143 ms: Scavenge 1348.5 (1420.3) -> 1347.9 (1420.3) MB, 2.2 / 0.0 ms  (average mu = 0.363, current mu = 0.369) allocation failure 
	[1:0x41d18b0]  1559150 ms: Scavenge 1348.6 (1420.3) -> 1348.2 (1420.8) MB, 2.8 / 0.0 ms  (average mu = 0.363, current mu = 0.369) allocation failure 


	<--- JS stacktrace --->

	==== JS stack trace =========================================

	    0: ExitFrame [pc: 0x4611ee5be1d]
	    1: StubFrame [pc: 0x4611ee5d3a6]
	Security context: 0x08945b91e6e1 <JSObject>
	    2: /* anonymous */ [0x256949414349] [/code/pelias/whosonfirst/node_modules/csv-stream/lib/parser.js:~49] [pc=0x4611f25017a](this=0x3e7d33e85fd9 <Parser map = 0x251ed9d9db09>,s=0x2da9409349a1 <Very long string[65536]>)
	    3: ondata [0x3e7d33e86c99] [_stream_readable.js:~664] [pc=0x4611f259356](this=0x3e7d33e86ac1 <Read...

	FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
	 1: 0x8db900 node::Abort() [node]
	 2: 0x8db94c  [node]
	 3: 0xad6c1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
	 4: 0xad6e54 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
	 5: 0xec44e2  [node]
	 6: 0xec45e8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
	 7: 0xed06c2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
	 8: 0xed0ff4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
	 9: 0xed3c61 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
	10: 0xe9d0e4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
	11: 0x113c88e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
	12: 0x4611ee5be1d 
```

[Similar problem from web](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory). How to solve this problem with `sudo pelias import wof` command ,Or how which code needs to rewrite?

**Comment by orangejulius** [comment]
Hi @sophia-xll,
@nilsnode just noticed the same thing over in our Gitter channel. I suspect the latest WOF data has caused it to grow just outside what will fit in memory.

Every importer has a `bin/start` file (such as this one for [OSM](https://github.com/pelias/openstreetmap/blob/master/bin/start#L3)) which includes the memory limit setting. Try bumping that up a bit, perhaps to 6000, and building a new Docker image. I suspect things will work then.

**Comment by sophia-xll** [comment]
Thanks for your quick reply @orangejulius，
It works well now.

**Comment by orangejulius** [comment]
Hi @sophia-xll,
Since this issue has been confirmed and the fix seems to work, we will need to update the max heap size across all our importers.

If you or someone else is interested in submitting PRs to do so, it would be a big help to us, even though the PR should be small and simple :) I'm reopening this issue to keep track of that task.

Thanks!

**Comment by orangejulius** [comment]
Okay, we've now put in PRs to all the importers to increase the memory limit, so we are good for now. Eventually, we plan to re-architect how admin lookup and the PIP service work, so perhaps we won't have to keep bumping this limit up every few years :)

**Comment by orangejulius** [comment]
The latest WOF `sqlite` files contain a _lot_ more data, and in my testing the required memory limit is now 8000MB, up from 6000 a few months ago, and 4000 before that.

In Node.js 12, the Node.js memory limit is configured automatically, so fortunately we may not need to keep doing this forever.

If anyone else sees any issues with out of memory errors, let us know.

**Comment by slvlirnoff** [comment]
@orangejulius we've just experienced this on import openaddresses on one of our server. we will quickly restart the import to see if it was just unfortunate (it was during parsing admin-us with sqlite: true).
If it happen again maybe this value should be bumped again.
