### ISSUE TITLE
Support for Node.js 12

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#800]
Node.js 12 was [released recently](https://medium.com/@nodejs/introducing-node-js-12-76c41a1b3f3f) and comes with the usual performance increases, new features, and breaking changes.

We should start adding CI tests for Node.js 12 and eventually add formal support to it, as we have done in the past, for example for [Node.js 10](https://github.com/pelias/pelias/issues/723)

**Comment by orangejulius** [comment]
If anyone has experiences running Pelias on Node.js 12, we'd love to hear about it.

**Comment by orangejulius** [comment]
I just attempted to run the `pelias/whosonfirst` importer with Node.js 12.

On my machine at least, it looks like the [integer](https://github.com/JoshuaWise/integer) module, which is used by our sqlite library, doesn't compile against Node.js 12 yet. This means none of our importers or WOF related code will work with Node.js 12. That's nearly all of Pelias, so we are probably blocked on that first.

**Comment by orangejulius** [comment]
Okay, it now appears that since version 5, `better-sqlite` uses a version of `integer` that supports Node.js 12. As of https://github.com/pelias/whosonfirst/pull/408 we are now using this version, and Node.js 12 appears to work great for the whosonfirst importer.

**Comment by orangejulius** [comment]
I did a little more testing on Node.js 12, and after one [fix for pbf2json](https://github.com/pelias/pbf2json/pull/83), it now appears there's only one issue blocking generally rolling out Node.js 12:

The interpolation engine shows different test results on Node.js 12 ([CI output here](https://travis-ci.org/pelias/interpolation/builds/575303990). @missinglink any idea what that might be caused by?

**Comment by missinglink** [comment]
Maybe partially because of https://twitter.com/mathias/status/1036626116654637057?
But I'm not sure that would account for the different row counts...

**Comment by orangejulius** [comment]
There's one more blocker for Node.js 12 support: we need to start using the libpostal service from within the interpolation service, as started in https://github.com/pelias/interpolation/pull/146.

The [node-postal](https://github.com/openvenues/node-postal) library currently used by the interpolation service is defunct, and does not support Node.js 12+.

**Comment by orangejulius** [comment]
I've added PRs to add Node.js to all the support modules used in Pelias. Since the importers and services have already been testing against Node.js 12 for some time, we didn't expect any issues, but it's good to have full coverage. I'll start merging those PRs soon.

Since there's so many of them and they will all trigger other builds for modules that depend on them, I'll merge them slowly so that other CI jobs don't get stuck behind a huge queue.

**Comment by orangejulius** [comment]
Node.js support has fully landed in the Interpolation service thanks to https://github.com/pelias/docker-libpostal_baseimage/pull/4 and https://github.com/pelias/interpolation/pull/245.

As far as I know, there's nothing left to do here, so this task is 100% complete! :tada: 

To be completely clear to anyone reading this issue, we recommend Node.js 12 as the preferred Node.js version for Pelias. That will only change once Node.js 14 comes out in [~April 2020](https://github.com/nodejs/Release#release-schedule), and we have merged full support for it to the project.

We always list the recommended version of all Pelias dependencies such as Node.js or Elasticsearch in our documentation: https://github.com/pelias/documentation/blob/master/requirements.md
