### ISSUE TITLE
# character causing url parse problems

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/pelias#805]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
It looks like the '#' character in a search will de-activate boundary country (and possibly other params) 
[search in Great Britain](https://pelias.github.io/compare/#/v1/search%3Ftext=Maidenhair%20Drive%204,%20%23A,%20Warwickshire,%20Rugby,%20CV230SE&boundary.country=GBR)

---
#### Here's what I got :scream_cat:
The boundary country is ignored - 
     1) Rugby District, England, United Kingdom
     2) Rugby, England, United Kingdom
     3) Rugby, England, United Kingdom
     4) Rugby, VA, USA
     5) Rugby, TN, USA
     6) Rugby, VA, USA
     7) Rugby, NC, USA
     8) Rugby, ON, Canada
     9) Rugby, Barbados
    10) Rugby, TN, USA

---
#### Here's what I was expecting :sparkles:
results restricted to GBR. Same for search 
[ymca #3 in gbr](https://pelias.github.io/compare/#/v1/search%3Ftext=YMCA%20%233&boundary.country=GBR)
as opposed to 
[ymca 3 in gbr](https://pelias.github.io/compare/#/v1/search%3Ftext=ymca%203&boundary.country=GBR)

---
#### Here's what I think could be improved :trophy:
figure out what's getting borked by the # char if that's indeed the problem

**Comment by missinglink** [comment]
This is an encoding bug in the compare app which I haven't got around to fixing yet.
For now, I would suggest always specifying the `text=` param as the final argument.

PR to fix this would be welcome!
