### ISSUE TITLE
Feature request: Add bounding box to suggest endpoint

### ISSUE THREAD

**Issue by mattkrick** [pelias/pelias#81]
For my app, I'd like to autocomplete from a list of schools in a given town. If I use the suggest endpoint, I get suggestions from the other side of the country, but if I use the search endpoint with a bbox, it can't predict things mid-word. I think this could be best solved with a bbox on the suggest endpoint.

Currently, I use the suggest endpoint and pull 40 results, then client-side I filter out things that are too far (and things without the word 'school' in it). Although it works, it's not optimal (and I feel bad about hitting the server so much).

**Comment by hkrishna** [comment]
Thank you @mattkrick for the feature request. I have opened an [issue](https://github.com/pelias/api/issues/110) for this. Adding bounding box support to ```/suggest``` endpoint is non trivial and might take us a couple of sprints to get around to implementing it. 

In the meantime, May I suggest you using the ```/suggest/nearby``` endpoint instead? [Here](https://github.com/pelias/api/blob/better-index-page/DOCS.md#suggestnearby) are some details. Basically, it works as autocomplete for places located near a latitude/longitude (this could be the center of your bounding box), this endpoint is the same as /suggest but the results are all from within 50 kilometers of the specified point. Unlike ```/suggest```, ```/suggest/nearby``` does not mix results from different precision levels (500km, 1000km etc from lat/lon) aka results from other side of the country.

```/suggest/nearby``` uses the lat/lon provided and draws a bounding box around it with a rough radius of ```50km``` (There are ways of tweaking this distance as well if need be) and returns suggestions thats present in that bbox. 

Let me know if this helps/ if you have questions

**Comment by mattkrick** [comment]
That is awesome! I had no idea that existed & that fits my case perfectly. Updated the wiki with the new endpoint.

**Comment by hkrishna** [comment]
thank you @mattkrick for updating the API Wiki!
