### ISSUE TITLE
Wrong admin data in CH

### ISSUE THREAD

**Issue by zifeo** [pelias/pelias#811]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---

This is a follow-up issue from https://github.com/whosonfirst-data/whosonfirst-data/issues/1334 which tries to solve incorrect projected geometries in Switzerland WOF data.

To better understand the issue, let's take the example of this wrong projection. Geneva is both a region, a localadmin and a locality, however the locality geometry is mis-projected:
https://spelunker.whosonfirst.org/id/101748445/

On the top left of this geometry, we have Meyrin which is a localadmin and a locality inside the Geneva region:
https://spelunker.whosonfirst.org/id/1126035727/

<img width="506" alt="image" src="https://user-images.githubusercontent.com/9053709/61532319-bcd57e80-aa29-11e9-8af3-e7168f0d2c23.png">

Let's consider 1 address in the area where there is an overlap between Meyrin and Geneva localities (which should not exist if correctly projected) and another in Meyrin without the Geneva overlap. Note that those examples come from the openaddresses CH data (countrywide) which is based on the weekly updated official addresses registry (CH-xxx).

A. CH-1021182: Chemin du Vieux-Bureau 88, 1217 Meyrin (46.22436, 6.071361)
B. CH-1020549: Chemin de la Maille 41, 1217 Meyrin (46.241398, 6.057633)

A leads to:

`curl http://pelias-api/v1/search?text=Chemin du Vieux-Bureau 88`
```json
{
  "geocoding": {
    "version": "0.2",
    "attribution": "Pelias",
    "query": {
      "text": "Chemin du Vieux-Bureau 88",
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": true
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "street": "chemin du vieux-bureau",
        "number": "88"
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1563536960851
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          6.071361,
          46.22436
        ]
      },
      "properties": {
        "id": "ch/geneva:2b43e0c3c6d09414",
        "gid": "openaddresses:address:ch/geneva:2b43e0c3c6d09414",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "ch/geneva:2b43e0c3c6d09414",
        "name": "88 Chemin Du Vieux-Bureau",
        "housenumber": "88",
        "street": "Chemin Du Vieux-Bureau",
        "postalcode": "1217",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "point",
        "country": "Switzerland",
        "country_gid": "whosonfirst:country:85633051",
        "country_a": "CHE",
        "region": "Canton of Geneva",
        "region_gid": "whosonfirst:region:85682291",
        "region_a": "GE",
        "localadmin": "Geneva",
        "localadmin_gid": "whosonfirst:localadmin:404328283",
        "locality": "Geneva",
        "locality_gid": "whosonfirst:locality:101748445",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "88 Chemin Du Vieux-Bureau, Geneva, Switzerland"
      }
    }
  ],
  "bbox": [
    6.071361,
    46.22436,
    6.071361,
    46.22436
  ]
}
```

`curl http://pelias-pip/6.071361/46.22436`
```json
{
  "continent": [
    {
      "id": 102191581,
      "name": "Europe",
      "centroid": {
        "lat": 55.924452,
        "lon": 28.09812
      },
      "bounding_box": "-24.539906,34.815009,69.033946,81.85871"
    }
  ],
  "country": [
    {
      "id": 85633051,
      "name": "Switzerland",
      "abbr": "CHE",
      "centroid": {
        "lat": 46.800148,
        "lon": 8.229121
      },
      "bounding_box": "5.95590226131,45.8179811114,10.4920636865,47.8084532093"
    }
  ],
  "localadmin": [
    {
      "id": 404328283,
      "name": "Gen\u00e8ve",
      "centroid": {
        "lat": 46.207076,
        "lon": 6.143744
      },
      "bounding_box": "6.11023254302,46.1777740781,6.17584546001,46.2318860153"
    }
  ],
  "locality": [
    {
      "id": 101748445,
      "name": "Gen\u00e8ve",
      "centroid": {
        "lat": 46.200302,
        "lon": 6.132705
      },
      "bounding_box": "6.04795946222,46.1583151533,6.226392,46.2414675"
    }
  ],
  "region": [
    {
      "id": 85682291,
      "name": "Gen\u00e8ve",
      "abbr": "GE",
      "centroid": {
        "lat": 46.220475,
        "lon": 6.133002
      },
      "bounding_box": "5.95590226131,46.1285503978,6.31028236874,46.3645785501"
    }
  ]
}
```

B leads to:

`curl http://pelias-api/v1/search?text=Chemin de la Maille 41`
```json
{
  "geocoding": {
    "version": "0.2",
    "attribution": "Pelias",
    "query": {
      "text": "Chemin de la Maille 41",
      "size": 10,
      "private": false,
      "lang": {
        "name": "English",
        "iso6391": "en",
        "iso6393": "eng",
        "defaulted": true
      },
      "querySize": 20,
      "parser": "libpostal",
      "parsed_text": {
        "street": "chemin de la maille",
        "number": "41"
      }
    },
    "engine": {
      "name": "Pelias",
      "author": "Mapzen",
      "version": "1.0"
    },
    "timestamp": 1563536799379
  },
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          6.057633,
          46.241398
        ]
      },
      "properties": {
        "id": "ch/countrywide:87e14cdb038196d9",
        "gid": "openaddresses:address:ch/countrywide:87e14cdb038196d9",
        "layer": "address",
        "source": "openaddresses",
        "source_id": "ch/countrywide:87e14cdb038196d9",
        "name": "41 Chemin De La Maille",
        "housenumber": "41",
        "street": "Chemin De La Maille",
        "postalcode": "1217",
        "confidence": 1,
        "match_type": "exact",
        "accuracy": "point",
        "country": "Switzerland",
        "country_gid": "whosonfirst:country:85633051",
        "country_a": "CHE",
        "region": "Canton of Geneva",
        "region_gid": "whosonfirst:region:85682291",
        "region_a": "GE",
        "localadmin": "Meyrin",
        "localadmin_gid": "whosonfirst:localadmin:404328435",
        "continent": "Europe",
        "continent_gid": "whosonfirst:continent:102191581",
        "label": "41 Chemin De La Maille, Meyrin, Switzerland"
      }
    }
  ],
  "bbox": [
    6.057633,
    46.241398,
    6.057633,
    46.241398
  ]
}
```

`curl http://pelias-pip/6.057633/46.241398`
```json
{
  "continent": [
    {
      "id": 102191581,
      "name": "Europe",
      "centroid": {
        "lat": 55.924452,
        "lon": 28.09812
      },
      "bounding_box": "-24.539906,34.815009,69.033946,81.85871"
    }
  ],
  "country": [
    {
      "id": 85633051,
      "name": "Switzerland",
      "abbr": "CHE",
      "centroid": {
        "lat": 46.800148,
        "lon": 8.229121
      },
      "bounding_box": "5.95590226131,45.8179811114,10.4920636865,47.8084532093"
    }
  ],
  "localadmin": [
    {
      "id": 404328435,
      "name": "Meyrin",
      "centroid": {
        "lat": 46.232229,
        "lon": 6.079097
      },
      "bounding_box": "6.04611135569,46.2171751198,6.11190930357,46.2471256965"
    }
  ],
  "region": [
    {
      "id": 85682291,
      "name": "Gen\u00e8ve",
      "abbr": "GE",
      "centroid": {
        "lat": 46.220475,
        "lon": 6.133002
      },
      "bounding_box": "5.95590226131,46.1285503978,6.31028236874,46.3645785501"
    }
  ]
}
```

While both addresses should have 1217 Meyrin as localadmin, the wrongly projected geometry seems to have updated the original import. The geometry should be soon fixed: https://github.com/whosonfirst-data/whosonfirst-data-admin-ch/pull/4.

Thanks a lot for this great piece of software :trophy:!

**Comment by zifeo** [comment]
Note: A has the id `ch/geneva:2b43e0c3c6d09414` but the same record exists also at countrywide level `ch/countrywide:44241684d7c6e543`. The ES records are already incorrect so I suspect that the WOF lookup is partially in cause when importing new data.

**Comment by zifeo** [comment]
@orangejulius did you get a chance to look at this?

**Comment by orangejulius** [comment]
Hi @zifeo,
Looks like this is indeed a case of incorrect data in WOF being used.

Would it also be correct to say that we should update our labels in Switzerland to include the postal code?

Would

`41 Chemin De La Maille, 1217 Meyrin, Switzerland`

be more correct than the current label value of 

`41 Chemin De La Maille, Meyrin, Switzerland`?

**Comment by zifeo** [comment]
@orangejulius yes, definitely! Would that fix be quicker than correcting the wrong projection?

**Comment by missinglink** [comment]
Hi @zifeo, I'm the one who opened https://github.com/whosonfirst-data/whosonfirst-data/issues/1334 back in October, I think it's best if we let the WOF team handle fixing the data, last time I spoke with Stephen he was getting close.

I read your issue description a couple of times now but I'm not quite understanding what you're asking? Is it just to make us aware of the geometry issues in Switzerland or are you suggesting that we re-protect the erroneous geometries and path WOF for Pelias?

**Comment by zifeo** [comment]
@missinglink @orangejulius ask me to open an issue here as he was not sure the WOF hierarchy was the cause of those issues. See this comment: https://github.com/whosonfirst-data/whosonfirst-data/issues/1334#issuecomment-513176846.

**Comment by zifeo** [comment]
It seems that now that we have correct hierarchy, the old hierarchy is still kept and used by Pelias.

**Comment by SToto98** [comment]
For reference the comment of @stepps00 here: https://github.com/whosonfirst-data/whosonfirst-data/issues/1334#issuecomment-521318828

**Comment by zifeo** [comment]
Seems all good now 🎉
