### ISSUE TITLE
Issue with Pelias Compose in Base Installation

### ISSUE THREAD

**Issue by emags15** [pelias/pelias#812]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
I basically followed the instructions on the pelias tutorial for the portland metro case on a Mac with High Sierra 10.13.4. 

---
#### Here's what I got :scream_cat:
< It is stopped at 26.6%
![IMG_0893](https://user-images.githubusercontent.com/52842276/61671508-ce728c80-ac9c-11e9-8011-0b5a743b0233.jpg)
>

---
#### Here's what I was expecting :sparkles:
I was expecting pelias to pull libpostal and interpolation without stopping at 26.6%. Tried deleting and reinstalling both docker and pelias but got the same result

---

**Comment by missinglink** [comment]
Hi @ghost, did you get it fixed in the end!
Any tips for others who might be suffering the same issue?

That part of the code is actually `docker-compose`, it could be a network issue or lack of disk space.

Restarting the docker service from the menubar icon should hopefully fix it.
