### ISSUE TITLE
Bad responses  for CA addresses

### ISSUE THREAD

**Issue by umar18** [pelias/pelias#813]
Hey team! 

I was using your awesome geocoding engine when I noticed something interesting.
Let me tell you more about it.

---
#### Here's what I did :innocent:
I have been using Portland metro project came up with pelias geocoder. I have imported Maryland and California datasets from open street maps, Open addresses and Who's On first

---
#### Here's what I got :scream_cat:
For Maryland I've been getting pretty much good results but for California state the confidence is very low.

Here is my request example
v1/search?text=299 North Hill Street Los Angeles, CA, USA

And the response
{
    "geocoding": {
        "version": "0.2",
        "attribution": "http://192.168.10.86:5002/attribution",
        "query": {
            "text": "299-269 N Hill St Los Angeles, CA, USA",
            "size": 10,
            "private": false,
            "focus.point.lat": 45.52,
            "focus.point.lon": -122.67,
            "lang": {
                "name": "English",
                "iso6391": "en",
                "iso6393": "eng",
                "defaulted": true
            },
            "querySize": 20,
            "parser": "libpostal",
            "parsed_text": {
                "number": "299-269",
                "street": "n hill st",
                "city": "los angeles",
                "state": "ca",
                "country": "usa"
            }
        },
        "engine": {
            "name": "Pelias",
            "author": "Mapzen",
            "version": "1.0"
        },
        "timestamp": 1564067647471
    },
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -96.999668,
                    39.715956
                ]
            },
            "properties": {
                "id": "85633793",
                "gid": "whosonfirst:country:85633793",
                "layer": "country",
                "source": "whosonfirst",
                "source_id": "85633793",
                "name": "United States",
                "confidence": 0.1,
                "match_type": "fallback",
                "distance": 2189.052,
                "accuracy": "centroid",
                "country": "United States",
                "country_gid": "whosonfirst:country:85633793",
                "country_a": "USA",
                "continent": "North America",
                "continent_gid": "whosonfirst:continent:102191575",
                "label": "United States"
            },
            "bbox": [
                -124.848973,
                24.396308,
                -66.885444,
                49.384358
            ]
        }
    ],
    "bbox": [
        -124.848973,
        24.396308,
        -66.885444,
        49.384358
    ]
}

---
#### Here's what I was expecting :sparkles:

---

**Comment by missinglink** [comment]
I suspect there is a configuration issue, can you please submit pull-requests to add the configs you have for Maryland and California to the `pelias/docker` repo so we can review them?

Looking at our production environment it seems to be functioning as expected?

https://pelias.github.io/compare/#/v1/search%3Ftext=299%20North%20Hill%20Street%20Los%20Angeles,%20CA,%20USA

**Comment by missinglink** [comment]
Or maybe the request example you posted above is incorrect? It doesn't seem to correspond to the `query.text` in the response header?

**Comment by umar18** [comment]
OK,
So here  what i did, i started from the scratch, deployed Portland metro projects and it worked like a charm. Now i want to add the following states:
Maryland
California
Washington
Connecticut
Virginia
Indiana
Texas
Wisconsin
Tennessee
Colorado

Question 1; What should i add in the json file for openstreets map, open addresses and wof ? 
Question 2; Should i need to execute all commands again after adding the states in json file ?

PS: Sorry if the above questions sounds stupid as i have 0 knowledge of Linux.
