### ISSUE TITLE
Backup file and use another server

### ISSUE THREAD

**Issue by toton6868** [pelias/pelias#816]
I have two instances, one is development and another is production. I am doing the import, indexing, etc time-consuming task in Development server. I do not want to use those time-consuming task in the Production  Server. Is there any way to Backup indexed data and paste it to the production server so that that development task does not hamper my production server. How can I do that?

**Comment by missinglink** [comment]
If you are using the docker setup then you should be able to stop the server and tar/zip your `DATA_DIR`.

**Comment by missinglink** [comment]
```bash
➜  portland-metro git:(master) ✗ cat .env
COMPOSE_PROJECT_NAME=pelias
DATA_DIR=/data/pelias/docker/projects/portland-metro
DOCKER_USER=1000

➜  portland-metro git:(master) ✗ ls -lah /data/pelias/docker/projects/portland-metro
total 0
drwxr-xr-x  13 peter  staff   416B Mar 27 14:54 .
drwxr-xr-x   4 peter  staff   128B Mar 14 09:53 ..
drwxr-xr-x   2 peter  staff    64B Feb  8  2019 blacklist
drwxr-xr-x   3 peter  staff    96B Feb  8  2019 csv
drwxr-xr-x   3 peter  staff    96B Mar 27 14:54 elasticsearch
drwxr-xr-x  20 peter  staff   640B Feb  8  2019 interpolation
drwxr-xr-x   4 peter  staff   128B Feb  8  2019 openaddresses
drwxr-xr-x   3 peter  staff    96B Feb  8  2019 openstreetmap
drwxr-xr-x   4 peter  staff   128B Feb  8  2019 placeholder
drwxr-xr-x   3 peter  staff    96B Feb  8  2019 polylines
drwxr-xr-x   4 peter  staff   128B Feb  8  2019 tiger
drwxr-xr-x  16 peter  staff   512B Feb  8  2019 transit
drwxr-xr-x   5 peter  staff   160B Feb  8  2019 whosonfirst
```

**Comment by missinglink** [comment]
If you're only concerned with the elasticsearch data then you can use the [snapshot/restore](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-snapshots.html) functionality.

We use this for our production builds in combination with the [repository-s3](https://www.elastic.co/guide/en/elasticsearch/plugins/5.6/repository-s3.html) (which is included in our docker images).

**Comment by toton6868** [comment]
Sorry for reopening. I have installed Pelias from scratch both in Development and Production Server. In Production server I am using managed elasticSearch of AWS. In this case, the `snapshot/restore` function will work?
