### ISSUE TITLE
Character encoding issues

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#82]
Today I noticed a character encoding issue I'd not see before, it may be a regression or it may have always been there?

eg. https://pelias.mapzen.com/search?bbox=34.88769107831441,33.097686767578125,34.83909744462777,32.932891845703125&input=%C3%8E%C2%96%C3%AF%C2%89%C3%AE%C2%BF%C3%AF%C2%80%C3%AE%C2%B7%C3%AE%C2%B3%C3%AE%C2%AE,+%CE%9B%CE%B5%CE%BC%CE%B5%CF%83%CF%8C%CF%82&lat=34.8634&lon=33.0153&size=10&zoom=14

```javascript
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"id":"82528:locality:cy:cyp:______________","layer":"locality","name":"Îïî¿ïî·î³î®","alpha3":"CYP","admin0":"Cyprus","admin1":"Λεμεσός","text":"Îïî¿ïî·î³î®, Λεμεσός"},"geometry":{"type":"Point","coordinates":[33.015327,34.863453]}},{"type":"Feature","properties":{"id":"63006:locality:cy:cyp:_____________________","layer":"locality","name":"Îî³î¹î¿ï Îî¬î¼î±ï","alpha3":"CYP","admin0":"Cyprus","admin1":"Λεμεσός","text":"Îî³î¹î¿ï Îî¬î¼î±ï, Λεμεσός"},"geometry":{"type":"Point","coordinates":[32.949686,34.851026]}},{"type":"Feature","properties":{"id":"82527:locality:cy:cyp:___________________","layer":"locality","name":"Îî±î»ï Î§ïïî¹ï","alpha3":"CYP","admin0":"Cyprus","admin1":"Λεμεσός","text":"Îî±î»ï Î§ïïî¹ï, Λεμεσός"},"geometry":{"type":"Point","coordinates":[33.031112,34.850528]}},{"type":"Feature","properties":{"id":"82525:locality:cy:cyp:___________________________________","layer":"locality","name":"Îî³î¹î¿ï Îïî½ïïî±î½ïî¯î½î¿ï","alpha3":"CYP","admin0":"Cyprus","admin1":"Λεμεσός","text":"Îî³î¹î¿ï Îïî½ïïî±î½ïî¯î½î¿ï, Λεμεσός"},"geometry":{"type":"Point","coordinates":[33.065426,34.867393]}},{"type":"Feature","properties":{"id":"82524:locality:cy:cyp:_______________________","layer":"locality","name":"Îî³î¹î¿ï Î Î¬ïî»î¿ï","alpha3":"CYP","admin0":"Cyprus","admin1":"Λεμεσός","text":"Îî³î¹î¿ï Î Î¬ïî»î¿ï, Λεμεσός"},"geometry":{"type":"Point","coordinates":[33.046165,34.864181]}}],"bbox":[32.949686,34.850528,33.065426,34.867393],"date":1429535433191}
```

**Comment by missinglink** [comment]
Here's another one I found today:
http://pelias.mapzen.com/doc?id=locality:71125:locality:de:deu:m__nchenbernsdorf

@sevko could you have a look in to this issue when you get some time please?

**Comment by sevko** [comment]
After checking out the vanilla Quattroshapes (from [quattroshapes.com](http://quattroshapes.com), it turns out this data's always been there. I've investigated it some and might have a solution. Migrating this ticket to pelias/quattroshapes-patch#9.

**Comment by missinglink** [comment]
I'm pulling this on-deck as this issue really needs to be addressed for the `v1` milestone cc/ @dianashk 

![encoding](http://peter.johnson.s3.amazonaws.com/char_encoding.png)

**Comment by dianashk** [comment]
:+1:

**Comment by nvkelso** [comment]
This last one about the bad "Zurich" parent of Zurichhorn looks to be a bad character encoding import on the neighborhoods QS file. Assuming you ignore the provided admin1 in the neighborhood file and instead calculate that hitting the QS admin1 file.
