### ISSUE TITLE
WOF importer name.default string or list

### ISSUE THREAD

**Issue by jgmarce** [pelias/pelias#820]
I've noticed that name.default is a list ["name"] in about ~500,000 cases.  It was my expectation that the WOF importer would have imported only a string or the first element of a list (if a list is found) rather than allowing name.default to be cast as type of "list".    Examining some of these records, I observe the first element of the name.default[] is sometimes duplicated in phrase.default[0,1], so I'll assume that the WOF importer is also not expecting a list to be found in the WOF SQLite3 distribution.

Two examples:
pelias-s7a$ wc -l skipped.json
495778 skipped.json
pelias-s7a$ grep "Ashburn" skipped.json | grep Virginia
```
{"name":{"default":**["Ashburn"]**,"ar":"آشبورن","bg":"Ашбърн","fa":"اشبرن، ویرجینیا","ja":"アッシュバーン","ko":"애슈번","ru":"Ашберн","sr":"Ашберн"},"phrase":{"default":["Ashburn","Ashburn"],"ar":"آشبورن","bg":"Ашбърн","fa":"اشبرن، ویرجینیا","ja":"アッシュバーン","ko":"애슈번","ru":"Ашберн","sr":"Ашберн"},"parent":{"country":["United States"],"country_id":["85633793"],"country_a":["USA"],"locality":["Ashburn"],"locality_id":["101729435"],"locality_a":[null],"region":["Virginia"],"region_id":["85688747"],"region_a":["VA"]},"center_point":{"lon":-77.467387,"lat":39.029265},"source":"whosonfirst","layer":"locality","source_id":"101729435","bounding_box":"{\"min_lat\":38.988286,\"max_lat\":39.071635,\"min_lon\":-77.522806,\"max_lon\":-77.43144}","population":43511}
{"name":{"default":**["Ashburn Junction"]**},"phrase":{"default":["Ashburn Junction","Ashburn Junction"]},"parent":{"continent":["North America"],"continent_id":["102191575"],"continent_a":[null],"country":["United States"],"country_id":["85633793"],"country_a":["USA"],"county":["Loudoun County"],"county_id":["102084951"],"county_a":[null],"locality":["Ashburn Junction"],"locality_id":["1125778649"],"locality_a":[null],"region":["Virginia"],"region_id":["85688747"],"region_a":["VA"]},"center_point":{"lon":-77.47971,"lat":39.07094},"source":"whosonfirst","layer":"locality","source_id":"1125778649","bounding_box":"{\"min_lat\":39.07094,\"max_lat\":39.07094,\"min_lon\":-77.47971,\"max_lon\":-77.47971}"}
pelias-s7a$
```

This seems different from #194 although changes in this area would affect both.

-jgmarce

**Comment by jgmarce** [comment]
For anyone that requires a quick fix for their processing:

jq -c '.name.default = .name.default[0] // .name.default | .phrase.default = .phrase.default[0] // .phrase.default' skipped.json > skipped_fixed.json

**Comment by orangejulius** [comment]
Hi @jgmarce,
All Elasticsearch string fields are allowed to be arrays of several strings, and we intentionally use this functionality to build support for alternative names.

The issue with duplicate values is probably not causing too much harm, but I believe it was fixed in https://github.com/pelias/model/pull/118.

You might not have the latest version of pelias/model, so run `rm -rf node_modules; npm install` to fix it.
