### ISSUE TITLE
Elasticsearch 7 Support

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#831]
This issue will track support for Elasticsearch 7 in Pelias.

Most Elasticsearch upgrades require two sets of changes:
- Base compatibility changes, often dropping use of functionality no longer supported by Elasticsearch. These changes are generally required before the new version of Elasticsearch works at all
- Tweaks and changes to ensure that queries return the correct results and with adequate performance. These are usually a bit more subjective and can come after initial support has been completed.

### Pelias Tasks

Here's the list of breaking changes we'll need to adapt to (this list will be updated over time):
- [x] Support running on [Elasticsearch 6](https://github.com/pelias/pelias/issues/719) as a base step
- [x] `[illegal_argument_exception] Token filter [word_delimiter] cannot be used to parse synonyms` when using pelias/schema (possibly related to https://github.com/pelias/schema/issues/381). **solved in https://github.com/pelias/schema/pull/403, another solution proposed in https://github.com/pelias/schema/pull/392**
- [x] Remove use of the `doc` mapping type in [pelias-model](https://github.com/pelias/model/blob/master/Document.js#L146-L149) and [pelias-schema](https://github.com/pelias/schema/blob/master/schema.js#L5-L7)
- [x] Remove [schema configuration to disable the `_all` field](https://github.com/pelias/schema/blob/master/mappings/document.js#L182-L184). The `_all` field is [always disabled in ES6+](https://www.elastic.co/blog/minimize-index-storage-size-elasticsearch-6-0), so this code isn't needed once we are on ES6. It is incompatible with ES7. (done in https://github.com/pelias/schema/pull/424)

### Reference links

 - [Breaking changes in Elasticsearch 7.0](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html)
- [Elasticsearch 7.0 release highlights](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/release-highlights-7.0.0.html)

**Comment by orangejulius** [comment]
With the list of changes above as of this writing, an ES7 build and an import of a few million records for the Portland Metro area works well, and querying with the latest API causes no errors.

I'm sure there's more work to do, in particular I think at least one geo query related change will be required, but it looks like the core part of the ES7 upgrade is now fairly well understood! :tada:

**Comment by missinglink** [comment]
after merging https://github.com/pelias/schema/pull/403 its now possible to create indices on ES 6.8.5 which will be compatible with 7.4.2

**Comment by missinglink** [comment]
For the adventurous among you, we have a [prelease `pelias/schema` branch here](https://github.com/pelias/schema/pull/394).
You'll find the corresponding [docker images here](https://hub.docker.com/r/pelias/schema/tags?page=1&name=es7).

At a minimum you should ensure that you've made the following configuration changes for ES7:
- Update `pelias.json` to set the correct `esclient.apiVersion` (`7.4` at time of writing)
- Set the `schema.typeName` to `_doc` in `pelias.json`
- Update `docker-compose.yml` to set the correct `services.elasticsearch.image` (`pelias/elasticsearch:7.4.2` at time of writing)

**Comment by orangejulius** [comment]
As of today, Elasticsearch 7 support has been merged to the `master` branches of all relevant Pelias repositories.

We'll follow up with additional changes or improvements as needed, but in our testing so far, ES7 appears to perform well.

We'll also soon start rolling out ES7 as the default to many of the regional projects in the [Pelias Docker](https://github.com/pelias/docker) project.

**Comment by orangejulius** [comment]
I think this is done now! :tada: 

In our testing ES7 performs well compared to ES6. There are no changes in query behavior and performance is the same or slightly better.

Please reach out to us if you find any ES7 related bugs! ES6 will continue to be supported for some time, but ES7 is now the recommended version!

**Comment by mihneadb** [comment]
@orangejulius I was trying to figure out if updating to a newer version of Pelias should imply data changes in ES and couldn't find this in any release notes / doc page. Is that a thing? And do you think maybe there should be such a page? I can add it to the docs repo via a PR (just need some tips re: its contents).
Thanks!

**Comment by orangejulius** [comment]
@mihneadb good point.

We definitely recommend starting fresh when updating to a new version, but you can follow the [general Elasticsearch compatibility](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html), where in general Elasticsearch can read indices created from _one prior major version_.

In our experience, using an index created in ES5 with ES6 lead to performance issues, but using an index created in ES6 with ES7 has worked fine.

**Comment by orangejulius** [comment]
Just in case anyone comes to this issue looking, Elasticsearch 7 is currently not only the highest supported, but also the _recommended_ version of Elasticsearch to use.

Until Elasticsearch 8 comes out and we add support for it, that will continue to be the case.
