### ISSUE TITLE
Travis-CI is broken on this repo

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#841]
Travis-CI integration is broken on this repo (pelias/pelias) and I'm not sure why...
I had to use admin privileges to merge a PR today after requesting the webhook be resent (which didn't help).

I can see this has been an issue for some time and is the same problem on the other open PR here.

What happened:

I opened the PR and merging was blocked by:

<img width="585" alt="Screenshot 2019-11-27 at 13 23 48" src="https://user-images.githubusercontent.com/738069/69723152-2d4b8500-1119-11ea-98ad-4591ace25ec7.png">

However, nothing showed up in Travis-CI 🤷‍♂ 

It's possible to view the webhook deliveries in https://github.com/pelias/pelias/settings/hooks/78799806 and I could see that GitHub thinks the payload was delivered, I even re-sent it to be sure, but nothing on the Travis-CI end...

Once I merged the PR [it did trigger a job for the merge commit](https://travis-ci.org/pelias/pelias/builds/617697603).

**Comment by orangejulius** [comment]
Just figured this out, it was something dumb I did a while ago :P Fixed in #859 :)
