### ISSUE TITLE
Sorting example: Liverpool, England vs Liverpool, Costa Rica

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#843]
Liverpool is both a well known [city in England](https://spelunker.whosonfirst.org/id/101750547/) and a less well known [neighbourhood in the canton of Limón](https://spelunker.whosonfirst.org/id/421169543/) in Costa Rica.

As it happens, both are represented extremely similarly in WOF. Both are localities, and both have very similar populations. Because of this, their sorting values are extremely similar, so it's a good case to consider for what data we can use to sort records correctly.

Here's some values for the two records that might be interesting to consider for use by Pelias in the future:

| Place | Liverpool, England | Liverpool, Costa Rica |
| --- | --- | --- |
| WOF Placetype: | locality | locality | 
| Population | 468945 | 466415 | 
| Concordances: | geonames, geoplanet, quattroshapes | geonames, geoplanet, quattroshapes, wikipedia, wikidata |
| `qs:placetype` | urban core | Town |
| `mz:is_current` | 1 | 1 |
| total `name:*` variant count | 138 | 127|

So some ideas that come out of this are sorting based on:

- existence of a wikipedia page
- quattroshapes placetype
- number of translated name variants

**Comment by mtmail** [comment]
I'd question the population number. It's a neighborhood of Limon and wikipedia puts the population of Limon at 58,522 (spanish version at 96,314)

**Comment by orangejulius** [comment]
Ah yes...it does look like it's actually pretty obvious that population number can't be valid! Well, that's an easy fix at least :)

**Comment by stepps00** [comment]
Good catch, @orangejulius - in this case, the population data in the Liverpool, Costa Rica record is incorrect. It looks like the neighbourhood in Costa Rica was incorrectly matched to the Liverpool, UK record through a bad concordance/join. I'll file an issue in WOF to fix.

Assuming population values are correct, the `wof:population` or `wof:population_rank` properties seem like decent sorting indicators.
