### ISSUE TITLE
Proposal: option to exclude specific sources or layers from search results

### ISSUE THREAD

**Issue by orangejulius** [pelias/pelias#844]
## Background

Pelias currently allows limiting search results to certain sources or layers, such as in the following query:

[/v1/search?text=New York&layers=region](https://pelias.github.io/compare/#/v1/search%3Ftext=New%20York&layers=region)

Without a sources or layers parameter, Pelias will search across all possible values for source or layer.

This works well if a user wants to search for a few specific sources or layers, but doesn't work well if the objective is something like "search all layers except...".

In order to solve that problem, a Pelias user has to look up the complete list of sources or layers, and perform the negation themselves. The list of layers is especially long, and each Pelias installation might have its own list, so this is not very easy to do.

## Proposal

Allow specifying "all except for" with a `-` in front of a layer.

For example:

`/v1/search?text=berlin&sources=-geonames` would search for Berlin in all sources except Geonames

`/v1/search?text=luxembourg&layers=-country` would search for Luxembourg in all layers except country.

## Questions to resolve

Because we already allow specifying "positive" layers, we have to decide what takes priority. For example, does the following query search only the locality layer, or locality and localadmin?

`/v1/search?text=berlin&layers=locality,localadmin,-locality`

The same question holds true with aliases:

`/v1/search?text=berlin&layers=coarse,-locality`

While this is a simple example, I'm sure Pelias users will come up with more complex situations where having a strong, clear, and consistent answer is important.

I think that most likely, we want the negation to take priority, but it's worth thinking about carefully.

## Benefits

Pelias currently performs several optimizations in order to ensure performance while still returning good results. One of these relates to addresses: since there are so many addresses, if we are reasonably sure a query is not for an address, then Pelias will internally omit the address layer, but _only if `address` was not explicitly specified in the list of layers_. This means anyone looking to filter out just a few layers would have no way of taking advantage of this optimization. We could ensure the negative layer filter allows this optimization.

Additionally, because the list of sources or layers can change over time as new data is added to a Pelias installation, avoiding the requirement that end users hardcode an enormous list of desired sources and layers into their queries could prevent them from using all available data, unless they periodically check to see what new sources and layers are available.

**Comment by Joxit** [comment]
That's a pretty cool and simple enhancement ! :+1:

**Comment by missinglink** [comment]
We got a support email today requesting the ability to show 'everything except India' using the `boundary.country` param.
Maybe that would be possible using a similar convention?

**Comment by missinglink** [comment]
I think this would benefit from https://github.com/pelias/config/pull/127 being merged, especially if we need to enumerate a list of potential layer/sources in the API.

**Comment by orangejulius** [comment]
This has been merged and is all good to go, hope people find it useful!

**Comment by missinglink** [comment]
See https://github.com/pelias/api/pull/1525 for more information
