### ISSUE TITLE
Is "pelias import all" stuck?

### ISSUE THREAD

**Issue by kshnkvn** [pelias/pelias#845]
I install pelias according to the docker instructions and now for more than 6 hours I see this:
```shell
Sat Feb 15 09:37:51 UTC 2020 /data/openaddresses/mx/bcn/statewide.csv
- conflating openstreetmap

```
I am trying to import all of North America.

**Comment by shekoufa** [comment]
I see you've already closed this issue but in case you're still wondering, it's not stuck. Conflating OpenStreetMap takes a long file for larger files (which is the case for North America). It's always a good idea to run top or htop and monitor the running tasks to make sure that there's no problem with running your Pelias targets.
