### ISSUE TITLE
Working behind firewall/SSL proxy requires baseimage change

### ISSUE THREAD

**Issue by mubaldino** [pelias/pelias#877]
`curl` is used for most downloads and fails as employed in Pelias:  default CA chain in docker `baseimage` is not easily overridden by command line `pelias`.   Use of Curl claim untrusted "Self-signed certificate".  Node scripts also raise a similar exception:

```
info: [interpolation(TIGER)] downloading all TIGER data
error: [interpolation(TIGER)]  message=self signed certificate in certificate chain, stack=Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12), code=SELF_SIGNED_CERT_IN_CHAIN, response=undefined
```

### Use-cases
creation of a Pelias node behind a SSL-inspection firewall is challenging in general.  All applications and libraries accessing external `https` URLs require various default adjustments to inserting a proper trusted CA chain.  

SSL-inspection may not be common in all corporate or other DevOps scenarios working behind a firewall.  In this situation I believe the following is happening:
- Secured content on external sites using `https` require a trusted certificate
- Such sessions are inspected for validity and require the insertion of a valid, trusted CA chain if one does not exist. In this case only the local, corporate CA is trusted.
- Without a trusted CA provided through the client initiating the HTTPS request, it fails.

// I'm not a security expert;  I also don't assume that this is all that common across enterprises, but is more common amongst those with higher security practice //

### Attempted Solutions
Considerations for a solution
[ ] Docker mount of a "CA" (`ca.crt` or `cacerts.pem`) to standard location in docker container
[ ] Influence docker containers through ENV (`-e XXX`) args, such as `CURL_CA_BUNDLE` for curl, or `NODE_EXTRA_CA_CERTS` for node.
[ ] Influence docker container through app-specific setting, e.g., in Node: `npm config set` or edit `~/.npmrc` directly. 
[x] Last resort, rebuild Pelias `baseimage` and `libpostal_baseimage` with any of the above solutions. In the absence of this patch.

Okay, here are some targets I tried:

* insert my "ca.crt" into   `/usr/local/share/ca-certificates/ca.crt`, which requires `update-ca-certificates`.  Seems unreasonable to change every invocation of `docker run` in Pelias.

```
 docker run -v myca.crt:/usr/local/share/ca-certificates/ca.crt .... IMG --name CONT
 docker exec -it CONT "update-ca-certificates"
```

* Rebuild `pelias:baseimage` and `pelias:libpostal_baseimage`
  * copy PEM cert to `ca.crt` file in `docker-baseimage` repo
  * `docker build . --tag pelias/baseimage:latest`

Dockerfile addition:
```
# Same CA file.  Two solutions. 
# Did not work:
COPY ca.crt /usr/local/share/ca-certificates/ca.crt
RUN update-ca-certificates

# ENV var here does work for curl:
COPY ca.crt /etc/ssl/ca.crt
ENV CURL_CA_BUNDLE '/etc/ssl/ca.crt'
```

**SUCCESS**.  Rebuilding the docker images with this tweak worked for curl uses; Still trying out interpolation which is more Node.

### Proposal

- Update base images to allow the addition of a deployer's own CA chain, mainly through `ENV` which would be inherited by children images.
- By convention assume if deployer is overriding, something like `PELIAS_CONFIG` would contain path to `USER_CA_BUNDLE` variable, in addition to `ENV` 
- Each docker image would need to accommodate CA override through `ENV`, default update, or settings file (`~/.npmrc`, etc)

### References

* Curl man page: https://curl.haxx.se/docs/manpage.html . `CURL_CA_BUNDLE` mentioned but no actual good reference in their own documentation on the ENV var.
* Curl note on SSL: https://curl.haxx.se/docs/sslcerts.html
* NPM usage: https://stackoverflow.com/questions/23788564/npm-add-root-ca

**Comment by orangejulius** [comment]
Hi @mubaldino,                                                                                                                          
This is definitely a valid, if rare use case.                                                                                           
                                                                                                                                        
That said it's probably outside the scope of what we can officially support through the Pelias Docker images. I don't think we should anything to Pelias code specifically to handle this.                                                                           
                                                                                                                                        
However, I think you should be able to solve it using nothing but standard Docker tools:                                                  
                                                                                                                                        
On my system at least, `update-ca-certificates` appears to manage symlinks in the `/etc/ssl/certs` directory. Can you achieve what you want by mounting a Docker volume with your certificate to that location? That would be nice since you can override any standard Pelias image with what you need.

**Comment by mubaldino** [comment]
Thanks @orangejulius!   I will purse a docker-compose tweak using Curl's posted CA PEM file. 
I'll update this issue, although its not likely to be a part of the code base.  I'm more interested in seeing how the best technique here could be documented.

**Comment by mubaldino** [comment]
Working solution.  Use ENV and voume solution in Docker Compose.  No docker image rebuilds or futzing with code.

1. create updated "CA" file.  See recipe below as one possible technique.  Copy to local file `"ca.crt"`

2. configure Pelias `.env`.  Added only:
```
CURL_CA_BUNDLE=/etc/ssl/certs/ca-cerfiticates.crt
```

3.  Update `docker-compose.yml` with mounted volume to inject CA path in \#2.
Any service in compose that needs updated CA chain add mount as such:

```yaml
<service>
    volumes:
      - "./ca.crt:/etc/ssl/certs/ca-certificates.crt"

# Repeat that line as often as needed.
```


How I created my "CA"
------------------
Create a CA with external and internal entries.  Acquire CA certs from trusted external source.
I concatenated Curl's CA chain and then my corporate chain into a single PEM formatted file.

```shell 
  # Copy to current folder the corporate, custom CA chain to "my-ca.crt"

   export CURL_CA_BUNDLE my-ca.crt
   curl https://curl.haxx.se/ca/cacert.pem > ./ca.crt
 
   cat <<EOF >>  ./ca.crt

# My CA Chain
#==================
EOF

  # Append custom chain to final. 
  cat my-ca.crt  >> ./ca.crt
```

**Comment by mubaldino** [comment]
This may be closed.  I addressed a solution as above.  That should work for those of us building this behind the corp firewall.

**Comment by missinglink** [comment]
Thanks!
