### ISSUE TITLE
Install documentation now inconsistent

### ISSUE THREAD

**Issue by bobtpawn** [pelias/pelias#882]
It looks like in https://github.com/pelias/pelias/issues/881, elasticsearch 6 is no longer supported.  However, the documentation at https://github.com/pelias/documentation/blob/master/pelias_from_scratch.md#install-elasticsearch links to the install documentation for elasticsearch 6.8.

**Comment by orangejulius** [comment]
Hi @bobtpawn,
Thanks for the quick catch. The Elasticsearch documentation is always a pain because they change/break links frequently, and there are significant differences between versions.

We'd gladly accept a PR to change the link to point to the latest in the Elasticsearch 7 series!
