### ISSUE TITLE
QUESTION: What's the best way to contribute missing addresses

### ISSUE THREAD

**Issue by msschl** [pelias/pelias#891]
Hi there,
just a short question...

As the title states: What's the best way (or your advice) to contribute missing addresses, so that I can import them in a timely manner?

Thanks in advance.

**Comment by orangejulius** [comment]
Hi @msschl,

This is actually a great question. I'll try to outline some possibilities that could help you or others.

If you...

### ...know of an official source of lots of addresses from a local government

Add it to [OpenAddresses](openaddresses.io/). Then the OpenAddresses project will periodically fetch the latest data and distribute it for everyone to easily use, including Pelias.

### ...know of just a few missing addresses

Add them to [OpenStreetMap](openstreetmap.org/) yourself. This will be picked up by both the Pelias OpenStreetMap importer for the addresses themselves, and the [Interpolation engine](https://github.com/pelias/interpolation/) (so a few addresses that cover a large range can go a long way).

OSM also supports [bulk imports](https://wiki.openstreetmap.org/wiki/Import) if you have a lot of addresses, but it's a difficult process that really isn't encouraged these days.

Of course everyone else in the OSM ecosystem benefits as well :)

### ... have some address data that you can't share (proprietary data, etc)

You can use the [CSV importer](https://github.com/pelias/csv-importer) to bring them into Pelias.

**Comment by msschl** [comment]
Thanks @orangejulius for your quick and detailed response 😄
