### ISSUE TITLE
Every address of small village in Germany is missing the locality field

### ISSUE THREAD

**Issue by fritzfr** [pelias/pelias#893]
**Describe the bug**
When looking up addresses for small villages in Germany, which share the postal code with a bigger city nearby, the results returned are missing the `locality` field. In fact, none of the fields returned mention the name of the city (or the name of the village for that matter).

**Steps to Reproduce**
Search for "Mühlgasse 20 35510", it will return:

```json
{
"id": "way/688338717",
"gid": "openstreetmap:address:way/688338717",
"layer": "address",
"source": "openstreetmap",
"source_id": "way/688338717",
"name": "Mühlgasse 20",
"housenumber": "20",
"street": "Mühlgasse",
"postalcode": "35510",
"accuracy": "point",
"country": "Deutschland",
"country_gid": "whosonfirst:country:85633111",
"country_a": "DEU",
"region": "Hessen",
"region_gid": "whosonfirst:region:85682531",
"region_a": "HE",
"macrocounty": "Regierungsbezirk Darmstadt",
"macrocounty_gid": "whosonfirst:macrocounty:404227581",
"county": "Wetteraukreis",
"county_gid": "whosonfirst:county:102063633",
"county_a": "WT",
"continent": "Europa",
"continent_gid": "whosonfirst:continent:102191581",
"label": "Mühlgasse 20, Deutschland"
}
```

```json
{
	"geometry": {
		"type": "Point",
		"coordinates": [
			8.678653,
			50.414923
		]
	}
}
```

This street is in a village called "Nieder-Weisel" and the next bigger city (with the postal code 35510) is called "Butzbach". None of these two names is anywhere in the payload, making it rather unusable for identifying the address just from the label and **would require an additional API call to figure out what the name of the city behind the postal code is**.

In addition (or because of this issue), a search for "Mühlgasse 20 Butzbach" does not return any results, you need to provide the postal code. That is an even more inconvenient issue for the user, because it does not need to be provided when the address is within a city with it's own postal code, but if it is in a village which shares a postal code, it is required.

**Expected behavior**
The locality should be included as a field and in the label. I should also be able to search with the name of the city, instead of the postal code only.

**Environment (please complete the following information):**
We are using the OpenRouteService API.

### References
https://github.com/pelias/pelias/issues/387

**Comment by missinglink** [comment]
The GeocodeEarth servers seem to be returning what you expected?
- https://pelias.github.io/compare/#/v1/search?size=1&text=M%C3%BChlgasse+20+35510
- https://pelias.github.io/compare/#/v1/search?size=1&text=M%C3%BChlgasse+20+Butzbach

**Comment by orangejulius** [comment]
Hi @fritzfr,
As Peter mentioned, this is working fine in the latest version of Pelias as shown in the links to our compare tool.

We built a feature specifically to solve this problem a while ago and enabled it by default in [May 2020](https://github.com/pelias/config/pull/129) so it looks like this is an issue with ORS, not Pelias.

Either they haven't done a build at all since May (possible, but I guess unlikely?) or they have been running with incorrect settings.

Since this isn't an issue with Pelias I'm going to close this issue. If the ORS team needs help configuring Pelias I assume they'll let us know :)

**Comment by fritzfr** [comment]
@orangejulius @missinglink Thank you for this insight, this has been very helpful.
