### ISSUE TITLE
autocomplete does not return postal codes lower than 10000

### ISSUE THREAD

**Issue by Joxit** [pelias/pelias#898]
**Describe the bug**

In France we have postal codes from 01000 to 97600. But when I looking for a postal code lower than 10000 I have no results. 

I try the same request on search API and it works fine... :shrug: 

**Steps to Reproduce**
When I search [`03100`](https://pelias.github.io/compare/#/v1/autocomplete?boundary.country=FRA&text=03100&debug=1) on autocomplete endpoint the result is

```
0) D 3100, Houilles, France
```

**Expected behavior**

The expected response is `03100, Montluçon, France`, just like [search endpoint](https://pelias.github.io/compare/#/v1/search?boundary.country=FRA&text=3100&debug=1):
```
0) D 3100, Houilles, France
1) 31000, Toulouse, France
2) 03100, Montluçon, France
3) Square des 31000 et des 45000, St.-Ouen, France
4) Station François Verdier, Sortie vers Rue de Metz, Ligne B, 31000 Toulouse, Toulouse, France
```

**Additional context**

I tried to debug this query and I found something.

```json
{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "type": "phrase",
            "query": "03100",
            "fields": [
              "phrase.default",
              "phrase.en"
            ],
            "analyzer": "peliasQuery",
            "boost": 1,
            "slop": 3
          }
        }
      ],
      "filter": [
        { "terms": { "layer": [ "postalcode" ] } },
        { "match": { "parent.country_a.ngram": { "analyzer": "standard", "query": "FRA" } } }
      ]
    }
  },
  "size": 20
}
```

The ES query looks like this and uses the field `phrase.default` (I added a filter on postalcode). When I change the the field to `name.default` it works... IDK yet if the issue is in the schema or model...

**Comment by orangejulius** [comment]
Oh, that's a good one. Our handling of pure postalcode queries is not so great. :(

Over in https://github.com/pelias/api/pull/1506 I've been experimenting with modifying the Pelias Parser result when it shares a value between `subject` and `street`. Looks like there's a similar parse here, except with postcode, so I wonder if the same approach will help?

If not, it might have something to do with the leading zero: maybe we strip those in the `phrase` field?

**Comment by Joxit** [comment]
I found something else when playing with the `multi_match`'s `fields` and `analyzer`.

| | `fields` | `analyzer` | result |
| -- | --- | --- | --- |
| Original | `phrase.default` | `peliasQuery` | :x: |
| Try 1 | `name.default` | `peliasQuery` | :heavy_check_mark:  |
| Try 2 | `parent.postalcode` | `peliasQuery` | :x: |
| Try 3 | `phrase.default` | empty | :x: |
| Try 4 | `name.default` | empty | :heavy_check_mark: |
| Try 5 | `parent.postalcode` | empty | :heavy_check_mark: |
| Try 5 | `phrase.default` | `peliasPhrase` | :heavy_check_mark: |

So this may be caused by `removeAllZeroNumericPrefix` (present in `peliasQuery` and not in `peliasPhrase`) ?

And `name.default` works thanks to its analyzer `peliasIndexOneEdgeGram` ? :thinking:

**Comment by orangejulius** [comment]
Huh yeah, great find @Joxit 👏 

@missinglink, the relevant code here is all pretty old, but I think I recall the _intent_ behind removing the leading zeros is to handle cases like those where a street name is in source data as, say `05th avenue`, right?

Maybe with a couple integration and acceptance tests we can judge if the `removeAllZeroNumericPrefix` filter is something we can add to the `peliasPhrase` analyzer. I _think_ that's safer than removing it from everywhere.
