### ISSUE TITLE
Adding a layer for transit data

### ISSUE THREAD

**Issue by hennihaus** [pelias/pelias#902]
Hi there,

it would be a nice feature to choose only transit stops (eg. stops form gtfs file) from all apis. So it would be possible to calculate via reverse call the nearest stations and via automplete call only transit stops? Is this still possible?

With best regards
Henni

**Comment by missinglink** [comment]
Hi Henni,

It's possible to add custom sources and layer:
https://github.com/pelias/api#custom-sources-and-layers

We'd like to enable the `auto_discover` flag by default but there is currently an issue blocking that, more info:
https://github.com/pelias/config/pull/127

Considering the importance of transit data in geocoding we'd consider adding it as an official layer if there was some consensus about how it would work, from wgat I've seen so far it might be better to call it `stop`?

**Comment by missinglink** [comment]
Also worth mentioning that you can currently filter transit information from OSM using the `?categories=transport` family of categories tags:

https://github.com/pelias/pelias/wiki/Taxonomy-v1#transport---second--third-level

https://github.com/pelias/openstreetmap/blob/master/config/category_map.js

**Comment by hennihaus** [comment]
And the default source for transit is "tranist"?

**Comment by missinglink** [comment]
At this stage there are no 'canonical' (ie. default) `source` and `layer` definitions for GTFS imports.

The list of our 'canonical' sources/layers can be found here: https://github.com/pelias/config/blob/master/config/defaults.json#L40

If you use the [pelias/transit](https://github.com/pelias/transit) importer (developed by [TriMet](https://en.wikipedia.org/wiki/TriMet)) to load the data then it uses the name `transit` for the source and a variety of layers such as `stops` and IIRC `landmarks` and `bikeshare`.

Any non-canonical sources/layers have no special handling within Pelias (out of the box) and so you can effectively call them whatever you like, and pick names that suit your problem domain and data.

You may be interested in ferries, busses, e-bikes, kayaks or airplanes. We don't currently have a unified model of `transit` with all these things included, and we don't have any special handling of them for now so it's not defined in the canonical sources/layers.

Our general advice for naming is that the `source` is where the data came from (the name of the provider), although calling the source `transit` isn't going to cause you any issues.

The idea behind `layers` is that *different sources can provide the same layers*, which is very powerful as it allows you to mix-and-match data from different providers.

You will likely only need to use `source` to 1. identify the origin of a document or 2. filter results to only show documents from that provider.

**Comment by hennihaus** [comment]
Thank you @missinglink for your detailed reply!
