### ISSUE TITLE
Wrong information about the city Bremen (Germany)

### ISSUE THREAD

**Issue by tst-abat** [pelias/pelias#906]
Hello all,

in one of my company's business applications we use the [openrouteservice](https://openrouteservice.org/) of the Heidelberg University in Germany. This service in turn uses the Pelias engine to find coordinates and addresses. For the last 2 weeks, the correct state, among other things, has not been found for the city of Bremen (Germany). A [query](https://ask.openrouteservice.org/t/wrong-state-for-adresses-from-bremen-germany/2880) at the openrouteservice brought us on the track of the whosonfirst data source. There I opened an [issue](https://github.com/whosonfirst-data/whosonfirst-data/issues/1945) which was closed with a correction of the two data sets (see links in the issue). Unfortunately, the correct entry for Bremen is still not found; Bremen in the federal state of Lower Saxony continues to appear as the answer. This is wrong and had worked a few weeks ago.
What is the reason for this and is the Pelias engine responsible? If so, can this problem be fixed, as some checks in the backend of our applications depend on it.

If more information is needed or if you want me to add the information contained in the two links here again, I am happy to do so. I hope I can be helped here. Thank you in advance.

With kind regards
tst-abat

**Comment by stepps00** [comment]
WE've patched a fix for this upstream in WOF through https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/46. This issue should be resolved once Pelias points to the most recent WOF changes for Bremen.

**Comment by orangejulius** [comment]
Hi @tst-abat,
Thanks for reporting this issue so it can be fixed! Since the data is now correct in WOF, it should be fixed in ORS the next time they rebuild their Pelias index. I don't know off hand how often they do that. The information will soon be up to date on Geocode Earth, and therefore correct in [this compare app query](https://pelias.github.io/compare/#/v1/search?boundary.country=DE&text=An+der+Reeperbahn+10+28217+Bremen) soon as well.

**Comment by tst-abat** [comment]
Dear @orangejulius 

ORS now returns the correct coordinates for Bremen when searching for a specific address.
Thank you for your efforts. The problem is now solved.

All the best furthermore.

Many greetings
tst-abat
