### ISSUE TITLE
What's the difference(s) with Photon

### ISSUE THREAD

**Issue by garaud** [pelias/pelias#92]
Hi,

I've known [Photon](https://github.com/komoot/photon) for a few weeks and I known this is an open-source Geocoder *over* ElasticSearch.

I wonder the difference between Pelias and Photon?

Thanks. Regards,
Damien Garaud

**Comment by missinglink** [comment]
Hi Damien, there are some similarities and some differences, most easily summed up here:

|   | Pelias  | Photon |
| ------------- |:-------------:|:-----:|
| based on elasticsearch | ✓ | ✓ |
| data: openstreetmap | ✓ | ✓ |
| data: openaddresses | ✓ |  |
| data: geonames | ✓ |  |
| data: quattroshapes | ✓ |  |
| data: other | ✓ |  |
| data: easy import via snapshots |  | ✓ |
| builds: require postgis |  | ✓ |
| builds: require nominatum |  | ✓ |
| api: geojson | ✓ | ✓ |
| api: centroid bias | ✓ | ✓ |
| api: bbox bias | ✓ |  |
| api: no geo bias | ✓ | ✓ |
| i18n: per-language analysis | | ✓ |
| data structures: ngram | soon | ✓ |
| data structures: FST | ✓ | |
| imports: language | javascript | java |
| actively maintained | ✓ | ✓ |
| dedicated team | ✓ |  |

We are in contact with Christoph at Komoot and really like their team and the products they build, I'd like to think that with our growing team we have and the swift progress we are making (particularly around testing) that Pelias is at least on-par with Photon.

Having said that there are some features of Photon that I really like such as per-language analysis (which it will take us a few sprints to get to) and the imports via snapshots which is really nice.

We made a couple difficult design decisions early on, such as not requiring postgres/nominatum to import data and supporting all the open geo data we can get our hands on, in the end I think these are our strengths, plus we have a team of 5 working on it full time and provide a planet-wide service which is suitable for most simple tasks.

**Comment by garaud** [comment]
Thank you for this complete and interesting answer.
I like the table summary with the different features between pelias and photon.

> It's a super difficult problem, building 80% of a geocoder is actually quite easy, it's the last 20% that takes a lifetime ;)

I think it's always true whatever the (ambitious) project, The latest 10/20% can take very long tiiiiime. *The devil is in the details*.
