### ISSUE TITLE
Add custom input field in autocompletion

### ISSUE THREAD

**Issue by xinyuluo** [pelias/pelias#928]
Hi! I wonder if it's possible to import custom dictionary for suggestions in autocompletion? For example (screenshot is from Qwant maps), the use case can be the following one:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/25223376/160569412-1c48f4f6-1f46-48f2-9b1d-da722dc94ef9.png">

Thank you.

**Comment by missinglink** [comment]
Hi @xinyuluo, does Qwant use Pelias? I seem to recall them using it in the past but haven't heard anything from them in years.

Regarding your question, the autocompletion is based on geographic data, so if you import custom geographic data then it will appear in search results, it isn't a general purpose search engine solutions where you could, for instance, mix product listings in with the results.

One of the easiest ways to import custom data is https://github.com/pelias/csv-importer, you can build a small region using https://github.com/pelias/docker and then run the csv importer on top of the base data.

**Comment by missinglink** [comment]
If you're looking for an off-the-shelf solution, check out https://geocode.earth/docs/components/autocomplete-element/
However this doesn't allow inclusion of custom data on the server-side, you'd need to add it on the client-side.

**Comment by xinyuluo** [comment]
@missinglink I'm not sure whether Qwant uses Pelias. I was just using it as an example :)

To my best knowledge, they probably use https://github.com/CanalTP/mimirsbrunn (but I might be wrong).

I'll check out the links you attached. Thanks for the quick response.
