### ISSUE TITLE
Missing entry for New Square, NY in autocomplete/search

### ISSUE THREAD

**Issue by rmglennon** [pelias/pelias#93]
This comment came in through technical support (see Zendesk 153), and posting here on behalf of the user.

"As you can see in the picture attached

There is a address

3 Taft Lane 
New Square NY 10977

And it's on the map when search New Square NY

And I scroll to it, but in the auto complete and search it does not find it :-("

![new_square](https://cloud.githubusercontent.com/assets/4380498/8112192/2d5b679e-101b-11e5-95c7-21f504d0f5b1.PNG)

**Comment by hkrishna** [comment]
this is known issue - currently the autocomplete endpoint ```/suggest``` only looks at the street address and does not handle city, state names. 

Our next release (that uses ngram) should fix this issue.

**Comment by missinglink** [comment]
That specific address is not in openstreetmap; however the street itself is:

Taft Lane: http://nominatim.openstreetmap.org/details.php?place_id=59479536
Centre Point: 41.1385925,-74.0315996
OSM: way 24170795

There is only one record in openstreetmap for that zip code:
http://www.openstreetmap.org/node/357550492

Looking at the openaddresses data, I found this one, but it seems to be many klicks away in NJ:
http://nominatim.openstreetmap.org/details.php?place_id=115604452

```json
{
  "type": "Feature",
  "properties": {
    "id": "fe9d6848f6b8499a8393942a3dd16fc5",
    "layer": "openaddresses",
    "name": "3 Taft Lane",
    "alpha3": "USA",
    "admin0": "United States",
    "admin1": "New Jersey",
    "admin1_abbr": "NJ",
    "admin2": "Morris County",
    "local_admin": "Morristown",
    "locality": "Morristown",
    "neighborhood": "Monroe",
    "category": [],
    "address": {
      "number": "3",
      "street": "Taft Lane"
    },
    "text": "3 Taft Lane, Morristown, NJ"
  },
  "geometry": {
    "type": "Point",
    "coordinates": [
      -74.469197,
      40.796116
    ]
  }
}
```

this specific issue will unfortunately not be solved until either:
- we get better coverage for global address data (via OSM or OA)
- we provide a better street fallback like nominatum does which provides the street names when the numbers are not found
