### ISSUE TITLE
Communication with Pelias developers: e-mail address

### ISSUE THREAD

**Issue by dawidl11** [pelias/pelias#937]
Hi there, 

my concern is a little different this time.
I would like to ask if the email address you provided on the first page "team@pelias.io" is the right one for communicating with you (Pelias Developers). Or do you not see this way of communication as the best?

I sent an email to you a week ago, but I am not sure if you received it (12.01.23 - "Suggestions ...").

Many thanks in advance for the answer!

**Comment by missinglink** [comment]
Hi @dawidl11, thanks for your email and apologies in not replying.
No team members have availably for bringing on additional consulting clients at this time.
