### ISSUE TITLE
Text search by category

### ISSUE THREAD

**Issue by michaelkirk** [pelias/pelias#938]
*Edit: I originally misunderstood the source of my "bug". I was trying to search places by category like "coffee", but that's not currently supported. Original issue text follows:*

**Describe the bug**

Results from `/search` specifying `focus` are less relevant than those from `/autocomplete` 

**Steps to Reproduce**

Visit: https://pelias.github.io/compare/#/v1/search?focus.point.lat=47.600607322920695&focus.point.lon=-122.32452392578126&text=coffee

Compared go the autocomplete endpoint, you'll see many results very far away from the focus.

**Expected behavior**

I expect the results from the `/search` endpoint to be as relevant or more relevant than those from `/autocomplete`. 

**Environment (please complete the following information):**

Reproducible on https://pelias.github.io

**Pastebin/Screenshots**

## `autocomplete` for "coffee" with `focus` in Seattle looks pretty good 👍 

https://pelias.github.io/compare/#/v1/autocomplete?focus.point.lat=47.600607322920695&focus.point.lon=-122.32452392578126&text=coffee

<img width="746" alt="Screenshot 2023-01-19 at 3 21 38 PM" src="https://user-images.githubusercontent.com/217057/213584912-32098dfb-6dcf-45ba-b294-629f8a93c305.png">

## `search` for "coffee" with `focus` in Seattle looks worse 😢 

https://pelias.github.io/compare/#/v1/search?focus.point.lat=47.600607322920695&focus.point.lon=-122.32452392578126&text=coffee

<img width="743" alt="Screenshot 2023-01-19 at 3 21 53 PM" src="https://user-images.githubusercontent.com/217057/213584906-28751f2a-b877-4539-a92a-96dac9ac3874.png">

**Comment by missinglink** [comment]
The `/v1/search` endpoint is designed for *complete* inputs, whereas `/v1/autocomplete` is for *partially complete* inputs.

You'll notice that search returns only a list of things named "coffee", including the first two results for "coffee county" where the records have been indexed without the "county" designation, as that's how they are commonly referred to.

**Comment by michaelkirk** [comment]
Thank you for the explanation, I understand better why I'm seeing these results.

Now I have a completely different question in pursuit of the same goal. In my use case "coffee" _is_ the complete input - it's the entirety of what I'm expecting the user to type. 

But I think the problem is that I was trying to use "coffee" as a category, whereas pelias is primarily concerned with names (and addresses).

Do you have any advice for producing categorical searches like that? 

e.g. If a user searches "coffee", I might expect results like https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcafe or https://wiki.openstreetmap.org/wiki/Tag:cuisine%3Dcoffee_shop.

"water fountain" might produce nodes labeled https://wiki.openstreetmap.org/wiki/Tag:fountain%3Ddrinking

Is this something considered inside the scope of what pelias should be able to do?

**Comment by missinglink** [comment]
Hi @michaelkirk, Pelias doesn't support free text search on categories at the moment, although I could see that being added in the future.

We do already have the ability to filter by category such as this query:
https://pelias.github.io/compare/#/v1/reverse?category=food%3Acoffee_shop&point.lat=47.600607322920695&point.lon=-122.32452392578126

The category mappings from openstreetmap are defined in this file:
https://github.com/pelias/openstreetmap/blob/master/config/category_map.js

It's not ideal for your use-case as you would like the ability for the user to type (and presumably autocomplete) an arbitrary category and get back a list of matches, the categories filter would require you to offer the user a list of predefined categories to select from.

**Comment by missinglink** [comment]
Hmm actually I'm not sure if that is working as expected, seems maybe the `?categories` filter isn't enabled for reverse 🤔

related: https://github.com/pelias/api/pull/1401

**Comment by michaelkirk** [comment]
> Pelias doesn't support free text search on categories at the moment, although I could see that being added in the future.

Sorry for the long delay on this (and thanks for your responses)! I'm going to update the issue subject to better reflect what my "real" feature request was.

I'd really like to have category text search in Headway, so I've just recently started getting acquainted with the Pelias code. I'm also new to elasticsearch, so I'm really out of my element here. 😅 

Still, I'm going to try to chip away at it for a while to see if I can make some progress. If you have any thoughts on directions (or if you want to collaborate more actively!), please let me know. I feel like even a well-aimed spitball of an idea from someone familiar with the codebase might be helpful to me at this point.

**Comment by MuhammadNaeem42** [comment]
hi everyone i need you help i build a pelias using docker for portland-metro region i access map http://3.110.112.168:4300/demo but search engine is not work how i implement the search engine please guide me.

**Comment by michaelkirk** [comment]
I've been looking into this again, and I realize it's pretty much a dupe of #99/#100, so I'll comment there and close this.
