### ISSUE TITLE
Daily updates

### ISSUE THREAD

**Issue by devopsnot** [pelias/pelias#941]
Is it possible to be performing the update process daily, without doing the complete process?

Downloading only the new information and not the full map.

**Comment by missinglink** [comment]
Pelias doesn't support partial updates and it's very unlikely that we would add this functionality in the future.

Most organizations do monthly builds/releases.

**Comment by arnesetzer** [comment]
If you refer to the osm/oa data, you may have a look at https://github.com/pelias/openstreetmap/issues/26 and https://github.com/pelias/pelias/issues/412. But as missinglink pointed out: Unfortunately there is no current official solution for that problem/feature.

**Comment by zackrspv** [comment]
Is that still the case here in 2025? This seems like  fairly critical feature to have missing.  Photon and Nominatim both support scheduled incremental updates, and something like Pelias with is just superior in every way, should as well.
