### ISSUE TITLE
Incorrect behavior if insert space between text addresses in search and Autocomplete API

### ISSUE THREAD

**Issue by rafi138** [pelias/pelias#942]
Hi there,
I have found issues while testing the APIs, For Example,
if `text=Kathmandu Durbar Square` we found the exact one but after inserting the space,
` text=Kath mandu Durbar Square ` I found some incorrect behavior.

**Comment by missinglink** [comment]
This issue doesn't contain enough information to reproduce the issue, it also doesn't explain what 'incorrect behavior' means within the context of the issue.

Please use the issue reporting template provided.
