### ISSUE TITLE
Get postal code in /search or /place API endpoint

### ISSUE THREAD

**Issue by stouch** [pelias/pelias#946]
I am trying to get the postal code (FR) of a locality when I use `search` and `place` API. I set up a pelias docker installation with whosonfirst and importPostalcodes set to true. I don't use openstreetmap neither openaddresses.

Is there any trick to accomplish this ?

### Use-cases
I'd like to get the postal code of a locality directly using :
http://localhost:4000/v1/search?text=Lille

Right now, it only returns:

```json
 {
		"id": "101750277",
		"gid": "whosonfirst:locality:101750277",
		"layer": "locality",
		"source": "whosonfirst",
		"source_id": "101750277",
		"country_code": "FR",
		"name": "Lille",
		"confidence": 1,
		"match_type": "exact",
		"distance": 203.228,
		"accuracy": "centroid",
		"country": "France",
		"country_gid": "whosonfirst:country:85633147",
		"country_a": "FRA",
		"macroregion": "Upper France",
		"macroregion_gid": "whosonfirst:macroregion:1108826399",
		"macroregion_a": "NC",
		"region": "Nord",
		"region_gid": "whosonfirst:region:85683445",
		"region_a": "NO",
		"macrocounty": "Lille",
		"macrocounty_gid": "whosonfirst:macrocounty:404228283",
		"county": "Lille",
		"county_gid": "whosonfirst:county:102071951",
		"localadmin": "Lille",
		"localadmin_gid": "whosonfirst:localadmin:1159322397",
		"locality": "Lille",
		"locality_gid": "whosonfirst:locality:101750277",
		"label": "Lille, France"
}
```

**Comment by missinglink** [comment]
Hi @stouch, postal codes are assigned to addresses, not localities.

In the case of Lille, it has many postcodes such as [59000](https://www.worldpostalcodes.org/en/france/postal-code/59000), [59350](https://www.worldpostalcodes.org/en/france/postal-code/59350), [59130](https://www.worldpostalcodes.org/en/france/postal-code/59130) etc.

If you search for an address within Lille you will get the postcode if we have it, for instance:
https://pelias.github.io/compare/#/v1/place?ids=openaddresses%3Aaddress%3Afr%2Fcountrywide%3A3e9871c9baaee154

**Comment by stouch** [comment]
> Hi @stouch, postal codes are assigned to addresses, not localities.
> 
> In the case of Lille, it has many postcodes such as [59000](https://www.worldpostalcodes.org/en/france/postal-code/59000), [59350](https://www.worldpostalcodes.org/en/france/postal-code/59350), [59130](https://www.worldpostalcodes.org/en/france/postal-code/59130) etc.
> 
> If you search for an address within Lille you will get the postcode if we have it, for instance: https://pelias.github.io/compare/#/v1/place?ids=openaddresses%3Aaddress%3Afr%2Fcountrywide%3A3e9871c9baaee154

I'd love to get any trick to list all the postal codes of a locality, using only whosonfirst (and/or geonames) only.

I guess it's not possible easily ?

**Comment by missinglink** [comment]
> I guess it's not possible easily ?

It would be trivial to implement using something like PostGIS but difficult to implement with Elasticsearch.

It's been requested before but unfortunately I don't think we would consider adding it, we don't want to be offering general GIS query functionality better suited to a RDBMS.

**Comment by stouch** [comment]
https://github.com/pelias/pelias/issues/887

**Comment by Joxit** [comment]
Hi there, sorry for the hijack, we did a special API some time ago for this special use case in France, Belgium, Italy and Switzerland. It was supposed to be a temporary solution until an integration in pelias.

```http
GET https://api.jawg.io/postalcode/api/postalcode?city=lille&access-token=
```
```json
[
  {
    "postalcode": "2275",
    "country": "BE"
  },
  {
    "postalcode": "59160",
    "country": "FR"
  },
  {
    "postalcode": "59000",
    "country": "FR"
  },
  {
    "postalcode": "59777",
    "country": "FR"
  },
  {
    "postalcode": "59260",
    "country": "FR"
  },
  {
    "postalcode": "59800",
    "country": "FR"
  }
]
```

The other solution, is by using two calls, one with search/autocomplete with your city and the second one a reverse geocoding (postalcode are available in reverse geocoding in Jawg APIs), this is the best solution IMO.
