### ISSUE TITLE
[Whosonfirst] API to get the WOF id (concordance) from a GeoName id

### ISSUE THREAD

**Issue by stouch** [pelias/pelias#947]
Hi, I'm looking for a way to get the wof:xxx:id that matches with a gn:xxx:id. For example, when I get a `v1/place?ids=gn:region:2976082`, I don't have any information for the WOF id that is concordant to it (whosonfirst:region:85683543).

Is there any API endpoint to do this ?

Thanks a lot.

**Comment by missinglink** [comment]
Hi @stouch we do not have an endpoint which allows you to return the corresponding WOF ID for a Geonames ID.

Are you running your own instance or using a provider such as Geocode Earth?
If you're running your own then you should be able to send a custom Elastic query to fulfil this request.

**Comment by stouch** [comment]
Yes, I'm running my own instance, Oh great where can I find some docs or information for making this custom ES query ?

**Comment by missinglink** [comment]
You'll need to learn elasticsearch.
The basic idea is that you POST a json query, the index name is 'pelias'

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html

Unfortunately I can't provide any support for custom queries, you will be able to find a lot of information online about how to query elasticsearch directly on port 9200.

**Comment by stouch** [comment]
Sorry I meant : Which properties should I query according any existing documentation of the Pelias index. But anyway I'm gonna do another way because I noticed that some macroregions and regions do not match between WOF and Geonames so the query will not be enough for what I need. Thanks anyway!
