### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by dianashk** [pelias/pelias#95]
Searching for 

`http://pelias.mapzen.com/search?input=on+ca`

You get back a result with :

```javascript
{
type: "Feature",
properties: {
id: "369180271",
layer: "osmnode",
name: "Happy Ca�on Coal Mine",
alpha3: "USA",
admin0: "United States",
admin1: "Colorado",
admin1_abbr: "CO",
admin2: "Montrose County",
category: [ ],
address: { },
text: "Happy Ca�on Coal Mine, Montrose County, CO"
},
geometry: {
type: "Point",
coordinates: [
-107.899508,
38.413876
]
}
}
```
Investigate strange character in place of `ñ`. 

There is a duplicate in geonames as well, that seems to be fine with the `ñ`. You can find it by searching for `happy coal mine`:

```javascript
{
type: "Feature",
properties: {
id: "5424358",
layer: "geoname",
name: "Happy Cañon Coal Mine",
alpha3: "USA",
admin0: "United States",
admin1: "Colorado",
admin1_abbr: "CO",
admin2: "Montrose County",
category: [
"industry"
],
address: { },
text: "Happy Cañon Coal Mine, Montrose County, CO"
},
geometry: {
type: "Point",
coordinates: [
-107.89951,
38.41388
]
}
}
```

**Comment by mtmail** [comment]
That would be a data issue because the mapper added it (imported it) wrong into openstreetmap http://www.openstreetmap.org/node/369180271

```
id: "369180271",
layer: "osmnode",
name: "Happy Ca�on Coal Mine",
```

**Comment by dianashk** [comment]
@mtmail, you take the prize for faster github issue reply we've seen in Pelias!!! Sub 3 minutes!!!

Thanks for checking the source. I guess this could be closed as `won't-fix`.

**Comment by dianashk** [comment]
...and I fixed it in OSM. Progress! :smile:

**Comment by dianashk** [comment]
fixed

**Comment by orangejulius** [comment]
I had to search for http://pelias.mapzen.com/search?input=happy%20coal%20mine but this definitely seems fixed in pelias production, closing :)
