### ISSUE TITLE
Pelias Snapshot Update Date

### ISSUE THREAD

**Issue by dawidl11** [pelias/pelias#955]
Hi all,
I have a running Pelias instance and would like to check when the Pelias snapshot is from (update date). Is there any way to check this directly?

Many thanks in advance
Dawid

**Comment by missinglink** [comment]
You should be able to view the creation date using the elastic search cat indices API

https://stackoverflow.com/a/42583024

**Comment by dawidl11** [comment]
Thanks for the Hint!
