### ISSUE TITLE
While integrating custom WhosOnFirst data, old WOF-data is also available

### ISSUE THREAD

**Issue by dawidl11** [pelias/pelias#961]
Hi, I have an urgent problem with my Pelias.

**What did I do**

I have created **my own WhosOnFirst data** and imported it into the snapshot as part of my Pelias build process (pelias.json customized). This also worked well.

**Problem**

Unfortunately, however, I have discovered that my Pelias snapshot also contains additional original data records (from the official, freely available WhosOnFirst data set). This causes my unstructured search to not always work.

I searched through everything and couldn't find anything where I would specify that I want to import the old WhosOnFirst records into my build.

**Question**

Does anyone have any idea where these old WhosOnFirst records might be coming from? Does Pelias perhaps do an automatic default download of the WhosOnFirst records?

Many thanks in advance!
Dawid

**Comment by missinglink** [comment]
Assuming you're using `pelias/docker` to run the import there is an `.env` file in your project which specifies the data directory eg.
https://github.com/pelias/docker/blob/master/projects/portland-metro/.env

Look in that directory to see which files exist, that folder is empty for newly cloned projects.

**Comment by missinglink** [comment]
Your issue doesn't provide enough detail to give much more help, just as an example of which records you're seeing and why they are unexpected.

**Comment by dawidl11** [comment]
Thank you for the quick attempt to support us. We have since found the problem and it was actually trivial.
For our Pelias build we used an outdated configuration and thus the wrong path for the WhosOnFirst data was used.

I already suspected that maybe the Pelias importer itself was somehow fetching the WhosOnFirst data from geocode.earth.
