### ISSUE TITLE
Neighborhood in the structured search worsens the results

### ISSUE THREAD

**Issue by dawidl11** [pelias/pelias#965]
Hi there,

I have a problem with the structured search with Pelias.
I use Standard-Pelias with open geodata (OSM, OA, GN and WOF). All services such as Placeholder or Libpostal are also used. 

I am looking for "Steinrutschweg xy, Köln, Kalk". If I search without specifying a neighbourhood, I get an exact match: 
`locality=Köln; address=Steinrutschweg 45`

If I search with a neighbourhood, I get a fallback:
`locality=Köln; address=Steinrutschweg 45; neighbourhood=Kalk`

I understand that the neighbourhood is not available in the WOF data. 
But is it possible to configure Pelias so that it does not return a fallback for such queries (e.g. that it ignores the neighbourhood)?

Many thanks in advance
Dawid

**Comment by missinglink** [comment]
Unfortunately not, the structured search queries currently require *all of the supplied terms* to be satisfied, there is no API to change that behaviour, although it can be done by editing this function and relinking the `pelias/query` module into `pelias/api`:

https://github.com/pelias/query/blob/a730d26fabddb41119eae7b918374621817b2a35/layout/StructuredFallbackQuery.js#L79-L90

This renders the neighbourhood subquery in an [elasticsearch MUST condition](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html).

<img width="321" alt="Screenshot 2024-04-05 at 11 14 32" src="https://github.com/pelias/pelias/assets/738069/afd1206b-322f-4ccb-a3e6-fadec6fcb8cd">

**Comment by missinglink** [comment]
In an ideal world we could get the missing data added to WOF 🤷‍♂️
