### ISSUE TITLE
Pelias does not return the address despite having it in index

### ISSUE THREAD

**Issue by mabilinab** [pelias/pelias#970]
Hi there,
I was trying to build Pelias on France data through the project example "/projects/france" and it seems like not all streets from openaddresses get imported.
There's for example this address "100 avenue andré rouy" – present in the openaddresses csv file – which is never returned. In fact, none of the addresses in the street "avenue andré rouy" are returned.
I even made a csv extract (149 lines) of only this street (changed the csv name etc..) and imported it through "pelias import oa" and yet it is never returned despite the logs not showing any import error 

When it comes to making a search through the Pelias API
`
curl -X GET 'http://localhost:4000/v1/search?text=100%20avenue%20andré%20rouy'
`
Pelias doesn't seem to understand that "avenue andré rouy" is the whole street name, and thinks that rouy is the city name
```
{
   "geocoding":{
      "version":"0.2",
      "attribution":"http://localhost:4000/attribution",
      "query":{
         "text":"100 avenue andrÃ© rouy",
         "size":10,
         "private":false,
         "focus.point.lat":46.61,
         "focus.point.lon":2.45,
         "lang":{
            "name":"English",
            "iso6391":"en",
            "iso6393":"eng",
            "via":"default",
            "defaulted":true
         },
         "querySize":20,
         "parser":"libpostal",
         "parsed_text":{
            "housenumber":"100",
            "street":"avenue andrã©",
            "city":"rouy"
         }
      },
      "engine":{
         "name":"Pelias",
         "author":"Mapzen",
         "version":"1.0"
      },
      "timestamp":1718089285600
   },
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "geometry":{
            "type":"Point",
            "coordinates":[
               3.53414,
               47.02586
            ]
         },
         "properties":{
            "id":"1125937687",
            "gid":"whosonfirst:locality:1125937687",
            "layer":"locality",
            "source":"whosonfirst",
            "source_id":"1125937687",
            "country_code":"FR",
            "name":"Rouy",
            "confidence":0.6,
            "match_type":"fallback",
            "distance":94.676,
            "accuracy":"centroid",
            "country":"France",
            "country_gid":"whosonfirst:country:85633147",
            "country_a":"FRA",
            "macroregion":"Burgundy-Franche-Comte",
            "macroregion_gid":"whosonfirst:macroregion:1108826395",
            "macroregion_a":"BF",
            "region":"Nièvre",
            "region_gid":"whosonfirst:region:85683359",
            "region_a":"NI",
            "macrocounty":"Nevers",
            "macrocounty_gid":"whosonfirst:macrocounty:404228123",
            "county":"Saint-Saulge",
            "county_gid":"whosonfirst:county:102068655",
            "localadmin":"Rouy",
            "localadmin_gid":"whosonfirst:localadmin:404405727",
            "locality":"Rouy",
            "locality_gid":"whosonfirst:locality:1125937687",
            "label":"Rouy, France"
         },
         "bbox":[
            3.485919,
            47.000747,
            3.586798,
            47.078234
         ]
      }
   ],
   "bbox":[
      3.485919,
      47.000747,
      3.586798,
      47.078234
   ]
}
```
However, when I directly query into the ES index, I get that address among the results
```
curl -X GET "http://localhost:9200/pelias/_search" -H 'Content-Type: application/json' -d'
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "address_parts.number": "100"
          }
        },
        {
          "match": {
            "address_parts.street": "avenue andré rouy"
          }
        }
      ]
    }
  }

```

**Environment**:
I'm using the docker image and the project files as they are. Test both on mac & Linux machine.
Here's also a snapshot of the data folder – I've skipped interpolation and polylines 

```
du -sh *
4.0K	blacklist
9.0G	elasticsearch
2.4G	openaddresses
4.3G	openstreetmap
365M	placeholder
2.6G	whosonfirst
```

Does anyone know what could be the cause? Thank you!

**Comment by missinglink** [comment]
Can you retrieve the address using the `/v1/autocomplete` endpoint instead of using `/v1/search`?

**Comment by mabilinab** [comment]
Ok I think I've finally found the issue: it's the special character "é" in "avenue André rouy" that is causing a problem with the parser
When using the percent-encoded value for é 
`curl -X GET "http://localhost:4000/v1/search?text=100%20avenue%20andr%C3%A9%20rouy"
`
instead of 
`curl -X GET "http://localhost:4000/v1/search?text=100%20avenue%20andré%20rouy"
`
the parser correctly understands that it's the whole street name, and that "rouy" is not a city name.
This might be explain why when directly querying into the ES index (thus bypassing the parser)  using the query in the initial post 
`
          "match": {
            "address_parts.street": "avenue andré rouy"
          }
`
ES is able to find the address with no issue.

I even tried to explicitly specify the encoding and yet the parser still incorrectly parsed the input
```
curl -X GET -H "Content-Type: application/json; charset=utf-8" "http://localhost:4000/v1/search?text=100%20avenue%20andré%20rouy"
```

Is this behavior normal? Does it mean all API calls need to be percent-encoded?

**Comment by missinglink** [comment]
> Is this behavior normal? Does it mean all API calls need to be percent-encoded?

Query parameters are expected to correctly URL encoded.

I'm not sure of edge-cases for incorrectly encoded URLs, the behaviour in Pelias will be undefined, we won't attempt to correct incorrectly formatted parameters.

The `encodeURIComponent()` javascript function can be used as reference:

```js
encodeURIComponent('100 avenue andré rouy')
'100%20avenue%20andr%C3%A9%20rouy'
```

If we're not correctly decoding the above format then please let us know, that would be a bug.
