### ISSUE TITLE
focus.point.lat and focut.point.lon doesn't work as expected

### ISSUE THREAD

**Issue by MALKARAJ** [pelias/pelias#973]
focus.point.lat and focus.point.lon doesn't have any effect on my autocomplete search

is there any issue in this parameters?

**Comment by missinglink** [comment]
> focus.point.lat and focus.point.lon doesn't have any effect on my autocomplete search

Please be more specific, including examples that would allow someone to reproduce your issue. 

We provide an issue template for this purpose:
https://github.com/pelias/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
