### ISSUE TITLE
administrative centroids

### ISSUE THREAD

**Issue by missinglink** [pelias/pelias#98]
this ticket is to track the discussion of how best to compute centroids for large/complex polygons such as countries/cities and states.

### background

there are a bunch of algorithms available for "computing the weighted centroid of an irregular polygon" which I covered briefly in https://github.com/pelias/pbf2json/issues/22

the issue is that:
- there is no 'true' center of an irregular polygon
- more complex algorithms require more CPU
- countries are not really polygons anyway

#### example

http://geojson.io/#id=gist:anonymous/f8696af2117e75a1971e&map=5/-37.440/171.167
this shows two different algorithms trying to figure out the center (the pins) of a polygon (the border)

as you can see they both fail to compute a centroid value which even lies *within* the polygon itself, we can try different algorithms which will ensure the intersection, but at the end of the day they are also going to provide an arbitrary centroid value which may be far from the road network.

#### issue

the issue really is:
- as a routing user, given I search 'New Zealand', I expect to start my search from a logical center on/near the road network.

#### discussion

it seems to me like the only real solution here is to define a single definative 'center' of each country/city/state, this could be the central train station, post office or whatever, but it needs to be near a routable road and needs to be on land and inside the polygon.

it also seems like using any algorithm to compute these centroids will only result in undesirable results?

**Comment by missinglink** [comment]
see: https://github.com/paulmach/go.geo/issues/23

**Comment by dianashk** [comment]
I had a need to compute the centroid of a multipolygon for Fences recently and ran into all the issues you're describing. Most algorithms were producing a point well outside the irregular region. 

Luckily, I came across something in `turf` called [`polygonreduce`](https://github.com/Turfjs/turf-polygon-reduce) which I had to tweak just a bit to allow for `Multipolygons` and you can see the modified version [here](https://github.com/pelias/fences-slicer/blob/master/src/util.js#L73)

It basically shrinks the polygon until it's practically a single point. I believe this is how they generally determine where to render country labels.

**Comment by riordan** [comment]
This came up in my discussion with the Routing team. It's a very common routing use case (I'm going to Dusseldorf, about how long will it be?). Solving this would be a very nice plus, and not something they'd encountered before.

**Comment by missinglink** [comment]
see: https://github.com/Turfjs/turf-point-on-surface

**Comment by riordan** [comment]
Nice! I imagine this with a couple of nice heuristics could get us pretty far in establishing "populated centroids".

@indyhurt, @nvkelso: would be great for you to weigh in here as to how we might be able to determine the "centroid" around the center of human activity, not just the spatial definition.

**Comment by IndyHurt** [comment]
Centroids! 
One easy thing is calculating weighted population centroids, but you won't get good population data from OSM.  Another option is to use kernel density to identify built up areas so the centroid can be placed there.  Check this out:  http://onlinelibrary.wiley.com/doi/10.1111/tgis.12135/abstract

@nvkelso may want to consider multiple locations - one for default labeling (yet please not static), one for routing

**Comment by IndyHurt** [comment]
Also, this is what happens when you rely on polygon centroids for routing:  http://www.cnn.com/2012/12/10/tech/apple-maps-australia-flaw/
Too often, the centroid is in the middle of nowhere, far away from the built up area.

**Comment by nvkelso** [comment]
We should also investigate using OSM's business POIs as a proxy for population within a given polygon. In San Francisco there are more POIs along Market Street than in the more residential neighborhoods, but all neighborhoods are (mostly) covered with roads with the jurisdiction.

**Comment by mtmail** [comment]
I gave a talk on using population density data a while back http://2011.sotm-eu.org/talk@56.html

The goal was to find the optimal initial zoom level of an area though. Similar to this blog post by Chris Lightfoot (may he rest in peace) https://www.mysociety.org/2005/11/30/population-density-and-customary-proximity/

http://sedac.ciesin.columbia.edu/data/set/gpw-v3-population-count gives you a two km2 grid of all countries. Here's how New Zealand looks like. The black areas might not seem useful but at least we know it's land area and not water.
![untitled 2](https://cloud.githubusercontent.com/assets/3727288/8687632/ad7fea12-2a92-11e5-8fba-f3897a865cd7.png)

**Comment by missinglink** [comment]
@IndyHurt this map has uncanny similarities to the places I suggested you visit in New Zealand ;)
maybe there is something to this...

**Comment by orangejulius** [comment]
The answer is: Who's on First will decide on the best centroid.
